-- KAPSORA migration 000008: global permission catalog (v1.2 Ek C plus fiscal/accounting
-- permissions from plan v2.0 section 2.10). Reference data, idempotent.

INSERT INTO iam.permission (code, description, sensitivity) VALUES
    ('platform.tenant.provision',        'Tenant oluşturma, askıya alma ve kapatma',                      'PRIVILEGED'),
    ('platform.support.access',          'Platform destek erişimi (maskeli)',                              'PRIVILEGED'),
    ('security.audit.read',              'Güvenlik olayları ve erişim raporlarını okuma',                  'SENSITIVE'),
    ('security.break_glass',             'Acil durum break-glass erişimi',                                 'PRIVILEGED'),
    ('identity.user.read',               'Kullanıcı ve üyelik listeleme',                                  'NORMAL'),
    ('identity.user.manage',             'Kullanıcı daveti ve üyelik yönetimi',                            'SENSITIVE'),
    ('identity.role.manage',             'Rol, permission ve scope atama',                                 'PRIVILEGED'),
    ('identity.access_review',           'Periyodik yetki doğrulama kampanyası',                           'SENSITIVE'),
    ('organization.read',                'Kurum ve sağlayıcı dizinini okuma',                              'NORMAL'),
    ('organization.manage',              'Kurum ilişkisi oluşturma ve güncelleme',                         'NORMAL'),
    ('member.read',                      'Hak sahibi kaydını okuma (maskeli)',                             'NORMAL'),
    ('member.identifier.read',           'Hassas identifier değerini görme',                               'SENSITIVE'),
    ('member.identifier.search',         'Hassas identifier ile arama',                                    'SENSITIVE'),
    ('member.manage',                    'Hak sahibi oluşturma ve güncelleme',                             'NORMAL'),
    ('member.relationship.manage',       'Aile ve ilişki kayıtlarını yönetme',                             'NORMAL'),
    ('membership.manage',                'Sponsor üyeliği yönetme',                                        'NORMAL'),
    ('enrollment.manage',                'Plan enrollment yönetme',                                        'NORMAL'),
    ('eligibility.check',                'Uygunluk sorgusu çalıştırma',                                    'NORMAL'),
    ('program.read',                     'Program okuma',                                                  'NORMAL'),
    ('program.manage',                   'Program yönetme',                                                'NORMAL'),
    ('plan.manage',                      'Plan ve taslak sürüm yönetme',                                   'NORMAL'),
    ('plan.publish',                     'Plan sürümü yayınlama (checker)',                                'PRIVILEGED'),
    ('entitlement.read',                 'Hak bakiyesi ve ledger okuma',                                   'NORMAL'),
    ('entitlement.adjust',               'Manuel hak düzeltmesi (maker-checker)',                          'PRIVILEGED'),
    ('catalog.read',                     'Hizmet kataloğu okuma',                                          'NORMAL'),
    ('catalog.manage',                   'Hizmet kataloğu yönetme',                                        'NORMAL'),
    ('provider.read',                    'Sağlayıcı ve lokasyon okuma',                                    'NORMAL'),
    ('provider.manage',                  'Sağlayıcı, lokasyon ve yetkinlik yönetme',                       'NORMAL'),
    ('provider.practitioner.manage',     'Uygulayıcı/doktor kayıtlarını yönetme',                          'SENSITIVE'),
    ('contract.read',                    'Sözleşme ve tarife okuma',                                       'NORMAL'),
    ('contract.manage',                  'Sözleşme taslağı ve fiyat yönetme',                              'NORMAL'),
    ('contract.publish',                 'Sözleşme sürümü yayınlama (checker)',                            'PRIVILEGED'),
    ('rule.read',                        'Kural seti okuma',                                               'NORMAL'),
    ('rule.draft',                       'Kural taslağı ve test senaryosu yazma',                          'NORMAL'),
    ('rule.publish',                     'Kural sürümü yayınlama (checker)',                               'PRIVILEGED'),
    ('service_request.read',             'Hizmet talebi okuma',                                            'NORMAL'),
    ('service_request.create',           'Hizmet talebi oluşturma',                                        'NORMAL'),
    ('service_request.submit',           'Hizmet talebi gönderme',                                         'NORMAL'),
    ('service_request.review',           'Hizmet talebi inceleme ve karar',                                'NORMAL'),
    ('service_request.cancel',           'Hizmet talebi iptali',                                           'NORMAL'),
    ('health.case.read',                 'Sağlık vakası okuma',                                            'SENSITIVE'),
    ('health.case.manage',               'Sağlık vakası ve encounter yönetme',                             'SENSITIVE'),
    ('health.clinical.read',             'Klinik detay (tanı, rapor) görme',                               'SENSITIVE'),
    ('health.medical_report.manage',     'Tedavi raporu oluşturma ve gönderme',                            'SENSITIVE'),
    ('health.medical_report.review',     'Tedavi raporu tıbbi inceleme',                                   'SENSITIVE'),
    ('accommodation.inventory.manage',   'Konaklama envanteri yönetme',                                    'NORMAL'),
    ('accommodation.booking.create',     'Rezervasyon oluşturma',                                          'NORMAL'),
    ('accommodation.booking.manage',     'Rezervasyon yönetme, check-in/out',                              'NORMAL'),
    ('claim.read',                       'Claim okuma',                                                    'NORMAL'),
    ('claim.create',                     'Claim oluşturma',                                                'NORMAL'),
    ('claim.submit',                     'Claim gönderme',                                                 'NORMAL'),
    ('claim.medical.review',             'Claim tıbbi inceleme',                                           'SENSITIVE'),
    ('claim.financial.review',           'Claim mali inceleme',                                            'NORMAL'),
    ('invoice.read',                     'Fatura okuma',                                                   'NORMAL'),
    ('invoice.manage',                   'Fatura kaydı yönetme',                                           'NORMAL'),
    ('batch.create',                     'İcmal oluşturma',                                                'NORMAL'),
    ('batch.submit',                     'İcmal gönderme',                                                 'NORMAL'),
    ('batch.review',                     'İcmal inceleme ve karar',                                        'NORMAL'),
    ('settlement.read',                  'Settlement okuma',                                               'NORMAL'),
    ('settlement.approve',               'Settlement onayı (eşik + checker)',                              'PRIVILEGED'),
    ('document.upload',                  'Belge yükleme',                                                  'NORMAL'),
    ('document.read',                    'Belge görüntüleme',                                              'NORMAL'),
    ('document.download.sensitive',      'Hassas belge indirme (step-up)',                                 'SENSITIVE'),
    ('notification.manage',              'Bildirim şablonu ve sağlayıcı yönetme',                          'NORMAL'),
    ('integration.manage',               'Entegrasyon uç noktası ve webhook yönetme',                      'SENSITIVE'),
    ('import.execute',                   'Toplu import çalıştırma',                                        'SENSITIVE'),
    ('report.read',                      'Rapor okuma',                                                    'NORMAL'),
    ('export.create',                    'Async export oluşturma',                                         'SENSITIVE'),
    ('export.personal_data',             'Kişisel veri export (step-up, maker-checker)',                   'PRIVILEGED'),
    ('audit.read',                       'Audit olaylarını okuma',                                         'SENSITIVE'),
    ('privacy.request.manage',           'Veri sahibi talebi (DSAR) yönetme',                              'SENSITIVE'),
    -- Plan v2.0 section 2.10: fiscal (e-Belge) and accounting
    ('fiscal.edocument.read',            'e-Belge okuma',                                                  'NORMAL'),
    ('fiscal.edocument.match',           'e-Belgeyi claim/icmal ile eşleştirme',                           'NORMAL'),
    ('fiscal.response.send',             'GİB uygulama yanıtı gönderme (maker-checker)',                   'PRIVILEGED'),
    ('fiscal.integrator.manage',         'Özel entegratör hesabı yönetme (step-up)',                       'PRIVILEGED'),
    ('fiscal.document.issue',            'e-Belge düzenleme (MVP+1)',                                      'PRIVILEGED'),
    ('accounting.mapping.manage',        'Hesap ve cari eşlemesi yönetme',                                 'SENSITIVE'),
    ('accounting.posting.read',          'Muhasebe kaydı okuma',                                           'NORMAL'),
    ('accounting.posting.send',          'Muhasebe kaydını ERP''ye gönderme',                              'PRIVILEGED'),
    ('accounting.reconcile',             'Cari mutabakat çalıştırma ve onaylama',                          'SENSITIVE')
ON CONFLICT (code) DO UPDATE
    SET description = EXCLUDED.description,
        sensitivity = EXCLUDED.sensitivity;
