// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accommodation_booking.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addInventoryHeld = `-- name: AddInventoryHeld :execrows
UPDATE accommodation.inventory_day
   SET held = held + $1::int
 WHERE tenant_id = $2
   AND room_type_id = $3
   AND stay_date >= $4::date
   AND stay_date <= $5::date
`

type AddInventoryHeldParams struct {
	Delta      int32
	TenantID   uuid.UUID
	RoomTypeID uuid.UUID
	FromDate   pgtype.Date
	ToDate     pgtype.Date
}

// Move `held` by a signed delta over the whole range in one statement. The caller has
// already locked these rows in stay_date order; this statement is the write that lock was
// taken for. A delta that would take `held` negative or push `held + confirmed` past
// `capacity` is refused by the row's own constraints, which is the outcome that matters
// when a caller forgets to look.
func (q *Queries) AddInventoryHeld(ctx context.Context, arg AddInventoryHeldParams) (int64, error) {
	result, err := q.db.Exec(ctx, addInventoryHeld,
		arg.Delta,
		arg.TenantID,
		arg.RoomTypeID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelBooking = `-- name: CancelBooking :execrows
UPDATE accommodation.booking
   SET status = 'CANCELLED', cancelled_at = $1,
       cancel_reason_code = $2, hold_expires_at = NULL,
       updated_by = $3
 WHERE tenant_id = $4
   AND id = $5
   AND status IN ('HOLD','PENDING_APPROVAL')
`

type CancelBookingParams struct {
	CancelledAt      *time.Time
	CancelReasonCode *string
	ActorID          uuid.NullUUID
	TenantID         uuid.UUID
	ID               uuid.UUID
}

func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelBooking,
		arg.CancelledAt,
		arg.CancelReasonCode,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmBooking = `-- name: ConfirmBooking :execrows
UPDATE accommodation.booking
   SET status = 'CONFIRMED', confirmed_at = $1,
       authorization_id = $2,
       policy_snapshot = $3,
       hold_expires_at = NULL, updated_by = $4
 WHERE tenant_id = $5
   AND id = $6
   AND status IN ('HOLD','PENDING_APPROVAL')
`

type ConfirmBookingParams struct {
	ConfirmedAt     *time.Time
	AuthorizationID uuid.NullUUID
	PolicySnapshot  []byte
	ActorID         uuid.NullUUID
	TenantID        uuid.UUID
	ID              uuid.UUID
}

// The approval, applied under the booking's own lock. Every write is guarded by the status
// predicate rather than by a flag: the outbox delivers at least once, and the second
// delivery has to find nothing to do rather than confirm a confirmed booking.
func (q *Queries) ConfirmBooking(ctx context.Context, arg ConfirmBookingParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmBooking,
		arg.ConfirmedAt,
		arg.AuthorizationID,
		arg.PolicySnapshot,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countBookingNights = `-- name: CountBookingNights :one
SELECT count(*)::int AS nights
  FROM accommodation.booking_night n
 WHERE n.tenant_id = $1
   AND n.booking_id = $2
`

type CountBookingNightsParams struct {
	TenantID  uuid.UUID
	BookingID uuid.UUID
}

func (q *Queries) CountBookingNights(ctx context.Context, arg CountBookingNightsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countBookingNights, arg.TenantID, arg.BookingID)
	var nights int32
	err := row.Scan(&nights)
	return nights, err
}

const createBooking = `-- name: CreateBooking :one

INSERT INTO accommodation.booking (
    tenant_id, reference, person_id, enrollment_id, program_id, property_id, room_type_id,
    check_in, check_out, nights, adults, children, status, hold_expires_at,
    entitlement_reservation_id, quote_snapshot, channel, created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8::date, $9::date,
        $10::int, $11::int, $12::int,
        $13, $14,
        $15, $16,
        $17, $18, $18)
RETURNING id, reference, person_id, enrollment_id, program_id, property_id, room_type_id,
          check_in, check_out, nights, adults, children, status, hold_expires_at,
          entitlement_reservation_id, service_request_id, authorization_id, voucher_id,
          quote_snapshot, policy_snapshot, channel, confirmed_at, checked_in_at,
          checked_out_at, cancelled_at, cancel_reason_code, actual_nights,
          created_at, updated_at, row_version
`

type CreateBookingParams struct {
	TenantID                 uuid.UUID
	Reference                string
	PersonID                 uuid.UUID
	EnrollmentID             uuid.UUID
	ProgramID                uuid.UUID
	PropertyID               uuid.UUID
	RoomTypeID               uuid.UUID
	CheckIn                  pgtype.Date
	CheckOut                 pgtype.Date
	Nights                   int32
	Adults                   int32
	Children                 int32
	Status                   string
	HoldExpiresAt            *time.Time
	EntitlementReservationID uuid.NullUUID
	QuoteSnapshot            []byte
	Channel                  string
	ActorID                  uuid.NullUUID
}

type CreateBookingRow struct {
	ID                       uuid.UUID
	Reference                string
	PersonID                 uuid.UUID
	EnrollmentID             uuid.UUID
	ProgramID                uuid.UUID
	PropertyID               uuid.UUID
	RoomTypeID               uuid.UUID
	CheckIn                  pgtype.Date
	CheckOut                 pgtype.Date
	Nights                   int32
	Adults                   int32
	Children                 int32
	Status                   string
	HoldExpiresAt            *time.Time
	EntitlementReservationID uuid.NullUUID
	ServiceRequestID         uuid.NullUUID
	AuthorizationID          uuid.NullUUID
	VoucherID                uuid.NullUUID
	QuoteSnapshot            []byte
	PolicySnapshot           []byte
	Channel                  string
	ConfirmedAt              *time.Time
	CheckedInAt              *time.Time
	CheckedOutAt             *time.Time
	CancelledAt              *time.Time
	CancelReasonCode         *string
	ActualNights             *int32
	CreatedAt                time.Time
	UpdatedAt                time.Time
	RowVersion               int64
}

// ---------------------------------------------------------------------------
// Booking
// ---------------------------------------------------------------------------
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.TenantID,
		arg.Reference,
		arg.PersonID,
		arg.EnrollmentID,
		arg.ProgramID,
		arg.PropertyID,
		arg.RoomTypeID,
		arg.CheckIn,
		arg.CheckOut,
		arg.Nights,
		arg.Adults,
		arg.Children,
		arg.Status,
		arg.HoldExpiresAt,
		arg.EntitlementReservationID,
		arg.QuoteSnapshot,
		arg.Channel,
		arg.ActorID,
	)
	var i CreateBookingRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.PersonID,
		&i.EnrollmentID,
		&i.ProgramID,
		&i.PropertyID,
		&i.RoomTypeID,
		&i.CheckIn,
		&i.CheckOut,
		&i.Nights,
		&i.Adults,
		&i.Children,
		&i.Status,
		&i.HoldExpiresAt,
		&i.EntitlementReservationID,
		&i.ServiceRequestID,
		&i.AuthorizationID,
		&i.VoucherID,
		&i.QuoteSnapshot,
		&i.PolicySnapshot,
		&i.Channel,
		&i.ConfirmedAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CancelledAt,
		&i.CancelReasonCode,
		&i.ActualNights,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const createBookingGuest = `-- name: CreateBookingGuest :exec
INSERT INTO accommodation.booking_guest (
    tenant_id, booking_id, person_id, display_name, guest_type, is_minor)
VALUES ($1, $2, $3,
        $4, $5, $6)
`

type CreateBookingGuestParams struct {
	TenantID    uuid.UUID
	BookingID   uuid.UUID
	PersonID    uuid.NullUUID
	DisplayName string
	GuestType   string
	IsMinor     bool
}

func (q *Queries) CreateBookingGuest(ctx context.Context, arg CreateBookingGuestParams) error {
	_, err := q.db.Exec(ctx, createBookingGuest,
		arg.TenantID,
		arg.BookingID,
		arg.PersonID,
		arg.DisplayName,
		arg.GuestType,
		arg.IsMinor,
	)
	return err
}

const createBookingNight = `-- name: CreateBookingNight :exec

INSERT INTO accommodation.booking_night (
    tenant_id, booking_id, stay_date, room_type_id, unit_amount, payer_amount,
    member_amount, currency_code)
VALUES ($1, $2, $3::date,
        $4, $5::text::numeric,
        $6::text::numeric, $7::text::numeric,
        $8)
`

type CreateBookingNightParams struct {
	TenantID     uuid.UUID
	BookingID    uuid.UUID
	StayDate     pgtype.Date
	RoomTypeID   uuid.UUID
	UnitAmount   string
	PayerAmount  string
	MemberAmount string
	CurrencyCode string
}

// ---------------------------------------------------------------------------
// Booking nights and guests
// ---------------------------------------------------------------------------
func (q *Queries) CreateBookingNight(ctx context.Context, arg CreateBookingNightParams) error {
	_, err := q.db.Exec(ctx, createBookingNight,
		arg.TenantID,
		arg.BookingID,
		arg.StayDate,
		arg.RoomTypeID,
		arg.UnitAmount,
		arg.PayerAmount,
		arg.MemberAmount,
		arg.CurrencyCode,
	)
	return err
}

const expireBooking = `-- name: ExpireBooking :execrows
UPDATE accommodation.booking
   SET status = 'EXPIRED', hold_expires_at = NULL
 WHERE tenant_id = $1
   AND id = $2
   AND status = 'HOLD'
`

type ExpireBookingParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// The sweep's own write. The predicate is the whole of its idempotency: a second run finds
// the row already EXPIRED, updates nothing, and the caller reads the zero row count as
// "somebody else already did this" rather than as a failure.
func (q *Queries) ExpireBooking(ctx context.Context, arg ExpireBookingParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireBooking, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBooking = `-- name: GetBooking :one
SELECT b.id, b.reference, b.person_id, b.enrollment_id, b.program_id, b.property_id,
       b.room_type_id, b.check_in, b.check_out, b.nights, b.adults, b.children, b.status,
       b.hold_expires_at, b.entitlement_reservation_id, b.service_request_id,
       b.authorization_id, b.voucher_id, b.quote_snapshot, b.policy_snapshot, b.channel,
       b.confirmed_at, b.checked_in_at, b.checked_out_at, b.cancelled_at,
       b.cancel_reason_code, b.actual_nights, b.created_at, b.updated_at, b.row_version
  FROM accommodation.booking b
  JOIN accommodation.property p
    ON p.tenant_id = b.tenant_id AND p.id = b.property_id
 WHERE b.tenant_id = $1
   AND b.id = $2
   AND ($3::uuid IS NULL OR b.person_id = $3::uuid)
   AND ($4::uuid[] IS NULL
        OR p.provider_organization_id = ANY($4::uuid[]))
`

type GetBookingParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	PersonID uuid.NullUUID
	ScopeIds []uuid.UUID
}

type GetBookingRow struct {
	ID                       uuid.UUID
	Reference                string
	PersonID                 uuid.UUID
	EnrollmentID             uuid.UUID
	ProgramID                uuid.UUID
	PropertyID               uuid.UUID
	RoomTypeID               uuid.UUID
	CheckIn                  pgtype.Date
	CheckOut                 pgtype.Date
	Nights                   int32
	Adults                   int32
	Children                 int32
	Status                   string
	HoldExpiresAt            *time.Time
	EntitlementReservationID uuid.NullUUID
	ServiceRequestID         uuid.NullUUID
	AuthorizationID          uuid.NullUUID
	VoucherID                uuid.NullUUID
	QuoteSnapshot            []byte
	PolicySnapshot           []byte
	Channel                  string
	ConfirmedAt              *time.Time
	CheckedInAt              *time.Time
	CheckedOutAt             *time.Time
	CancelledAt              *time.Time
	CancelReasonCode         *string
	ActualNights             *int32
	CreatedAt                time.Time
	UpdatedAt                time.Time
	RowVersion               int64
}

// The single read, with both boundaries applied. `person_id` NULL is a caller that is not
// bound to a member; `scope_ids` NULL is one that is not bound to a provider. A booking
// outside either is not found rather than forbidden: that a member is going to Antalya is
// not another provider's business.
func (q *Queries) GetBooking(ctx context.Context, arg GetBookingParams) (GetBookingRow, error) {
	row := q.db.QueryRow(ctx, getBooking,
		arg.TenantID,
		arg.ID,
		arg.PersonID,
		arg.ScopeIds,
	)
	var i GetBookingRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.PersonID,
		&i.EnrollmentID,
		&i.ProgramID,
		&i.PropertyID,
		&i.RoomTypeID,
		&i.CheckIn,
		&i.CheckOut,
		&i.Nights,
		&i.Adults,
		&i.Children,
		&i.Status,
		&i.HoldExpiresAt,
		&i.EntitlementReservationID,
		&i.ServiceRequestID,
		&i.AuthorizationID,
		&i.VoucherID,
		&i.QuoteSnapshot,
		&i.PolicySnapshot,
		&i.Channel,
		&i.ConfirmedAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CancelledAt,
		&i.CancelReasonCode,
		&i.ActualNights,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getBookingByRequest = `-- name: GetBookingByRequest :one
SELECT b.id, b.reference, b.person_id, b.enrollment_id, b.program_id, b.property_id,
       b.room_type_id, b.check_in, b.check_out, b.nights, b.adults, b.children, b.status,
       b.hold_expires_at, b.entitlement_reservation_id, b.service_request_id,
       b.authorization_id, b.voucher_id, b.quote_snapshot, b.policy_snapshot, b.channel,
       b.confirmed_at, b.checked_in_at, b.checked_out_at, b.cancelled_at,
       b.cancel_reason_code, b.actual_nights, b.created_at, b.updated_at, b.row_version
  FROM accommodation.booking b
 WHERE b.tenant_id = $1
   AND b.service_request_id = $2
`

type GetBookingByRequestParams struct {
	TenantID         uuid.UUID
	ServiceRequestID uuid.NullUUID
}

type GetBookingByRequestRow struct {
	ID                       uuid.UUID
	Reference                string
	PersonID                 uuid.UUID
	EnrollmentID             uuid.UUID
	ProgramID                uuid.UUID
	PropertyID               uuid.UUID
	RoomTypeID               uuid.UUID
	CheckIn                  pgtype.Date
	CheckOut                 pgtype.Date
	Nights                   int32
	Adults                   int32
	Children                 int32
	Status                   string
	HoldExpiresAt            *time.Time
	EntitlementReservationID uuid.NullUUID
	ServiceRequestID         uuid.NullUUID
	AuthorizationID          uuid.NullUUID
	VoucherID                uuid.NullUUID
	QuoteSnapshot            []byte
	PolicySnapshot           []byte
	Channel                  string
	ConfirmedAt              *time.Time
	CheckedInAt              *time.Time
	CheckedOutAt             *time.Time
	CancelledAt              *time.Time
	CancelReasonCode         *string
	ActualNights             *int32
	CreatedAt                time.Time
	UpdatedAt                time.Time
	RowVersion               int64
}

// The booking a decided service request belongs to. Most decided requests belong to none,
// and the subscriber reads that as "not mine" rather than as an error.
func (q *Queries) GetBookingByRequest(ctx context.Context, arg GetBookingByRequestParams) (GetBookingByRequestRow, error) {
	row := q.db.QueryRow(ctx, getBookingByRequest, arg.TenantID, arg.ServiceRequestID)
	var i GetBookingByRequestRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.PersonID,
		&i.EnrollmentID,
		&i.ProgramID,
		&i.PropertyID,
		&i.RoomTypeID,
		&i.CheckIn,
		&i.CheckOut,
		&i.Nights,
		&i.Adults,
		&i.Children,
		&i.Status,
		&i.HoldExpiresAt,
		&i.EntitlementReservationID,
		&i.ServiceRequestID,
		&i.AuthorizationID,
		&i.VoucherID,
		&i.QuoteSnapshot,
		&i.PolicySnapshot,
		&i.Channel,
		&i.ConfirmedAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CancelledAt,
		&i.CancelReasonCode,
		&i.ActualNights,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getBookingEntitlementCode = `-- name: GetBookingEntitlementCode :one
SELECT d.code AS entitlement_code
  FROM benefit.enrollment e
  JOIN benefit.plan_version v
    ON v.tenant_id = e.tenant_id
   AND v.plan_id = e.plan_id
   AND v.status = 'PUBLISHED'
   AND v.valid_period @> $1::date
  JOIN benefit.service_entitlement_mapping m
    ON m.tenant_id = v.tenant_id
   AND m.plan_version_id = v.id
   AND m.service_definition_id = $2
  JOIN benefit.entitlement_definition d
    ON d.tenant_id = m.tenant_id
   AND d.id = m.entitlement_definition_id
 WHERE e.tenant_id = $3
   AND e.id = $4
   AND (m.valid_from IS NULL OR m.valid_from <= $1::date)
   AND (m.valid_to IS NULL OR m.valid_to > $1::date)
 LIMIT 1
`

type GetBookingEntitlementCodeParams struct {
	ServiceDate         pgtype.Date
	ServiceDefinitionID uuid.UUID
	TenantID            uuid.UUID
	EnrollmentID        uuid.UUID
}

// Which entitlement a room type's service draws on, under the plan version in force for
// this enrollment on the first night (WP-I5-05's `benefit.service_entitlement_mapping`).
//
// The mapping and not the service's own code. A room type is a catalogue service and the
// entitlement it spends is the tenant's configuration: OTEL_GECE may be mapped to
// KONAKLAMA_GECE, or to a shared family budget, or to nothing at all. Matching on the code
// would work for whichever tenant happened to name them the same and quietly reserve the
// wrong balance -- or none -- for every other one.
func (q *Queries) GetBookingEntitlementCode(ctx context.Context, arg GetBookingEntitlementCodeParams) (string, error) {
	row := q.db.QueryRow(ctx, getBookingEntitlementCode,
		arg.ServiceDate,
		arg.ServiceDefinitionID,
		arg.TenantID,
		arg.EnrollmentID,
	)
	var entitlement_code string
	err := row.Scan(&entitlement_code)
	return entitlement_code, err
}

const getBookingRoomTypeContext = `-- name: GetBookingRoomTypeContext :one

SELECT rt.id AS room_type_id, rt.code AS room_type_code, rt.name AS room_type_name,
       rt.max_adults, rt.max_children, rt.max_occupancy, rt.service_definition_id,
       rt.status AS room_type_status,
       sd.code AS service_definition_code, sd.default_unit_type, sd.active AS service_active,
       p.id AS property_id, p.name AS property_name, p.timezone,
       p.provider_organization_id, p.status AS property_status
  FROM accommodation.room_type rt
  JOIN accommodation.property p
    ON p.tenant_id = rt.tenant_id AND p.id = rt.property_id
  JOIN catalog.service_definition sd
    ON sd.tenant_id = rt.tenant_id AND sd.id = rt.service_definition_id
 WHERE rt.tenant_id = $1
   AND rt.id = $2
   AND ($3::uuid[] IS NULL
        OR p.provider_organization_id = ANY($3::uuid[]))
`

type GetBookingRoomTypeContextParams struct {
	TenantID   uuid.UUID
	RoomTypeID uuid.UUID
	ScopeIds   []uuid.UUID
}

type GetBookingRoomTypeContextRow struct {
	RoomTypeID             uuid.UUID
	RoomTypeCode           string
	RoomTypeName           string
	MaxAdults              int32
	MaxChildren            int32
	MaxOccupancy           int32
	ServiceDefinitionID    uuid.UUID
	RoomTypeStatus         string
	ServiceDefinitionCode  string
	DefaultUnitType        string
	ServiceActive          bool
	PropertyID             uuid.UUID
	PropertyName           string
	Timezone               string
	ProviderOrganizationID uuid.UUID
	PropertyStatus         string
}

// ---------------------------------------------------------------------------
// What a hold needs to know before it takes one
// ---------------------------------------------------------------------------
// The room type with everything the hold decides on: the building it is in, the provider
// behind it, the clock the nights are counted against, and the catalogue service the
// request line and the entitlement both hang off.
func (q *Queries) GetBookingRoomTypeContext(ctx context.Context, arg GetBookingRoomTypeContextParams) (GetBookingRoomTypeContextRow, error) {
	row := q.db.QueryRow(ctx, getBookingRoomTypeContext, arg.TenantID, arg.RoomTypeID, arg.ScopeIds)
	var i GetBookingRoomTypeContextRow
	err := row.Scan(
		&i.RoomTypeID,
		&i.RoomTypeCode,
		&i.RoomTypeName,
		&i.MaxAdults,
		&i.MaxChildren,
		&i.MaxOccupancy,
		&i.ServiceDefinitionID,
		&i.RoomTypeStatus,
		&i.ServiceDefinitionCode,
		&i.DefaultUnitType,
		&i.ServiceActive,
		&i.PropertyID,
		&i.PropertyName,
		&i.Timezone,
		&i.ProviderOrganizationID,
		&i.PropertyStatus,
	)
	return i, err
}

const getContractVersionForRoomType = `-- name: GetContractVersionForRoomType :one
SELECT cv.id AS contract_version_id
  FROM contract.contract_version cv
  JOIN contract.contract c
    ON c.tenant_id = cv.tenant_id AND c.id = cv.contract_id
 WHERE cv.tenant_id = $1
   AND c.provider_profile_id = $2
   AND c.status = 'ACTIVE'
   AND cv.status = 'PUBLISHED'
   AND cv.valid_from <= $3::date
   AND (cv.valid_to IS NULL OR cv.valid_to > $3::date)
 ORDER BY (c.domain_code = 'ACCOMMODATION') DESC, cv.valid_from DESC, cv.id
 LIMIT 1
`

type GetContractVersionForRoomTypeParams struct {
	TenantID          uuid.UUID
	ProviderProfileID uuid.UUID
	ServiceDate       pgtype.Date
}

// The contract version the room type's price came from on the first night, which is the
// version whose lodging terms a confirmation freezes. It is read rather than passed in
// because the terms have to be the ones behind the price the member was quoted, and a
// caller that could name a version could freeze somebody else's policy onto this stay.
func (q *Queries) GetContractVersionForRoomType(ctx context.Context, arg GetContractVersionForRoomTypeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getContractVersionForRoomType, arg.TenantID, arg.ProviderProfileID, arg.ServiceDate)
	var contract_version_id uuid.UUID
	err := row.Scan(&contract_version_id)
	return contract_version_id, err
}

const getPersonEnrollmentForStay = `-- name: GetPersonEnrollmentForStay :one
SELECT e.id AS enrollment_id, pr.id AS program_id
  FROM benefit.enrollment e
  JOIN party.sponsor_membership m ON m.tenant_id = e.tenant_id AND m.id = e.sponsor_membership_id
  JOIN benefit.plan pl ON pl.tenant_id = e.tenant_id AND pl.id = e.plan_id
  JOIN benefit.program pr ON pr.tenant_id = pl.tenant_id AND pr.id = pl.program_id
 WHERE e.tenant_id = $1
   AND m.person_id = $2
   AND e.status = 'ACTIVE'
   AND pr.status = 'ACTIVE'
   AND e.valid_period @> $3::date
   AND ($4::uuid IS NULL OR pr.id = $4::uuid)
 ORDER BY e.id
 LIMIT 1
`

type GetPersonEnrollmentForStayParams struct {
	TenantID    uuid.UUID
	PersonID    uuid.UUID
	ServiceDate pgtype.Date
	ProgramID   uuid.NullUUID
}

type GetPersonEnrollmentForStayRow struct {
	EnrollmentID uuid.UUID
	ProgramID    uuid.UUID
}

// The enrollment the stay is booked under: the person's own active enrollment covering the
// first night, narrowed to one program when the caller named one. A person with none has
// no plan to book against, and the hold refuses rather than guessing.
func (q *Queries) GetPersonEnrollmentForStay(ctx context.Context, arg GetPersonEnrollmentForStayParams) (GetPersonEnrollmentForStayRow, error) {
	row := q.db.QueryRow(ctx, getPersonEnrollmentForStay,
		arg.TenantID,
		arg.PersonID,
		arg.ServiceDate,
		arg.ProgramID,
	)
	var i GetPersonEnrollmentForStayRow
	err := row.Scan(&i.EnrollmentID, &i.ProgramID)
	return i, err
}

const getProviderProfileForProperty = `-- name: GetProviderProfileForProperty :one
SELECT pp.id AS provider_profile_id
  FROM provider.provider_profile pp
  JOIN accommodation.property p
    ON p.tenant_id = pp.tenant_id AND p.provider_organization_id = pp.tenant_organization_id
 WHERE pp.tenant_id = $1
   AND p.id = $2
   AND pp.status = 'ACTIVE'
 ORDER BY pp.id
 LIMIT 1
`

type GetProviderProfileForPropertyParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

func (q *Queries) GetProviderProfileForProperty(ctx context.Context, arg GetProviderProfileForPropertyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getProviderProfileForProperty, arg.TenantID, arg.PropertyID)
	var provider_profile_id uuid.UUID
	err := row.Scan(&provider_profile_id)
	return provider_profile_id, err
}

const listBookingGuests = `-- name: ListBookingGuests :many
SELECT g.id, g.person_id, g.display_name, g.guest_type, g.is_minor
  FROM accommodation.booking_guest g
 WHERE g.tenant_id = $1
   AND g.booking_id = $2
 ORDER BY g.created_at, g.id
`

type ListBookingGuestsParams struct {
	TenantID  uuid.UUID
	BookingID uuid.UUID
}

type ListBookingGuestsRow struct {
	ID          uuid.UUID
	PersonID    uuid.NullUUID
	DisplayName string
	GuestType   string
	IsMinor     bool
}

func (q *Queries) ListBookingGuests(ctx context.Context, arg ListBookingGuestsParams) ([]ListBookingGuestsRow, error) {
	rows, err := q.db.Query(ctx, listBookingGuests, arg.TenantID, arg.BookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingGuestsRow
	for rows.Next() {
		var i ListBookingGuestsRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.DisplayName,
			&i.GuestType,
			&i.IsMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingNights = `-- name: ListBookingNights :many
SELECT n.stay_date, n.room_type_id, n.unit_amount::text AS unit_amount,
       n.payer_amount::text AS payer_amount, n.member_amount::text AS member_amount,
       n.currency_code
  FROM accommodation.booking_night n
 WHERE n.tenant_id = $1
   AND n.booking_id = $2
 ORDER BY n.stay_date
`

type ListBookingNightsParams struct {
	TenantID  uuid.UUID
	BookingID uuid.UUID
}

type ListBookingNightsRow struct {
	StayDate     pgtype.Date
	RoomTypeID   uuid.UUID
	UnitAmount   string
	PayerAmount  string
	MemberAmount string
	CurrencyCode string
}

func (q *Queries) ListBookingNights(ctx context.Context, arg ListBookingNightsParams) ([]ListBookingNightsRow, error) {
	rows, err := q.db.Query(ctx, listBookingNights, arg.TenantID, arg.BookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingNightsRow
	for rows.Next() {
		var i ListBookingNightsRow
		if err := rows.Scan(
			&i.StayDate,
			&i.RoomTypeID,
			&i.UnitAmount,
			&i.PayerAmount,
			&i.MemberAmount,
			&i.CurrencyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookings = `-- name: ListBookings :many
SELECT b.id, b.reference, b.person_id, b.enrollment_id, b.program_id, b.property_id,
       b.room_type_id, b.check_in, b.check_out, b.nights, b.adults, b.children, b.status,
       b.hold_expires_at, b.entitlement_reservation_id, b.service_request_id,
       b.authorization_id, b.voucher_id, b.quote_snapshot, b.policy_snapshot, b.channel,
       b.confirmed_at, b.checked_in_at, b.checked_out_at, b.cancelled_at,
       b.cancel_reason_code, b.actual_nights, b.created_at, b.updated_at, b.row_version
  FROM accommodation.booking b
  JOIN accommodation.property p
    ON p.tenant_id = b.tenant_id AND p.id = b.property_id
 WHERE b.tenant_id = $1
   AND ($2::uuid[] IS NULL
        OR p.provider_organization_id = ANY($2::uuid[]))
   AND ($3::uuid IS NULL OR b.person_id = $3::uuid)
   AND ($4::uuid IS NULL OR b.property_id = $4::uuid)
   AND ($5::text IS NULL OR b.status = $5::text)
   AND ($6::date IS NULL OR b.check_in >= $6::date)
   AND ($7::date IS NULL OR b.check_in <= $7::date)
   AND ($8::timestamptz IS NULL
        OR (b.created_at, b.id) < ($8::timestamptz, $9::uuid))
 ORDER BY b.created_at DESC, b.id DESC
 LIMIT $10
`

type ListBookingsParams struct {
	TenantID    uuid.UUID
	ScopeIds    []uuid.UUID
	PersonID    uuid.NullUUID
	PropertyID  uuid.NullUUID
	Status      *string
	CheckInFrom pgtype.Date
	CheckInTo   pgtype.Date
	AfterAt     *time.Time
	AfterID     uuid.NullUUID
	PageSize    int32
}

type ListBookingsRow struct {
	ID                       uuid.UUID
	Reference                string
	PersonID                 uuid.UUID
	EnrollmentID             uuid.UUID
	ProgramID                uuid.UUID
	PropertyID               uuid.UUID
	RoomTypeID               uuid.UUID
	CheckIn                  pgtype.Date
	CheckOut                 pgtype.Date
	Nights                   int32
	Adults                   int32
	Children                 int32
	Status                   string
	HoldExpiresAt            *time.Time
	EntitlementReservationID uuid.NullUUID
	ServiceRequestID         uuid.NullUUID
	AuthorizationID          uuid.NullUUID
	VoucherID                uuid.NullUUID
	QuoteSnapshot            []byte
	PolicySnapshot           []byte
	Channel                  string
	ConfirmedAt              *time.Time
	CheckedInAt              *time.Time
	CheckedOutAt             *time.Time
	CancelledAt              *time.Time
	CancelReasonCode         *string
	ActualNights             *int32
	CreatedAt                time.Time
	UpdatedAt                time.Time
	RowVersion               int64
}

// Keyset pagination on (created_at DESC, id DESC), the same shape every list in this
// repository uses; the caller asks for limit+1 rows to learn whether a next page exists.
func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings,
		arg.TenantID,
		arg.ScopeIds,
		arg.PersonID,
		arg.PropertyID,
		arg.Status,
		arg.CheckInFrom,
		arg.CheckInTo,
		arg.AfterAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsRow
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.PersonID,
			&i.EnrollmentID,
			&i.ProgramID,
			&i.PropertyID,
			&i.RoomTypeID,
			&i.CheckIn,
			&i.CheckOut,
			&i.Nights,
			&i.Adults,
			&i.Children,
			&i.Status,
			&i.HoldExpiresAt,
			&i.EntitlementReservationID,
			&i.ServiceRequestID,
			&i.AuthorizationID,
			&i.VoucherID,
			&i.QuoteSnapshot,
			&i.PolicySnapshot,
			&i.Channel,
			&i.ConfirmedAt,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.CancelledAt,
			&i.CancelReasonCode,
			&i.ActualNights,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsForReminder = `-- name: ListBookingsForReminder :many
SELECT b.id, b.reference, b.person_id, b.check_in, p.name AS property_name, p.timezone
  FROM accommodation.booking b
  JOIN accommodation.property p
    ON p.tenant_id = b.tenant_id AND p.id = b.property_id
 WHERE b.tenant_id = $1
   AND b.status = 'CONFIRMED'
   AND b.check_in = $2::date
 ORDER BY b.id
 LIMIT $3
`

type ListBookingsForReminderParams struct {
	TenantID uuid.UUID
	CheckIn  pgtype.Date
	PageSize int32
}

type ListBookingsForReminderRow struct {
	ID           uuid.UUID
	Reference    string
	PersonID     uuid.UUID
	CheckIn      pgtype.Date
	PropertyName string
	Timezone     string
}

// The bookings whose check-in falls on one civil date, with the property's own zone and
// name, for the day-before reminder. The zone comes back with the row because a night
// belongs to the calendar hanging on the wall of that building: a sweep that used one
// tenant-wide zone would remind a member in Berlin on the wrong day.
func (q *Queries) ListBookingsForReminder(ctx context.Context, arg ListBookingsForReminderParams) ([]ListBookingsForReminderRow, error) {
	rows, err := q.db.Query(ctx, listBookingsForReminder, arg.TenantID, arg.CheckIn, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsForReminderRow
	for rows.Next() {
		var i ListBookingsForReminderRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.PersonID,
			&i.CheckIn,
			&i.PropertyName,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredHolds = `-- name: ListExpiredHolds :many
SELECT b.id
  FROM accommodation.booking b
 WHERE b.tenant_id = $1
   AND b.status = 'HOLD'
   AND b.hold_expires_at <= $2
 ORDER BY b.hold_expires_at
 LIMIT $3
   FOR UPDATE SKIP LOCKED
`

type ListExpiredHoldsParams struct {
	TenantID uuid.UUID
	Before   *time.Time
	PageSize int32
}

// The sweep's read: holds past their deadline, taken FOR UPDATE SKIP LOCKED so two
// schedulers that both believe they lead cannot expire the same booking twice, and neither
// waits on the other.
func (q *Queries) ListExpiredHolds(ctx context.Context, arg ListExpiredHoldsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredHolds, arg.TenantID, arg.Before, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBooking = `-- name: LockBooking :one
SELECT b.id, b.reference, b.person_id, b.enrollment_id, b.program_id, b.property_id,
       b.room_type_id, b.check_in, b.check_out, b.nights, b.adults, b.children, b.status,
       b.hold_expires_at, b.entitlement_reservation_id, b.service_request_id,
       b.authorization_id, b.voucher_id, b.quote_snapshot, b.policy_snapshot, b.channel,
       b.confirmed_at, b.checked_in_at, b.checked_out_at, b.cancelled_at,
       b.cancel_reason_code, b.actual_nights, b.created_at, b.updated_at, b.row_version
  FROM accommodation.booking b
 WHERE b.tenant_id = $1
   AND b.id = $2
   FOR UPDATE
`

type LockBookingParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type LockBookingRow struct {
	ID                       uuid.UUID
	Reference                string
	PersonID                 uuid.UUID
	EnrollmentID             uuid.UUID
	ProgramID                uuid.UUID
	PropertyID               uuid.UUID
	RoomTypeID               uuid.UUID
	CheckIn                  pgtype.Date
	CheckOut                 pgtype.Date
	Nights                   int32
	Adults                   int32
	Children                 int32
	Status                   string
	HoldExpiresAt            *time.Time
	EntitlementReservationID uuid.NullUUID
	ServiceRequestID         uuid.NullUUID
	AuthorizationID          uuid.NullUUID
	VoucherID                uuid.NullUUID
	QuoteSnapshot            []byte
	PolicySnapshot           []byte
	Channel                  string
	ConfirmedAt              *time.Time
	CheckedInAt              *time.Time
	CheckedOutAt             *time.Time
	CancelledAt              *time.Time
	CancelReasonCode         *string
	ActualNights             *int32
	CreatedAt                time.Time
	UpdatedAt                time.Time
	RowVersion               int64
}

// The same row FOR UPDATE, for a command that is about to move it. The boundaries are not
// applied here: every caller of this has already found the booking through GetBooking or
// reached it from the outbox, and re-applying a scope inside the lock would mean the
// expiry sweep -- which acts for the tenant and for no provider -- could not take it.
func (q *Queries) LockBooking(ctx context.Context, arg LockBookingParams) (LockBookingRow, error) {
	row := q.db.QueryRow(ctx, lockBooking, arg.TenantID, arg.ID)
	var i LockBookingRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.PersonID,
		&i.EnrollmentID,
		&i.ProgramID,
		&i.PropertyID,
		&i.RoomTypeID,
		&i.CheckIn,
		&i.CheckOut,
		&i.Nights,
		&i.Adults,
		&i.Children,
		&i.Status,
		&i.HoldExpiresAt,
		&i.EntitlementReservationID,
		&i.ServiceRequestID,
		&i.AuthorizationID,
		&i.VoucherID,
		&i.QuoteSnapshot,
		&i.PolicySnapshot,
		&i.Channel,
		&i.ConfirmedAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CancelledAt,
		&i.CancelReasonCode,
		&i.ActualNights,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const lockBookingInventoryRange = `-- name: LockBookingInventoryRange :many


SELECT i.stay_date, i.capacity, i.held, i.confirmed,
       (i.capacity - i.held - i.confirmed)::int AS available
  FROM accommodation.inventory_day i
 WHERE i.tenant_id = $1
   AND i.room_type_id = $2
   AND i.stay_date >= $3::date
   AND i.stay_date <= $4::date
 ORDER BY i.stay_date
   FOR UPDATE
`

type LockBookingInventoryRangeParams struct {
	TenantID   uuid.UUID
	RoomTypeID uuid.UUID
	FromDate   pgtype.Date
	ToDate     pgtype.Date
}

type LockBookingInventoryRangeRow struct {
	StayDate  pgtype.Date
	Capacity  int32
	Held      int32
	Confirmed int32
	Available int32
}

// The hold and the booking it becomes (WP-I6-02, v1.2 10.6 steps 4-7, 11.13, 13.5).
//
// Four things about this file are load-bearing and none of them is repeated in Go.
//
// **The lock order is `stay_date`.** `LockBookingInventoryRange` is the read every hold,
// every release and every confirmation makes before it writes, and it is `ORDER BY
// stay_date ... FOR UPDATE`. That single clause is what turns five hundred concurrent
// holds on the same three nights into a queue rather than a deadlock: every transaction
// takes the same rows in the same order, so none of them can be holding night two while
// waiting for night one that somebody else holds while waiting for night two.
//
// **The counters move by a statement, never by a read-modify-write.** `AddInventoryHeld`
// and `MoveHeldToConfirmed` are `UPDATE ... SET held = held + $n` over the whole range, so
// the arithmetic happens in the database with the row already locked. The CHECK
// `held + confirmed <= capacity` of migration 000040 is the belt: if the availability
// check above were deleted tomorrow these statements would still fail rather than
// oversell.
//
// **A booking is found through its own boundary.** `scope_ids` is the provider boundary
// (NULL means the whole tenant) and `person_id` is the member boundary; both are applied
// in the WHERE rather than after the read, because a filter applied after a LIMIT is a
// filter that has already been defeated.
//
// **Money is `numeric(20,6)` returned as `::text`.** The decimal the member was shown is
// the decimal that comes back; nothing here passes through a float.
// ---------------------------------------------------------------------------
// Inventory under the lock
// ---------------------------------------------------------------------------
// The nights of `[check_in, check_out)`, locked in stay_date order. It is separate from
// LockRoomTypeInventoryRange only in what it returns -- the availability as well as the
// counters -- because the hold refuses on `capacity - held - confirmed < 1` and the
// allotment writer refuses on `held + confirmed > capacity`, and each should read the
// number it decides on rather than subtract for itself.
func (q *Queries) LockBookingInventoryRange(ctx context.Context, arg LockBookingInventoryRangeParams) ([]LockBookingInventoryRangeRow, error) {
	rows, err := q.db.Query(ctx, lockBookingInventoryRange,
		arg.TenantID,
		arg.RoomTypeID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockBookingInventoryRangeRow
	for rows.Next() {
		var i LockBookingInventoryRangeRow
		if err := rows.Scan(
			&i.StayDate,
			&i.Capacity,
			&i.Held,
			&i.Confirmed,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBookingPendingApproval = `-- name: MarkBookingPendingApproval :execrows
UPDATE accommodation.booking
   SET status = 'PENDING_APPROVAL', hold_expires_at = $1,
       updated_by = $2
 WHERE tenant_id = $3
   AND id = $4
   AND status = 'HOLD'
`

type MarkBookingPendingApprovalParams struct {
	HoldExpiresAt *time.Time
	ActorID       uuid.NullUUID
	TenantID      uuid.UUID
	ID            uuid.UUID
}

// A reviewer has the request and the room is not lost while they decide: the status moves
// and the countdown is pushed out to the request's own SLA.
func (q *Queries) MarkBookingPendingApproval(ctx context.Context, arg MarkBookingPendingApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBookingPendingApproval,
		arg.HoldExpiresAt,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveHeldToConfirmed = `-- name: MoveHeldToConfirmed :execrows
UPDATE accommodation.inventory_day
   SET held = held - 1, confirmed = confirmed + 1
 WHERE tenant_id = $1
   AND room_type_id = $2
   AND stay_date >= $3::date
   AND stay_date <= $4::date
`

type MoveHeldToConfirmedParams struct {
	TenantID   uuid.UUID
	RoomTypeID uuid.UUID
	FromDate   pgtype.Date
	ToDate     pgtype.Date
}

// Confirmation: the room stops being held and starts being taken. It is one statement
// rather than a decrement and an increment because the two halves must not be separable --
// a transaction that ran only the first would give a confirmed room back to the pool.
func (q *Queries) MoveHeldToConfirmed(ctx context.Context, arg MoveHeldToConfirmedParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveHeldToConfirmed,
		arg.TenantID,
		arg.RoomTypeID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBookingRequest = `-- name: SetBookingRequest :execrows
UPDATE accommodation.booking
   SET service_request_id = $1, updated_by = $2
 WHERE tenant_id = $3
   AND id = $4
   AND status = 'HOLD'
   AND service_request_id IS NULL
`

type SetBookingRequestParams struct {
	ServiceRequestID uuid.NullUUID
	ActorID          uuid.NullUUID
	TenantID         uuid.UUID
	ID               uuid.UUID
}

// The RESERVATION request the confirmation raised, written in the same transaction that
// raised it. The HOLD predicate is what makes a replayed confirmation a no-op rather than
// a second request.
func (q *Queries) SetBookingRequest(ctx context.Context, arg SetBookingRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBookingRequest,
		arg.ServiceRequestID,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBookingReservation = `-- name: SetBookingReservation :execrows
UPDATE accommodation.booking
   SET entitlement_reservation_id = $1
 WHERE tenant_id = $2
   AND id = $3
`

type SetBookingReservationParams struct {
	EntitlementReservationID uuid.NullUUID
	TenantID                 uuid.UUID
	ID                       uuid.UUID
}

// The plan's hold, written onto the booking the statement above inserted. It is a second
// statement rather than a column of the insert because the reservation references the
// booking: the row has to exist before anything can point at it, and the whole pair is one
// transaction so neither half can be committed without the other.
func (q *Queries) SetBookingReservation(ctx context.Context, arg SetBookingReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBookingReservation, arg.EntitlementReservationID, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBookingVoucher = `-- name: SetBookingVoucher :execrows
UPDATE accommodation.booking
   SET voucher_id = $1, updated_by = $2
 WHERE tenant_id = $3
   AND id = $4
`

type SetBookingVoucherParams struct {
	VoucherID uuid.NullUUID
	ActorID   uuid.NullUUID
	TenantID  uuid.UUID
	ID        uuid.UUID
}

// The voucher row this booking's proof of entitlement is. It is the id and never the
// token: the plaintext exists in one response body and in no column anywhere.
func (q *Queries) SetBookingVoucher(ctx context.Context, arg SetBookingVoucherParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBookingVoucher,
		arg.VoucherID,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
