// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accommodation.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProperty = `-- name: CreateProperty :one


INSERT INTO accommodation.property (
    tenant_id, provider_organization_id, location_id, code, name, property_type,
    timezone, city, region_code, amenities, cost_center, status, created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8, $9,
        $10, $11, $12,
        $13, $13)
RETURNING id, provider_organization_id, location_id, code, name, property_type, timezone,
          city, region_code, amenities, cost_center, status, created_at, updated_at, row_version
`

type CreatePropertyParams struct {
	TenantID               uuid.UUID
	ProviderOrganizationID uuid.UUID
	LocationID             uuid.NullUUID
	Code                   string
	Name                   string
	PropertyType           string
	Timezone               string
	City                   *string
	RegionCode             *string
	Amenities              []byte
	CostCenter             *string
	Status                 string
	ActorID                uuid.NullUUID
}

type CreatePropertyRow struct {
	ID                     uuid.UUID
	ProviderOrganizationID uuid.UUID
	LocationID             uuid.NullUUID
	Code                   string
	Name                   string
	PropertyType           string
	Timezone               string
	City                   *string
	RegionCode             *string
	Amenities              []byte
	CostCenter             *string
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	RowVersion             int64
}

// Property, room type, daily inventory and the availability search (WP-I6-01, v1.2 9.13,
// 10.6, 11.11, 16.7).
//
// Three properties shape this file.
//
// **`accommodation.inventory_day` is the only place a room is counted.** There is no
// statement here that derives availability from bookings, and none that stores a
// room-type-level total. `available` is `capacity - held - confirmed` and it is computed
// in SQL rather than on a screen, so two screens cannot disagree about it.
//
// **A missing inventory row is not zero and not unlimited: it is no allotment.** The range
// read below returns the minimum availability *and the number of rows it saw*, because
// those are two different facts. A room type with capacity on twenty-nine of thirty nights
// has a healthy minimum and is not available for the stay, and only the count says so.
//
// **The provider boundary is `scope_ids`**, the same nullable `uuid[]` of tenant
// organization ids the health and service-request queries apply: NULL means the caller
// sees the whole tenant, a non-null array binds it to those organizations. It is applied
// on the single-row reads too, so another provider's room type is 404 rather than 403 --
// that it exists at all is not this caller's business.
//
// Money is `numeric(20,6)` and never touches a float: the candidate read below returns
// every amount as `::text`, exactly as db/queries/contract.sql does, so the decimal the
// contract states is the decimal the quote sums.
// ---------------------------------------------------------------------------
// Property
// ---------------------------------------------------------------------------
func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (CreatePropertyRow, error) {
	row := q.db.QueryRow(ctx, createProperty,
		arg.TenantID,
		arg.ProviderOrganizationID,
		arg.LocationID,
		arg.Code,
		arg.Name,
		arg.PropertyType,
		arg.Timezone,
		arg.City,
		arg.RegionCode,
		arg.Amenities,
		arg.CostCenter,
		arg.Status,
		arg.ActorID,
	)
	var i CreatePropertyRow
	err := row.Scan(
		&i.ID,
		&i.ProviderOrganizationID,
		&i.LocationID,
		&i.Code,
		&i.Name,
		&i.PropertyType,
		&i.Timezone,
		&i.City,
		&i.RegionCode,
		&i.Amenities,
		&i.CostCenter,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const createRoomType = `-- name: CreateRoomType :one

INSERT INTO accommodation.room_type (
    tenant_id, property_id, code, name, max_adults, max_children, max_occupancy,
    attributes, service_definition_id, status, created_by, updated_by)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10,
        $11, $11)
RETURNING id, property_id, code, name, max_adults, max_children, max_occupancy,
          attributes, service_definition_id, status, created_at, updated_at, row_version
`

type CreateRoomTypeParams struct {
	TenantID            uuid.UUID
	PropertyID          uuid.UUID
	Code                string
	Name                string
	MaxAdults           int32
	MaxChildren         int32
	MaxOccupancy        int32
	Attributes          []byte
	ServiceDefinitionID uuid.UUID
	Status              string
	ActorID             uuid.NullUUID
}

type CreateRoomTypeRow struct {
	ID                  uuid.UUID
	PropertyID          uuid.UUID
	Code                string
	Name                string
	MaxAdults           int32
	MaxChildren         int32
	MaxOccupancy        int32
	Attributes          []byte
	ServiceDefinitionID uuid.UUID
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	RowVersion          int64
}

// ---------------------------------------------------------------------------
// Room type
// ---------------------------------------------------------------------------
func (q *Queries) CreateRoomType(ctx context.Context, arg CreateRoomTypeParams) (CreateRoomTypeRow, error) {
	row := q.db.QueryRow(ctx, createRoomType,
		arg.TenantID,
		arg.PropertyID,
		arg.Code,
		arg.Name,
		arg.MaxAdults,
		arg.MaxChildren,
		arg.MaxOccupancy,
		arg.Attributes,
		arg.ServiceDefinitionID,
		arg.Status,
		arg.ActorID,
	)
	var i CreateRoomTypeRow
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.MaxAdults,
		&i.MaxChildren,
		&i.MaxOccupancy,
		&i.Attributes,
		&i.ServiceDefinitionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getProperty = `-- name: GetProperty :one
SELECT p.id, p.provider_organization_id, p.location_id, p.code, p.name, p.property_type,
       p.timezone, p.city, p.region_code, p.amenities, p.cost_center, p.status,
       p.created_at, p.updated_at, p.row_version
  FROM accommodation.property p
 WHERE p.tenant_id = $1
   AND p.id = $2
   AND ($3::uuid[] IS NULL
        OR p.provider_organization_id = ANY($3::uuid[]))
`

type GetPropertyParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type GetPropertyRow struct {
	ID                     uuid.UUID
	ProviderOrganizationID uuid.UUID
	LocationID             uuid.NullUUID
	Code                   string
	Name                   string
	PropertyType           string
	Timezone               string
	City                   *string
	RegionCode             *string
	Amenities              []byte
	CostCenter             *string
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	RowVersion             int64
}

func (q *Queries) GetProperty(ctx context.Context, arg GetPropertyParams) (GetPropertyRow, error) {
	row := q.db.QueryRow(ctx, getProperty, arg.TenantID, arg.ID, arg.ScopeIds)
	var i GetPropertyRow
	err := row.Scan(
		&i.ID,
		&i.ProviderOrganizationID,
		&i.LocationID,
		&i.Code,
		&i.Name,
		&i.PropertyType,
		&i.Timezone,
		&i.City,
		&i.RegionCode,
		&i.Amenities,
		&i.CostCenter,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getRoomType = `-- name: GetRoomType :one
SELECT r.id, r.property_id, r.code, r.name, r.max_adults, r.max_children, r.max_occupancy,
       r.attributes, r.service_definition_id, r.status, r.created_at, r.updated_at, r.row_version,
       p.provider_organization_id, p.timezone AS property_timezone, p.status AS property_status
  FROM accommodation.room_type r
  JOIN accommodation.property p ON p.tenant_id = r.tenant_id AND p.id = r.property_id
 WHERE r.tenant_id = $1
   AND r.id = $2
   AND ($3::uuid[] IS NULL
        OR p.provider_organization_id = ANY($3::uuid[]))
`

type GetRoomTypeParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type GetRoomTypeRow struct {
	ID                     uuid.UUID
	PropertyID             uuid.UUID
	Code                   string
	Name                   string
	MaxAdults              int32
	MaxChildren            int32
	MaxOccupancy           int32
	Attributes             []byte
	ServiceDefinitionID    uuid.UUID
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	RowVersion             int64
	ProviderOrganizationID uuid.UUID
	PropertyTimezone       string
	PropertyStatus         string
}

// The property is joined rather than trusted, so the provider boundary reaches a room type
// through the building it belongs to: another provider's room type is no row at all.
func (q *Queries) GetRoomType(ctx context.Context, arg GetRoomTypeParams) (GetRoomTypeRow, error) {
	row := q.db.QueryRow(ctx, getRoomType, arg.TenantID, arg.ID, arg.ScopeIds)
	var i GetRoomTypeRow
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.MaxAdults,
		&i.MaxChildren,
		&i.MaxOccupancy,
		&i.Attributes,
		&i.ServiceDefinitionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
		&i.ProviderOrganizationID,
		&i.PropertyTimezone,
		&i.PropertyStatus,
	)
	return i, err
}

const getRoomTypeInventoryRange = `-- name: GetRoomTypeInventoryRange :many

SELECT i.stay_date, i.capacity, i.held, i.confirmed,
       (i.capacity - i.held - i.confirmed)::int AS available,
       i.updated_at, i.row_version
  FROM accommodation.inventory_day i
 WHERE i.tenant_id = $1
   AND i.room_type_id = $2
   AND i.stay_date >= $3::date
   AND i.stay_date <= $4::date
 ORDER BY i.stay_date
`

type GetRoomTypeInventoryRangeParams struct {
	TenantID   uuid.UUID
	RoomTypeID uuid.UUID
	FromDate   pgtype.Date
	ToDate     pgtype.Date
}

type GetRoomTypeInventoryRangeRow struct {
	StayDate   pgtype.Date
	Capacity   int32
	Held       int32
	Confirmed  int32
	Available  int32
	UpdatedAt  time.Time
	RowVersion int64
}

// ---------------------------------------------------------------------------
// Daily inventory
// ---------------------------------------------------------------------------
// `available` is computed here and nowhere else, so no screen subtracts. The rows that
// exist are returned; the caller fills the gaps with "no allotment", which is a different
// statement from "zero free" and has to stay one.
func (q *Queries) GetRoomTypeInventoryRange(ctx context.Context, arg GetRoomTypeInventoryRangeParams) ([]GetRoomTypeInventoryRangeRow, error) {
	rows, err := q.db.Query(ctx, getRoomTypeInventoryRange,
		arg.TenantID,
		arg.RoomTypeID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomTypeInventoryRangeRow
	for rows.Next() {
		var i GetRoomTypeInventoryRangeRow
		if err := rows.Scan(
			&i.StayDate,
			&i.Capacity,
			&i.Held,
			&i.Confirmed,
			&i.Available,
			&i.UpdatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccommodationPriceCandidates = `-- name: ListAccommodationPriceCandidates :many
SELECT i.id AS price_item_id, i.price_list_id, l.contract_version_id,
       i.service_definition_id, i.service_category_id, i.package_definition_id,
       i.location_id, i.valid_from, i.valid_to, i.priority AS item_priority,
       i.unit_type, i.pricing_method,
       coalesce(i.amount::text, '')::text AS amount,
       coalesce(i.percent::text, '')::text AS percent,
       i.formula_key,
       coalesce(i.min_amount::text, '')::text AS min_amount,
       coalesce(i.max_amount::text, '')::text AS max_amount,
       i.member_share_method,
       coalesce(i.member_share_amount::text, '')::text AS member_share_amount,
       coalesce(i.member_share_percent::text, '')::text AS member_share_percent,
       l.code AS price_list_code, l.priority AS list_priority,
       l.season_from, l.season_to, l.weekday_mask,
       v.version_no, v.currency_code, v.valid_from AS version_valid_from, v.valid_to AS version_valid_to,
       c.id AS contract_id, c.code AS contract_code, c.provider_profile_id
  FROM contract.price_item i
  JOIN contract.price_list l ON l.tenant_id = i.tenant_id AND l.id = i.price_list_id
  JOIN contract.contract_version v ON v.tenant_id = l.tenant_id AND v.id = l.contract_version_id
  JOIN contract.contract c ON c.tenant_id = v.tenant_id AND c.id = v.contract_id
 WHERE i.tenant_id = $1
   AND v.status = 'PUBLISHED'
   AND c.status = 'ACTIVE'
   AND c.provider_profile_id = ANY($2::uuid[])
   AND v.valid_from <= $3::date
   AND (v.valid_to IS NULL OR v.valid_to > $4::date)
   AND (i.service_definition_id = ANY($5::uuid[])
        OR i.service_category_id = ANY($6::uuid[])
        OR i.package_definition_id = ANY($7::uuid[]))
 ORDER BY i.id
`

type ListAccommodationPriceCandidatesParams struct {
	TenantID             uuid.UUID
	ProviderProfileIds   []uuid.UUID
	LastNight            pgtype.Date
	CheckIn              pgtype.Date
	ServiceDefinitionIds []uuid.UUID
	CategoryIds          []uuid.UUID
	PackageIds           []uuid.UUID
}

type ListAccommodationPriceCandidatesRow struct {
	PriceItemID         uuid.UUID
	PriceListID         uuid.UUID
	ContractVersionID   uuid.UUID
	ServiceDefinitionID uuid.NullUUID
	ServiceCategoryID   uuid.NullUUID
	PackageDefinitionID uuid.NullUUID
	LocationID          uuid.NullUUID
	ValidFrom           pgtype.Date
	ValidTo             pgtype.Date
	ItemPriority        int32
	UnitType            string
	PricingMethod       string
	Amount              string
	Percent             string
	FormulaKey          *string
	MinAmount           string
	MaxAmount           string
	MemberShareMethod   string
	MemberShareAmount   string
	MemberSharePercent  string
	PriceListCode       string
	ListPriority        int32
	SeasonFrom          pgtype.Date
	SeasonTo            pgtype.Date
	WeekdayMask         *int16
	VersionNo           int32
	CurrencyCode        string
	VersionValidFrom    pgtype.Date
	VersionValidTo      pgtype.Date
	ContractID          uuid.UUID
	ContractCode        string
	ProviderProfileID   uuid.UUID
}

// Every contracted price that could apply to any of these room types on any night of the
// stay, loaded once for the whole search. It is db/queries/contract.sql's
// ListPriceCandidates widened in two ways and narrowed in none: the service date becomes a
// half-open range, and the provider becomes a set, because a search over a region asks
// about several hotels and thirty nights and one round trip per pair would be a thousand.
//
// The version's own period comes back with the row, so the caller can decide per night
// which candidates were in force -- the filtering the single-date query does in its WHERE.
// Season, weekday, item period, location and the specificity ladder stay in
// internal/contract/selection, which is the only place any of them is judged.
func (q *Queries) ListAccommodationPriceCandidates(ctx context.Context, arg ListAccommodationPriceCandidatesParams) ([]ListAccommodationPriceCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAccommodationPriceCandidates,
		arg.TenantID,
		arg.ProviderProfileIds,
		arg.LastNight,
		arg.CheckIn,
		arg.ServiceDefinitionIds,
		arg.CategoryIds,
		arg.PackageIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccommodationPriceCandidatesRow
	for rows.Next() {
		var i ListAccommodationPriceCandidatesRow
		if err := rows.Scan(
			&i.PriceItemID,
			&i.PriceListID,
			&i.ContractVersionID,
			&i.ServiceDefinitionID,
			&i.ServiceCategoryID,
			&i.PackageDefinitionID,
			&i.LocationID,
			&i.ValidFrom,
			&i.ValidTo,
			&i.ItemPriority,
			&i.UnitType,
			&i.PricingMethod,
			&i.Amount,
			&i.Percent,
			&i.FormulaKey,
			&i.MinAmount,
			&i.MaxAmount,
			&i.MemberShareMethod,
			&i.MemberShareAmount,
			&i.MemberSharePercent,
			&i.PriceListCode,
			&i.ListPriority,
			&i.SeasonFrom,
			&i.SeasonTo,
			&i.WeekdayMask,
			&i.VersionNo,
			&i.CurrencyCode,
			&i.VersionValidFrom,
			&i.VersionValidTo,
			&i.ContractID,
			&i.ContractCode,
			&i.ProviderProfileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityProperties = `-- name: ListAvailabilityProperties :many

SELECT p.id, p.provider_organization_id, p.location_id, p.code, p.name, p.property_type,
       p.timezone, p.city, p.region_code, p.amenities, p.cost_center, p.status,
       p.created_at, p.updated_at, p.row_version,
       pp.id AS provider_profile_id
  FROM accommodation.property p
  JOIN provider.provider_profile pp
    ON pp.tenant_id = p.tenant_id AND pp.tenant_organization_id = p.provider_organization_id
 WHERE p.tenant_id = $1
   AND p.status = 'ACTIVE'
   AND pp.status = 'ACTIVE'
   AND ($2::uuid IS NULL OR p.id = $2::uuid)
   AND ($3::text IS NULL OR p.region_code = $3::text)
   AND ($4::uuid[] IS NULL
        OR p.provider_organization_id = ANY($4::uuid[]))
   AND EXISTS (
        SELECT 1
          FROM contract.contract c
          JOIN contract.contract_version v
            ON v.tenant_id = c.tenant_id AND v.contract_id = c.id
         WHERE c.tenant_id = p.tenant_id
           AND c.provider_profile_id = pp.id
           AND c.status = 'ACTIVE'
           AND v.status = 'PUBLISHED'
           AND v.valid_from <= $5::date
           AND (v.valid_to IS NULL OR v.valid_to > $6::date)
           AND ($7::uuid[] IS NULL
                OR c.payer_organization_id = ANY($7::uuid[])))
 ORDER BY p.name, p.id
 LIMIT $8
`

type ListAvailabilityPropertiesParams struct {
	TenantID             uuid.UUID
	PropertyID           uuid.NullUUID
	RegionCode           *string
	ScopeIds             []uuid.UUID
	LastNight            pgtype.Date
	CheckIn              pgtype.Date
	PayerOrganizationIds []uuid.UUID
	PageSize             int32
}

type ListAvailabilityPropertiesRow struct {
	ID                     uuid.UUID
	ProviderOrganizationID uuid.UUID
	LocationID             uuid.NullUUID
	Code                   string
	Name                   string
	PropertyType           string
	Timezone               string
	City                   *string
	RegionCode             *string
	Amenities              []byte
	CostCenter             *string
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	RowVersion             int64
	ProviderProfileID      uuid.UUID
}

// ---------------------------------------------------------------------------
// Availability search
// ---------------------------------------------------------------------------
// The properties a search may answer with: ACTIVE buildings of ACTIVE providers that hold
// an ACTIVE contract, published over the stay, with one of the payer organizations behind
// the person's programs. `payer_organization_ids` NULL is a back-office search that is not
// narrowed to one member's programs; a member's own search always carries the array, so a
// hotel nobody contracted for their program is not on the list at all.
func (q *Queries) ListAvailabilityProperties(ctx context.Context, arg ListAvailabilityPropertiesParams) ([]ListAvailabilityPropertiesRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityProperties,
		arg.TenantID,
		arg.PropertyID,
		arg.RegionCode,
		arg.ScopeIds,
		arg.LastNight,
		arg.CheckIn,
		arg.PayerOrganizationIds,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailabilityPropertiesRow
	for rows.Next() {
		var i ListAvailabilityPropertiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderOrganizationID,
			&i.LocationID,
			&i.Code,
			&i.Name,
			&i.PropertyType,
			&i.Timezone,
			&i.City,
			&i.RegionCode,
			&i.Amenities,
			&i.CostCenter,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
			&i.ProviderProfileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonProgramPayers = `-- name: ListPersonProgramPayers :many
SELECT DISTINCT pr.payer_tenant_organization_id AS payer_organization_id
  FROM benefit.enrollment e
  JOIN party.sponsor_membership m ON m.tenant_id = e.tenant_id AND m.id = e.sponsor_membership_id
  JOIN benefit.plan pl ON pl.tenant_id = e.tenant_id AND pl.id = e.plan_id
  JOIN benefit.program pr ON pr.tenant_id = pl.tenant_id AND pr.id = pl.program_id
 WHERE e.tenant_id = $1
   AND m.person_id = $2
   AND e.status = 'ACTIVE'
   AND pr.status = 'ACTIVE'
   AND e.valid_period @> $3::date
   AND ($4::uuid IS NULL OR pr.id = $4::uuid)
`

type ListPersonProgramPayersParams struct {
	TenantID    uuid.UUID
	PersonID    uuid.UUID
	ServiceDate pgtype.Date
	ProgramID   uuid.NullUUID
}

// The payer organizations behind the programs this person is actually enrolled in on the
// stay's first night. It is what narrows a search to the hotels somebody contracted for
// this member, and it is a read of the enrollment rather than of the request: a member
// cannot widen it by naming a program.
func (q *Queries) ListPersonProgramPayers(ctx context.Context, arg ListPersonProgramPayersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPersonProgramPayers,
		arg.TenantID,
		arg.PersonID,
		arg.ServiceDate,
		arg.ProgramID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var payer_organization_id uuid.UUID
		if err := rows.Scan(&payer_organization_id); err != nil {
			return nil, err
		}
		items = append(items, payer_organization_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProperties = `-- name: ListProperties :many
SELECT p.id, p.provider_organization_id, p.location_id, p.code, p.name, p.property_type,
       p.timezone, p.city, p.region_code, p.amenities, p.cost_center, p.status,
       p.created_at, p.updated_at, p.row_version
  FROM accommodation.property p
 WHERE p.tenant_id = $1
   AND ($2::uuid[] IS NULL
        OR p.provider_organization_id = ANY($2::uuid[]))
   AND ($3::uuid IS NULL
        OR p.provider_organization_id = $3::uuid)
   AND ($4::text IS NULL OR p.status = $4::text)
   AND ($5::text IS NULL OR p.property_type = $5::text)
   AND ($6::text IS NULL OR p.region_code = $6::text)
   AND ($7::text IS NULL OR p.city = $7::text)
   AND ($8::timestamptz IS NULL
        OR (p.created_at, p.id) < ($8::timestamptz, $9::uuid))
 ORDER BY p.created_at DESC, p.id DESC
 LIMIT $10
`

type ListPropertiesParams struct {
	TenantID               uuid.UUID
	ScopeIds               []uuid.UUID
	ProviderOrganizationID uuid.NullUUID
	Status                 *string
	PropertyType           *string
	RegionCode             *string
	City                   *string
	AfterAt                *time.Time
	AfterID                uuid.NullUUID
	PageSize               int32
}

type ListPropertiesRow struct {
	ID                     uuid.UUID
	ProviderOrganizationID uuid.UUID
	LocationID             uuid.NullUUID
	Code                   string
	Name                   string
	PropertyType           string
	Timezone               string
	City                   *string
	RegionCode             *string
	Amenities              []byte
	CostCenter             *string
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	RowVersion             int64
}

// Keyset pagination on (created_at DESC, id DESC); the caller asks for limit+1 rows to
// learn whether a next page exists.
func (q *Queries) ListProperties(ctx context.Context, arg ListPropertiesParams) ([]ListPropertiesRow, error) {
	rows, err := q.db.Query(ctx, listProperties,
		arg.TenantID,
		arg.ScopeIds,
		arg.ProviderOrganizationID,
		arg.Status,
		arg.PropertyType,
		arg.RegionCode,
		arg.City,
		arg.AfterAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPropertiesRow
	for rows.Next() {
		var i ListPropertiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderOrganizationID,
			&i.LocationID,
			&i.Code,
			&i.Name,
			&i.PropertyType,
			&i.Timezone,
			&i.City,
			&i.RegionCode,
			&i.Amenities,
			&i.CostCenter,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomTypes = `-- name: ListRoomTypes :many
SELECT r.id, r.property_id, r.code, r.name, r.max_adults, r.max_children, r.max_occupancy,
       r.attributes, r.service_definition_id, r.status, r.created_at, r.updated_at, r.row_version
  FROM accommodation.room_type r
  JOIN accommodation.property p ON p.tenant_id = r.tenant_id AND p.id = r.property_id
 WHERE r.tenant_id = $1
   AND r.property_id = $2
   AND ($3::uuid[] IS NULL
        OR p.provider_organization_id = ANY($3::uuid[]))
   AND ($4::text IS NULL OR r.status = $4::text)
 ORDER BY r.code, r.id
`

type ListRoomTypesParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	ScopeIds   []uuid.UUID
	Status     *string
}

type ListRoomTypesRow struct {
	ID                  uuid.UUID
	PropertyID          uuid.UUID
	Code                string
	Name                string
	MaxAdults           int32
	MaxChildren         int32
	MaxOccupancy        int32
	Attributes          []byte
	ServiceDefinitionID uuid.UUID
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	RowVersion          int64
}

func (q *Queries) ListRoomTypes(ctx context.Context, arg ListRoomTypesParams) ([]ListRoomTypesRow, error) {
	rows, err := q.db.Query(ctx, listRoomTypes,
		arg.TenantID,
		arg.PropertyID,
		arg.ScopeIds,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomTypesRow
	for rows.Next() {
		var i ListRoomTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Code,
			&i.Name,
			&i.MaxAdults,
			&i.MaxChildren,
			&i.MaxOccupancy,
			&i.Attributes,
			&i.ServiceDefinitionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomTypesForAvailability = `-- name: ListRoomTypesForAvailability :many
SELECT r.id, r.property_id, r.code, r.name, r.max_adults, r.max_children, r.max_occupancy,
       r.attributes, r.service_definition_id, r.status,
       r.created_at, r.updated_at, r.row_version
  FROM accommodation.room_type r
 WHERE r.tenant_id = $1
   AND r.property_id = ANY($2::uuid[])
   AND r.status = 'ACTIVE'
   AND r.max_adults >= $3
   AND r.max_children >= $4
   AND r.max_occupancy >= $5
 ORDER BY r.property_id, r.code, r.id
`

type ListRoomTypesForAvailabilityParams struct {
	TenantID    uuid.UUID
	PropertyIds []uuid.UUID
	Adults      int32
	Children    int32
	Guests      int32
}

type ListRoomTypesForAvailabilityRow struct {
	ID                  uuid.UUID
	PropertyID          uuid.UUID
	Code                string
	Name                string
	MaxAdults           int32
	MaxChildren         int32
	MaxOccupancy        int32
	Attributes          []byte
	ServiceDefinitionID uuid.UUID
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	RowVersion          int64
}

// The ACTIVE room types of those buildings that could hold the party at all. The occupancy
// filter is here rather than in Go because a room that cannot take the guests is not an
// answer with a caveat, it is not an answer.
func (q *Queries) ListRoomTypesForAvailability(ctx context.Context, arg ListRoomTypesForAvailabilityParams) ([]ListRoomTypesForAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listRoomTypesForAvailability,
		arg.TenantID,
		arg.PropertyIds,
		arg.Adults,
		arg.Children,
		arg.Guests,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomTypesForAvailabilityRow
	for rows.Next() {
		var i ListRoomTypesForAvailabilityRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Code,
			&i.Name,
			&i.MaxAdults,
			&i.MaxChildren,
			&i.MaxOccupancy,
			&i.Attributes,
			&i.ServiceDefinitionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoomTypeInventoryRange = `-- name: LockRoomTypeInventoryRange :many
SELECT i.stay_date, i.capacity, i.held, i.confirmed
  FROM accommodation.inventory_day i
 WHERE i.tenant_id = $1
   AND i.room_type_id = $2
   AND i.stay_date >= $3::date
   AND i.stay_date <= $4::date
 ORDER BY i.stay_date
   FOR UPDATE
`

type LockRoomTypeInventoryRangeParams struct {
	TenantID   uuid.UUID
	RoomTypeID uuid.UUID
	FromDate   pgtype.Date
	ToDate     pgtype.Date
}

type LockRoomTypeInventoryRangeRow struct {
	StayDate  pgtype.Date
	Capacity  int32
	Held      int32
	Confirmed int32
}

// The read the allotment writer makes before it writes, in `stay_date` order -- the same
// order WP-I6-02 locks these rows in, so a season being opened and a hold being taken
// cannot deadlock each other. It returns what is already committed on each night, which is
// what decides whether a new capacity is below what has been promised.
func (q *Queries) LockRoomTypeInventoryRange(ctx context.Context, arg LockRoomTypeInventoryRangeParams) ([]LockRoomTypeInventoryRangeRow, error) {
	rows, err := q.db.Query(ctx, lockRoomTypeInventoryRange,
		arg.TenantID,
		arg.RoomTypeID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockRoomTypeInventoryRangeRow
	for rows.Next() {
		var i LockRoomTypeInventoryRangeRow
		if err := rows.Scan(
			&i.StayDate,
			&i.Capacity,
			&i.Held,
			&i.Confirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoomTypeInventoryCapacity = `-- name: SetRoomTypeInventoryCapacity :execrows
INSERT INTO accommodation.inventory_day (tenant_id, room_type_id, stay_date, capacity)
SELECT $1::uuid, $2::uuid, d::date, $3::int
  FROM generate_series($4::date, $5::date, interval '1 day') AS d
ON CONFLICT (tenant_id, room_type_id, stay_date)
DO UPDATE SET capacity = EXCLUDED.capacity
`

type SetRoomTypeInventoryCapacityParams struct {
	TenantID   uuid.UUID
	RoomTypeID uuid.UUID
	Capacity   int32
	FromDate   pgtype.Date
	ToDate     pgtype.Date
}

// A whole season in one statement: one row per day of the range, capacity set, `held` and
// `confirmed` untouched on the days that already exist. The CHECK on the table is the last
// word -- if a day's commitment exceeds the new capacity this statement fails and the
// transaction takes the range with it, which is the only correct outcome for an allotment
// that was meant to apply to the whole season.
func (q *Queries) SetRoomTypeInventoryCapacity(ctx context.Context, arg SetRoomTypeInventoryCapacityParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRoomTypeInventoryCapacity,
		arg.TenantID,
		arg.RoomTypeID,
		arg.Capacity,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const summariseInventoryOverRange = `-- name: SummariseInventoryOverRange :many
SELECT i.room_type_id,
       min(i.capacity - i.held - i.confirmed)::int AS min_available,
       count(*)::int AS night_count
  FROM accommodation.inventory_day i
 WHERE i.tenant_id = $1
   AND i.room_type_id = ANY($2::uuid[])
   AND i.stay_date >= $3::date
   AND i.stay_date <= $4::date
 GROUP BY i.room_type_id
`

type SummariseInventoryOverRangeParams struct {
	TenantID    uuid.UUID
	RoomTypeIds []uuid.UUID
	FromDate    pgtype.Date
	ToDate      pgtype.Date
}

type SummariseInventoryOverRangeRow struct {
	RoomTypeID   uuid.UUID
	MinAvailable int32
	NightCount   int32
}

// The two facts the search needs about each room type over the stay, in one pass: the
// smallest number of rooms free on any night it has a row for, and how many nights it has
// a row for at all. The second is not decoration -- a room type with an allotment on every
// night but one has a perfectly healthy minimum and is not available, and nothing but the
// count says so.
func (q *Queries) SummariseInventoryOverRange(ctx context.Context, arg SummariseInventoryOverRangeParams) ([]SummariseInventoryOverRangeRow, error) {
	rows, err := q.db.Query(ctx, summariseInventoryOverRange,
		arg.TenantID,
		arg.RoomTypeIds,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummariseInventoryOverRangeRow
	for rows.Next() {
		var i SummariseInventoryOverRangeRow
		if err := rows.Scan(&i.RoomTypeID, &i.MinAvailable, &i.NightCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProperty = `-- name: UpdateProperty :execrows
UPDATE accommodation.property
   SET location_id   = $1,
       name          = $2,
       property_type = $3,
       timezone      = $4,
       city          = $5,
       region_code   = $6,
       amenities     = $7,
       cost_center   = $8,
       status        = $9,
       updated_by    = $10
 WHERE tenant_id = $11
   AND id = $12
   AND row_version = $13
   AND ($14::uuid[] IS NULL
        OR provider_organization_id = ANY($14::uuid[]))
`

type UpdatePropertyParams struct {
	LocationID         uuid.NullUUID
	Name               string
	PropertyType       string
	Timezone           string
	City               *string
	RegionCode         *string
	Amenities          []byte
	CostCenter         *string
	Status             string
	ActorID            uuid.NullUUID
	TenantID           uuid.UUID
	ID                 uuid.UUID
	ExpectedRowVersion int64
	ScopeIds           []uuid.UUID
}

// Every field is sent every time (the contract's PatchProperty says so), so this is plain
// assignment and not a merge: a merge would make "this hotel no longer has a location" and
// "this hotel has a cost centre no more" inexpressible, and a property that cannot be
// un-set is a property somebody edits by hand in the database.
//
// The whole precondition is the predicate: a property somebody else has moved since the
// caller read it, or one outside the caller's provider scope, matches no row and updates
// nothing.
func (q *Queries) UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProperty,
		arg.LocationID,
		arg.Name,
		arg.PropertyType,
		arg.Timezone,
		arg.City,
		arg.RegionCode,
		arg.Amenities,
		arg.CostCenter,
		arg.Status,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.ExpectedRowVersion,
		arg.ScopeIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRoomType = `-- name: UpdateRoomType :execrows
UPDATE accommodation.room_type r
   SET name          = $1,
       max_adults    = $2,
       max_children  = $3,
       max_occupancy = $4,
       attributes    = $5,
       status        = $6,
       updated_by    = $7
 WHERE r.tenant_id = $8
   AND r.id = $9
   AND r.row_version = $10
   AND ($11::uuid[] IS NULL
        OR EXISTS (SELECT 1 FROM accommodation.property p
                    WHERE p.tenant_id = r.tenant_id AND p.id = r.property_id
                      AND p.provider_organization_id = ANY($11::uuid[])))
`

type UpdateRoomTypeParams struct {
	Name               string
	MaxAdults          int32
	MaxChildren        int32
	MaxOccupancy       int32
	Attributes         []byte
	Status             string
	ActorID            uuid.NullUUID
	TenantID           uuid.UUID
	ID                 uuid.UUID
	ExpectedRowVersion int64
	ScopeIds           []uuid.UUID
}

// Plain assignment for the same reason UpdateProperty is. `service_definition_id` is not
// here and never will be: a room type re-pointed at another service would silently change
// what every existing booking of it was priced and entitled as.
func (q *Queries) UpdateRoomType(ctx context.Context, arg UpdateRoomTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRoomType,
		arg.Name,
		arg.MaxAdults,
		arg.MaxChildren,
		arg.MaxOccupancy,
		arg.Attributes,
		arg.Status,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.ExpectedRowVersion,
		arg.ScopeIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
