// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const insertAccessEvent = `-- name: InsertAccessEvent :one
INSERT INTO audit.access_event (
    tenant_id, actor_id, membership_id, person_id, resource_type, resource_id,
    access_type, data_classification, purpose_code, reason_text, outcome,
    request_id, trace_id, source_ip
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14
)
RETURNING id, occurred_at
`

type InsertAccessEventParams struct {
	TenantID           uuid.UUID
	ActorID            uuid.UUID
	MembershipID       uuid.NullUUID
	PersonID           uuid.NullUUID
	ResourceType       string
	ResourceID         uuid.NullUUID
	AccessType         string
	DataClassification string
	PurposeCode        *string
	ReasonText         *string
	Outcome            string
	RequestID          uuid.NullUUID
	TraceID            *string
	SourceIp           *netip.Addr
}

type InsertAccessEventRow struct {
	ID         uuid.UUID
	OccurredAt time.Time
}

func (q *Queries) InsertAccessEvent(ctx context.Context, arg InsertAccessEventParams) (InsertAccessEventRow, error) {
	row := q.db.QueryRow(ctx, insertAccessEvent,
		arg.TenantID,
		arg.ActorID,
		arg.MembershipID,
		arg.PersonID,
		arg.ResourceType,
		arg.ResourceID,
		arg.AccessType,
		arg.DataClassification,
		arg.PurposeCode,
		arg.ReasonText,
		arg.Outcome,
		arg.RequestID,
		arg.TraceID,
		arg.SourceIp,
	)
	var i InsertAccessEventRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :one

INSERT INTO audit.event (
    tenant_id, actor_id, membership_id, event_category, action_code,
    resource_type, resource_id, outcome, request_id, trace_id, source_ip,
    user_agent_hash, reason_code, purpose_code, detail_json, before_hash, after_hash
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17
)
RETURNING id, occurred_at
`

type InsertAuditEventParams struct {
	TenantID      uuid.NullUUID
	ActorID       uuid.NullUUID
	MembershipID  uuid.NullUUID
	EventCategory string
	ActionCode    string
	ResourceType  *string
	ResourceID    uuid.NullUUID
	Outcome       string
	RequestID     uuid.NullUUID
	TraceID       *string
	SourceIp      *netip.Addr
	UserAgentHash []byte
	ReasonCode    *string
	PurposeCode   *string
	DetailJson    []byte
	BeforeHash    []byte
	AfterHash     []byte
}

type InsertAuditEventRow struct {
	ID         uuid.UUID
	OccurredAt time.Time
}

// Audit writes. Both tables are append-only and written inside the caller's transaction.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (InsertAuditEventRow, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.TenantID,
		arg.ActorID,
		arg.MembershipID,
		arg.EventCategory,
		arg.ActionCode,
		arg.ResourceType,
		arg.ResourceID,
		arg.Outcome,
		arg.RequestID,
		arg.TraceID,
		arg.SourceIp,
		arg.UserAgentHash,
		arg.ReasonCode,
		arg.PurposeCode,
		arg.DetailJson,
		arg.BeforeHash,
		arg.AfterHash,
	)
	var i InsertAuditEventRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}
