// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization_correction.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findAuthorizationConsumption = `-- name: FindAuthorizationConsumption :one
SELECT l.id, l.delta_consumed::text AS quantity,
       EXISTS (SELECT 1 FROM benefit.entitlement_ledger r
         WHERE r.tenant_id=l.tenant_id AND r.movement_type='REVERSE' AND r.reference_id=l.id) AS reversed
FROM benefit.entitlement_ledger l
WHERE l.tenant_id=$1 AND l.reservation_id=$2
  AND l.reference_type='AUTHORIZATION'
  AND l.reference_id IN (SELECT ai.id FROM service.authorization_item ai
    WHERE ai.tenant_id=l.tenant_id AND ai.authorization_id=$3
      AND ai.entitlement_reservation_id=l.reservation_id)
  AND l.movement_type='CONSUME' AND l.idempotency_key=$4
  AND l.reason_code=$5
`

type FindAuthorizationConsumptionParams struct {
	TenantID        uuid.UUID
	ReservationID   uuid.NullUUID
	AuthorizationID uuid.UUID
	Key             string
	ReasonCode      *string
}

type FindAuthorizationConsumptionRow struct {
	ID       uuid.UUID
	Quantity string
	Reversed bool
}

// A correction can undo only this authorization item's exact original consumption.
func (q *Queries) FindAuthorizationConsumption(ctx context.Context, arg FindAuthorizationConsumptionParams) (FindAuthorizationConsumptionRow, error) {
	row := q.db.QueryRow(ctx, findAuthorizationConsumption,
		arg.TenantID,
		arg.ReservationID,
		arg.AuthorizationID,
		arg.Key,
		arg.ReasonCode,
	)
	var i FindAuthorizationConsumptionRow
	err := row.Scan(&i.ID, &i.Quantity, &i.Reversed)
	return i, err
}

const restoreAuthorizationConsumption = `-- name: RestoreAuthorizationConsumption :execrows
UPDATE service.authorization
SET consumed_total=consumed_total-$1::text::numeric,
    status=CASE
      WHEN status IN ('CANCELLED','EXPIRED') THEN status
      WHEN valid_to<=$2::timestamptz THEN 'EXPIRED'
      WHEN consumed_total-$1::text::numeric=0 THEN 'ACTIVE'
      ELSE 'PARTIALLY_USED' END,
    updated_by=$3
WHERE tenant_id=$4 AND id=$5
  AND consumed_total>=$1::text::numeric
`

type RestoreAuthorizationConsumptionParams struct {
	Quantity string
	Now      time.Time
	ActorID  uuid.NullUUID
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) RestoreAuthorizationConsumption(ctx context.Context, arg RestoreAuthorizationConsumptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreAuthorizationConsumption,
		arg.Quantity,
		arg.Now,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
