// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAuthorizationItemConsumption = `-- name: AddAuthorizationItemConsumption :execrows
UPDATE service.authorization_item
   SET consumed_quantity = consumed_quantity + $1::text::numeric
 WHERE tenant_id = $2
   AND id = $3
`

type AddAuthorizationItemConsumptionParams struct {
	DeltaConsumed string
	TenantID      uuid.UUID
	ID            uuid.UUID
}

func (q *Queries) AddAuthorizationItemConsumption(ctx context.Context, arg AddAuthorizationItemConsumptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, addAuthorizationItemConsumption, arg.DeltaConsumed, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyAuthorizationConsumption = `-- name: ApplyAuthorizationConsumption :execrows
UPDATE service.authorization
   SET consumed_total = consumed_total + $1::text::numeric,
       status         = CASE
                          WHEN consumed_total + $1::text::numeric
                               >= reserved_total THEN 'USED'
                          ELSE 'PARTIALLY_USED'
                        END,
       updated_by     = $2
 WHERE tenant_id = $3
   AND id = $4
   AND status IN ('ACTIVE','PARTIALLY_USED')
`

type ApplyAuthorizationConsumptionParams struct {
	DeltaConsumed string
	ActorID       uuid.NullUUID
	TenantID      uuid.UUID
	ID            uuid.UUID
}

// Adds what a completed fulfilment delivered and moves the authorization to the status
// the new total implies. ck_authorization_consumed refuses a total above what was
// promised, so an over-fulfilment that slipped past the application layer still cannot
// be written.
func (q *Queries) ApplyAuthorizationConsumption(ctx context.Context, arg ApplyAuthorizationConsumptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyAuthorizationConsumption,
		arg.DeltaConsumed,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelAuthorization = `-- name: CancelAuthorization :execrows
UPDATE service.authorization
   SET status             = 'CANCELLED',
       cancel_reason_code = $1,
       updated_by         = $2
 WHERE tenant_id = $3
   AND id = $4
   AND row_version = $5
   AND status IN ('ACTIVE','PARTIALLY_USED')
`

type CancelAuthorizationParams struct {
	CancelReasonCode *string
	ActorID          uuid.NullUUID
	TenantID         uuid.UUID
	ID               uuid.UUID
	RowVersion       int64
}

func (q *Queries) CancelAuthorization(ctx context.Context, arg CancelAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelAuthorization,
		arg.CancelReasonCode,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelFulfilmentRecord = `-- name: CancelFulfilmentRecord :execrows
UPDATE service.fulfilment
   SET status = 'CANCELLED', cancelled_at = $1,
       cancel_reason_code = $2
 WHERE tenant_id = $3
   AND id = $4
   AND row_version = $5
   AND status = 'RECORDED'
`

type CancelFulfilmentRecordParams struct {
	CancelledAt      *time.Time
	CancelReasonCode *string
	TenantID         uuid.UUID
	ID               uuid.UUID
	RowVersion       int64
}

// Only a RECORDED fulfilment may be cancelled. A completed one has already consumed from
// the ledger, and undoing that is a reversal movement rather than a status change.
func (q *Queries) CancelFulfilmentRecord(ctx context.Context, arg CancelFulfilmentRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelFulfilmentRecord,
		arg.CancelledAt,
		arg.CancelReasonCode,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeFulfilment = `-- name: CompleteFulfilment :execrows
UPDATE service.fulfilment
   SET status = 'COMPLETED', completed_at = $1
 WHERE tenant_id = $2
   AND id = $3
   AND row_version = $4
   AND status = 'RECORDED'
`

type CompleteFulfilmentParams struct {
	CompletedAt *time.Time
	TenantID    uuid.UUID
	ID          uuid.UUID
	RowVersion  int64
}

func (q *Queries) CompleteFulfilment(ctx context.Context, arg CompleteFulfilmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeFulfilment,
		arg.CompletedAt,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLiveVouchers = `-- name: CountLiveVouchers :one
SELECT count(*)
  FROM service.voucher
 WHERE tenant_id = $1
   AND authorization_id = $2
   AND status = 'ISSUED'
`

type CountLiveVouchersParams struct {
	TenantID        uuid.UUID
	AuthorizationID uuid.UUID
}

// How many vouchers for this authorization are still usable. Issuing takes the
// authorization's row lock first, so this count cannot change underneath the check that
// reads it; uq_voucher_one_live_per_authorization is the guarantee, and this is only how
// the caller is told which of its two clicks arrived second.
func (q *Queries) CountLiveVouchers(ctx context.Context, arg CountLiveVouchersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveVouchers, arg.TenantID, arg.AuthorizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthorization = `-- name: CreateAuthorization :one

INSERT INTO service.authorization (
    tenant_id, request_id, authorization_reference, valid_from, valid_to,
    reserved_total, currency_code, price_quote_id, approved_by, approved_at,
    idempotency_key, created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5,
        $6::text::numeric, $7,
        $8, $9, $10,
        $11, $9, $9)
RETURNING id, authorization_reference, status, created_at, row_version
`

type CreateAuthorizationParams struct {
	TenantID               uuid.UUID
	RequestID              uuid.UUID
	AuthorizationReference string
	ValidFrom              time.Time
	ValidTo                time.Time
	ReservedTotal          string
	CurrencyCode           *string
	PriceQuoteID           uuid.NullUUID
	ActorID                uuid.NullUUID
	ApprovedAt             time.Time
	IdempotencyKey         string
}

type CreateAuthorizationRow struct {
	ID                     uuid.UUID
	AuthorizationReference string
	Status                 string
	CreatedAt              time.Time
	RowVersion             int64
}

// Authorization, fulfilment and voucher queries (WP-I4-02, v1.2 9.11, 11.4, 16.7).
//
// Three properties shape this file.
//
// The provider boundary is the same one the service request queries apply: `scope_ids` is
// a nullable uuid[], NULL means the caller is tenant-wide and a non-null array binds it to
// those organizations. An authorization has no provider column of its own, so the boundary
// is read from the request it was granted against; it is applied in every read, including
// the single-row ones, so a caller outside it finds no row and is answered 404 rather than
// 403 — that such an authorization exists at all is somebody else's business.
//
// Quantities and amounts are read as `::text` and written as `::text::numeric`, so an
// exact decimal never passes through a float in either direction (handbook section 3).
//
// Nothing here writes a balance. `reserved_total` and `consumed_total` are the
// authorization's arithmetic over its own lines; the entitlement itself moves only through
// benefit.entitlement_ledger, which has its own statements and its own account lock.
// The reference is generated by the caller and unique per tenant; a collision surfaces as
// a unique violation and is retried with a new one. The idempotency key is unique too:
// creating twice under one key must return the first authorization, not reserve again.
func (q *Queries) CreateAuthorization(ctx context.Context, arg CreateAuthorizationParams) (CreateAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, createAuthorization,
		arg.TenantID,
		arg.RequestID,
		arg.AuthorizationReference,
		arg.ValidFrom,
		arg.ValidTo,
		arg.ReservedTotal,
		arg.CurrencyCode,
		arg.PriceQuoteID,
		arg.ActorID,
		arg.ApprovedAt,
		arg.IdempotencyKey,
	)
	var i CreateAuthorizationRow
	err := row.Scan(
		&i.ID,
		&i.AuthorizationReference,
		&i.Status,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const createAuthorizationItem = `-- name: CreateAuthorizationItem :one
INSERT INTO service.authorization_item (
    tenant_id, authorization_id, request_item_id, service_definition_id,
    approved_quantity, approved_amount, member_amount)
VALUES ($1, $2, $3,
        $4, $5::text::numeric,
        $6::text::numeric, $7::text::numeric)
RETURNING id, created_at, row_version
`

type CreateAuthorizationItemParams struct {
	TenantID            uuid.UUID
	AuthorizationID     uuid.UUID
	RequestItemID       uuid.UUID
	ServiceDefinitionID uuid.UUID
	ApprovedQuantity    string
	ApprovedAmount      *string
	MemberAmount        string
}

type CreateAuthorizationItemRow struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	RowVersion int64
}

// The line is written before its hold is taken, because the reservation references the
// line: two lines of one authorization may draw on the same entitlement account, and
// uq_entitlement_reservation_reference would fold them into a single hold if they shared
// a reference. The reservation id is written back by SetAuthorizationItemReservation.
func (q *Queries) CreateAuthorizationItem(ctx context.Context, arg CreateAuthorizationItemParams) (CreateAuthorizationItemRow, error) {
	row := q.db.QueryRow(ctx, createAuthorizationItem,
		arg.TenantID,
		arg.AuthorizationID,
		arg.RequestItemID,
		arg.ServiceDefinitionID,
		arg.ApprovedQuantity,
		arg.ApprovedAmount,
		arg.MemberAmount,
	)
	var i CreateAuthorizationItemRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.RowVersion)
	return i, err
}

const createFulfilment = `-- name: CreateFulfilment :one
INSERT INTO service.fulfilment (
    tenant_id, fulfilment_reference, authorization_id, provider_profile_id, location_id,
    practitioner_id, performed_at, recorded_by)
VALUES ($1, $2, $3,
        $4, $5,
        $6, $7, $8)
RETURNING id, fulfilment_reference, status, created_at, row_version
`

type CreateFulfilmentParams struct {
	TenantID            uuid.UUID
	FulfilmentReference string
	AuthorizationID     uuid.UUID
	ProviderProfileID   uuid.NullUUID
	LocationID          uuid.NullUUID
	PractitionerID      uuid.NullUUID
	PerformedAt         time.Time
	ActorID             uuid.NullUUID
}

type CreateFulfilmentRow struct {
	ID                  uuid.UUID
	FulfilmentReference string
	Status              string
	CreatedAt           time.Time
	RowVersion          int64
}

func (q *Queries) CreateFulfilment(ctx context.Context, arg CreateFulfilmentParams) (CreateFulfilmentRow, error) {
	row := q.db.QueryRow(ctx, createFulfilment,
		arg.TenantID,
		arg.FulfilmentReference,
		arg.AuthorizationID,
		arg.ProviderProfileID,
		arg.LocationID,
		arg.PractitionerID,
		arg.PerformedAt,
		arg.ActorID,
	)
	var i CreateFulfilmentRow
	err := row.Scan(
		&i.ID,
		&i.FulfilmentReference,
		&i.Status,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const createFulfilmentItem = `-- name: CreateFulfilmentItem :one
INSERT INTO service.fulfilment_item (
    tenant_id, fulfilment_id, authorization_item_id, service_definition_id,
    actual_quantity, actual_amount)
VALUES ($1, $2, $3,
        $4, $5::text::numeric,
        $6::text::numeric)
RETURNING id, created_at
`

type CreateFulfilmentItemParams struct {
	TenantID            uuid.UUID
	FulfilmentID        uuid.UUID
	AuthorizationItemID uuid.UUID
	ServiceDefinitionID uuid.UUID
	ActualQuantity      string
	ActualAmount        *string
}

type CreateFulfilmentItemRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateFulfilmentItem(ctx context.Context, arg CreateFulfilmentItemParams) (CreateFulfilmentItemRow, error) {
	row := q.db.QueryRow(ctx, createFulfilmentItem,
		arg.TenantID,
		arg.FulfilmentID,
		arg.AuthorizationItemID,
		arg.ServiceDefinitionID,
		arg.ActualQuantity,
		arg.ActualAmount,
	)
	var i CreateFulfilmentItemRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createVoucher = `-- name: CreateVoucher :one
INSERT INTO service.voucher (
    tenant_id, authorization_id, token_hash, token_masked, valid_from, valid_to, issued_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7)
RETURNING id, status, issued_at, created_at, row_version
`

type CreateVoucherParams struct {
	TenantID        uuid.UUID
	AuthorizationID uuid.UUID
	TokenHash       []byte
	TokenMasked     string
	ValidFrom       time.Time
	ValidTo         time.Time
	ActorID         uuid.NullUUID
}

type CreateVoucherRow struct {
	ID         uuid.UUID
	Status     string
	IssuedAt   time.Time
	CreatedAt  time.Time
	RowVersion int64
}

// Only the digest and the masked tail are written. The plaintext exists in the issue
// response and nowhere else: not in a column, not in a log line, not in an audit row.
func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) (CreateVoucherRow, error) {
	row := q.db.QueryRow(ctx, createVoucher,
		arg.TenantID,
		arg.AuthorizationID,
		arg.TokenHash,
		arg.TokenMasked,
		arg.ValidFrom,
		arg.ValidTo,
		arg.ActorID,
	)
	var i CreateVoucherRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.IssuedAt,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const extendAuthorization = `-- name: ExtendAuthorization :execrows
UPDATE service.authorization
   SET valid_to   = $1,
       updated_by = $2
 WHERE tenant_id = $3
   AND id = $4
   AND row_version = $5
   AND status = 'ACTIVE'
   AND valid_to < $1
`

type ExtendAuthorizationParams struct {
	ValidTo    time.Time
	ActorID    uuid.NullUUID
	TenantID   uuid.UUID
	ID         uuid.UUID
	RowVersion int64
}

// valid_to moves forward only, and only while the authorization is ACTIVE: extending a
// promise that has already been used up or withdrawn would revive it.
func (q *Queries) ExtendAuthorization(ctx context.Context, arg ExtendAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendAuthorization,
		arg.ValidTo,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthorization = `-- name: GetAuthorization :one
SELECT a.id, a.request_id, a.authorization_reference, a.valid_from, a.valid_to, a.status,
       a.reserved_total::text AS reserved_total, a.consumed_total::text AS consumed_total,
       a.currency_code, a.price_quote_id, a.approved_by, a.approved_at,
       a.cancel_reason_code, a.created_at, a.row_version
  FROM service.authorization a
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE a.tenant_id = $1
   AND a.id = $2
   AND ($3::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY($3::uuid[]))
`

type GetAuthorizationParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type GetAuthorizationRow struct {
	ID                     uuid.UUID
	RequestID              uuid.UUID
	AuthorizationReference string
	ValidFrom              time.Time
	ValidTo                time.Time
	Status                 string
	ReservedTotal          string
	ConsumedTotal          string
	CurrencyCode           *string
	PriceQuoteID           uuid.NullUUID
	ApprovedBy             uuid.NullUUID
	ApprovedAt             time.Time
	CancelReasonCode       *string
	CreatedAt              time.Time
	RowVersion             int64
}

func (q *Queries) GetAuthorization(ctx context.Context, arg GetAuthorizationParams) (GetAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, getAuthorization, arg.TenantID, arg.ID, arg.ScopeIds)
	var i GetAuthorizationRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.AuthorizationReference,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Status,
		&i.ReservedTotal,
		&i.ConsumedTotal,
		&i.CurrencyCode,
		&i.PriceQuoteID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CancelReasonCode,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getAuthorizationByIdempotencyKey = `-- name: GetAuthorizationByIdempotencyKey :one
SELECT a.id, a.request_id, a.authorization_reference, a.valid_from, a.valid_to, a.status,
       a.reserved_total::text AS reserved_total, a.consumed_total::text AS consumed_total,
       a.currency_code, a.price_quote_id, a.approved_by, a.approved_at,
       a.cancel_reason_code, a.created_at, a.row_version
  FROM service.authorization a
 WHERE a.tenant_id = $1
   AND a.idempotency_key = $2
`

type GetAuthorizationByIdempotencyKeyParams struct {
	TenantID       uuid.UUID
	IdempotencyKey string
}

type GetAuthorizationByIdempotencyKeyRow struct {
	ID                     uuid.UUID
	RequestID              uuid.UUID
	AuthorizationReference string
	ValidFrom              time.Time
	ValidTo                time.Time
	Status                 string
	ReservedTotal          string
	ConsumedTotal          string
	CurrencyCode           *string
	PriceQuoteID           uuid.NullUUID
	ApprovedBy             uuid.NullUUID
	ApprovedAt             time.Time
	CancelReasonCode       *string
	CreatedAt              time.Time
	RowVersion             int64
}

// The replay path of createAuthorization. It ignores the provider boundary on purpose:
// the key is the caller's own, so a row under it was written by this caller.
func (q *Queries) GetAuthorizationByIdempotencyKey(ctx context.Context, arg GetAuthorizationByIdempotencyKeyParams) (GetAuthorizationByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizationByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i GetAuthorizationByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.AuthorizationReference,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Status,
		&i.ReservedTotal,
		&i.ConsumedTotal,
		&i.CurrencyCode,
		&i.PriceQuoteID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CancelReasonCode,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getFulfilment = `-- name: GetFulfilment :one
SELECT f.id, f.fulfilment_reference, f.authorization_id, f.provider_profile_id, f.location_id,
       f.practitioner_id, f.performed_at, f.status, f.completed_at, f.cancelled_at,
       f.cancel_reason_code, f.recorded_by, f.created_at, f.row_version
  FROM service.fulfilment f
  JOIN service.authorization a
    ON a.tenant_id = f.tenant_id AND a.id = f.authorization_id
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE f.tenant_id = $1
   AND f.id = $2
   AND ($3::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY($3::uuid[]))
`

type GetFulfilmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type GetFulfilmentRow struct {
	ID                  uuid.UUID
	FulfilmentReference string
	AuthorizationID     uuid.UUID
	ProviderProfileID   uuid.NullUUID
	LocationID          uuid.NullUUID
	PractitionerID      uuid.NullUUID
	PerformedAt         time.Time
	Status              string
	CompletedAt         *time.Time
	CancelledAt         *time.Time
	CancelReasonCode    *string
	RecordedBy          uuid.NullUUID
	CreatedAt           time.Time
	RowVersion          int64
}

func (q *Queries) GetFulfilment(ctx context.Context, arg GetFulfilmentParams) (GetFulfilmentRow, error) {
	row := q.db.QueryRow(ctx, getFulfilment, arg.TenantID, arg.ID, arg.ScopeIds)
	var i GetFulfilmentRow
	err := row.Scan(
		&i.ID,
		&i.FulfilmentReference,
		&i.AuthorizationID,
		&i.ProviderProfileID,
		&i.LocationID,
		&i.PractitionerID,
		&i.PerformedAt,
		&i.Status,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReasonCode,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getVoucherByTokenHash = `-- name: GetVoucherByTokenHash :one
SELECT v.id, v.authorization_id, v.token_masked, v.valid_from, v.valid_to, v.status,
       v.redeemed_at, v.redeemed_by_actor_id, v.issued_at, v.created_at, v.row_version
  FROM service.voucher v
  JOIN service.authorization a
    ON a.tenant_id = v.tenant_id AND a.id = v.authorization_id
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE v.tenant_id = $1
   AND v.token_hash = $2
   AND ($3::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY($3::uuid[]))
   FOR UPDATE OF v
`

type GetVoucherByTokenHashParams struct {
	TenantID  uuid.UUID
	TokenHash []byte
	ScopeIds  []uuid.UUID
}

type GetVoucherByTokenHashRow struct {
	ID                uuid.UUID
	AuthorizationID   uuid.UUID
	TokenMasked       string
	ValidFrom         time.Time
	ValidTo           time.Time
	Status            string
	RedeemedAt        *time.Time
	RedeemedByActorID uuid.NullUUID
	IssuedAt          time.Time
	CreatedAt         time.Time
	RowVersion        int64
}

// Redemption looks the voucher up by digest, never by the token itself, so the plaintext
// never becomes a query parameter that a statement log could keep.
func (q *Queries) GetVoucherByTokenHash(ctx context.Context, arg GetVoucherByTokenHashParams) (GetVoucherByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getVoucherByTokenHash, arg.TenantID, arg.TokenHash, arg.ScopeIds)
	var i GetVoucherByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.TokenMasked,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Status,
		&i.RedeemedAt,
		&i.RedeemedByActorID,
		&i.IssuedAt,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const listAuthorizationItems = `-- name: ListAuthorizationItems :many
SELECT id, authorization_id, request_item_id, service_definition_id,
       approved_quantity::text AS approved_quantity,
       COALESCE(approved_amount::text, '')::text AS approved_amount,
       member_amount::text AS member_amount,
       entitlement_reservation_id,
       consumed_quantity::text AS consumed_quantity,
       row_version
  FROM service.authorization_item
 WHERE tenant_id = $1
   AND authorization_id = $2
 ORDER BY created_at, id
`

type ListAuthorizationItemsParams struct {
	TenantID        uuid.UUID
	AuthorizationID uuid.UUID
}

type ListAuthorizationItemsRow struct {
	ID                       uuid.UUID
	AuthorizationID          uuid.UUID
	RequestItemID            uuid.UUID
	ServiceDefinitionID      uuid.UUID
	ApprovedQuantity         string
	ApprovedAmount           string
	MemberAmount             string
	EntitlementReservationID uuid.NullUUID
	ConsumedQuantity         string
	RowVersion               int64
}

func (q *Queries) ListAuthorizationItems(ctx context.Context, arg ListAuthorizationItemsParams) ([]ListAuthorizationItemsRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizationItems, arg.TenantID, arg.AuthorizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorizationItemsRow
	for rows.Next() {
		var i ListAuthorizationItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorizationID,
			&i.RequestItemID,
			&i.ServiceDefinitionID,
			&i.ApprovedQuantity,
			&i.ApprovedAmount,
			&i.MemberAmount,
			&i.EntitlementReservationID,
			&i.ConsumedQuantity,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorizations = `-- name: ListAuthorizations :many
SELECT a.id, a.request_id, a.authorization_reference, a.valid_from, a.valid_to, a.status,
       a.reserved_total::text AS reserved_total, a.consumed_total::text AS consumed_total,
       a.currency_code, a.price_quote_id, a.approved_by, a.approved_at,
       a.cancel_reason_code, a.created_at, a.row_version
  FROM service.authorization a
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE a.tenant_id = $1
   AND ($2::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY($2::uuid[]))
   AND ($3::text IS NULL OR a.status = $3::text)
   AND ($4::uuid IS NULL OR a.request_id = $4::uuid)
   AND ($5::uuid IS NULL OR r.person_id = $5::uuid)
   AND ($6::uuid IS NULL
        OR r.provider_tenant_organization_id = $6::uuid)
   AND ($7::timestamptz IS NULL
        OR a.valid_to >= $7::timestamptz)
   AND ($8::timestamptz IS NULL
        OR a.valid_from <= $8::timestamptz)
   AND ($9::timestamptz IS NULL
        OR (a.created_at, a.id) < ($9::timestamptz, $10::uuid))
 ORDER BY a.created_at DESC, a.id DESC
 LIMIT $11
`

type ListAuthorizationsParams struct {
	TenantID        uuid.UUID
	ScopeIds        []uuid.UUID
	Status          *string
	RequestID       uuid.NullUUID
	PersonID        uuid.NullUUID
	ProviderID      uuid.NullUUID
	ValidFrom       *time.Time
	ValidTo         *time.Time
	CursorCreatedAt *time.Time
	CursorID        uuid.NullUUID
	PageSize        int32
}

type ListAuthorizationsRow struct {
	ID                     uuid.UUID
	RequestID              uuid.UUID
	AuthorizationReference string
	ValidFrom              time.Time
	ValidTo                time.Time
	Status                 string
	ReservedTotal          string
	ConsumedTotal          string
	CurrencyCode           *string
	PriceQuoteID           uuid.NullUUID
	ApprovedBy             uuid.NullUUID
	ApprovedAt             time.Time
	CancelReasonCode       *string
	CreatedAt              time.Time
	RowVersion             int64
}

// Keyset pagination on (created_at DESC, id DESC); the caller asks for limit+1 rows to
// learn whether a next page exists.
func (q *Queries) ListAuthorizations(ctx context.Context, arg ListAuthorizationsParams) ([]ListAuthorizationsRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizations,
		arg.TenantID,
		arg.ScopeIds,
		arg.Status,
		arg.RequestID,
		arg.PersonID,
		arg.ProviderID,
		arg.ValidFrom,
		arg.ValidTo,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorizationsRow
	for rows.Next() {
		var i ListAuthorizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.AuthorizationReference,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Status,
			&i.ReservedTotal,
			&i.ConsumedTotal,
			&i.CurrencyCode,
			&i.PriceQuoteID,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CancelReasonCode,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpirableAuthorizations = `-- name: ListExpirableAuthorizations :many
SELECT a.id, a.row_version
  FROM service.authorization a
 WHERE a.tenant_id = $1
   AND a.status IN ('ACTIVE','PARTIALLY_USED')
   AND a.valid_to < $2
 ORDER BY a.valid_to
 LIMIT $3
   FOR UPDATE SKIP LOCKED
`

type ListExpirableAuthorizationsParams struct {
	TenantID      uuid.UUID
	ExpiredBefore time.Time
	PageSize      int32
}

type ListExpirableAuthorizationsRow struct {
	ID         uuid.UUID
	RowVersion int64
}

// The expiry sweep, one tenant at a time. Only holds that still hold something are
// listed, so re-running the job after it has done its work returns nothing.
func (q *Queries) ListExpirableAuthorizations(ctx context.Context, arg ListExpirableAuthorizationsParams) ([]ListExpirableAuthorizationsRow, error) {
	rows, err := q.db.Query(ctx, listExpirableAuthorizations, arg.TenantID, arg.ExpiredBefore, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpirableAuthorizationsRow
	for rows.Next() {
		var i ListExpirableAuthorizationsRow
		if err := rows.Scan(&i.ID, &i.RowVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringAuthorizations = `-- name: ListExpiringAuthorizations :many
SELECT a.id, a.authorization_reference, a.valid_to, r.person_id
  FROM service.authorization a
  JOIN service.service_request r ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE a.tenant_id = $1
   AND a.status IN ('ACTIVE','PARTIALLY_USED')
   AND a.valid_to >= $2
   AND a.valid_to < $3
 ORDER BY a.valid_to, a.id
 LIMIT $4
`

type ListExpiringAuthorizationsParams struct {
	TenantID uuid.UUID
	DayStart time.Time
	DayEnd   time.Time
	PageSize int32
}

type ListExpiringAuthorizationsRow struct {
	ID                     uuid.UUID
	AuthorizationReference string
	ValidTo                time.Time
	PersonID               uuid.UUID
}

// The authorizations whose validity ends on one particular day, with the member behind
// them. It is a day and not a window because the reminder is published once per
// authorization per expiry day: the job's deduplication key carries the same date, so an
// hourly sweep of the same day writes one message and twenty-three no-ops.
func (q *Queries) ListExpiringAuthorizations(ctx context.Context, arg ListExpiringAuthorizationsParams) ([]ListExpiringAuthorizationsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringAuthorizations,
		arg.TenantID,
		arg.DayStart,
		arg.DayEnd,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringAuthorizationsRow
	for rows.Next() {
		var i ListExpiringAuthorizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorizationReference,
			&i.ValidTo,
			&i.PersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFulfilmentItems = `-- name: ListFulfilmentItems :many
SELECT id, fulfilment_id, authorization_item_id, service_definition_id,
       actual_quantity::text AS actual_quantity,
       COALESCE(actual_amount::text, '')::text AS actual_amount
  FROM service.fulfilment_item
 WHERE tenant_id = $1
   AND fulfilment_id = $2
 ORDER BY created_at, id
`

type ListFulfilmentItemsParams struct {
	TenantID     uuid.UUID
	FulfilmentID uuid.UUID
}

type ListFulfilmentItemsRow struct {
	ID                  uuid.UUID
	FulfilmentID        uuid.UUID
	AuthorizationItemID uuid.UUID
	ServiceDefinitionID uuid.UUID
	ActualQuantity      string
	ActualAmount        string
}

func (q *Queries) ListFulfilmentItems(ctx context.Context, arg ListFulfilmentItemsParams) ([]ListFulfilmentItemsRow, error) {
	rows, err := q.db.Query(ctx, listFulfilmentItems, arg.TenantID, arg.FulfilmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFulfilmentItemsRow
	for rows.Next() {
		var i ListFulfilmentItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.FulfilmentID,
			&i.AuthorizationItemID,
			&i.ServiceDefinitionID,
			&i.ActualQuantity,
			&i.ActualAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFulfilments = `-- name: ListFulfilments :many
SELECT f.id, f.fulfilment_reference, f.authorization_id, f.provider_profile_id, f.location_id,
       f.practitioner_id, f.performed_at, f.status, f.completed_at, f.cancelled_at,
       f.cancel_reason_code, f.recorded_by, f.created_at, f.row_version
  FROM service.fulfilment f
  JOIN service.authorization a
    ON a.tenant_id = f.tenant_id AND a.id = f.authorization_id
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE f.tenant_id = $1
   AND ($2::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY($2::uuid[]))
   AND ($3::text IS NULL OR f.status = $3::text)
   AND ($4::uuid IS NULL
        OR f.authorization_id = $4::uuid)
   AND ($5::uuid IS NULL
        OR f.provider_profile_id = $5::uuid)
   AND ($6::timestamptz IS NULL
        OR f.performed_at >= $6::timestamptz)
   AND ($7::timestamptz IS NULL
        OR f.performed_at <= $7::timestamptz)
   AND ($8::timestamptz IS NULL
        OR (f.created_at, f.id) < ($8::timestamptz, $9::uuid))
 ORDER BY f.created_at DESC, f.id DESC
 LIMIT $10
`

type ListFulfilmentsParams struct {
	TenantID          uuid.UUID
	ScopeIds          []uuid.UUID
	Status            *string
	AuthorizationID   uuid.NullUUID
	ProviderProfileID uuid.NullUUID
	PerformedFrom     *time.Time
	PerformedTo       *time.Time
	CursorCreatedAt   *time.Time
	CursorID          uuid.NullUUID
	PageSize          int32
}

type ListFulfilmentsRow struct {
	ID                  uuid.UUID
	FulfilmentReference string
	AuthorizationID     uuid.UUID
	ProviderProfileID   uuid.NullUUID
	LocationID          uuid.NullUUID
	PractitionerID      uuid.NullUUID
	PerformedAt         time.Time
	Status              string
	CompletedAt         *time.Time
	CancelledAt         *time.Time
	CancelReasonCode    *string
	RecordedBy          uuid.NullUUID
	CreatedAt           time.Time
	RowVersion          int64
}

func (q *Queries) ListFulfilments(ctx context.Context, arg ListFulfilmentsParams) ([]ListFulfilmentsRow, error) {
	rows, err := q.db.Query(ctx, listFulfilments,
		arg.TenantID,
		arg.ScopeIds,
		arg.Status,
		arg.AuthorizationID,
		arg.ProviderProfileID,
		arg.PerformedFrom,
		arg.PerformedTo,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFulfilmentsRow
	for rows.Next() {
		var i ListFulfilmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FulfilmentReference,
			&i.AuthorizationID,
			&i.ProviderProfileID,
			&i.LocationID,
			&i.PractitionerID,
			&i.PerformedAt,
			&i.Status,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancelReasonCode,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVouchers = `-- name: ListVouchers :many
SELECT v.id, v.authorization_id, v.token_masked, v.valid_from, v.valid_to, v.status,
       v.redeemed_at, v.redeemed_by_actor_id, v.issued_at, v.created_at, v.row_version
  FROM service.voucher v
 WHERE v.tenant_id = $1
   AND v.authorization_id = $2
 ORDER BY v.issued_at DESC, v.id DESC
`

type ListVouchersParams struct {
	TenantID        uuid.UUID
	AuthorizationID uuid.UUID
}

type ListVouchersRow struct {
	ID                uuid.UUID
	AuthorizationID   uuid.UUID
	TokenMasked       string
	ValidFrom         time.Time
	ValidTo           time.Time
	Status            string
	RedeemedAt        *time.Time
	RedeemedByActorID uuid.NullUUID
	IssuedAt          time.Time
	CreatedAt         time.Time
	RowVersion        int64
}

func (q *Queries) ListVouchers(ctx context.Context, arg ListVouchersParams) ([]ListVouchersRow, error) {
	rows, err := q.db.Query(ctx, listVouchers, arg.TenantID, arg.AuthorizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVouchersRow
	for rows.Next() {
		var i ListVouchersRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorizationID,
			&i.TokenMasked,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Status,
			&i.RedeemedAt,
			&i.RedeemedByActorID,
			&i.IssuedAt,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuthorization = `-- name: LockAuthorization :one
SELECT a.id, a.request_id, a.authorization_reference, a.valid_from, a.valid_to, a.status,
       a.reserved_total::text AS reserved_total, a.consumed_total::text AS consumed_total,
       a.currency_code, a.price_quote_id, a.approved_by, a.approved_at,
       a.cancel_reason_code, a.created_at, a.row_version
  FROM service.authorization a
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE a.tenant_id = $1
   AND a.id = $2
   AND ($3::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY($3::uuid[]))
   FOR UPDATE OF a
`

type LockAuthorizationParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type LockAuthorizationRow struct {
	ID                     uuid.UUID
	RequestID              uuid.UUID
	AuthorizationReference string
	ValidFrom              time.Time
	ValidTo                time.Time
	Status                 string
	ReservedTotal          string
	ConsumedTotal          string
	CurrencyCode           *string
	PriceQuoteID           uuid.NullUUID
	ApprovedBy             uuid.NullUUID
	ApprovedAt             time.Time
	CancelReasonCode       *string
	CreatedAt              time.Time
	RowVersion             int64
}

// The same read taken FOR UPDATE, so two commands on one authorization serialise instead
// of racing each other into two different outcomes. Only the authorization row is locked:
// the request it points at is read here, never written.
func (q *Queries) LockAuthorization(ctx context.Context, arg LockAuthorizationParams) (LockAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, lockAuthorization, arg.TenantID, arg.ID, arg.ScopeIds)
	var i LockAuthorizationRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.AuthorizationReference,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Status,
		&i.ReservedTotal,
		&i.ConsumedTotal,
		&i.CurrencyCode,
		&i.PriceQuoteID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CancelReasonCode,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const lockAuthorizationItems = `-- name: LockAuthorizationItems :many
SELECT id, authorization_id, request_item_id, service_definition_id,
       approved_quantity::text AS approved_quantity,
       COALESCE(approved_amount::text, '')::text AS approved_amount,
       member_amount::text AS member_amount,
       entitlement_reservation_id,
       consumed_quantity::text AS consumed_quantity,
       row_version
  FROM service.authorization_item
 WHERE tenant_id = $1
   AND authorization_id = $2
 ORDER BY created_at, id
   FOR UPDATE
`

type LockAuthorizationItemsParams struct {
	TenantID        uuid.UUID
	AuthorizationID uuid.UUID
}

type LockAuthorizationItemsRow struct {
	ID                       uuid.UUID
	AuthorizationID          uuid.UUID
	RequestItemID            uuid.UUID
	ServiceDefinitionID      uuid.UUID
	ApprovedQuantity         string
	ApprovedAmount           string
	MemberAmount             string
	EntitlementReservationID uuid.NullUUID
	ConsumedQuantity         string
	RowVersion               int64
}

// The line set taken FOR UPDATE, which is what a completing fulfilment reads before it
// consumes: the remainder it checks must be one nobody else can change until it commits.
func (q *Queries) LockAuthorizationItems(ctx context.Context, arg LockAuthorizationItemsParams) ([]LockAuthorizationItemsRow, error) {
	rows, err := q.db.Query(ctx, lockAuthorizationItems, arg.TenantID, arg.AuthorizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockAuthorizationItemsRow
	for rows.Next() {
		var i LockAuthorizationItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorizationID,
			&i.RequestItemID,
			&i.ServiceDefinitionID,
			&i.ApprovedQuantity,
			&i.ApprovedAmount,
			&i.MemberAmount,
			&i.EntitlementReservationID,
			&i.ConsumedQuantity,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFulfilment = `-- name: LockFulfilment :one
SELECT f.id, f.fulfilment_reference, f.authorization_id, f.provider_profile_id, f.location_id,
       f.practitioner_id, f.performed_at, f.status, f.completed_at, f.cancelled_at,
       f.cancel_reason_code, f.recorded_by, f.created_at, f.row_version
  FROM service.fulfilment f
  JOIN service.authorization a
    ON a.tenant_id = f.tenant_id AND a.id = f.authorization_id
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE f.tenant_id = $1
   AND f.id = $2
   AND ($3::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY($3::uuid[]))
   FOR UPDATE OF f
`

type LockFulfilmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type LockFulfilmentRow struct {
	ID                  uuid.UUID
	FulfilmentReference string
	AuthorizationID     uuid.UUID
	ProviderProfileID   uuid.NullUUID
	LocationID          uuid.NullUUID
	PractitionerID      uuid.NullUUID
	PerformedAt         time.Time
	Status              string
	CompletedAt         *time.Time
	CancelledAt         *time.Time
	CancelReasonCode    *string
	RecordedBy          uuid.NullUUID
	CreatedAt           time.Time
	RowVersion          int64
}

func (q *Queries) LockFulfilment(ctx context.Context, arg LockFulfilmentParams) (LockFulfilmentRow, error) {
	row := q.db.QueryRow(ctx, lockFulfilment, arg.TenantID, arg.ID, arg.ScopeIds)
	var i LockFulfilmentRow
	err := row.Scan(
		&i.ID,
		&i.FulfilmentReference,
		&i.AuthorizationID,
		&i.ProviderProfileID,
		&i.LocationID,
		&i.PractitionerID,
		&i.PerformedAt,
		&i.Status,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReasonCode,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const markAuthorizationExpired = `-- name: MarkAuthorizationExpired :execrows
UPDATE service.authorization
   SET status = 'EXPIRED'
 WHERE tenant_id = $1
   AND id = $2
   AND status IN ('ACTIVE','PARTIALLY_USED')
`

type MarkAuthorizationExpiredParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) MarkAuthorizationExpired(ctx context.Context, arg MarkAuthorizationExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAuthorizationExpired, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const redeemVoucher = `-- name: RedeemVoucher :execrows
UPDATE service.voucher
   SET status = 'REDEEMED', redeemed_at = $1,
       redeemed_by_actor_id = $2
 WHERE tenant_id = $3
   AND id = $4
   AND status = 'ISSUED'
`

type RedeemVoucherParams struct {
	RedeemedAt *time.Time
	ActorID    uuid.NullUUID
	TenantID   uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) RedeemVoucher(ctx context.Context, arg RedeemVoucherParams) (int64, error) {
	result, err := q.db.Exec(ctx, redeemVoucher,
		arg.RedeemedAt,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeVoucher = `-- name: RevokeVoucher :execrows
UPDATE service.voucher
   SET status = 'REVOKED', revoke_reason_code = $1
 WHERE tenant_id = $2
   AND id = $3
   AND status = 'ISSUED'
`

type RevokeVoucherParams struct {
	RevokeReasonCode *string
	TenantID         uuid.UUID
	ID               uuid.UUID
}

// Withdraw a live voucher so a replacement may be issued (WP-I6-02's reissue: a member who
// lost the code they were shown gets a new one, and the old digest stops working the
// instant the new one exists).
//
// The ISSUED predicate is the whole of it: a voucher already redeemed is history and a
// second revoke changes nothing, so running this twice is the same as running it once.
func (q *Queries) RevokeVoucher(ctx context.Context, arg RevokeVoucherParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeVoucher, arg.RevokeReasonCode, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAuthorizationItemReservation = `-- name: SetAuthorizationItemReservation :execrows
UPDATE service.authorization_item
   SET entitlement_reservation_id = $1
 WHERE tenant_id = $2 AND id = $3
`

type SetAuthorizationItemReservationParams struct {
	EntitlementReservationID uuid.NullUUID
	TenantID                 uuid.UUID
	ID                       uuid.UUID
}

func (q *Queries) SetAuthorizationItemReservation(ctx context.Context, arg SetAuthorizationItemReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAuthorizationItemReservation, arg.EntitlementReservationID, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
