// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlcgen

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createPractitionerLocation = `-- name: CreatePractitionerLocation :batchexec
INSERT INTO provider.practitioner_location (tenant_id, practitioner_id, location_id, role,
                                            valid_from, valid_to)
VALUES ($1, $2, $3,
        $4, $5, $6)
`

type CreatePractitionerLocationBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreatePractitionerLocationParams struct {
	TenantID       uuid.UUID
	PractitionerID uuid.UUID
	LocationID     uuid.UUID
	Role           string
	ValidFrom      pgtype.Date
	ValidTo        pgtype.Date
}

func (q *Queries) CreatePractitionerLocation(ctx context.Context, arg []CreatePractitionerLocationParams) *CreatePractitionerLocationBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TenantID,
			a.PractitionerID,
			a.LocationID,
			a.Role,
			a.ValidFrom,
			a.ValidTo,
		}
		batch.Queue(createPractitionerLocation, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreatePractitionerLocationBatchResults{br, len(arg), false}
}

func (b *CreatePractitionerLocationBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreatePractitionerLocationBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createProviderCapability = `-- name: CreateProviderCapability :batchexec
INSERT INTO provider.capability (tenant_id, location_id, service_definition_id,
                                 service_category_id, valid_from, valid_to, notes)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7)
`

type CreateProviderCapabilityBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateProviderCapabilityParams struct {
	TenantID            uuid.UUID
	LocationID          uuid.UUID
	ServiceDefinitionID uuid.NullUUID
	ServiceCategoryID   uuid.NullUUID
	ValidFrom           pgtype.Date
	ValidTo             pgtype.Date
	Notes               *string
}

func (q *Queries) CreateProviderCapability(ctx context.Context, arg []CreateProviderCapabilityParams) *CreateProviderCapabilityBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TenantID,
			a.LocationID,
			a.ServiceDefinitionID,
			a.ServiceCategoryID,
			a.ValidFrom,
			a.ValidTo,
			a.Notes,
		}
		batch.Queue(createProviderCapability, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateProviderCapabilityBatchResults{br, len(arg), false}
}

func (b *CreateProviderCapabilityBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateProviderCapabilityBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createServiceCodeMapping = `-- name: CreateServiceCodeMapping :batchexec
INSERT INTO catalog.service_code_mapping (tenant_id, service_definition_id, code_system_id,
                                          code, valid_from, valid_to, is_primary)
VALUES ($1, $2, $3,
        $4, $5, $6, $7)
`

type CreateServiceCodeMappingBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateServiceCodeMappingParams struct {
	TenantID            uuid.UUID
	ServiceDefinitionID uuid.UUID
	CodeSystemID        uuid.UUID
	Code                string
	ValidFrom           pgtype.Date
	ValidTo             pgtype.Date
	IsPrimary           bool
}

func (q *Queries) CreateServiceCodeMapping(ctx context.Context, arg []CreateServiceCodeMappingParams) *CreateServiceCodeMappingBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TenantID,
			a.ServiceDefinitionID,
			a.CodeSystemID,
			a.Code,
			a.ValidFrom,
			a.ValidTo,
			a.IsPrimary,
		}
		batch.Queue(createServiceCodeMapping, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateServiceCodeMappingBatchResults{br, len(arg), false}
}

func (b *CreateServiceCodeMappingBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateServiceCodeMappingBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertImportRow = `-- name: InsertImportRow :batchexec
INSERT INTO party.import_row (tenant_id, batch_id, row_no, source_record_id, payload,
                              identifiers, identifier_cipher, status, errors)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9)
`

type InsertImportRowBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertImportRowParams struct {
	TenantID         uuid.UUID
	BatchID          uuid.UUID
	RowNo            int32
	SourceRecordID   string
	Payload          []byte
	Identifiers      []byte
	IdentifierCipher []byte
	Status           string
	Errors           []byte
}

// Staging writes one pgx batch per chunk, so a 50 000 row file is a few round trips.
// The row already carries the verdict of the text-level checks: a row whose columns do
// not parse is stored INVALID with its field errors and never reaches matching.
func (q *Queries) InsertImportRow(ctx context.Context, arg []InsertImportRowParams) *InsertImportRowBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TenantID,
			a.BatchID,
			a.RowNo,
			a.SourceRecordID,
			a.Payload,
			a.Identifiers,
			a.IdentifierCipher,
			a.Status,
			a.Errors,
		}
		batch.Queue(insertImportRow, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertImportRowBatchResults{br, len(arg), false}
}

func (b *InsertImportRowBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertImportRowBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertCodeValue = `-- name: UpsertCodeValue :batchone
INSERT INTO catalog.code_value (tenant_id, code_system_id, code, display, parent_code,
                                valid_from, valid_to, active, attributes)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9)
ON CONFLICT (tenant_id, code_system_id, code, valid_from) DO UPDATE
   SET display = excluded.display,
       parent_code = excluded.parent_code,
       valid_to = excluded.valid_to,
       active = excluded.active,
       attributes = excluded.attributes
 WHERE (code_value.display, code_value.parent_code, code_value.valid_to,
        code_value.active, code_value.attributes)
       IS DISTINCT FROM (excluded.display, excluded.parent_code, excluded.valid_to,
                         excluded.active, excluded.attributes)
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertCodeValueBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertCodeValueParams struct {
	TenantID     uuid.UUID
	CodeSystemID uuid.UUID
	Code         string
	Display      string
	ParentCode   *string
	ValidFrom    pgtype.Date
	ValidTo      pgtype.Date
	Active       bool
	Attributes   []byte
}

type UpsertCodeValueRow struct {
	ID      uuid.UUID
	Created bool
}

// Import upserts on (code, valid_from). A row whose payload is byte-for-byte what is
// already stored updates nothing and returns no row, which the caller counts as skipped;
// xmax distinguishes a fresh insert from an update of an existing row.
func (q *Queries) UpsertCodeValue(ctx context.Context, arg []UpsertCodeValueParams) *UpsertCodeValueBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TenantID,
			a.CodeSystemID,
			a.Code,
			a.Display,
			a.ParentCode,
			a.ValidFrom,
			a.ValidTo,
			a.Active,
			a.Attributes,
		}
		batch.Queue(upsertCodeValue, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertCodeValueBatchResults{br, len(arg), false}
}

func (b *UpsertCodeValueBatchResults) QueryRow(f func(int, UpsertCodeValueRow, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i UpsertCodeValueRow
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&i.ID, &i.Created)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *UpsertCodeValueBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
