// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: benefit_mapping.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceEntitlementMapping = `-- name: CreateServiceEntitlementMapping :one
INSERT INTO benefit.service_entitlement_mapping (
    tenant_id, plan_version_id, service_definition_id, entitlement_definition_id,
    unit_factor, valid_from, valid_to, created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5::text::numeric,
        $6, $7,
        $8, $8)
RETURNING id
`

type CreateServiceEntitlementMappingParams struct {
	TenantID                uuid.UUID
	PlanVersionID           uuid.UUID
	ServiceDefinitionID     uuid.UUID
	EntitlementDefinitionID uuid.UUID
	UnitFactor              string
	ValidFrom               pgtype.Date
	ValidTo                 pgtype.Date
	ActorID                 uuid.NullUUID
}

func (q *Queries) CreateServiceEntitlementMapping(ctx context.Context, arg CreateServiceEntitlementMappingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createServiceEntitlementMapping,
		arg.TenantID,
		arg.PlanVersionID,
		arg.ServiceDefinitionID,
		arg.EntitlementDefinitionID,
		arg.UnitFactor,
		arg.ValidFrom,
		arg.ValidTo,
		arg.ActorID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteServiceEntitlementMappings = `-- name: DeleteServiceEntitlementMappings :execrows
DELETE FROM benefit.service_entitlement_mapping
 WHERE tenant_id = $1
   AND plan_version_id = $2
`

type DeleteServiceEntitlementMappingsParams struct {
	TenantID      uuid.UUID
	PlanVersionID uuid.UUID
}

// The whole set of one version. A replace deletes and re-inserts rather than merging: a
// merge would leave behind a mapping the caller believed they had removed.
func (q *Queries) DeleteServiceEntitlementMappings(ctx context.Context, arg DeleteServiceEntitlementMappingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceEntitlementMappings, arg.TenantID, arg.PlanVersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveServiceDefinitionsByID = `-- name: ListActiveServiceDefinitionsByID :many
SELECT id, code, name, default_unit_type, active
  FROM catalog.service_definition
 WHERE tenant_id = $1
   AND id = ANY($2::uuid[])
`

type ListActiveServiceDefinitionsByIDParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

type ListActiveServiceDefinitionsByIDRow struct {
	ID              uuid.UUID
	Code            string
	Name            string
	DefaultUnitType string
	Active          bool
}

// The catalogue rows a mapping names, for the existence and active checks.
func (q *Queries) ListActiveServiceDefinitionsByID(ctx context.Context, arg ListActiveServiceDefinitionsByIDParams) ([]ListActiveServiceDefinitionsByIDRow, error) {
	rows, err := q.db.Query(ctx, listActiveServiceDefinitionsByID, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveServiceDefinitionsByIDRow
	for rows.Next() {
		var i ListActiveServiceDefinitionsByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.DefaultUnitType,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftPlanVersionsForSeed = `-- name: ListDraftPlanVersionsForSeed :many
SELECT v.id, v.plan_id, p.code AS plan_code
  FROM benefit.plan_version v
  JOIN benefit.plan p ON p.tenant_id = v.tenant_id AND p.id = v.plan_id
 WHERE v.tenant_id = $1
   AND v.status = 'DRAFT'
 ORDER BY p.code, v.version_no
`

type ListDraftPlanVersionsForSeedRow struct {
	ID       uuid.UUID
	PlanID   uuid.UUID
	PlanCode string
}

// Every draft plan version of a tenant, used by the seed to attach mappings to the
// versions a demo world happens to have.
func (q *Queries) ListDraftPlanVersionsForSeed(ctx context.Context, tenantID uuid.UUID) ([]ListDraftPlanVersionsForSeedRow, error) {
	rows, err := q.db.Query(ctx, listDraftPlanVersionsForSeed, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftPlanVersionsForSeedRow
	for rows.Next() {
		var i ListDraftPlanVersionsForSeedRow
		if err := rows.Scan(&i.ID, &i.PlanID, &i.PlanCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibilityMappings = `-- name: ListEligibilityMappings :many
SELECT m.service_definition_id, ed.code AS entitlement_code,
       m.unit_factor::text AS unit_factor
  FROM benefit.service_entitlement_mapping m
  JOIN benefit.entitlement_definition ed
       ON ed.tenant_id = m.tenant_id AND ed.id = m.entitlement_definition_id
 WHERE m.tenant_id = $1
   AND m.plan_version_id = $2
   AND (m.valid_from IS NULL OR m.valid_from <= $3::date)
   AND (m.valid_to IS NULL OR m.valid_to > $3::date)
`

type ListEligibilityMappingsParams struct {
	TenantID      uuid.UUID
	PlanVersionID uuid.UUID
	ServiceDate   pgtype.Date
}

type ListEligibilityMappingsRow struct {
	ServiceDefinitionID uuid.UUID
	EntitlementCode     string
	UnitFactor          string
}

// What the eligibility resolver reads: the entitlement code a service draws from and the
// factor it draws it at, for the plan version the check resolved. The service date filter
// is here rather than in Go because a mapping outside its own window is not a mapping.
func (q *Queries) ListEligibilityMappings(ctx context.Context, arg ListEligibilityMappingsParams) ([]ListEligibilityMappingsRow, error) {
	rows, err := q.db.Query(ctx, listEligibilityMappings, arg.TenantID, arg.PlanVersionID, arg.ServiceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibilityMappingsRow
	for rows.Next() {
		var i ListEligibilityMappingsRow
		if err := rows.Scan(&i.ServiceDefinitionID, &i.EntitlementCode, &i.UnitFactor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitlementDefinitionsForMapping = `-- name: ListEntitlementDefinitionsForMapping :many
SELECT id, code, unit_type
  FROM benefit.entitlement_definition
 WHERE tenant_id = $1
   AND plan_version_id = $2
 ORDER BY code
`

type ListEntitlementDefinitionsForMappingParams struct {
	TenantID      uuid.UUID
	PlanVersionID uuid.UUID
}

type ListEntitlementDefinitionsForMappingRow struct {
	ID       uuid.UUID
	Code     string
	UnitType string
}

// The definitions a mapping of this version may point at, by code. The put command
// resolves the caller's entitlement code against this list, so a code that belongs to a
// different version is a field error rather than a foreign key violation.
func (q *Queries) ListEntitlementDefinitionsForMapping(ctx context.Context, arg ListEntitlementDefinitionsForMappingParams) ([]ListEntitlementDefinitionsForMappingRow, error) {
	rows, err := q.db.Query(ctx, listEntitlementDefinitionsForMapping, arg.TenantID, arg.PlanVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntitlementDefinitionsForMappingRow
	for rows.Next() {
		var i ListEntitlementDefinitionsForMappingRow
		if err := rows.Scan(&i.ID, &i.Code, &i.UnitType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceEntitlementMappings = `-- name: ListServiceEntitlementMappings :many

SELECT m.id, m.plan_version_id, m.service_definition_id, m.entitlement_definition_id,
       m.unit_factor::text AS unit_factor,
       m.valid_from, m.valid_to, m.created_at, m.row_version,
       sd.code AS service_code, sd.name AS service_name,
       ed.code AS entitlement_code, ed.unit_type AS unit_type
  FROM benefit.service_entitlement_mapping m
  JOIN catalog.service_definition sd
       ON sd.tenant_id = m.tenant_id AND sd.id = m.service_definition_id
  JOIN benefit.entitlement_definition ed
       ON ed.tenant_id = m.tenant_id AND ed.id = m.entitlement_definition_id
 WHERE m.tenant_id = $1
   AND m.plan_version_id = $2
 ORDER BY sd.code, m.id
`

type ListServiceEntitlementMappingsParams struct {
	TenantID      uuid.UUID
	PlanVersionID uuid.UUID
}

type ListServiceEntitlementMappingsRow struct {
	ID                      uuid.UUID
	PlanVersionID           uuid.UUID
	ServiceDefinitionID     uuid.UUID
	EntitlementDefinitionID uuid.UUID
	UnitFactor              string
	ValidFrom               pgtype.Date
	ValidTo                 pgtype.Date
	CreatedAt               time.Time
	RowVersion              int64
	ServiceCode             string
	ServiceName             string
	EntitlementCode         string
	UnitType                string
}

// Service → entitlement mapping (WP-I5-05 section 2.1): the sentence that says which
// balance a catalogue service spends, and how much of it.
//
// Every write here runs against a DRAFT plan version. That is not asserted in SQL because
// the trigger of migration 000035 asserts it for every statement, including the ones
// nobody has written yet.
// The set of one plan version, with the two codes a person reads it by. Ordered by the
// service code so the list a screen shows is stable between calls.
func (q *Queries) ListServiceEntitlementMappings(ctx context.Context, arg ListServiceEntitlementMappingsParams) ([]ListServiceEntitlementMappingsRow, error) {
	rows, err := q.db.Query(ctx, listServiceEntitlementMappings, arg.TenantID, arg.PlanVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceEntitlementMappingsRow
	for rows.Next() {
		var i ListServiceEntitlementMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanVersionID,
			&i.ServiceDefinitionID,
			&i.EntitlementDefinitionID,
			&i.UnitFactor,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.RowVersion,
			&i.ServiceCode,
			&i.ServiceName,
			&i.EntitlementCode,
			&i.UnitType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
