// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claim_source.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimSourceAlreadyRaised = `-- name: ClaimSourceAlreadyRaised :one
SELECT EXISTS (SELECT 1 FROM claim.claim cl WHERE cl.tenant_id=$1
 AND cl.case_id=$2 AND cl.status<>'CANCELLED') AS already_raised
`

type ClaimSourceAlreadyRaisedParams struct {
	TenantID uuid.UUID
	CaseID   uuid.NullUUID
}

// Called AFTER acquiring the case lock: a new READ COMMITTED snapshot sees a competing
// handoff that committed while LockClaimSource was waiting.
func (q *Queries) ClaimSourceAlreadyRaised(ctx context.Context, arg ClaimSourceAlreadyRaisedParams) (bool, error) {
	row := q.db.QueryRow(ctx, claimSourceAlreadyRaised, arg.TenantID, arg.CaseID)
	var already_raised bool
	err := row.Scan(&already_raised)
	return already_raised, err
}

const claimSourceLines = `-- name: ClaimSourceLines :many
SELECT ai.service_definition_id, sd.code AS service_code, sd.name AS service_name, ri.unit_type,
       (ai.approved_quantity-ai.consumed_quantity)::text AS quantity,
       COALESCE((SELECT jsonb_agg(m.id) FROM health.medical_report m
         JOIN health.medical_report_service ms ON ms.tenant_id=m.tenant_id AND ms.report_id=m.id
         WHERE m.tenant_id=ai.tenant_id AND m.case_id=$1 AND m.person_id=$2
           AND m.issuing_provider_organization_id=$3 AND m.status='APPROVED'
           AND m.valid_from<=$4::date AND m.valid_to>=$4::date
           AND ms.service_definition_id=ai.service_definition_id),'[]'::jsonb) AS report_ids
FROM service.authorization_item ai
JOIN catalog.service_definition sd ON sd.tenant_id=ai.tenant_id AND sd.id=ai.service_definition_id
JOIN service.service_request_item ri ON ri.tenant_id=ai.tenant_id AND ri.id=ai.request_item_id
WHERE ai.tenant_id=$5 AND ai.authorization_id=$6
  AND ai.approved_quantity>ai.consumed_quantity
ORDER BY ri.line_no
`

type ClaimSourceLinesParams struct {
	CaseID          uuid.NullUUID
	PersonID        uuid.UUID
	ProviderID      uuid.NullUUID
	ServiceDate     pgtype.Date
	TenantID        uuid.UUID
	AuthorizationID uuid.UUID
}

type ClaimSourceLinesRow struct {
	ServiceDefinitionID uuid.UUID
	ServiceCode         string
	ServiceName         string
	UnitType            string
	Quantity            string
	ReportIds           interface{}
}

func (q *Queries) ClaimSourceLines(ctx context.Context, arg ClaimSourceLinesParams) ([]ClaimSourceLinesRow, error) {
	rows, err := q.db.Query(ctx, claimSourceLines,
		arg.CaseID,
		arg.PersonID,
		arg.ProviderID,
		arg.ServiceDate,
		arg.TenantID,
		arg.AuthorizationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimSourceLinesRow
	for rows.Next() {
		var i ClaimSourceLinesRow
		if err := rows.Scan(
			&i.ServiceDefinitionID,
			&i.ServiceCode,
			&i.ServiceName,
			&i.UnitType,
			&i.Quantity,
			&i.ReportIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimSources = `-- name: ListClaimSources :many
SELECT c.id, c.opened_at, c.row_version, r.request_reference, r.service_date,
       concat_ws(' ', p.first_name, p.middle_name, p.last_name)::text AS person_display_name
FROM health.health_case c
JOIN service.service_request r ON r.tenant_id=c.tenant_id AND r.id=c.service_request_id
  AND r.person_id=c.person_id AND r.program_id=c.program_id AND r.enrollment_id=c.enrollment_id
  AND r.provider_tenant_organization_id=c.provider_organization_id
JOIN party.person p ON p.tenant_id=c.tenant_id AND p.id=c.person_id
WHERE c.tenant_id=$1 AND c.case_type='OUTPATIENT'
  AND ($2::uuid[] IS NULL OR c.provider_organization_id=ANY($2::uuid[]))
  AND r.status IN ('APPROVED','PARTIALLY_APPROVED')
  AND EXISTS (SELECT 1 FROM service.authorization a WHERE a.tenant_id=c.tenant_id AND a.request_id=r.id
    AND a.status IN ('ACTIVE','PARTIALLY_USED') AND a.valid_to>$3::timestamptz)
  AND NOT EXISTS (SELECT 1 FROM claim.claim cl WHERE cl.tenant_id=c.tenant_id AND cl.case_id=c.id AND cl.status<>'CANCELLED')
  AND ($4::uuid IS NULL OR (c.opened_at,c.id)<($5::timestamptz,$4::uuid))
ORDER BY c.opened_at DESC,c.id DESC LIMIT $6
`

type ListClaimSourcesParams struct {
	TenantID  uuid.UUID
	ScopeIds  []uuid.UUID
	Now       time.Time
	AfterID   uuid.NullUUID
	AfterTime *time.Time
	PageSize  int32
}

type ListClaimSourcesRow struct {
	ID                uuid.UUID
	OpenedAt          time.Time
	RowVersion        int64
	RequestReference  string
	ServiceDate       pgtype.Date
	PersonDisplayName string
}

// Financial handoff: every join stays within the tenant and the case's provider.
// Clinical references in LockClaimSource are internal only, never source response fields.
func (q *Queries) ListClaimSources(ctx context.Context, arg ListClaimSourcesParams) ([]ListClaimSourcesRow, error) {
	rows, err := q.db.Query(ctx, listClaimSources,
		arg.TenantID,
		arg.ScopeIds,
		arg.Now,
		arg.AfterID,
		arg.AfterTime,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClaimSourcesRow
	for rows.Next() {
		var i ListClaimSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.OpenedAt,
			&i.RowVersion,
			&i.RequestReference,
			&i.ServiceDate,
			&i.PersonDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClaimSource = `-- name: LockClaimSource :one
SELECT c.id, c.person_id, c.program_id, c.enrollment_id, c.provider_organization_id,
       c.opened_at, c.row_version, r.request_reference, r.service_date,
       concat_ws(' ', p.first_name,p.middle_name,p.last_name)::text AS person_display_name,
       EXISTS (SELECT 1 FROM claim.claim cl WHERE cl.tenant_id=c.tenant_id AND cl.case_id=c.id AND cl.status<>'CANCELLED') AS already_raised,
       COALESCE((SELECT jsonb_agg(a.id) FROM service.authorization a WHERE a.tenant_id=c.tenant_id AND a.request_id=r.id
         AND a.status IN ('ACTIVE','PARTIALLY_USED') AND a.valid_to>$1::timestamptz),'[]'::jsonb) AS authorization_ids,
       COALESCE((SELECT jsonb_agg(d.id) FROM health.encounter e JOIN health.diagnosis d ON d.tenant_id=e.tenant_id AND d.encounter_id=e.id
         WHERE e.tenant_id=c.tenant_id AND e.case_id=c.id AND e.ended_at IS NOT NULL AND d.diagnosis_type='PRIMARY'),'[]'::jsonb) AS diagnosis_ids,
       EXISTS (SELECT 1 FROM health.encounter e WHERE e.tenant_id=c.tenant_id AND e.case_id=c.id AND e.ended_at IS NULL) AS ongoing
FROM health.health_case c
JOIN service.service_request r ON r.tenant_id=c.tenant_id AND r.id=c.service_request_id
  AND r.person_id=c.person_id AND r.program_id=c.program_id AND r.enrollment_id=c.enrollment_id
  AND r.provider_tenant_organization_id=c.provider_organization_id
JOIN party.person p ON p.tenant_id=c.tenant_id AND p.id=c.person_id
WHERE c.tenant_id=$2 AND c.id=$3 AND c.case_type='OUTPATIENT'
  AND r.status IN ('APPROVED','PARTIALLY_APPROVED')
  AND ($4::uuid[] IS NULL OR c.provider_organization_id=ANY($4::uuid[]))
FOR UPDATE OF c
`

type LockClaimSourceParams struct {
	Now      time.Time
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type LockClaimSourceRow struct {
	ID                     uuid.UUID
	PersonID               uuid.UUID
	ProgramID              uuid.UUID
	EnrollmentID           uuid.UUID
	ProviderOrganizationID uuid.NullUUID
	OpenedAt               time.Time
	RowVersion             int64
	RequestReference       string
	ServiceDate            pgtype.Date
	PersonDisplayName      string
	AlreadyRaised          bool
	AuthorizationIds       interface{}
	DiagnosisIds           interface{}
	Ongoing                bool
}

func (q *Queries) LockClaimSource(ctx context.Context, arg LockClaimSourceParams) (LockClaimSourceRow, error) {
	row := q.db.QueryRow(ctx, lockClaimSource,
		arg.Now,
		arg.TenantID,
		arg.ID,
		arg.ScopeIds,
	)
	var i LockClaimSourceRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ProgramID,
		&i.EnrollmentID,
		&i.ProviderOrganizationID,
		&i.OpenedAt,
		&i.RowVersion,
		&i.RequestReference,
		&i.ServiceDate,
		&i.PersonDisplayName,
		&i.AlreadyRaised,
		&i.AuthorizationIds,
		&i.DiagnosisIds,
		&i.Ongoing,
	)
	return i, err
}
