// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directory.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addOrganizationIdentifier = `-- name: AddOrganizationIdentifier :execrows
INSERT INTO directory.organization_identifier (organization_id, identifier_type, identifier_value, issuing_country, is_primary)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (identifier_type, identifier_value) DO NOTHING
`

type AddOrganizationIdentifierParams struct {
	OrganizationID  uuid.UUID
	IdentifierType  string
	IdentifierValue string
	IssuingCountry  *string
	IsPrimary       bool
}

func (q *Queries) AddOrganizationIdentifier(ctx context.Context, arg AddOrganizationIdentifierParams) (int64, error) {
	result, err := q.db.Exec(ctx, addOrganizationIdentifier,
		arg.OrganizationID,
		arg.IdentifierType,
		arg.IdentifierValue,
		arg.IssuingCountry,
		arg.IsPrimary,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO directory.organization (legal_name, display_name, organization_kind, country_code, tax_number_cipher, tax_number_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateOrganizationParams struct {
	LegalName        string
	DisplayName      string
	OrganizationKind string
	CountryCode      string
	TaxNumberCipher  []byte
	TaxNumberHash    []byte
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.LegalName,
		arg.DisplayName,
		arg.OrganizationKind,
		arg.CountryCode,
		arg.TaxNumberCipher,
		arg.TaxNumberHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTenantOrganizationRelationship = `-- name: CreateTenantOrganizationRelationship :one
INSERT INTO directory.tenant_organization (tenant_id, organization_id, relationship_role, tenant_code)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, row_version, status, valid_period
`

type CreateTenantOrganizationRelationshipParams struct {
	TenantID         uuid.UUID
	OrganizationID   uuid.UUID
	RelationshipRole string
	TenantCode       *string
}

type CreateTenantOrganizationRelationshipRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	RowVersion  int64
	Status      string
	ValidPeriod pgtype.Range[pgtype.Date]
}

func (q *Queries) CreateTenantOrganizationRelationship(ctx context.Context, arg CreateTenantOrganizationRelationshipParams) (CreateTenantOrganizationRelationshipRow, error) {
	row := q.db.QueryRow(ctx, createTenantOrganizationRelationship,
		arg.TenantID,
		arg.OrganizationID,
		arg.RelationshipRole,
		arg.TenantCode,
	)
	var i CreateTenantOrganizationRelationshipRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.RowVersion,
		&i.Status,
		&i.ValidPeriod,
	)
	return i, err
}

const findOrganizationByTaxHash = `-- name: FindOrganizationByTaxHash :one

SELECT id, legal_name, display_name, organization_kind, country_code, status, row_version
  FROM directory.organization
 WHERE country_code = $1 AND tax_number_hash = $2
`

type FindOrganizationByTaxHashParams struct {
	CountryCode   string
	TaxNumberHash []byte
}

type FindOrganizationByTaxHashRow struct {
	ID               uuid.UUID
	LegalName        string
	DisplayName      string
	OrganizationKind string
	CountryCode      string
	Status           string
	RowVersion       int64
}

// Organization directory queries (WP-I1-03). Global rows (directory.organization,
// directory.organization_identifier) have no RLS; relationship rows are tenant-bound.
func (q *Queries) FindOrganizationByTaxHash(ctx context.Context, arg FindOrganizationByTaxHashParams) (FindOrganizationByTaxHashRow, error) {
	row := q.db.QueryRow(ctx, findOrganizationByTaxHash, arg.CountryCode, arg.TaxNumberHash)
	var i FindOrganizationByTaxHashRow
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.DisplayName,
		&i.OrganizationKind,
		&i.CountryCode,
		&i.Status,
		&i.RowVersion,
	)
	return i, err
}

const findOrganizationIdentifierOwner = `-- name: FindOrganizationIdentifierOwner :one
SELECT organization_id FROM directory.organization_identifier
 WHERE identifier_type = $1 AND identifier_value = $2
`

type FindOrganizationIdentifierOwnerParams struct {
	IdentifierType  string
	IdentifierValue string
}

func (q *Queries) FindOrganizationIdentifierOwner(ctx context.Context, arg FindOrganizationIdentifierOwnerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findOrganizationIdentifierOwner, arg.IdentifierType, arg.IdentifierValue)
	var organization_id uuid.UUID
	err := row.Scan(&organization_id)
	return organization_id, err
}

const getTenantOrganization = `-- name: GetTenantOrganization :one
SELECT t.id, t.organization_id, t.relationship_role, t.tenant_code, t.status AS relationship_status,
       lower(t.valid_period)::date AS valid_from, upper(t.valid_period)::date AS valid_to,
       t.created_at, t.row_version,
       o.legal_name, o.display_name, o.organization_kind, o.country_code, o.status AS organization_status,
       o.tax_number_cipher
  FROM directory.tenant_organization t
  JOIN directory.organization o ON o.id = t.organization_id
 WHERE t.tenant_id = $1 AND t.id = $2
`

type GetTenantOrganizationParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetTenantOrganizationRow struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	RelationshipRole   string
	TenantCode         *string
	RelationshipStatus string
	ValidFrom          pgtype.Date
	ValidTo            pgtype.Date
	CreatedAt          time.Time
	RowVersion         int64
	LegalName          string
	DisplayName        string
	OrganizationKind   string
	CountryCode        string
	OrganizationStatus string
	TaxNumberCipher    []byte
}

func (q *Queries) GetTenantOrganization(ctx context.Context, arg GetTenantOrganizationParams) (GetTenantOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getTenantOrganization, arg.TenantID, arg.ID)
	var i GetTenantOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RelationshipRole,
		&i.TenantCode,
		&i.RelationshipStatus,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
		&i.RowVersion,
		&i.LegalName,
		&i.DisplayName,
		&i.OrganizationKind,
		&i.CountryCode,
		&i.OrganizationStatus,
		&i.TaxNumberCipher,
	)
	return i, err
}

const listOrganizationIdentifiers = `-- name: ListOrganizationIdentifiers :many
SELECT identifier_type, identifier_value, is_primary
  FROM directory.organization_identifier
 WHERE organization_id = $1
 ORDER BY is_primary DESC, identifier_type, identifier_value
`

type ListOrganizationIdentifiersRow struct {
	IdentifierType  string
	IdentifierValue string
	IsPrimary       bool
}

func (q *Queries) ListOrganizationIdentifiers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationIdentifiersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationIdentifiers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationIdentifiersRow
	for rows.Next() {
		var i ListOrganizationIdentifiersRow
		if err := rows.Scan(&i.IdentifierType, &i.IdentifierValue, &i.IsPrimary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantOrganizations = `-- name: ListTenantOrganizations :many
SELECT t.id, t.organization_id, t.relationship_role, t.status AS relationship_status,
       t.created_at, o.display_name, o.organization_kind
  FROM directory.tenant_organization t
  JOIN directory.organization o ON o.id = t.organization_id
 WHERE t.tenant_id = $1
   AND ($2::text IS NULL OR t.relationship_role = $2::text)
   AND ($3::text IS NULL OR o.display_name ILIKE '%' || $3::text || '%')
   AND ($4::timestamptz IS NULL
        OR (t.created_at, t.id) < ($4::timestamptz, $5::uuid))
 ORDER BY t.created_at DESC, t.id DESC
 LIMIT $6
`

type ListTenantOrganizationsParams struct {
	TenantID        uuid.UUID
	Role            *string
	Q               *string
	CursorCreatedAt *time.Time
	CursorID        uuid.NullUUID
	PageSize        int32
}

type ListTenantOrganizationsRow struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	RelationshipRole   string
	RelationshipStatus string
	CreatedAt          time.Time
	DisplayName        string
	OrganizationKind   string
}

// Keyset pagination on (created_at DESC, id DESC); the caller asks for limit+1 rows to
// learn whether a next page exists.
func (q *Queries) ListTenantOrganizations(ctx context.Context, arg ListTenantOrganizationsParams) ([]ListTenantOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listTenantOrganizations,
		arg.TenantID,
		arg.Role,
		arg.Q,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantOrganizationsRow
	for rows.Next() {
		var i ListTenantOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RelationshipRole,
			&i.RelationshipStatus,
			&i.CreatedAt,
			&i.DisplayName,
			&i.OrganizationKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationRelationshipCount = `-- name: OrganizationRelationshipCount :one
SELECT directory.organization_relationship_count($1)::integer AS relationship_count
`

func (q *Queries) OrganizationRelationshipCount(ctx context.Context, org uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, organizationRelationshipCount, org)
	var relationship_count int32
	err := row.Scan(&relationship_count)
	return relationship_count, err
}

const updateOrganizationDisplayName = `-- name: UpdateOrganizationDisplayName :exec
UPDATE directory.organization SET display_name = $2 WHERE id = $1
`

type UpdateOrganizationDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName string
}

func (q *Queries) UpdateOrganizationDisplayName(ctx context.Context, arg UpdateOrganizationDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationDisplayName, arg.ID, arg.DisplayName)
	return err
}

const updateTenantOrganization = `-- name: UpdateTenantOrganization :one
UPDATE directory.tenant_organization
   SET status = $3,
       tenant_code = $4
 WHERE tenant_id = $1 AND id = $2 AND row_version = $5
RETURNING row_version
`

type UpdateTenantOrganizationParams struct {
	TenantID   uuid.UUID
	ID         uuid.UUID
	Status     string
	TenantCode *string
	RowVersion int64
}

// Optimistic concurrency: the WHERE on row_version makes a stale If-Match update no rows.
// The trigger platform.tg_touch_row bumps row_version and updated_at.
func (q *Queries) UpdateTenantOrganization(ctx context.Context, arg UpdateTenantOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateTenantOrganization,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.TenantCode,
		arg.RowVersion,
	)
	var row_version int64
	err := row.Scan(&row_version)
	return row_version, err
}
