// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDocumentLegalHold = `-- name: CreateDocumentLegalHold :one
INSERT INTO document.legal_hold (
    tenant_id, object_id, person_id, aggregate_type, aggregate_id, reason, placed_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7)
RETURNING id, object_id, person_id, aggregate_type, aggregate_id, reason, placed_by,
          placed_at, released_at, released_by, row_version
`

type CreateDocumentLegalHoldParams struct {
	TenantID      uuid.UUID
	ObjectID      uuid.NullUUID
	PersonID      uuid.NullUUID
	AggregateType *string
	AggregateID   uuid.NullUUID
	Reason        string
	ActorID       uuid.NullUUID
}

type CreateDocumentLegalHoldRow struct {
	ID            uuid.UUID
	ObjectID      uuid.NullUUID
	PersonID      uuid.NullUUID
	AggregateType *string
	AggregateID   uuid.NullUUID
	Reason        string
	PlacedBy      uuid.NullUUID
	PlacedAt      time.Time
	ReleasedAt    *time.Time
	ReleasedBy    uuid.NullUUID
	RowVersion    int64
}

func (q *Queries) CreateDocumentLegalHold(ctx context.Context, arg CreateDocumentLegalHoldParams) (CreateDocumentLegalHoldRow, error) {
	row := q.db.QueryRow(ctx, createDocumentLegalHold,
		arg.TenantID,
		arg.ObjectID,
		arg.PersonID,
		arg.AggregateType,
		arg.AggregateID,
		arg.Reason,
		arg.ActorID,
	)
	var i CreateDocumentLegalHoldRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.PersonID,
		&i.AggregateType,
		&i.AggregateID,
		&i.Reason,
		&i.PlacedBy,
		&i.PlacedAt,
		&i.ReleasedAt,
		&i.ReleasedBy,
		&i.RowVersion,
	)
	return i, err
}

const createDocumentLink = `-- name: CreateDocumentLink :one
INSERT INTO document.link (
    tenant_id, object_id, aggregate_type, aggregate_id, document_type_code, purpose,
    required_permission, created_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8)
RETURNING id, object_id, aggregate_type, aggregate_id, document_type_code, purpose,
          required_permission, created_by, created_at
`

type CreateDocumentLinkParams struct {
	TenantID           uuid.UUID
	ObjectID           uuid.UUID
	AggregateType      string
	AggregateID        uuid.UUID
	DocumentTypeCode   string
	Purpose            *string
	RequiredPermission *string
	ActorID            uuid.NullUUID
}

type CreateDocumentLinkRow struct {
	ID                 uuid.UUID
	ObjectID           uuid.UUID
	AggregateType      string
	AggregateID        uuid.UUID
	DocumentTypeCode   string
	Purpose            *string
	RequiredPermission *string
	CreatedBy          uuid.NullUUID
	CreatedAt          time.Time
}

func (q *Queries) CreateDocumentLink(ctx context.Context, arg CreateDocumentLinkParams) (CreateDocumentLinkRow, error) {
	row := q.db.QueryRow(ctx, createDocumentLink,
		arg.TenantID,
		arg.ObjectID,
		arg.AggregateType,
		arg.AggregateID,
		arg.DocumentTypeCode,
		arg.Purpose,
		arg.RequiredPermission,
		arg.ActorID,
	)
	var i CreateDocumentLinkRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.AggregateType,
		&i.AggregateID,
		&i.DocumentTypeCode,
		&i.Purpose,
		&i.RequiredPermission,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createDocumentObject = `-- name: CreateDocumentObject :one

INSERT INTO document.object (
    id, tenant_id, object_key, classification, original_filename, content_type,
    owner_tenant_organization_id, uploaded_by, created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8,
        $8, $8)
RETURNING id, object_key, bucket, classification, original_filename, content_type,
          byte_size, sha256, scan_status, owner_tenant_organization_id,
          duplicate_of_object_id, uploaded_by, uploaded_at, purged_at, created_at, row_version
`

type CreateDocumentObjectParams struct {
	ID                        uuid.UUID
	TenantID                  uuid.UUID
	ObjectKey                 string
	Classification            string
	OriginalFilename          string
	ContentType               string
	OwnerTenantOrganizationID uuid.NullUUID
	ActorID                   uuid.NullUUID
}

type CreateDocumentObjectRow struct {
	ID                        uuid.UUID
	ObjectKey                 string
	Bucket                    string
	Classification            string
	OriginalFilename          string
	ContentType               string
	ByteSize                  *int64
	Sha256                    []byte
	ScanStatus                string
	OwnerTenantOrganizationID uuid.NullUUID
	DuplicateOfObjectID       uuid.NullUUID
	UploadedBy                uuid.NullUUID
	UploadedAt                time.Time
	PurgedAt                  *time.Time
	CreatedAt                 time.Time
	RowVersion                int64
}

// Document object, version, link, scan result and legal hold queries (WP-I4-04,
// v1.2 9.15, 19.x, 39.14).
//
// Four properties shape this file.
//
// **No statement here reads or writes a file body.** There is none to read: the object
// store holds the bytes and these rows hold the key they are under. The only bytea that
// appears at all is a 32-byte digest.
//
// The boundary is the same shape the service request and authorization queries apply, over
// this package's own resource: `scope_ids` is a nullable uuid[] of tenant organization ids,
// NULL means the caller sees every document of the tenant and a non-null array binds it to
// the documents those organizations own plus the tenant's own. It is applied in every read
// including the single-row ones, so a document outside it is answered 404 rather than 403 —
// that such a document exists at all is somebody else's business.
//
// The scan status is never a parameter. PENDING is the insert default, MarkScanning moves
// to SCANNING, and CLEAN, INFECTED and FAILED each have a statement of their own whose
// predicate carries the status it may move from. There is deliberately no way for a caller
// to hand this file a status.
//
// PromoteDocumentObject is the only statement that writes bucket = 'secure', and its
// predicate carries the CLEAN verdict that earns it.
// The id and the key are given rather than generated: the key contains the id, so they are
// one decision made in one place.
func (q *Queries) CreateDocumentObject(ctx context.Context, arg CreateDocumentObjectParams) (CreateDocumentObjectRow, error) {
	row := q.db.QueryRow(ctx, createDocumentObject,
		arg.ID,
		arg.TenantID,
		arg.ObjectKey,
		arg.Classification,
		arg.OriginalFilename,
		arg.ContentType,
		arg.OwnerTenantOrganizationID,
		arg.ActorID,
	)
	var i CreateDocumentObjectRow
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Bucket,
		&i.Classification,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256,
		&i.ScanStatus,
		&i.OwnerTenantOrganizationID,
		&i.DuplicateOfObjectID,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.PurgedAt,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const createDocumentScanResult = `-- name: CreateDocumentScanResult :one
INSERT INTO document.scan_result (
    tenant_id, object_id, version_id, engine, signature_version, outcome, finding)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7)
RETURNING id, object_id, version_id, engine, signature_version, outcome, finding, scanned_at
`

type CreateDocumentScanResultParams struct {
	TenantID         uuid.UUID
	ObjectID         uuid.UUID
	VersionID        uuid.UUID
	Engine           string
	SignatureVersion *string
	Outcome          string
	Finding          *string
}

type CreateDocumentScanResultRow struct {
	ID               uuid.UUID
	ObjectID         uuid.UUID
	VersionID        uuid.UUID
	Engine           string
	SignatureVersion *string
	Outcome          string
	Finding          *string
	ScannedAt        time.Time
}

// scanned_at is part of the unique key, so two attempts on one version are two rows rather
// than a conflict: a file that failed and then passed keeps both verdicts.
func (q *Queries) CreateDocumentScanResult(ctx context.Context, arg CreateDocumentScanResultParams) (CreateDocumentScanResultRow, error) {
	row := q.db.QueryRow(ctx, createDocumentScanResult,
		arg.TenantID,
		arg.ObjectID,
		arg.VersionID,
		arg.Engine,
		arg.SignatureVersion,
		arg.Outcome,
		arg.Finding,
	)
	var i CreateDocumentScanResultRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.VersionID,
		&i.Engine,
		&i.SignatureVersion,
		&i.Outcome,
		&i.Finding,
		&i.ScannedAt,
	)
	return i, err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document.version (
    tenant_id, object_id, version_no, byte_size, content_type, encryption_key_ref, created_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7)
RETURNING id, object_id, version_no, byte_size, content_type, encryption_key_ref, created_at
`

type CreateDocumentVersionParams struct {
	TenantID         uuid.UUID
	ObjectID         uuid.UUID
	VersionNo        int32
	ByteSize         int64
	ContentType      string
	EncryptionKeyRef *string
	ActorID          uuid.NullUUID
}

type CreateDocumentVersionRow struct {
	ID               uuid.UUID
	ObjectID         uuid.UUID
	VersionNo        int32
	ByteSize         int64
	ContentType      string
	EncryptionKeyRef *string
	CreatedAt        time.Time
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (CreateDocumentVersionRow, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.TenantID,
		arg.ObjectID,
		arg.VersionNo,
		arg.ByteSize,
		arg.ContentType,
		arg.EncryptionKeyRef,
		arg.ActorID,
	)
	var i CreateDocumentVersionRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.VersionNo,
		&i.ByteSize,
		&i.ContentType,
		&i.EncryptionKeyRef,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocumentLink = `-- name: DeleteDocumentLink :execrows
DELETE FROM document.link
 WHERE tenant_id = $1
   AND object_id = $2
   AND id = $3
`

type DeleteDocumentLinkParams struct {
	TenantID uuid.UUID
	ObjectID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteDocumentLink(ctx context.Context, arg DeleteDocumentLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocumentLink, arg.TenantID, arg.ObjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const documentHasActiveLegalHold = `-- name: DocumentHasActiveLegalHold :one
SELECT EXISTS (
    SELECT 1
      FROM document.legal_hold h
     WHERE h.tenant_id = $1
       AND h.released_at IS NULL
       AND (h.object_id = $2
            OR (h.aggregate_id IS NOT NULL AND EXISTS (
                    SELECT 1 FROM document.link l
                     WHERE l.tenant_id = h.tenant_id
                       AND l.object_id = $2
                       AND l.aggregate_type = h.aggregate_type
                       AND l.aggregate_id = h.aggregate_id)))
) AS held
`

type DocumentHasActiveLegalHoldParams struct {
	TenantID uuid.UUID
	ObjectID uuid.NullUUID
}

// Whether anything holds this document: a hold on the document itself, or one on a record
// it is linked to. Both count, because a hold over a case is a hold over the case's
// documents.
func (q *Queries) DocumentHasActiveLegalHold(ctx context.Context, arg DocumentHasActiveLegalHoldParams) (bool, error) {
	row := q.db.QueryRow(ctx, documentHasActiveLegalHold, arg.TenantID, arg.ObjectID)
	var held bool
	err := row.Scan(&held)
	return held, err
}

const findCleanDocumentByDigest = `-- name: FindCleanDocumentByDigest :one
SELECT o.id, o.object_key, o.bucket, o.classification, o.original_filename, o.content_type,
       o.byte_size, o.sha256, o.scan_status, o.owner_tenant_organization_id,
       o.duplicate_of_object_id, o.uploaded_by, o.uploaded_at, o.purged_at, o.created_at,
       o.row_version
  FROM document.object o
 WHERE o.tenant_id = $1
   AND o.sha256 = $2
   AND o.scan_status = 'CLEAN'
   AND o.duplicate_of_object_id IS NULL
   AND o.purged_at IS NULL
   AND ($3::uuid[] IS NULL
        OR o.owner_tenant_organization_id IS NULL
        OR o.owner_tenant_organization_id = ANY($3::uuid[]))
 LIMIT 1
`

type FindCleanDocumentByDigestParams struct {
	TenantID uuid.UUID
	Sha256   []byte
	ScopeIds []uuid.UUID
}

type FindCleanDocumentByDigestRow struct {
	ID                        uuid.UUID
	ObjectKey                 string
	Bucket                    string
	Classification            string
	OriginalFilename          string
	ContentType               string
	ByteSize                  *int64
	Sha256                    []byte
	ScanStatus                string
	OwnerTenantOrganizationID uuid.NullUUID
	DuplicateOfObjectID       uuid.NullUUID
	UploadedBy                uuid.NullUUID
	UploadedAt                time.Time
	PurgedAt                  *time.Time
	CreatedAt                 time.Time
	RowVersion                int64
}

// The canonical stored copy of one digest. Duplicates are excluded: they are pointers at
// this row, and returning one would send the caller to a pointer instead of the file.
func (q *Queries) FindCleanDocumentByDigest(ctx context.Context, arg FindCleanDocumentByDigestParams) (FindCleanDocumentByDigestRow, error) {
	row := q.db.QueryRow(ctx, findCleanDocumentByDigest, arg.TenantID, arg.Sha256, arg.ScopeIds)
	var i FindCleanDocumentByDigestRow
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Bucket,
		&i.Classification,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256,
		&i.ScanStatus,
		&i.OwnerTenantOrganizationID,
		&i.DuplicateOfObjectID,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.PurgedAt,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getDocumentLegalHold = `-- name: GetDocumentLegalHold :one
SELECT h.id, h.object_id, h.person_id, h.aggregate_type, h.aggregate_id, h.reason,
       h.placed_by, h.placed_at, h.released_at, h.released_by, h.row_version
  FROM document.legal_hold h
 WHERE h.tenant_id = $1
   AND h.id = $2
`

type GetDocumentLegalHoldParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetDocumentLegalHoldRow struct {
	ID            uuid.UUID
	ObjectID      uuid.NullUUID
	PersonID      uuid.NullUUID
	AggregateType *string
	AggregateID   uuid.NullUUID
	Reason        string
	PlacedBy      uuid.NullUUID
	PlacedAt      time.Time
	ReleasedAt    *time.Time
	ReleasedBy    uuid.NullUUID
	RowVersion    int64
}

func (q *Queries) GetDocumentLegalHold(ctx context.Context, arg GetDocumentLegalHoldParams) (GetDocumentLegalHoldRow, error) {
	row := q.db.QueryRow(ctx, getDocumentLegalHold, arg.TenantID, arg.ID)
	var i GetDocumentLegalHoldRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.PersonID,
		&i.AggregateType,
		&i.AggregateID,
		&i.Reason,
		&i.PlacedBy,
		&i.PlacedAt,
		&i.ReleasedAt,
		&i.ReleasedBy,
		&i.RowVersion,
	)
	return i, err
}

const getDocumentObject = `-- name: GetDocumentObject :one
SELECT o.id, o.object_key, o.bucket, o.classification, o.original_filename, o.content_type,
       o.byte_size, o.sha256, o.scan_status, o.owner_tenant_organization_id,
       o.duplicate_of_object_id, o.uploaded_by, o.uploaded_at, o.purged_at, o.created_at,
       o.row_version
  FROM document.object o
 WHERE o.tenant_id = $1
   AND o.id = $2
   AND ($3::uuid[] IS NULL
        OR o.owner_tenant_organization_id IS NULL
        OR o.owner_tenant_organization_id = ANY($3::uuid[]))
`

type GetDocumentObjectParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type GetDocumentObjectRow struct {
	ID                        uuid.UUID
	ObjectKey                 string
	Bucket                    string
	Classification            string
	OriginalFilename          string
	ContentType               string
	ByteSize                  *int64
	Sha256                    []byte
	ScanStatus                string
	OwnerTenantOrganizationID uuid.NullUUID
	DuplicateOfObjectID       uuid.NullUUID
	UploadedBy                uuid.NullUUID
	UploadedAt                time.Time
	PurgedAt                  *time.Time
	CreatedAt                 time.Time
	RowVersion                int64
}

func (q *Queries) GetDocumentObject(ctx context.Context, arg GetDocumentObjectParams) (GetDocumentObjectRow, error) {
	row := q.db.QueryRow(ctx, getDocumentObject, arg.TenantID, arg.ID, arg.ScopeIds)
	var i GetDocumentObjectRow
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Bucket,
		&i.Classification,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256,
		&i.ScanStatus,
		&i.OwnerTenantOrganizationID,
		&i.DuplicateOfObjectID,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.PurgedAt,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getLatestDocumentVersion = `-- name: GetLatestDocumentVersion :one
SELECT v.id, v.object_id, v.version_no, v.byte_size, v.content_type, v.encryption_key_ref,
       v.created_at
  FROM document.version v
 WHERE v.tenant_id = $1
   AND v.object_id = $2
 ORDER BY v.version_no DESC
 LIMIT 1
`

type GetLatestDocumentVersionParams struct {
	TenantID uuid.UUID
	ObjectID uuid.UUID
}

type GetLatestDocumentVersionRow struct {
	ID               uuid.UUID
	ObjectID         uuid.UUID
	VersionNo        int32
	ByteSize         int64
	ContentType      string
	EncryptionKeyRef *string
	CreatedAt        time.Time
}

func (q *Queries) GetLatestDocumentVersion(ctx context.Context, arg GetLatestDocumentVersionParams) (GetLatestDocumentVersionRow, error) {
	row := q.db.QueryRow(ctx, getLatestDocumentVersion, arg.TenantID, arg.ObjectID)
	var i GetLatestDocumentVersionRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.VersionNo,
		&i.ByteSize,
		&i.ContentType,
		&i.EncryptionKeyRef,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentLinks = `-- name: ListDocumentLinks :many
SELECT l.id, l.object_id, l.aggregate_type, l.aggregate_id, l.document_type_code, l.purpose,
       l.required_permission, l.created_by, l.created_at
  FROM document.link l
 WHERE l.tenant_id = $1
   AND l.object_id = $2
 ORDER BY l.created_at, l.id
`

type ListDocumentLinksParams struct {
	TenantID uuid.UUID
	ObjectID uuid.UUID
}

type ListDocumentLinksRow struct {
	ID                 uuid.UUID
	ObjectID           uuid.UUID
	AggregateType      string
	AggregateID        uuid.UUID
	DocumentTypeCode   string
	Purpose            *string
	RequiredPermission *string
	CreatedBy          uuid.NullUUID
	CreatedAt          time.Time
}

func (q *Queries) ListDocumentLinks(ctx context.Context, arg ListDocumentLinksParams) ([]ListDocumentLinksRow, error) {
	rows, err := q.db.Query(ctx, listDocumentLinks, arg.TenantID, arg.ObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentLinksRow
	for rows.Next() {
		var i ListDocumentLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.AggregateType,
			&i.AggregateID,
			&i.DocumentTypeCode,
			&i.Purpose,
			&i.RequiredPermission,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentObjects = `-- name: ListDocumentObjects :many
SELECT o.id, o.object_key, o.bucket, o.classification, o.original_filename, o.content_type,
       o.byte_size, o.sha256, o.scan_status, o.owner_tenant_organization_id,
       o.duplicate_of_object_id, o.uploaded_by, o.uploaded_at, o.purged_at, o.created_at,
       o.row_version
  FROM document.object o
 WHERE o.tenant_id = $1
   AND ($2::uuid[] IS NULL
        OR o.owner_tenant_organization_id IS NULL
        OR o.owner_tenant_organization_id = ANY($2::uuid[]))
   AND ($3::text IS NULL OR o.scan_status = $3::text)
   AND ($4::text IS NULL
        OR o.classification = $4::text)
   AND ($5::text IS NULL OR EXISTS (
            SELECT 1 FROM document.link l
             WHERE l.tenant_id = o.tenant_id AND l.object_id = o.id
               AND l.aggregate_type = $5::text
               AND ($6::uuid IS NULL
                    OR l.aggregate_id = $6::uuid)))
   AND ($7::timestamptz IS NULL
        OR (o.created_at, o.id) < ($7::timestamptz, $8::uuid))
 ORDER BY o.created_at DESC, o.id DESC
 LIMIT $9
`

type ListDocumentObjectsParams struct {
	TenantID        uuid.UUID
	ScopeIds        []uuid.UUID
	ScanStatus      *string
	Classification  *string
	AggregateType   *string
	AggregateID     uuid.NullUUID
	CursorCreatedAt *time.Time
	CursorID        uuid.NullUUID
	PageSize        int32
}

type ListDocumentObjectsRow struct {
	ID                        uuid.UUID
	ObjectKey                 string
	Bucket                    string
	Classification            string
	OriginalFilename          string
	ContentType               string
	ByteSize                  *int64
	Sha256                    []byte
	ScanStatus                string
	OwnerTenantOrganizationID uuid.NullUUID
	DuplicateOfObjectID       uuid.NullUUID
	UploadedBy                uuid.NullUUID
	UploadedAt                time.Time
	PurgedAt                  *time.Time
	CreatedAt                 time.Time
	RowVersion                int64
}

// Keyset pagination on (created_at DESC, id DESC); the caller asks for limit+1 rows to
// learn whether a next page exists. Filtering by a record is an EXISTS over the links,
// because a document may belong to several records and a join would return it once per one.
func (q *Queries) ListDocumentObjects(ctx context.Context, arg ListDocumentObjectsParams) ([]ListDocumentObjectsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentObjects,
		arg.TenantID,
		arg.ScopeIds,
		arg.ScanStatus,
		arg.Classification,
		arg.AggregateType,
		arg.AggregateID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentObjectsRow
	for rows.Next() {
		var i ListDocumentObjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ObjectKey,
			&i.Bucket,
			&i.Classification,
			&i.OriginalFilename,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256,
			&i.ScanStatus,
			&i.OwnerTenantOrganizationID,
			&i.DuplicateOfObjectID,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.PurgedAt,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentScanResults = `-- name: ListDocumentScanResults :many
SELECT r.id, r.object_id, r.version_id, r.engine, r.signature_version, r.outcome,
       r.finding, r.scanned_at
  FROM document.scan_result r
 WHERE r.tenant_id = $1
   AND r.object_id = $2
 ORDER BY r.scanned_at DESC, r.id DESC
`

type ListDocumentScanResultsParams struct {
	TenantID uuid.UUID
	ObjectID uuid.UUID
}

type ListDocumentScanResultsRow struct {
	ID               uuid.UUID
	ObjectID         uuid.UUID
	VersionID        uuid.UUID
	Engine           string
	SignatureVersion *string
	Outcome          string
	Finding          *string
	ScannedAt        time.Time
}

func (q *Queries) ListDocumentScanResults(ctx context.Context, arg ListDocumentScanResultsParams) ([]ListDocumentScanResultsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentScanResults, arg.TenantID, arg.ObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentScanResultsRow
	for rows.Next() {
		var i ListDocumentScanResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.VersionID,
			&i.Engine,
			&i.SignatureVersion,
			&i.Outcome,
			&i.Finding,
			&i.ScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurgeableDocuments = `-- name: ListPurgeableDocuments :many
SELECT o.id, o.object_key, o.bucket, o.classification, o.original_filename, o.content_type,
       o.byte_size, o.sha256, o.scan_status, o.owner_tenant_organization_id,
       o.duplicate_of_object_id, o.uploaded_by, o.uploaded_at, o.purged_at, o.created_at,
       o.row_version
  FROM document.object o
 WHERE o.tenant_id = $1
   AND o.scan_status = 'CLEAN'
   AND o.purged_at IS NULL
   AND o.uploaded_at < $2
 ORDER BY o.uploaded_at
 LIMIT $3
`

type ListPurgeableDocumentsParams struct {
	TenantID uuid.UUID
	Before   time.Time
	PageSize int32
}

type ListPurgeableDocumentsRow struct {
	ID                        uuid.UUID
	ObjectKey                 string
	Bucket                    string
	Classification            string
	OriginalFilename          string
	ContentType               string
	ByteSize                  *int64
	Sha256                    []byte
	ScanStatus                string
	OwnerTenantOrganizationID uuid.NullUUID
	DuplicateOfObjectID       uuid.NullUUID
	UploadedBy                uuid.NullUUID
	UploadedAt                time.Time
	PurgedAt                  *time.Time
	CreatedAt                 time.Time
	RowVersion                int64
}

// Stored documents older than the cutoff whose bytes are still there. The legal hold is
// deliberately not part of the predicate: skipping is a decision the sweep makes and
// reports, not one a WHERE clause makes silently.
func (q *Queries) ListPurgeableDocuments(ctx context.Context, arg ListPurgeableDocumentsParams) ([]ListPurgeableDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listPurgeableDocuments, arg.TenantID, arg.Before, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurgeableDocumentsRow
	for rows.Next() {
		var i ListPurgeableDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ObjectKey,
			&i.Bucket,
			&i.Classification,
			&i.OriginalFilename,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256,
			&i.ScanStatus,
			&i.OwnerTenantOrganizationID,
			&i.DuplicateOfObjectID,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.PurgedAt,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDocumentObject = `-- name: LockDocumentObject :one
SELECT o.id, o.object_key, o.bucket, o.classification, o.original_filename, o.content_type,
       o.byte_size, o.sha256, o.scan_status, o.owner_tenant_organization_id,
       o.duplicate_of_object_id, o.uploaded_by, o.uploaded_at, o.purged_at, o.created_at,
       o.row_version
  FROM document.object o
 WHERE o.tenant_id = $1
   AND o.id = $2
   FOR UPDATE
`

type LockDocumentObjectParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type LockDocumentObjectRow struct {
	ID                        uuid.UUID
	ObjectKey                 string
	Bucket                    string
	Classification            string
	OriginalFilename          string
	ContentType               string
	ByteSize                  *int64
	Sha256                    []byte
	ScanStatus                string
	OwnerTenantOrganizationID uuid.NullUUID
	DuplicateOfObjectID       uuid.NullUUID
	UploadedBy                uuid.NullUUID
	UploadedAt                time.Time
	PurgedAt                  *time.Time
	CreatedAt                 time.Time
	RowVersion                int64
}

// The worker's read. It carries no scope: the worker acts for the system rather than for a
// person, and a scan skipped because nobody happened to hold the document's organization
// would leave a file unscanned.
func (q *Queries) LockDocumentObject(ctx context.Context, arg LockDocumentObjectParams) (LockDocumentObjectRow, error) {
	row := q.db.QueryRow(ctx, lockDocumentObject, arg.TenantID, arg.ID)
	var i LockDocumentObjectRow
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Bucket,
		&i.Classification,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256,
		&i.ScanStatus,
		&i.OwnerTenantOrganizationID,
		&i.DuplicateOfObjectID,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.PurgedAt,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const markDocumentObjectDuplicate = `-- name: MarkDocumentObjectDuplicate :execrows
UPDATE document.object
   SET scan_status            = 'CLEAN',
       bucket                 = 'secure',
       object_key             = $1,
       duplicate_of_object_id = $2,
       sha256                 = $3,
       byte_size              = $4
 WHERE tenant_id = $5
   AND id = $6
   AND scan_status IN ('SCANNING','FAILED')
`

type MarkDocumentObjectDuplicateParams struct {
	ObjectKey           string
	DuplicateOfObjectID uuid.NullUUID
	Sha256              []byte
	ByteSize            *int64
	TenantID            uuid.UUID
	ID                  uuid.UUID
}

// The losing side of a race for one digest. It keeps no bytes of its own: it carries the
// canonical key, so there is one stored file however many rows name it.
func (q *Queries) MarkDocumentObjectDuplicate(ctx context.Context, arg MarkDocumentObjectDuplicateParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentObjectDuplicate,
		arg.ObjectKey,
		arg.DuplicateOfObjectID,
		arg.Sha256,
		arg.ByteSize,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentObjectFailed = `-- name: MarkDocumentObjectFailed :execrows
UPDATE document.object
   SET scan_status = 'FAILED'
 WHERE tenant_id = $1
   AND id = $2
   AND scan_status IN ('SCANNING','FAILED')
`

type MarkDocumentObjectFailedParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) MarkDocumentObjectFailed(ctx context.Context, arg MarkDocumentObjectFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentObjectFailed, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentObjectInfected = `-- name: MarkDocumentObjectInfected :execrows
UPDATE document.object
   SET scan_status = 'INFECTED',
       sha256      = $1,
       byte_size   = $2
 WHERE tenant_id = $3
   AND id = $4
   AND scan_status IN ('SCANNING','FAILED')
`

type MarkDocumentObjectInfectedParams struct {
	Sha256   []byte
	ByteSize *int64
	TenantID uuid.UUID
	ID       uuid.UUID
}

// The bucket stays quarantine and no statement will ever move it: an INFECTED row is a
// record of an incident, not a file.
func (q *Queries) MarkDocumentObjectInfected(ctx context.Context, arg MarkDocumentObjectInfectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentObjectInfected,
		arg.Sha256,
		arg.ByteSize,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentObjectPurged = `-- name: MarkDocumentObjectPurged :execrows
UPDATE document.object
   SET purged_at = $1
 WHERE tenant_id = $2
   AND id = $3
   AND purged_at IS NULL
`

type MarkDocumentObjectPurgedParams struct {
	PurgedAt *time.Time
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) MarkDocumentObjectPurged(ctx context.Context, arg MarkDocumentObjectPurgedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentObjectPurged, arg.PurgedAt, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentObjectScanning = `-- name: MarkDocumentObjectScanning :execrows
UPDATE document.object
   SET byte_size   = $1,
       sha256      = $2,
       scan_status = 'SCANNING'
 WHERE tenant_id = $3
   AND id = $4
   AND scan_status = 'PENDING'
`

type MarkDocumentObjectScanningParams struct {
	ByteSize *int64
	Sha256   []byte
	TenantID uuid.UUID
	ID       uuid.UUID
}

// What the client claims about bytes the API never saw. The predicate carries PENDING, so
// a second completeUpload changes nothing and the caller is told so.
func (q *Queries) MarkDocumentObjectScanning(ctx context.Context, arg MarkDocumentObjectScanningParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentObjectScanning,
		arg.ByteSize,
		arg.Sha256,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteDocumentObject = `-- name: PromoteDocumentObject :execrows
UPDATE document.object
   SET scan_status = 'CLEAN',
       bucket      = 'secure',
       object_key  = $1,
       sha256      = $2,
       byte_size   = $3
 WHERE tenant_id = $4
   AND id = $5
   AND scan_status IN ('SCANNING','FAILED')
`

type PromoteDocumentObjectParams struct {
	ObjectKey string
	Sha256    []byte
	ByteSize  *int64
	TenantID  uuid.UUID
	ID        uuid.UUID
}

// The only statement in the schema that writes bucket = 'secure'. Its predicate carries the
// statuses a verdict may arrive from, and the digest it writes is the one the worker
// computed from the bytes it scanned.
func (q *Queries) PromoteDocumentObject(ctx context.Context, arg PromoteDocumentObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, promoteDocumentObject,
		arg.ObjectKey,
		arg.Sha256,
		arg.ByteSize,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseDocumentLegalHold = `-- name: ReleaseDocumentLegalHold :execrows
UPDATE document.legal_hold
   SET released_at = $1,
       released_by = $2
 WHERE tenant_id = $3
   AND id = $4
   AND released_at IS NULL
   AND row_version = $5
`

type ReleaseDocumentLegalHoldParams struct {
	ReleasedAt *time.Time
	ActorID    uuid.NullUUID
	TenantID   uuid.UUID
	ID         uuid.UUID
	RowVersion int64
}

// The expected row_version is part of the predicate, so a stale If-Match releases nothing,
// and released_at IS NULL means a second release is refused rather than overwriting who
// lifted the hold first.
func (q *Queries) ReleaseDocumentLegalHold(ctx context.Context, arg ReleaseDocumentLegalHoldParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseDocumentLegalHold,
		arg.ReleasedAt,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
