// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :exec
INSERT INTO iam.credential (actor_id, password_hash, must_change_password)
VALUES ($1, $2, $3)
`

type CreateCredentialParams struct {
	ActorID            uuid.UUID
	PasswordHash       string
	MustChangePassword bool
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential, arg.ActorID, arg.PasswordHash, arg.MustChangePassword)
	return err
}

const createLocalActor = `-- name: CreateLocalActor :one

INSERT INTO iam.actor (identity_issuer, identity_subject, actor_type, display_name, email, status)
VALUES ($1, $2, 'HUMAN', $3, $4, 'ACTIVE')
RETURNING id
`

type CreateLocalActorParams struct {
	IdentityIssuer  string
	IdentitySubject string
	DisplayName     string
	Email           *string
}

// Identity queries: local password credentials and BFF sessions (WP-I1-01).
// Sessions are addressed by the SHA-256 hash of the opaque cookie value.
func (q *Queries) CreateLocalActor(ctx context.Context, arg CreateLocalActorParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createLocalActor,
		arg.IdentityIssuer,
		arg.IdentitySubject,
		arg.DisplayName,
		arg.Email,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO iam.session (
    id_hash, actor_id, active_tenant_id, user_agent_hash, source_ip,
    created_at, last_seen_at, expires_at, step_up_until
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateSessionParams struct {
	IDHash         []byte
	ActorID        uuid.UUID
	ActiveTenantID uuid.NullUUID
	UserAgentHash  []byte
	SourceIp       *netip.Addr
	CreatedAt      time.Time
	LastSeenAt     time.Time
	ExpiresAt      time.Time
	StepUpUntil    *time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.IDHash,
		arg.ActorID,
		arg.ActiveTenantID,
		arg.UserAgentHash,
		arg.SourceIp,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.StepUpUntil,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM iam.session WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM iam.session WHERE id_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, idHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, idHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionsByActor = `-- name: DeleteSessionsByActor :execrows
DELETE FROM iam.session WHERE actor_id = $1
`

func (q *Queries) DeleteSessionsByActor(ctx context.Context, actorID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionsByActor, actorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAccountByActorID = `-- name: FindAccountByActorID :one
SELECT a.id, a.identity_subject, a.display_name, a.email, a.status,
       c.password_hash, c.must_change_password, c.failed_attempts, c.locked_until
  FROM iam.actor a
  JOIN iam.credential c ON c.actor_id = a.id
 WHERE a.id = $1
`

type FindAccountByActorIDRow struct {
	ID                 uuid.UUID
	IdentitySubject    string
	DisplayName        string
	Email              *string
	Status             string
	PasswordHash       string
	MustChangePassword bool
	FailedAttempts     int32
	LockedUntil        *time.Time
}

func (q *Queries) FindAccountByActorID(ctx context.Context, id uuid.UUID) (FindAccountByActorIDRow, error) {
	row := q.db.QueryRow(ctx, findAccountByActorID, id)
	var i FindAccountByActorIDRow
	err := row.Scan(
		&i.ID,
		&i.IdentitySubject,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.FailedAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const findAccountByUsername = `-- name: FindAccountByUsername :one
SELECT a.id, a.identity_subject, a.display_name, a.email, a.status,
       c.password_hash, c.must_change_password, c.failed_attempts, c.locked_until
  FROM iam.actor a
  JOIN iam.credential c ON c.actor_id = a.id
 WHERE a.identity_issuer = $1
   AND a.identity_subject = $2
   AND a.actor_type = 'HUMAN'
`

type FindAccountByUsernameParams struct {
	IdentityIssuer  string
	IdentitySubject string
}

type FindAccountByUsernameRow struct {
	ID                 uuid.UUID
	IdentitySubject    string
	DisplayName        string
	Email              *string
	Status             string
	PasswordHash       string
	MustChangePassword bool
	FailedAttempts     int32
	LockedUntil        *time.Time
}

func (q *Queries) FindAccountByUsername(ctx context.Context, arg FindAccountByUsernameParams) (FindAccountByUsernameRow, error) {
	row := q.db.QueryRow(ctx, findAccountByUsername, arg.IdentityIssuer, arg.IdentitySubject)
	var i FindAccountByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.IdentitySubject,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.FailedAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id_hash, actor_id, active_tenant_id, created_at, last_seen_at, expires_at, step_up_until
  FROM iam.session
 WHERE id_hash = $1
   AND revoked_at IS NULL
   AND expires_at > clock_timestamp()
`

type GetSessionRow struct {
	IDHash         []byte
	ActorID        uuid.UUID
	ActiveTenantID uuid.NullUUID
	CreatedAt      time.Time
	LastSeenAt     time.Time
	ExpiresAt      time.Time
	StepUpUntil    *time.Time
}

// Revoked and absolutely expired sessions are invisible; the idle timeout is applied in Go.
func (q *Queries) GetSession(ctx context.Context, idHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, idHash)
	var i GetSessionRow
	err := row.Scan(
		&i.IDHash,
		&i.ActorID,
		&i.ActiveTenantID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.StepUpUntil,
	)
	return i, err
}

const registerLoginFailure = `-- name: RegisterLoginFailure :exec
UPDATE iam.credential
   SET failed_attempts = failed_attempts + 1,
       locked_until = CASE WHEN failed_attempts + 1 >= $2 THEN $3 ELSE locked_until END
 WHERE actor_id = $1
`

type RegisterLoginFailureParams struct {
	ActorID        uuid.UUID
	FailedAttempts int32
	LockedUntil    *time.Time
}

// Increments and locks in one statement so parallel attempts cannot overshoot the
// threshold. $2 is the threshold, $3 the instant the lock would end.
func (q *Queries) RegisterLoginFailure(ctx context.Context, arg RegisterLoginFailureParams) error {
	_, err := q.db.Exec(ctx, registerLoginFailure, arg.ActorID, arg.FailedAttempts, arg.LockedUntil)
	return err
}

const registerLoginSuccess = `-- name: RegisterLoginSuccess :exec
UPDATE iam.credential
   SET failed_attempts = 0, locked_until = NULL, last_login_at = $2
 WHERE actor_id = $1
`

type RegisterLoginSuccessParams struct {
	ActorID     uuid.UUID
	LastLoginAt *time.Time
}

func (q *Queries) RegisterLoginSuccess(ctx context.Context, arg RegisterLoginSuccessParams) error {
	_, err := q.db.Exec(ctx, registerLoginSuccess, arg.ActorID, arg.LastLoginAt)
	return err
}

const setCredentialPassword = `-- name: SetCredentialPassword :exec
UPDATE iam.credential
   SET password_hash = $2, password_updated_at = $3, must_change_password = false,
       failed_attempts = 0, locked_until = NULL
 WHERE actor_id = $1
`

type SetCredentialPasswordParams struct {
	ActorID           uuid.UUID
	PasswordHash      string
	PasswordUpdatedAt time.Time
}

func (q *Queries) SetCredentialPassword(ctx context.Context, arg SetCredentialPasswordParams) error {
	_, err := q.db.Exec(ctx, setCredentialPassword, arg.ActorID, arg.PasswordHash, arg.PasswordUpdatedAt)
	return err
}

const setSessionActiveTenant = `-- name: SetSessionActiveTenant :execrows
UPDATE iam.session SET active_tenant_id = $2 WHERE id_hash = $1 AND revoked_at IS NULL
`

type SetSessionActiveTenantParams struct {
	IDHash         []byte
	ActiveTenantID uuid.NullUUID
}

func (q *Queries) SetSessionActiveTenant(ctx context.Context, arg SetSessionActiveTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSessionActiveTenant, arg.IDHash, arg.ActiveTenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSessionStepUp = `-- name: SetSessionStepUp :execrows
UPDATE iam.session SET step_up_until = $2 WHERE id_hash = $1 AND revoked_at IS NULL
`

type SetSessionStepUpParams struct {
	IDHash      []byte
	StepUpUntil *time.Time
}

func (q *Queries) SetSessionStepUp(ctx context.Context, arg SetSessionStepUpParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSessionStepUp, arg.IDHash, arg.StepUpUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE iam.session SET last_seen_at = $2 WHERE id_hash = $1 AND revoked_at IS NULL
`

type TouchSessionParams struct {
	IDHash     []byte
	LastSeenAt time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.IDHash, arg.LastSeenAt)
	return err
}
