// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inpatient.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const admitInpatientStay = `-- name: AdmitInpatientStay :execrows
UPDATE health.inpatient_stay
   SET status = 'ADMITTED', updated_by = $1
 WHERE tenant_id = $2
   AND id = $3
   AND status = 'AUTHORIZED'
`

type AdmitInpatientStayParams struct {
	ActorID  uuid.NullUUID
	TenantID uuid.UUID
	ID       uuid.UUID
}

// The patient is in a bed. It is not a command of its own: recording where somebody
// actually is *is* the admission, so the segment write raises it.
func (q *Queries) AdmitInpatientStay(ctx context.Context, arg AdmitInpatientStayParams) (int64, error) {
	result, err := q.db.Exec(ctx, admitInpatientStay, arg.ActorID, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const approveStayExtension = `-- name: ApproveStayExtension :execrows
UPDATE health.stay_extension
   SET status = 'APPROVED',
       authorization_id = $1,
       updated_by = $2
 WHERE tenant_id = $3
   AND id = $4
   AND status = 'REQUESTED'
`

type ApproveStayExtensionParams struct {
	AuthorizationID uuid.NullUUID
	ActorID         uuid.NullUUID
	TenantID        uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) ApproveStayExtension(ctx context.Context, arg ApproveStayExtensionParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveStayExtension,
		arg.AuthorizationID,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const authorizeInpatientStay = `-- name: AuthorizeInpatientStay :execrows
UPDATE health.inpatient_stay
   SET status = 'AUTHORIZED',
       authorization_id = $1,
       authorized_days = $2::text::numeric,
       updated_by = $3
 WHERE tenant_id = $4
   AND id = $5
   AND status = 'REQUESTED'
`

type AuthorizeInpatientStayParams struct {
	AuthorizationID uuid.NullUUID
	AuthorizedDays  string
	ActorID         uuid.NullUUID
	TenantID        uuid.UUID
	ID              uuid.UUID
}

// The approval half of the outbox subscriber. REQUESTED is in the predicate, so a
// redelivered decision finds nothing to do rather than reauthorizing a stay that has since
// been admitted or discharged.
func (q *Queries) AuthorizeInpatientStay(ctx context.Context, arg AuthorizeInpatientStayParams) (int64, error) {
	result, err := q.db.Exec(ctx, authorizeInpatientStay,
		arg.AuthorizationID,
		arg.AuthorizedDays,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelInpatientStay = `-- name: CancelInpatientStay :execrows
UPDATE health.inpatient_stay
   SET status = 'CANCELLED',
       cancel_reason_code = $1,
       updated_by = $2
 WHERE tenant_id = $3
   AND id = $4
   AND status IN ('REQUESTED','AUTHORIZED','ADMITTED')
   AND row_version = $5
`

type CancelInpatientStayParams struct {
	ReasonCode         *string
	ActorID            uuid.NullUUID
	TenantID           uuid.UUID
	ID                 uuid.UUID
	ExpectedRowVersion int64
}

func (q *Queries) CancelInpatientStay(ctx context.Context, arg CancelInpatientStayParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelInpatientStay,
		arg.ReasonCode,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.ExpectedRowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelStayExtensions = `-- name: CancelStayExtensions :execrows
UPDATE health.stay_extension
   SET status = 'CANCELLED', updated_by = $1
 WHERE tenant_id = $2
   AND stay_id = $3
   AND status = 'REQUESTED'
`

type CancelStayExtensionsParams struct {
	ActorID  uuid.NullUUID
	TenantID uuid.UUID
	StayID   uuid.UUID
}

// Every undecided extension of a stay that is being cancelled. An extension outliving the
// admission it extends would be a request nobody can decide against anything.
func (q *Queries) CancelStayExtensions(ctx context.Context, arg CancelStayExtensionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelStayExtensions, arg.ActorID, arg.TenantID, arg.StayID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOpenInpatientStays = `-- name: CountOpenInpatientStays :one
SELECT count(*)
  FROM health.inpatient_stay s
 WHERE s.tenant_id = $1
   AND s.case_id = $2
   AND s.status IN ('REQUESTED','AUTHORIZED','ADMITTED')
`

type CountOpenInpatientStaysParams struct {
	TenantID uuid.UUID
	CaseID   uuid.UUID
}

// What stops a case being closed over a stay that is still running (WP-I5-01's StayPort).
// The three statuses are the same three the partial unique index calls open, because "still
// running" has to mean one thing.
func (q *Queries) CountOpenInpatientStays(ctx context.Context, arg CountOpenInpatientStaysParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenInpatientStays, arg.TenantID, arg.CaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingStayExtensions = `-- name: CountPendingStayExtensions :one
SELECT count(*)
  FROM health.stay_extension
 WHERE tenant_id = $1
   AND stay_id = $2
   AND status = 'REQUESTED'
`

type CountPendingStayExtensionsParams struct {
	TenantID uuid.UUID
	StayID   uuid.UUID
}

// The service's half of the one-undecided-extension rule. The database's half is the
// partial unique index, and both exist on purpose: the caller is told plainly, and the
// index refuses whatever writes it.
func (q *Queries) CountPendingStayExtensions(ctx context.Context, arg CountPendingStayExtensionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingStayExtensions, arg.TenantID, arg.StayID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInpatientStay = `-- name: CreateInpatientStay :one
INSERT INTO health.inpatient_stay (
    tenant_id, case_id, provider_organization_id, location_id, attending_practitioner_id,
    admission_at, estimated_days, expected_discharge_at, service_request_id,
    admission_diagnosis_id, created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5,
        $6, $7, $8,
        $9, $10,
        $11, $11)
RETURNING id, case_id, provider_organization_id, location_id, attending_practitioner_id,
          admission_at, estimated_days, expected_discharge_at, discharge_at, status,
          service_request_id, authorization_id, admission_diagnosis_id,
          COALESCE(trim_scale(authorized_days)::text, '')::text AS authorized_days,
          COALESCE(trim_scale(actual_days)::text, '')::text AS actual_days,
          COALESCE(trim_scale(released_days)::text, '')::text AS released_days, over_authorization, cancel_reason_code,
          created_at, row_version
`

type CreateInpatientStayParams struct {
	TenantID                uuid.UUID
	CaseID                  uuid.UUID
	ProviderOrganizationID  uuid.UUID
	LocationID              uuid.NullUUID
	AttendingPractitionerID uuid.NullUUID
	AdmissionAt             time.Time
	EstimatedDays           int32
	ExpectedDischargeAt     time.Time
	ServiceRequestID        uuid.UUID
	AdmissionDiagnosisID    uuid.NullUUID
	ActorID                 uuid.NullUUID
}

type CreateInpatientStayRow struct {
	ID                      uuid.UUID
	CaseID                  uuid.UUID
	ProviderOrganizationID  uuid.UUID
	LocationID              uuid.NullUUID
	AttendingPractitionerID uuid.NullUUID
	AdmissionAt             time.Time
	EstimatedDays           int32
	ExpectedDischargeAt     time.Time
	DischargeAt             *time.Time
	Status                  string
	ServiceRequestID        uuid.UUID
	AuthorizationID         uuid.NullUUID
	AdmissionDiagnosisID    uuid.NullUUID
	AuthorizedDays          string
	ActualDays              string
	ReleasedDays            string
	OverAuthorization       bool
	CancelReasonCode        *string
	CreatedAt               time.Time
	RowVersion              int64
}

// `expected_discharge_at` is derived by the caller from the admission and the estimate. It
// is passed in rather than computed here because the authorization's validity is set from
// the same value, and two places computing it is one place for them to differ.
func (q *Queries) CreateInpatientStay(ctx context.Context, arg CreateInpatientStayParams) (CreateInpatientStayRow, error) {
	row := q.db.QueryRow(ctx, createInpatientStay,
		arg.TenantID,
		arg.CaseID,
		arg.ProviderOrganizationID,
		arg.LocationID,
		arg.AttendingPractitionerID,
		arg.AdmissionAt,
		arg.EstimatedDays,
		arg.ExpectedDischargeAt,
		arg.ServiceRequestID,
		arg.AdmissionDiagnosisID,
		arg.ActorID,
	)
	var i CreateInpatientStayRow
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.ProviderOrganizationID,
		&i.LocationID,
		&i.AttendingPractitionerID,
		&i.AdmissionAt,
		&i.EstimatedDays,
		&i.ExpectedDischargeAt,
		&i.DischargeAt,
		&i.Status,
		&i.ServiceRequestID,
		&i.AuthorizationID,
		&i.AdmissionDiagnosisID,
		&i.AuthorizedDays,
		&i.ActualDays,
		&i.ReleasedDays,
		&i.OverAuthorization,
		&i.CancelReasonCode,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const createStayExtension = `-- name: CreateStayExtension :one
INSERT INTO health.stay_extension (
    tenant_id, stay_id, sequence_no, additional_days, reason_code, reason_text,
    service_request_id, created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8, $8)
RETURNING id, stay_id, sequence_no, additional_days, reason_code, reason_text,
          service_request_id, authorization_id, status, created_at, row_version
`

type CreateStayExtensionParams struct {
	TenantID         uuid.UUID
	StayID           uuid.UUID
	SequenceNo       int32
	AdditionalDays   int32
	ReasonCode       string
	ReasonText       *string
	ServiceRequestID uuid.UUID
	ActorID          uuid.NullUUID
}

type CreateStayExtensionRow struct {
	ID               uuid.UUID
	StayID           uuid.UUID
	SequenceNo       int32
	AdditionalDays   int32
	ReasonCode       string
	ReasonText       *string
	ServiceRequestID uuid.UUID
	AuthorizationID  uuid.NullUUID
	Status           string
	CreatedAt        time.Time
	RowVersion       int64
}

func (q *Queries) CreateStayExtension(ctx context.Context, arg CreateStayExtensionParams) (CreateStayExtensionRow, error) {
	row := q.db.QueryRow(ctx, createStayExtension,
		arg.TenantID,
		arg.StayID,
		arg.SequenceNo,
		arg.AdditionalDays,
		arg.ReasonCode,
		arg.ReasonText,
		arg.ServiceRequestID,
		arg.ActorID,
	)
	var i CreateStayExtensionRow
	err := row.Scan(
		&i.ID,
		&i.StayID,
		&i.SequenceNo,
		&i.AdditionalDays,
		&i.ReasonCode,
		&i.ReasonText,
		&i.ServiceRequestID,
		&i.AuthorizationID,
		&i.Status,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const createStaySegment = `-- name: CreateStaySegment :one
INSERT INTO health.stay_segment (
    tenant_id, stay_id, segment_type, starts_at, ends_at, room_code, bed_code,
    created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8, $8)
RETURNING id, stay_id, segment_type, starts_at, ends_at, room_code, bed_code,
          created_at, row_version
`

type CreateStaySegmentParams struct {
	TenantID    uuid.UUID
	StayID      uuid.UUID
	SegmentType string
	StartsAt    time.Time
	EndsAt      *time.Time
	RoomCode    *string
	BedCode     *string
	ActorID     uuid.NullUUID
}

type CreateStaySegmentRow struct {
	ID          uuid.UUID
	StayID      uuid.UUID
	SegmentType string
	StartsAt    time.Time
	EndsAt      *time.Time
	RoomCode    *string
	BedCode     *string
	CreatedAt   time.Time
	RowVersion  int64
}

func (q *Queries) CreateStaySegment(ctx context.Context, arg CreateStaySegmentParams) (CreateStaySegmentRow, error) {
	row := q.db.QueryRow(ctx, createStaySegment,
		arg.TenantID,
		arg.StayID,
		arg.SegmentType,
		arg.StartsAt,
		arg.EndsAt,
		arg.RoomCode,
		arg.BedCode,
		arg.ActorID,
	)
	var i CreateStaySegmentRow
	err := row.Scan(
		&i.ID,
		&i.StayID,
		&i.SegmentType,
		&i.StartsAt,
		&i.EndsAt,
		&i.RoomCode,
		&i.BedCode,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const deleteStaySegments = `-- name: DeleteStaySegments :exec
DELETE FROM health.stay_segment
 WHERE tenant_id = $1
   AND stay_id = $2
`

type DeleteStaySegmentsParams struct {
	TenantID uuid.UUID
	StayID   uuid.UUID
}

// The segment set is replaced as a whole: a segment id is not something anything else hangs
// off, and a diff would be a second way to end up with a gap nobody meant.
func (q *Queries) DeleteStaySegments(ctx context.Context, arg DeleteStaySegmentsParams) error {
	_, err := q.db.Exec(ctx, deleteStaySegments, arg.TenantID, arg.StayID)
	return err
}

const dischargeInpatientStay = `-- name: DischargeInpatientStay :execrows
UPDATE health.inpatient_stay
   SET status = 'DISCHARGED',
       discharge_at = $1,
       actual_days = $2::text::numeric,
       released_days = $3::text::numeric,
       over_authorization = $4,
       updated_by = $5
 WHERE tenant_id = $6
   AND id = $7
   AND status IN ('AUTHORIZED','ADMITTED')
   AND row_version = $8
`

type DischargeInpatientStayParams struct {
	DischargeAt        *time.Time
	ActualDays         string
	ReleasedDays       string
	OverAuthorization  bool
	ActorID            uuid.NullUUID
	TenantID           uuid.UUID
	ID                 uuid.UUID
	ExpectedRowVersion int64
}

// The whole reconciliation in one statement, so a stay is never momentarily discharged
// without its figures. The predicate names both live statuses and the row version, so
// discharging twice updates nothing the second time — which is what makes "running
// discharge twice releases nothing twice" a property of the schema rather than of a flag.
func (q *Queries) DischargeInpatientStay(ctx context.Context, arg DischargeInpatientStayParams) (int64, error) {
	result, err := q.db.Exec(ctx, dischargeInpatientStay,
		arg.DischargeAt,
		arg.ActualDays,
		arg.ReleasedDays,
		arg.OverAuthorization,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.ExpectedRowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endOpenStaySegments = `-- name: EndOpenStaySegments :execrows
UPDATE health.stay_segment
   SET ends_at = $1, updated_by = $2
 WHERE tenant_id = $3
   AND stay_id = $4
   AND ends_at IS NULL
   AND $1::timestamptz > starts_at
`

type EndOpenStaySegmentsParams struct {
	EndsAt   *time.Time
	ActorID  uuid.NullUUID
	TenantID uuid.UUID
	StayID   uuid.UUID
}

// Discharge ends every segment nobody ended. A segment left open past the discharge would
// price a night the patient was not there for.
func (q *Queries) EndOpenStaySegments(ctx context.Context, arg EndOpenStaySegmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, endOpenStaySegments,
		arg.EndsAt,
		arg.ActorID,
		arg.TenantID,
		arg.StayID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendInpatientStayAuthorization = `-- name: ExtendInpatientStayAuthorization :execrows
UPDATE health.inpatient_stay
   SET authorized_days = coalesce(authorized_days, 0) + $1::text::numeric,
       expected_discharge_at = $2,
       updated_by = $3
 WHERE tenant_id = $4
   AND id = $5
   AND status IN ('AUTHORIZED','ADMITTED')
`

type ExtendInpatientStayAuthorizationParams struct {
	AdditionalDays      string
	ExpectedDischargeAt time.Time
	ActorID             uuid.NullUUID
	TenantID            uuid.UUID
	ID                  uuid.UUID
}

// The approved half of an extension, on the stay: more promised days and a later expected
// discharge. `authorized_days` is added to rather than replaced, because the extension's
// own authorization holds the added days and the original one holds the first lot.
func (q *Queries) ExtendInpatientStayAuthorization(ctx context.Context, arg ExtendInpatientStayAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendInpatientStayAuthorization,
		arg.AdditionalDays,
		arg.ExpectedDischargeAt,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInpatientAdmissionService = `-- name: GetInpatientAdmissionService :one
SELECT d.id, d.code, d.default_unit_type, d.requires_provider, d.active
  FROM catalog.service_definition d
 WHERE d.tenant_id = $1
   AND d.code = $2
`

type GetInpatientAdmissionServiceParams struct {
	TenantID uuid.UUID
	Code     string
}

type GetInpatientAdmissionServiceRow struct {
	ID               uuid.UUID
	Code             string
	DefaultUnitType  string
	RequiresProvider bool
	Active           bool
}

// The catalogue definition the admission is requested against. It is found by code rather
// than named by the caller: which service an admission is booked as is the tenant's
// configuration, and a provider that could choose it could book a ward night as a session.
func (q *Queries) GetInpatientAdmissionService(ctx context.Context, arg GetInpatientAdmissionServiceParams) (GetInpatientAdmissionServiceRow, error) {
	row := q.db.QueryRow(ctx, getInpatientAdmissionService, arg.TenantID, arg.Code)
	var i GetInpatientAdmissionServiceRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DefaultUnitType,
		&i.RequiresProvider,
		&i.Active,
	)
	return i, err
}

const getInpatientStay = `-- name: GetInpatientStay :one
SELECT s.id, s.case_id, s.provider_organization_id, s.location_id, s.attending_practitioner_id,
       s.admission_at, s.estimated_days, s.expected_discharge_at, s.discharge_at, s.status,
       s.service_request_id, s.authorization_id, s.admission_diagnosis_id,
       COALESCE(trim_scale(s.authorized_days)::text, '')::text AS authorized_days,
       COALESCE(trim_scale(s.actual_days)::text, '')::text AS actual_days,
       COALESCE(trim_scale(s.released_days)::text, '')::text AS released_days, s.over_authorization, s.cancel_reason_code,
       s.created_at, s.row_version,
       -- The case's own sensitivity, carried with the row because that is what the
       -- projection decides on; a second round trip for it would be a second chance to
       -- forget it.
       c.sensitivity AS case_sensitivity, c.person_id
  FROM health.inpatient_stay s
  JOIN health.health_case c ON c.tenant_id = s.tenant_id AND c.id = s.case_id
 WHERE s.tenant_id = $1
   AND s.id = $2
   AND ($3::uuid[] IS NULL
        OR s.provider_organization_id = ANY($3::uuid[]))
`

type GetInpatientStayParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type GetInpatientStayRow struct {
	ID                      uuid.UUID
	CaseID                  uuid.UUID
	ProviderOrganizationID  uuid.UUID
	LocationID              uuid.NullUUID
	AttendingPractitionerID uuid.NullUUID
	AdmissionAt             time.Time
	EstimatedDays           int32
	ExpectedDischargeAt     time.Time
	DischargeAt             *time.Time
	Status                  string
	ServiceRequestID        uuid.UUID
	AuthorizationID         uuid.NullUUID
	AdmissionDiagnosisID    uuid.NullUUID
	AuthorizedDays          string
	ActualDays              string
	ReleasedDays            string
	OverAuthorization       bool
	CancelReasonCode        *string
	CreatedAt               time.Time
	RowVersion              int64
	CaseSensitivity         string
	PersonID                uuid.UUID
}

func (q *Queries) GetInpatientStay(ctx context.Context, arg GetInpatientStayParams) (GetInpatientStayRow, error) {
	row := q.db.QueryRow(ctx, getInpatientStay, arg.TenantID, arg.ID, arg.ScopeIds)
	var i GetInpatientStayRow
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.ProviderOrganizationID,
		&i.LocationID,
		&i.AttendingPractitionerID,
		&i.AdmissionAt,
		&i.EstimatedDays,
		&i.ExpectedDischargeAt,
		&i.DischargeAt,
		&i.Status,
		&i.ServiceRequestID,
		&i.AuthorizationID,
		&i.AdmissionDiagnosisID,
		&i.AuthorizedDays,
		&i.ActualDays,
		&i.ReleasedDays,
		&i.OverAuthorization,
		&i.CancelReasonCode,
		&i.CreatedAt,
		&i.RowVersion,
		&i.CaseSensitivity,
		&i.PersonID,
	)
	return i, err
}

const getInpatientStayCase = `-- name: GetInpatientStayCase :one
SELECT c.id, c.person_id, c.program_id, c.enrollment_id, c.case_type,
       c.provider_organization_id, c.status, c.sensitivity
  FROM health.health_case c
 WHERE c.tenant_id = $1
   AND c.id = $2
   AND ($3::uuid[] IS NULL
        OR c.provider_organization_id = ANY($3::uuid[]))
`

type GetInpatientStayCaseParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type GetInpatientStayCaseRow struct {
	ID                     uuid.UUID
	PersonID               uuid.UUID
	ProgramID              uuid.UUID
	EnrollmentID           uuid.UUID
	CaseType               string
	ProviderOrganizationID uuid.NullUUID
	Status                 string
	Sensitivity            string
}

// The case a stay is being opened against, with everything the create command has to check:
// that it is open, whose it is, and which provider it belongs to.
func (q *Queries) GetInpatientStayCase(ctx context.Context, arg GetInpatientStayCaseParams) (GetInpatientStayCaseRow, error) {
	row := q.db.QueryRow(ctx, getInpatientStayCase, arg.TenantID, arg.ID, arg.ScopeIds)
	var i GetInpatientStayCaseRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ProgramID,
		&i.EnrollmentID,
		&i.CaseType,
		&i.ProviderOrganizationID,
		&i.Status,
		&i.Sensitivity,
	)
	return i, err
}

const getInpatientWindowSetting = `-- name: GetInpatientWindowSetting :one

SELECT (value_json #>> '{}')::text AS value
  FROM platform.tenant_setting
 WHERE tenant_id = $1
   AND setting_key = $2
`

type GetInpatientWindowSettingParams struct {
	TenantID   uuid.UUID
	SettingKey string
}

// Inpatient stay, extension and segment queries (WP-I5-03, v1.2 10.4, 12.2, 16.7).
//
// Four properties shape this file.
//
// **No statement here decides what a caller may see.** Every read returns the whole row,
// the extension's `reason_text` included, and the application service drops what the caller
// may not have before the record reaches the wire. The projection is one decision made in
// one place — the same one WP-I5-01 built — and a second copy of it in SQL would be a
// second place for it to disagree.
//
// The provider boundary is `scope_ids`, exactly as health.sql applies it: a nullable uuid[]
// of tenant organization ids, NULL meaning the caller sees every stay of the tenant and a
// non-null array binding it to the stays those organizations admitted. It is applied in
// every read including the single-row ones and the ones that reach an extension or a segment
// through its stay, so a row outside it is answered 404 rather than 403.
//
// **No statement here moves a stay that has stopped being movable.** Every `Mark…`
// statement names the statuses it may act on in its own predicate, so a command racing
// another one changes nothing and reports it, rather than discharging a cancelled stay or
// authorizing one somebody has already refused.
//
// Days are read as `::text` and written as `::text::numeric`, so an exact decimal never
// passes through a float on the way in or out (handbook section 3). They are read through
// `trim_scale` as well, so five days comes back as "5" rather than "5.000000": the value is
// the same exact decimal either way, and one canonical spelling is what lets a caller compare
// two figures without parsing both first.
// How far back and how far forward an admission may be dated, in days. Two keys, one
// statement, because a tenant that has set one and not the other is ordinary: a missing row
// is not an error and the service falls back to its documented defaults.
func (q *Queries) GetInpatientWindowSetting(ctx context.Context, arg GetInpatientWindowSettingParams) (string, error) {
	row := q.db.QueryRow(ctx, getInpatientWindowSetting, arg.TenantID, arg.SettingKey)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getStayAdmissionDiagnosis = `-- name: GetStayAdmissionDiagnosis :one
SELECT g.id, e.case_id
  FROM health.diagnosis g
  JOIN health.encounter e ON e.tenant_id = g.tenant_id AND e.id = g.encounter_id
 WHERE g.tenant_id = $1
   AND g.id = $2
`

type GetStayAdmissionDiagnosisParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetStayAdmissionDiagnosisRow struct {
	ID     uuid.UUID
	CaseID uuid.UUID
}

// The admission diagnosis has to belong to an encounter of this stay's own case. A
// diagnosis borrowed from another case would put another person's condition on this
// admission.
func (q *Queries) GetStayAdmissionDiagnosis(ctx context.Context, arg GetStayAdmissionDiagnosisParams) (GetStayAdmissionDiagnosisRow, error) {
	row := q.db.QueryRow(ctx, getStayAdmissionDiagnosis, arg.TenantID, arg.ID)
	var i GetStayAdmissionDiagnosisRow
	err := row.Scan(&i.ID, &i.CaseID)
	return i, err
}

const listInpatientStays = `-- name: ListInpatientStays :many
SELECT s.id, s.case_id, s.provider_organization_id, s.location_id, s.attending_practitioner_id,
       s.admission_at, s.estimated_days, s.expected_discharge_at, s.discharge_at, s.status,
       s.service_request_id, s.authorization_id, s.admission_diagnosis_id,
       COALESCE(trim_scale(s.authorized_days)::text, '')::text AS authorized_days,
       COALESCE(trim_scale(s.actual_days)::text, '')::text AS actual_days,
       COALESCE(trim_scale(s.released_days)::text, '')::text AS released_days, s.over_authorization, s.cancel_reason_code,
       s.created_at, s.row_version,
       c.sensitivity AS case_sensitivity, c.person_id
  FROM health.inpatient_stay s
  JOIN health.health_case c ON c.tenant_id = s.tenant_id AND c.id = s.case_id
 WHERE s.tenant_id = $1
   AND ($2::uuid[] IS NULL
        OR s.provider_organization_id = ANY($2::uuid[]))
   AND ($3::uuid IS NULL OR s.case_id = $3::uuid)
   AND ($4::uuid IS NULL OR c.person_id = $4::uuid)
   AND ($5::uuid IS NULL
        OR s.provider_organization_id = $5::uuid)
   AND ($6::text IS NULL OR s.status = $6::text)
   AND ($7::timestamptz IS NULL
        OR s.admission_at >= $7::timestamptz)
   AND ($8::timestamptz IS NULL
        OR s.admission_at < $8::timestamptz)
   AND ($9::timestamptz IS NULL
        OR (s.admission_at, s.id) < ($9::timestamptz, $10::uuid))
 ORDER BY s.admission_at DESC, s.id DESC
 LIMIT $11
`

type ListInpatientStaysParams struct {
	TenantID               uuid.UUID
	ScopeIds               []uuid.UUID
	CaseID                 uuid.NullUUID
	PersonID               uuid.NullUUID
	ProviderOrganizationID uuid.NullUUID
	Status                 *string
	AdmittedFrom           *time.Time
	AdmittedTo             *time.Time
	AfterAt                *time.Time
	AfterID                uuid.NullUUID
	PageSize               int32
}

type ListInpatientStaysRow struct {
	ID                      uuid.UUID
	CaseID                  uuid.UUID
	ProviderOrganizationID  uuid.UUID
	LocationID              uuid.NullUUID
	AttendingPractitionerID uuid.NullUUID
	AdmissionAt             time.Time
	EstimatedDays           int32
	ExpectedDischargeAt     time.Time
	DischargeAt             *time.Time
	Status                  string
	ServiceRequestID        uuid.UUID
	AuthorizationID         uuid.NullUUID
	AdmissionDiagnosisID    uuid.NullUUID
	AuthorizedDays          string
	ActualDays              string
	ReleasedDays            string
	OverAuthorization       bool
	CancelReasonCode        *string
	CreatedAt               time.Time
	RowVersion              int64
	CaseSensitivity         string
	PersonID                uuid.UUID
}

// Keyset pagination on (admission_at DESC, id DESC); the caller asks for limit+1 rows to
// learn whether a next page exists.
func (q *Queries) ListInpatientStays(ctx context.Context, arg ListInpatientStaysParams) ([]ListInpatientStaysRow, error) {
	rows, err := q.db.Query(ctx, listInpatientStays,
		arg.TenantID,
		arg.ScopeIds,
		arg.CaseID,
		arg.PersonID,
		arg.ProviderOrganizationID,
		arg.Status,
		arg.AdmittedFrom,
		arg.AdmittedTo,
		arg.AfterAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInpatientStaysRow
	for rows.Next() {
		var i ListInpatientStaysRow
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.ProviderOrganizationID,
			&i.LocationID,
			&i.AttendingPractitionerID,
			&i.AdmissionAt,
			&i.EstimatedDays,
			&i.ExpectedDischargeAt,
			&i.DischargeAt,
			&i.Status,
			&i.ServiceRequestID,
			&i.AuthorizationID,
			&i.AdmissionDiagnosisID,
			&i.AuthorizedDays,
			&i.ActualDays,
			&i.ReleasedDays,
			&i.OverAuthorization,
			&i.CancelReasonCode,
			&i.CreatedAt,
			&i.RowVersion,
			&i.CaseSensitivity,
			&i.PersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStayExtensions = `-- name: ListStayExtensions :many
SELECT e.id, e.stay_id, e.sequence_no, e.additional_days, e.reason_code, e.reason_text,
       e.service_request_id, e.authorization_id, e.status, e.created_at, e.row_version
  FROM health.stay_extension e
 WHERE e.tenant_id = $1
   AND e.stay_id = $2
 ORDER BY e.sequence_no
`

type ListStayExtensionsParams struct {
	TenantID uuid.UUID
	StayID   uuid.UUID
}

type ListStayExtensionsRow struct {
	ID               uuid.UUID
	StayID           uuid.UUID
	SequenceNo       int32
	AdditionalDays   int32
	ReasonCode       string
	ReasonText       *string
	ServiceRequestID uuid.UUID
	AuthorizationID  uuid.NullUUID
	Status           string
	CreatedAt        time.Time
	RowVersion       int64
}

func (q *Queries) ListStayExtensions(ctx context.Context, arg ListStayExtensionsParams) ([]ListStayExtensionsRow, error) {
	rows, err := q.db.Query(ctx, listStayExtensions, arg.TenantID, arg.StayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStayExtensionsRow
	for rows.Next() {
		var i ListStayExtensionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StayID,
			&i.SequenceNo,
			&i.AdditionalDays,
			&i.ReasonCode,
			&i.ReasonText,
			&i.ServiceRequestID,
			&i.AuthorizationID,
			&i.Status,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaySegments = `-- name: ListStaySegments :many
SELECT g.id, g.stay_id, g.segment_type, g.starts_at, g.ends_at, g.room_code, g.bed_code,
       g.created_at, g.row_version
  FROM health.stay_segment g
 WHERE g.tenant_id = $1
   AND g.stay_id = $2
 ORDER BY g.starts_at, g.id
`

type ListStaySegmentsParams struct {
	TenantID uuid.UUID
	StayID   uuid.UUID
}

type ListStaySegmentsRow struct {
	ID          uuid.UUID
	StayID      uuid.UUID
	SegmentType string
	StartsAt    time.Time
	EndsAt      *time.Time
	RoomCode    *string
	BedCode     *string
	CreatedAt   time.Time
	RowVersion  int64
}

func (q *Queries) ListStaySegments(ctx context.Context, arg ListStaySegmentsParams) ([]ListStaySegmentsRow, error) {
	rows, err := q.db.Query(ctx, listStaySegments, arg.TenantID, arg.StayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaySegmentsRow
	for rows.Next() {
		var i ListStaySegmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StayID,
			&i.SegmentType,
			&i.StartsAt,
			&i.EndsAt,
			&i.RoomCode,
			&i.BedCode,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInpatientStay = `-- name: LockInpatientStay :one
SELECT s.id, s.case_id, s.provider_organization_id, s.location_id, s.attending_practitioner_id,
       s.admission_at, s.estimated_days, s.expected_discharge_at, s.discharge_at, s.status,
       s.service_request_id, s.authorization_id, s.admission_diagnosis_id,
       COALESCE(trim_scale(s.authorized_days)::text, '')::text AS authorized_days,
       COALESCE(trim_scale(s.actual_days)::text, '')::text AS actual_days,
       COALESCE(trim_scale(s.released_days)::text, '')::text AS released_days, s.over_authorization, s.cancel_reason_code,
       s.created_at, s.row_version,
       c.sensitivity AS case_sensitivity, c.person_id
  FROM health.inpatient_stay s
  JOIN health.health_case c ON c.tenant_id = s.tenant_id AND c.id = s.case_id
 WHERE s.tenant_id = $1
   AND s.id = $2
   AND ($3::uuid[] IS NULL
        OR s.provider_organization_id = ANY($3::uuid[]))
   FOR UPDATE OF s
`

type LockInpatientStayParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type LockInpatientStayRow struct {
	ID                      uuid.UUID
	CaseID                  uuid.UUID
	ProviderOrganizationID  uuid.UUID
	LocationID              uuid.NullUUID
	AttendingPractitionerID uuid.NullUUID
	AdmissionAt             time.Time
	EstimatedDays           int32
	ExpectedDischargeAt     time.Time
	DischargeAt             *time.Time
	Status                  string
	ServiceRequestID        uuid.UUID
	AuthorizationID         uuid.NullUUID
	AdmissionDiagnosisID    uuid.NullUUID
	AuthorizedDays          string
	ActualDays              string
	ReleasedDays            string
	OverAuthorization       bool
	CancelReasonCode        *string
	CreatedAt               time.Time
	RowVersion              int64
	CaseSensitivity         string
	PersonID                uuid.UUID
}

// The read a command makes before it writes, so two commands on one stay serialise. The
// lock is taken on the stay alone: locking the case as well would make an unrelated
// encounter write wait behind a discharge.
func (q *Queries) LockInpatientStay(ctx context.Context, arg LockInpatientStayParams) (LockInpatientStayRow, error) {
	row := q.db.QueryRow(ctx, lockInpatientStay, arg.TenantID, arg.ID, arg.ScopeIds)
	var i LockInpatientStayRow
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.ProviderOrganizationID,
		&i.LocationID,
		&i.AttendingPractitionerID,
		&i.AdmissionAt,
		&i.EstimatedDays,
		&i.ExpectedDischargeAt,
		&i.DischargeAt,
		&i.Status,
		&i.ServiceRequestID,
		&i.AuthorizationID,
		&i.AdmissionDiagnosisID,
		&i.AuthorizedDays,
		&i.ActualDays,
		&i.ReleasedDays,
		&i.OverAuthorization,
		&i.CancelReasonCode,
		&i.CreatedAt,
		&i.RowVersion,
		&i.CaseSensitivity,
		&i.PersonID,
	)
	return i, err
}

const lockInpatientStayByRequest = `-- name: LockInpatientStayByRequest :one
SELECT s.id, s.case_id, s.provider_organization_id, s.location_id, s.attending_practitioner_id,
       s.admission_at, s.estimated_days, s.expected_discharge_at, s.discharge_at, s.status,
       s.service_request_id, s.authorization_id, s.admission_diagnosis_id,
       COALESCE(trim_scale(s.authorized_days)::text, '')::text AS authorized_days,
       COALESCE(trim_scale(s.actual_days)::text, '')::text AS actual_days,
       COALESCE(trim_scale(s.released_days)::text, '')::text AS released_days, s.over_authorization, s.cancel_reason_code,
       s.created_at, s.row_version,
       c.sensitivity AS case_sensitivity, c.person_id
  FROM health.inpatient_stay s
  JOIN health.health_case c ON c.tenant_id = s.tenant_id AND c.id = s.case_id
 WHERE s.tenant_id = $1
   AND s.service_request_id = $2
   FOR UPDATE OF s
`

type LockInpatientStayByRequestParams struct {
	TenantID         uuid.UUID
	ServiceRequestID uuid.UUID
}

type LockInpatientStayByRequestRow struct {
	ID                      uuid.UUID
	CaseID                  uuid.UUID
	ProviderOrganizationID  uuid.UUID
	LocationID              uuid.NullUUID
	AttendingPractitionerID uuid.NullUUID
	AdmissionAt             time.Time
	EstimatedDays           int32
	ExpectedDischargeAt     time.Time
	DischargeAt             *time.Time
	Status                  string
	ServiceRequestID        uuid.UUID
	AuthorizationID         uuid.NullUUID
	AdmissionDiagnosisID    uuid.NullUUID
	AuthorizedDays          string
	ActualDays              string
	ReleasedDays            string
	OverAuthorization       bool
	CancelReasonCode        *string
	CreatedAt               time.Time
	RowVersion              int64
	CaseSensitivity         string
	PersonID                uuid.UUID
}

// How the outbox subscriber finds what a decision moved. There is no scope here on purpose:
// the subscriber is the worker acting for the tenant, not a person acting for a provider,
// and a stay it could not see is a stay whose decision would silently do nothing.
func (q *Queries) LockInpatientStayByRequest(ctx context.Context, arg LockInpatientStayByRequestParams) (LockInpatientStayByRequestRow, error) {
	row := q.db.QueryRow(ctx, lockInpatientStayByRequest, arg.TenantID, arg.ServiceRequestID)
	var i LockInpatientStayByRequestRow
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.ProviderOrganizationID,
		&i.LocationID,
		&i.AttendingPractitionerID,
		&i.AdmissionAt,
		&i.EstimatedDays,
		&i.ExpectedDischargeAt,
		&i.DischargeAt,
		&i.Status,
		&i.ServiceRequestID,
		&i.AuthorizationID,
		&i.AdmissionDiagnosisID,
		&i.AuthorizedDays,
		&i.ActualDays,
		&i.ReleasedDays,
		&i.OverAuthorization,
		&i.CancelReasonCode,
		&i.CreatedAt,
		&i.RowVersion,
		&i.CaseSensitivity,
		&i.PersonID,
	)
	return i, err
}

const lockStayExtensionByRequest = `-- name: LockStayExtensionByRequest :one
SELECT e.id, e.stay_id, e.sequence_no, e.additional_days, e.reason_code, e.reason_text,
       e.service_request_id, e.authorization_id, e.status, e.created_at, e.row_version
  FROM health.stay_extension e
 WHERE e.tenant_id = $1
   AND e.service_request_id = $2
   FOR UPDATE
`

type LockStayExtensionByRequestParams struct {
	TenantID         uuid.UUID
	ServiceRequestID uuid.UUID
}

type LockStayExtensionByRequestRow struct {
	ID               uuid.UUID
	StayID           uuid.UUID
	SequenceNo       int32
	AdditionalDays   int32
	ReasonCode       string
	ReasonText       *string
	ServiceRequestID uuid.UUID
	AuthorizationID  uuid.NullUUID
	Status           string
	CreatedAt        time.Time
	RowVersion       int64
}

// The extension half of the outbox subscriber; no scope, for the same reason the stay's
// lookup has none.
func (q *Queries) LockStayExtensionByRequest(ctx context.Context, arg LockStayExtensionByRequestParams) (LockStayExtensionByRequestRow, error) {
	row := q.db.QueryRow(ctx, lockStayExtensionByRequest, arg.TenantID, arg.ServiceRequestID)
	var i LockStayExtensionByRequestRow
	err := row.Scan(
		&i.ID,
		&i.StayID,
		&i.SequenceNo,
		&i.AdditionalDays,
		&i.ReasonCode,
		&i.ReasonText,
		&i.ServiceRequestID,
		&i.AuthorizationID,
		&i.Status,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const nextStayExtensionSequence = `-- name: NextStayExtensionSequence :one
SELECT coalesce(max(sequence_no), 0)::int + 1 AS next_no
  FROM health.stay_extension
 WHERE tenant_id = $1
   AND stay_id = $2
`

type NextStayExtensionSequenceParams struct {
	TenantID uuid.UUID
	StayID   uuid.UUID
}

// The next sequence number of a stay. It is a max rather than a counter because the
// extensions of one stay are few and the row is locked by the command that reads it.
func (q *Queries) NextStayExtensionSequence(ctx context.Context, arg NextStayExtensionSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextStayExtensionSequence, arg.TenantID, arg.StayID)
	var next_no int32
	err := row.Scan(&next_no)
	return next_no, err
}

const rejectInpatientStay = `-- name: RejectInpatientStay :execrows
UPDATE health.inpatient_stay
   SET status = 'REJECTED', updated_by = $1
 WHERE tenant_id = $2
   AND id = $3
   AND status = 'REQUESTED'
`

type RejectInpatientStayParams struct {
	ActorID  uuid.NullUUID
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) RejectInpatientStay(ctx context.Context, arg RejectInpatientStayParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectInpatientStay, arg.ActorID, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectStayExtension = `-- name: RejectStayExtension :execrows
UPDATE health.stay_extension
   SET status = 'REJECTED', updated_by = $1
 WHERE tenant_id = $2
   AND id = $3
   AND status = 'REQUESTED'
`

type RejectStayExtensionParams struct {
	ActorID  uuid.NullUUID
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) RejectStayExtension(ctx context.Context, arg RejectStayExtensionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectStayExtension, arg.ActorID, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
