// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeTenantsForReports = `-- name: ActiveTenantsForReports :many
SELECT t.id FROM platform.tenant t
 WHERE t.status IN ('ACTIVE', 'SUSPENDED')
 ORDER BY t.id
`

// The tenants the reconciliation and the expiry sweep walk. `platform.tenant` carries no RLS, so
// it is read outside a tenant transaction like the other cross-tenant jobs.
func (q *Queries) ActiveTenantsForReports(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, activeTenantsForReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const computeReconciliationTotals = `-- name: ComputeReconciliationTotals :one
SELECT
    (SELECT trim_scale(COALESCE(sum(i.payable_amount), 0))::text
       FROM billing.invoice i
      WHERE i.tenant_id = $1
        AND i.currency_code = $2
        AND ($3::uuid IS NULL
             OR i.provider_organization_id = $3::uuid)
        AND i.invoice_date BETWEEN $4 AND $5
        AND i.status NOT IN ('DRAFT', 'CANCELLED')) AS invoiced_total,
    (SELECT trim_scale(COALESCE(sum(b.approved_total), 0))::text
       FROM billing.batch b
      WHERE b.tenant_id = $1
        AND b.currency_code = $2
        AND ($3::uuid IS NULL
             OR b.provider_organization_id = $3::uuid)
        AND b.status IN ('DECIDED', 'SETTLING', 'CLOSED')
        AND b.decided_at::date BETWEEN $4 AND $5)
        AS approved_total,
    (SELECT trim_scale(COALESCE(sum(b.cut_total), 0))::text
       FROM billing.batch b
      WHERE b.tenant_id = $1
        AND b.currency_code = $2
        AND ($3::uuid IS NULL
             OR b.provider_organization_id = $3::uuid)
        AND b.status IN ('DECIDED', 'SETTLING', 'CLOSED')
        AND b.decided_at::date BETWEEN $4 AND $5)
        AS cut_total,
    (SELECT trim_scale(COALESCE(sum(b.returned_total), 0))::text
       FROM billing.batch b
      WHERE b.tenant_id = $1
        AND b.currency_code = $2
        AND ($3::uuid IS NULL
             OR b.provider_organization_id = $3::uuid)
        AND b.status IN ('DECIDED', 'SETTLING', 'CLOSED')
        AND b.decided_at::date BETWEEN $4 AND $5)
        AS returned_total,
    (SELECT trim_scale(COALESCE(sum(b.rejected_total), 0))::text
       FROM billing.batch b
      WHERE b.tenant_id = $1
        AND b.currency_code = $2
        AND ($3::uuid IS NULL
             OR b.provider_organization_id = $3::uuid)
        AND b.status IN ('DECIDED', 'SETTLING', 'CLOSED')
        AND b.decided_at::date BETWEEN $4 AND $5)
        AS rejected_total,
    (SELECT trim_scale(COALESCE(sum(s.payable_amount), 0))::text
       FROM billing.settlement s
      WHERE s.tenant_id = $1
        AND s.currency_code = $2
        AND ($3::uuid IS NULL
             OR s.provider_organization_id = $3::uuid)
        AND s.status <> 'CANCELLED'
        AND s.due_date BETWEEN $4 AND $5)
        AS settled_total,
    (SELECT trim_scale(COALESCE(sum(s.paid_amount), 0))::text
       FROM billing.settlement s
      WHERE s.tenant_id = $1
        AND s.currency_code = $2
        AND ($3::uuid IS NULL
             OR s.provider_organization_id = $3::uuid)
        AND s.status <> 'CANCELLED'
        AND s.due_date BETWEEN $4 AND $5)
        AS paid_total,
    -- What is still open, subtracted by PostgreSQL rather than by Go. It is a column of its own
    -- rather than a difference the service works out, because ` + "`" + `ck_billing_reconciliation_run_open` + "`" + `
    -- is going to check it against the other two and an exact decimal is not a thing to compute
    -- twice in two languages.
    (SELECT trim_scale(COALESCE(sum(s.payable_amount - s.paid_amount), 0))::text
       FROM billing.settlement s
      WHERE s.tenant_id = $1
        AND s.currency_code = $2
        AND ($3::uuid IS NULL
             OR s.provider_organization_id = $3::uuid)
        AND s.status <> 'CANCELLED'
        AND s.due_date BETWEEN $4 AND $5)
        AS open_total,
    (SELECT count(*)
       FROM billing.settlement s
      WHERE s.tenant_id = $1
        AND s.currency_code = $2
        AND ($3::uuid IS NULL
             OR s.provider_organization_id = $3::uuid)
        AND s.status <> 'CANCELLED'
        AND s.due_date BETWEEN $4 AND $5)
        AS settlement_count
`

type ComputeReconciliationTotalsParams struct {
	TenantID               uuid.UUID
	CurrencyCode           string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
}

type ComputeReconciliationTotalsRow struct {
	InvoicedTotal   string
	ApprovedTotal   string
	CutTotal        string
	ReturnedTotal   string
	RejectedTotal   string
	SettledTotal    string
	PaidTotal       string
	OpenTotal       string
	SettlementCount int64
}

// Everything one run compares, in **one query**.
//
// `provider_organization_id` is passed as a nullable argument and every arm reads
// "this provider, or every provider when none was named". That is what makes the TENANT run and
// the PROVIDER run the same arithmetic over a different scope rather than two arithmetics that
// could drift apart -- and it is why a TENANT run's totals are exactly the sum of its PROVIDER
// runs', which is a property a test can check.
func (q *Queries) ComputeReconciliationTotals(ctx context.Context, arg ComputeReconciliationTotalsParams) (ComputeReconciliationTotalsRow, error) {
	row := q.db.QueryRow(ctx, computeReconciliationTotals,
		arg.TenantID,
		arg.CurrencyCode,
		arg.ProviderOrganizationID,
		arg.PeriodFrom,
		arg.PeriodTo,
	)
	var i ComputeReconciliationTotalsRow
	err := row.Scan(
		&i.InvoicedTotal,
		&i.ApprovedTotal,
		&i.CutTotal,
		&i.ReturnedTotal,
		&i.RejectedTotal,
		&i.SettledTotal,
		&i.PaidTotal,
		&i.OpenTotal,
		&i.SettlementCount,
	)
	return i, err
}

const countExportDownload = `-- name: CountExportDownload :one
UPDATE report.export e
   SET download_count = e.download_count + 1
 WHERE e.tenant_id = $1 AND e.id = $2
 RETURNING e.download_count
`

type CountExportDownloadParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// One more download. It is an increment in SQL rather than a read-modify-write in Go: two clicks
// at the same moment are two downloads, and a counter built from a value Go had already read
// would record one.
func (q *Queries) CountExportDownload(ctx context.Context, arg CountExportDownloadParams) (int32, error) {
	row := q.db.QueryRow(ctx, countExportDownload, arg.TenantID, arg.ID)
	var download_count int32
	err := row.Scan(&download_count)
	return download_count, err
}

const createExport = `-- name: CreateExport :one

INSERT INTO report.export (
    id, tenant_id, kind, parameters, format, status, provider_organization_id, period_from,
    period_to, currency_code, requested_by, requested_at, expires_at, watermark, created_by,
    updated_by)
VALUES ($1, $2, $3, $4,
        $5,
        'QUEUED', $6, $7,
        $8, $9, $10,
        $11, $12, $13,
        $10, $10)
RETURNING id, kind, parameters, format, status, provider_organization_id, period_from,
          period_to, currency_code, document_id, row_count, requested_by, requested_at,
          expires_at, watermark, download_count, failure_code, created_at, row_version
`

type CreateExportParams struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	Kind                   string
	Parameters             []byte
	Format                 string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	CurrencyCode           *string
	RequestedBy            uuid.UUID
	RequestedAt            time.Time
	ExpiresAt              time.Time
	Watermark              string
}

type CreateExportRow struct {
	ID                     uuid.UUID
	Kind                   string
	Parameters             []byte
	Format                 string
	Status                 string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	CurrencyCode           *string
	DocumentID             uuid.NullUUID
	RowCount               int32
	RequestedBy            uuid.UUID
	RequestedAt            time.Time
	ExpiresAt              time.Time
	Watermark              string
	DownloadCount          int32
	FailureCode            *string
	CreatedAt              time.Time
	RowVersion             int64
}

// ---------------------------------------------------------------------------
// report.export
// ---------------------------------------------------------------------------
// The queued request. `parameters` is refused by the database if it carries a uuid or a key that
// names an identifier, so a service that put a provider id in the filter blob fails here rather
// than storing one.
//
// The id is passed in rather than defaulted, because the watermark carries it: a stamp naming an
// id the row does not have would be a stamp nothing can be traced back to, and drawing the id
// first is what lets the two be written together.
func (q *Queries) CreateExport(ctx context.Context, arg CreateExportParams) (CreateExportRow, error) {
	row := q.db.QueryRow(ctx, createExport,
		arg.ID,
		arg.TenantID,
		arg.Kind,
		arg.Parameters,
		arg.Format,
		arg.ProviderOrganizationID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.CurrencyCode,
		arg.RequestedBy,
		arg.RequestedAt,
		arg.ExpiresAt,
		arg.Watermark,
	)
	var i CreateExportRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Parameters,
		&i.Format,
		&i.Status,
		&i.ProviderOrganizationID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.CurrencyCode,
		&i.DocumentID,
		&i.RowCount,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.Watermark,
		&i.DownloadCount,
		&i.FailureCode,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const createReconciliationRun = `-- name: CreateReconciliationRun :one
INSERT INTO billing.reconciliation_run (
    tenant_id, scope, provider_organization_id, period_from, period_to, run_no, currency_code,
    invoiced_total, approved_total, cut_total, returned_total, rejected_total,
    settled_total, paid_total, open_total, erp_total, difference, difference_count,
    differences, status, failure_code, ran_at, created_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7,
        $8::text::numeric,
        $9::text::numeric,
        $10::text::numeric,
        $11::text::numeric,
        $12::text::numeric,
        $13::text::numeric,
        $14::text::numeric,
        $15::text::numeric,
        $16::text::numeric,
        $17::text::numeric,
        $18,
        $19, $20, $21,
        $22, $23)
RETURNING id, scope, provider_organization_id, period_from, period_to, run_no, currency_code,
          trim_scale(invoiced_total)::text AS invoiced_total,
          trim_scale(approved_total)::text AS approved_total,
          trim_scale(cut_total)::text AS cut_total,
          trim_scale(returned_total)::text AS returned_total,
          trim_scale(rejected_total)::text AS rejected_total,
          trim_scale(settled_total)::text AS settled_total,
          trim_scale(paid_total)::text AS paid_total,
          trim_scale(open_total)::text AS open_total,
          concat(trim_scale(erp_total))::text AS erp_total,
          trim_scale(difference)::text AS difference,
          difference_count, differences, status, failure_code, ran_at, created_at
`

type CreateReconciliationRunParams struct {
	TenantID               uuid.UUID
	Scope                  string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	RunNo                  int32
	CurrencyCode           string
	InvoicedTotal          string
	ApprovedTotal          string
	CutTotal               string
	ReturnedTotal          string
	RejectedTotal          string
	SettledTotal           string
	PaidTotal              string
	OpenTotal              string
	ErpTotal               *string
	Difference             string
	DifferenceCount        int32
	Differences            []byte
	Status                 string
	FailureCode            *string
	RanAt                  time.Time
	ActorID                uuid.NullUUID
}

type CreateReconciliationRunRow struct {
	ID                     uuid.UUID
	Scope                  string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	RunNo                  int32
	CurrencyCode           string
	InvoicedTotal          string
	ApprovedTotal          string
	CutTotal               string
	ReturnedTotal          string
	RejectedTotal          string
	SettledTotal           string
	PaidTotal              string
	OpenTotal              string
	ErpTotal               string
	Difference             string
	DifferenceCount        int32
	Differences            []byte
	Status                 string
	FailureCode            *string
	RanAt                  time.Time
	CreatedAt              time.Time
}

// `erp_total` comes back as the empty string when the ERP has not spoken, rather than as a
// null the generated code would have to carry as a pointer through five layers. An amount is
// never the empty string, so the encoding loses nothing and the mapper turns it back into
// "absent" in exactly one place.
// The run, written once. Every amount arrives as exact decimal text and the constraints check the
// arithmetic: `open_total` has to be settled minus paid and `difference` has to be settled minus
// the ERP's figure or the paid one, so a service that got either wrong fails here.
func (q *Queries) CreateReconciliationRun(ctx context.Context, arg CreateReconciliationRunParams) (CreateReconciliationRunRow, error) {
	row := q.db.QueryRow(ctx, createReconciliationRun,
		arg.TenantID,
		arg.Scope,
		arg.ProviderOrganizationID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.RunNo,
		arg.CurrencyCode,
		arg.InvoicedTotal,
		arg.ApprovedTotal,
		arg.CutTotal,
		arg.ReturnedTotal,
		arg.RejectedTotal,
		arg.SettledTotal,
		arg.PaidTotal,
		arg.OpenTotal,
		arg.ErpTotal,
		arg.Difference,
		arg.DifferenceCount,
		arg.Differences,
		arg.Status,
		arg.FailureCode,
		arg.RanAt,
		arg.ActorID,
	)
	var i CreateReconciliationRunRow
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ProviderOrganizationID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.RunNo,
		&i.CurrencyCode,
		&i.InvoicedTotal,
		&i.ApprovedTotal,
		&i.CutTotal,
		&i.ReturnedTotal,
		&i.RejectedTotal,
		&i.SettledTotal,
		&i.PaidTotal,
		&i.OpenTotal,
		&i.ErpTotal,
		&i.Difference,
		&i.DifferenceCount,
		&i.Differences,
		&i.Status,
		&i.FailureCode,
		&i.RanAt,
		&i.CreatedAt,
	)
	return i, err
}

const dashboardBatchesAwaitingReview = `-- name: DashboardBatchesAwaitingReview :one
SELECT count(*) AS batch_count,
       trim_scale(COALESCE(sum(b.submitted_total), 0))::text AS submitted_total,
       min(b.submitted_at) AS oldest_submitted_at,
       (SELECT min(w.due_at)
          FROM workflow.work_item w
          JOIN workflow.work_queue q ON q.tenant_id = w.tenant_id AND q.id = w.queue_id
         WHERE w.tenant_id = $1
           AND q.code = $2
           AND w.status IN ('OPEN', 'CLAIMED', 'ESCALATED')) AS oldest_sla_due_at
  FROM billing.batch b
 WHERE b.tenant_id = $1
   AND b.status IN ('SUBMITTED', 'UNDER_REVIEW')
   AND (cardinality($3::uuid[]) = 0
        OR b.provider_organization_id = ANY($3::uuid[]))
`

type DashboardBatchesAwaitingReviewParams struct {
	TenantID        uuid.UUID
	ReviewQueueCode string
	ScopeIds        []uuid.UUID
}

type DashboardBatchesAwaitingReviewRow struct {
	BatchCount        int64
	SubmittedTotal    string
	OldestSubmittedAt interface{}
	OldestSlaDueAt    interface{}
}

// The icmals waiting for a decision, what they are worth, and how long the oldest has waited. The
// SLA is the work queue's own: the oldest item's due date is what an operator is judged by, and
// reading it here is what makes "past SLA" the same number on this screen and in the worklist.
func (q *Queries) DashboardBatchesAwaitingReview(ctx context.Context, arg DashboardBatchesAwaitingReviewParams) (DashboardBatchesAwaitingReviewRow, error) {
	row := q.db.QueryRow(ctx, dashboardBatchesAwaitingReview, arg.TenantID, arg.ReviewQueueCode, arg.ScopeIds)
	var i DashboardBatchesAwaitingReviewRow
	err := row.Scan(
		&i.BatchCount,
		&i.SubmittedTotal,
		&i.OldestSubmittedAt,
		&i.OldestSlaDueAt,
	)
	return i, err
}

const dashboardClaimAging = `-- name: DashboardClaimAging :many
SELECT CASE
           WHEN $1::timestamptz - c.created_at < interval '2 days' THEN 'D0_1'
           WHEN $1::timestamptz - c.created_at < interval '8 days' THEN 'D2_7'
           WHEN $1::timestamptz - c.created_at < interval '31 days' THEN 'D8_30'
           ELSE 'D31_PLUS'
       END AS bucket,
       count(*) AS claim_count,
       trim_scale(COALESCE(sum(billing.claim_approved_total(c.tenant_id, c.id)), 0))::text
           AS approved_total
  FROM claim.claim c
 WHERE c.tenant_id = $2
   AND c.status IN ('SUBMITTED', 'AUTO_ADJUDICATED', 'PENDING_MEDICAL', 'PENDING_FINANCIAL',
                    'RETURNED')
   AND (cardinality($3::uuid[]) = 0
        OR c.provider_organization_id = ANY($3::uuid[]))
 GROUP BY 1
 ORDER BY 1
`

type DashboardClaimAgingParams struct {
	AsOf     time.Time
	TenantID uuid.UUID
	ScopeIds []uuid.UUID
}

type DashboardClaimAgingRow struct {
	Bucket        string
	ClaimCount    int64
	ApprovedTotal string
}

// The same open claims, bucketed by how long they have been waiting. The buckets are days and
// they are computed here rather than in Go: a bucket boundary a client chose would be a boundary
// the list behind the link does not use.
func (q *Queries) DashboardClaimAging(ctx context.Context, arg DashboardClaimAgingParams) ([]DashboardClaimAgingRow, error) {
	rows, err := q.db.Query(ctx, dashboardClaimAging, arg.AsOf, arg.TenantID, arg.ScopeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardClaimAgingRow
	for rows.Next() {
		var i DashboardClaimAgingRow
		if err := rows.Scan(&i.Bucket, &i.ClaimCount, &i.ApprovedTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardClaimsByStatus = `-- name: DashboardClaimsByStatus :many

SELECT c.status,
       count(*) AS claim_count,
       trim_scale(COALESCE(sum(billing.claim_approved_total(c.tenant_id, c.id)), 0))::text
           AS approved_total
  FROM claim.claim c
 WHERE c.tenant_id = $1
   AND c.status NOT IN ('CANCELLED', 'SETTLED')
   AND (cardinality($2::uuid[]) = 0
        OR c.provider_organization_id = ANY($2::uuid[]))
 GROUP BY c.status
 ORDER BY c.status
`

type DashboardClaimsByStatusParams struct {
	TenantID uuid.UUID
	ScopeIds []uuid.UUID
}

type DashboardClaimsByStatusRow struct {
	Status        string
	ClaimCount    int64
	ApprovedTotal string
}

// ---------------------------------------------------------------------------
// The operations dashboard
// ---------------------------------------------------------------------------
//
// One query per figure, each one a count and a sum the server computed, each one reproducible by
// the filter the response carries beside it. Nothing on this dashboard is a percentage, because a
// percentage is a number two screens can round differently.
// How many claims sit in each status and what they are worth. The amount is the claim's approved
// total through `billing.claim_approved_total`, which is the one place that arithmetic lives.
func (q *Queries) DashboardClaimsByStatus(ctx context.Context, arg DashboardClaimsByStatusParams) ([]DashboardClaimsByStatusRow, error) {
	rows, err := q.db.Query(ctx, dashboardClaimsByStatus, arg.TenantID, arg.ScopeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardClaimsByStatusRow
	for rows.Next() {
		var i DashboardClaimsByStatusRow
		if err := rows.Scan(&i.Status, &i.ClaimCount, &i.ApprovedTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardReimbursementsAwaitingDecision = `-- name: DashboardReimbursementsAwaitingDecision :one
SELECT count(*) AS reimbursement_count,
       trim_scale(COALESCE(sum(r.requested_amount), 0))::text AS requested_total,
       min(r.submitted_at) AS oldest_submitted_at
  FROM billing.reimbursement r
 WHERE r.tenant_id = $1
   AND r.status IN ('SUBMITTED', 'UNDER_REVIEW')
`

type DashboardReimbursementsAwaitingDecisionRow struct {
	ReimbursementCount int64
	RequestedTotal     string
	OldestSubmittedAt  interface{}
}

// The members waiting for an answer, and what they asked for. It carries no provider scope:
// a reimbursement is the payer's business with its own member and a provider has no part in it.
func (q *Queries) DashboardReimbursementsAwaitingDecision(ctx context.Context, tenantID uuid.UUID) (DashboardReimbursementsAwaitingDecisionRow, error) {
	row := q.db.QueryRow(ctx, dashboardReimbursementsAwaitingDecision, tenantID)
	var i DashboardReimbursementsAwaitingDecisionRow
	err := row.Scan(&i.ReimbursementCount, &i.RequestedTotal, &i.OldestSubmittedAt)
	return i, err
}

const dashboardSettlements = `-- name: DashboardSettlements :one
SELECT
    count(*) FILTER (
        WHERE s.due_date BETWEEN $1::date
                             AND $1::date + 7) AS due_soon_count,
    trim_scale(COALESCE(sum(s.payable_amount - s.paid_amount) FILTER (
        WHERE s.due_date BETWEEN $1::date
                             AND $1::date + 7), 0))::text AS due_soon_total,
    count(*) FILTER (WHERE s.due_date < $1::date) AS overdue_count,
    trim_scale(COALESCE(sum(s.payable_amount - s.paid_amount) FILTER (
        WHERE s.due_date < $1::date), 0))::text AS overdue_total
  FROM billing.settlement s
 WHERE s.tenant_id = $2
   AND s.status IN ('APPROVED', 'POSTED', 'PARTIALLY_PAID')
   AND s.paid_amount < s.payable_amount
   AND (cardinality($3::uuid[]) = 0
        OR s.provider_organization_id = ANY($3::uuid[]))
`

type DashboardSettlementsParams struct {
	AsOf     pgtype.Date
	TenantID uuid.UUID
	ScopeIds []uuid.UUID
}

type DashboardSettlementsRow struct {
	DueSoonCount int64
	DueSoonTotal string
	OverdueCount int64
	OverdueTotal string
}

// What is due this week and what is already overdue, as counts and sums of what is still open.
// Both arms read the same table with the same status filter and differ only in the date, so the
// two figures cannot be built from two different ideas of what an open settlement is.
func (q *Queries) DashboardSettlements(ctx context.Context, arg DashboardSettlementsParams) (DashboardSettlementsRow, error) {
	row := q.db.QueryRow(ctx, dashboardSettlements, arg.AsOf, arg.TenantID, arg.ScopeIds)
	var i DashboardSettlementsRow
	err := row.Scan(
		&i.DueSoonCount,
		&i.DueSoonTotal,
		&i.OverdueCount,
		&i.OverdueTotal,
	)
	return i, err
}

const dashboardWorkItemsPastSla = `-- name: DashboardWorkItemsPastSla :one
SELECT count(*) AS item_count,
       min(w.due_at) AS oldest_due_at
  FROM workflow.work_item w
 WHERE w.tenant_id = $1
   AND w.status IN ('OPEN', 'CLAIMED', 'ESCALATED')
   AND w.due_at IS NOT NULL
   AND w.due_at < $2
`

type DashboardWorkItemsPastSlaParams struct {
	TenantID uuid.UUID
	AsOf     *time.Time
}

type DashboardWorkItemsPastSlaRow struct {
	ItemCount   int64
	OldestDueAt interface{}
}

// The work items whose clock has run out, over every queue. `due_at` is the queue's SLA as it
// stood when the item was raised (migration 000027), so an item is late against the promise made
// when it arrived rather than against whatever the queue says this morning.
func (q *Queries) DashboardWorkItemsPastSla(ctx context.Context, arg DashboardWorkItemsPastSlaParams) (DashboardWorkItemsPastSlaRow, error) {
	row := q.db.QueryRow(ctx, dashboardWorkItemsPastSla, arg.TenantID, arg.AsOf)
	var i DashboardWorkItemsPastSlaRow
	err := row.Scan(&i.ItemCount, &i.OldestDueAt)
	return i, err
}

const exportBatchRows = `-- name: ExportBatchRows :many
SELECT b.reference, o.display_name AS provider_name, b.currency_code, b.period_from, b.period_to,
       b.status, b.invoice_count,
       trim_scale(b.submitted_total)::text AS submitted_total,
       trim_scale(b.approved_total)::text AS approved_total,
       trim_scale(b.cut_total)::text AS cut_total,
       trim_scale(b.returned_total)::text AS returned_total,
       trim_scale(b.rejected_total)::text AS rejected_total
  FROM billing.batch b
  JOIN directory.tenant_organization t
    ON t.tenant_id = b.tenant_id AND t.id = b.provider_organization_id
  JOIN directory.organization o ON o.id = t.organization_id
 WHERE b.tenant_id = $1
   AND ($2::uuid IS NULL
        OR b.provider_organization_id = $2::uuid)
   AND ($3::text IS NULL
        OR b.currency_code = $3::text)
   AND ($4::date IS NULL
        OR b.period_from >= $4::date)
   AND ($5::date IS NULL OR b.period_to <= $5::date)
   AND (cardinality($6::uuid[]) = 0
        OR b.provider_organization_id = ANY($6::uuid[]))
 ORDER BY b.period_from, b.id
 LIMIT $7
`

type ExportBatchRowsParams struct {
	TenantID               uuid.UUID
	ProviderOrganizationID uuid.NullUUID
	CurrencyCode           *string
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	ScopeIds               []uuid.UUID
	RowLimit               int32
}

type ExportBatchRowsRow struct {
	Reference      string
	ProviderName   string
	CurrencyCode   string
	PeriodFrom     pgtype.Date
	PeriodTo       pgtype.Date
	Status         string
	InvoiceCount   int32
	SubmittedTotal string
	ApprovedTotal  string
	CutTotal       string
	ReturnedTotal  string
	RejectedTotal  string
}

func (q *Queries) ExportBatchRows(ctx context.Context, arg ExportBatchRowsParams) ([]ExportBatchRowsRow, error) {
	rows, err := q.db.Query(ctx, exportBatchRows,
		arg.TenantID,
		arg.ProviderOrganizationID,
		arg.CurrencyCode,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.ScopeIds,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportBatchRowsRow
	for rows.Next() {
		var i ExportBatchRowsRow
		if err := rows.Scan(
			&i.Reference,
			&i.ProviderName,
			&i.CurrencyCode,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.Status,
			&i.InvoiceCount,
			&i.SubmittedTotal,
			&i.ApprovedTotal,
			&i.CutTotal,
			&i.ReturnedTotal,
			&i.RejectedTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportClaimRows = `-- name: ExportClaimRows :many
SELECT c.reference, o.display_name AS provider_name, c.status, c.domain_code,
       c.service_date_from, c.service_date_to,
       COALESCE(l.description, '') AS description,
       COALESCE(sd.code, '') AS service_code,
       trim_scale(l.line_amount)::text AS line_amount,
       trim_scale(COALESCE(d.approved_amount, 0))::text AS approved_amount,
       l.currency_code
  FROM claim.claim c
  JOIN directory.tenant_organization t
    ON t.tenant_id = c.tenant_id AND t.id = c.provider_organization_id
  JOIN directory.organization o ON o.id = t.organization_id
  JOIN claim.claim_version v
    ON v.tenant_id = c.tenant_id AND v.claim_id = c.id AND v.version_no = c.current_version_no
  JOIN claim.claim_line l ON l.tenant_id = v.tenant_id AND l.version_id = v.id
  LEFT JOIN catalog.service_definition sd
         ON sd.tenant_id = l.tenant_id AND sd.id = l.service_definition_id
  LEFT JOIN LATERAL (
      SELECT ld.approved_amount
        FROM claim.line_decision ld
       WHERE ld.tenant_id = l.tenant_id AND ld.line_id = l.id
       ORDER BY ld.decided_at DESC, ld.id DESC
       LIMIT 1
  ) d ON true
 WHERE c.tenant_id = $1
   AND ($2::uuid IS NULL
        OR c.provider_organization_id = $2::uuid)
   AND ($3::date IS NULL
        OR c.service_date_from >= $3::date)
   AND ($4::date IS NULL
        OR c.service_date_to <= $4::date)
   AND (cardinality($5::uuid[]) = 0
        OR c.provider_organization_id = ANY($5::uuid[]))
 ORDER BY c.service_date_from, c.id, l.line_no
 LIMIT $6
`

type ExportClaimRowsParams struct {
	TenantID               uuid.UUID
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	ScopeIds               []uuid.UUID
	RowLimit               int32
}

type ExportClaimRowsRow struct {
	Reference       string
	ProviderName    string
	Status          string
	DomainCode      string
	ServiceDateFrom pgtype.Date
	ServiceDateTo   pgtype.Date
	Description     string
	ServiceCode     string
	LineAmount      string
	ApprovedAmount  string
	CurrencyCode    string
}

// The only export whose rows carry prose. `description` is what a member was treated for written
// in words, which is why this kind needs `report.export.sensitive` and why the line is joined
// from the claim's *current* version rather than from a snapshot: an export is a picture of today.
func (q *Queries) ExportClaimRows(ctx context.Context, arg ExportClaimRowsParams) ([]ExportClaimRowsRow, error) {
	rows, err := q.db.Query(ctx, exportClaimRows,
		arg.TenantID,
		arg.ProviderOrganizationID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.ScopeIds,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportClaimRowsRow
	for rows.Next() {
		var i ExportClaimRowsRow
		if err := rows.Scan(
			&i.Reference,
			&i.ProviderName,
			&i.Status,
			&i.DomainCode,
			&i.ServiceDateFrom,
			&i.ServiceDateTo,
			&i.Description,
			&i.ServiceCode,
			&i.LineAmount,
			&i.ApprovedAmount,
			&i.CurrencyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportReconciliationRows = `-- name: ExportReconciliationRows :many
SELECT r.scope, COALESCE(o.display_name, '') AS provider_name, r.period_from, r.period_to,
       r.run_no, r.currency_code, r.status, r.difference_count,
       trim_scale(r.settled_total)::text AS settled_total,
       trim_scale(r.paid_total)::text AS paid_total,
       trim_scale(r.open_total)::text AS open_total,
       trim_scale(r.difference)::text AS difference
  FROM billing.reconciliation_run r
  LEFT JOIN directory.tenant_organization t
         ON t.tenant_id = r.tenant_id AND t.id = r.provider_organization_id
  LEFT JOIN directory.organization o ON o.id = t.organization_id
 WHERE r.tenant_id = $1
   AND ($2::uuid IS NULL
        OR r.provider_organization_id = $2::uuid)
   AND ($3::text IS NULL
        OR r.currency_code = $3::text)
   AND ($4::date IS NULL
        OR r.period_from >= $4::date)
   AND ($5::date IS NULL OR r.period_to <= $5::date)
   AND (cardinality($6::uuid[]) = 0
        OR r.provider_organization_id = ANY($6::uuid[]))
 ORDER BY r.period_from DESC, r.id DESC
 LIMIT $7
`

type ExportReconciliationRowsParams struct {
	TenantID               uuid.UUID
	ProviderOrganizationID uuid.NullUUID
	CurrencyCode           *string
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	ScopeIds               []uuid.UUID
	RowLimit               int32
}

type ExportReconciliationRowsRow struct {
	Scope           string
	ProviderName    string
	PeriodFrom      pgtype.Date
	PeriodTo        pgtype.Date
	RunNo           int32
	CurrencyCode    string
	Status          string
	DifferenceCount int32
	SettledTotal    string
	PaidTotal       string
	OpenTotal       string
	Difference      string
}

func (q *Queries) ExportReconciliationRows(ctx context.Context, arg ExportReconciliationRowsParams) ([]ExportReconciliationRowsRow, error) {
	rows, err := q.db.Query(ctx, exportReconciliationRows,
		arg.TenantID,
		arg.ProviderOrganizationID,
		arg.CurrencyCode,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.ScopeIds,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportReconciliationRowsRow
	for rows.Next() {
		var i ExportReconciliationRowsRow
		if err := rows.Scan(
			&i.Scope,
			&i.ProviderName,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.RunNo,
			&i.CurrencyCode,
			&i.Status,
			&i.DifferenceCount,
			&i.SettledTotal,
			&i.PaidTotal,
			&i.OpenTotal,
			&i.Difference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportSettlementRows = `-- name: ExportSettlementRows :many

SELECT s.reference, o.display_name AS provider_name, b.reference AS batch_reference,
       s.currency_code, s.due_date, s.status,
       trim_scale(s.approved_amount)::text AS approved_amount,
       trim_scale(s.withheld_amount)::text AS withheld_amount,
       trim_scale(s.payable_amount)::text AS payable_amount,
       trim_scale(s.paid_amount)::text AS paid_amount,
       trim_scale(s.payable_amount - s.paid_amount)::text AS open_amount
  FROM billing.settlement s
  JOIN billing.batch b ON b.tenant_id = s.tenant_id AND b.id = s.batch_id
  JOIN directory.tenant_organization t
    ON t.tenant_id = s.tenant_id AND t.id = s.provider_organization_id
  JOIN directory.organization o ON o.id = t.organization_id
 WHERE s.tenant_id = $1
   AND ($2::uuid IS NULL
        OR s.provider_organization_id = $2::uuid)
   AND ($3::text IS NULL
        OR s.currency_code = $3::text)
   AND ($4::date IS NULL
        OR s.due_date BETWEEN $4::date AND $5::date)
   AND (cardinality($6::uuid[]) = 0
        OR s.provider_organization_id = ANY($6::uuid[]))
 ORDER BY s.due_date, s.id
 LIMIT $7
`

type ExportSettlementRowsParams struct {
	TenantID               uuid.UUID
	ProviderOrganizationID uuid.NullUUID
	CurrencyCode           *string
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	ScopeIds               []uuid.UUID
	RowLimit               int32
}

type ExportSettlementRowsRow struct {
	Reference      string
	ProviderName   string
	BatchReference string
	CurrencyCode   string
	DueDate        pgtype.Date
	Status         string
	ApprovedAmount string
	WithheldAmount string
	PayableAmount  string
	PaidAmount     string
	OpenAmount     string
}

// ---------------------------------------------------------------------------
// The rows an export renders
// ---------------------------------------------------------------------------
//
// Each of these answers one kind. They return text rather than typed columns on purpose: the
// worker's job is to write a file, and a renderer that had to know how to format five different
// shapes of decimal would be five places for a figure to come out differently from the screen.
func (q *Queries) ExportSettlementRows(ctx context.Context, arg ExportSettlementRowsParams) ([]ExportSettlementRowsRow, error) {
	rows, err := q.db.Query(ctx, exportSettlementRows,
		arg.TenantID,
		arg.ProviderOrganizationID,
		arg.CurrencyCode,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.ScopeIds,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportSettlementRowsRow
	for rows.Next() {
		var i ExportSettlementRowsRow
		if err := rows.Scan(
			&i.Reference,
			&i.ProviderName,
			&i.BatchReference,
			&i.CurrencyCode,
			&i.DueDate,
			&i.Status,
			&i.ApprovedAmount,
			&i.WithheldAmount,
			&i.PayableAmount,
			&i.PaidAmount,
			&i.OpenAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportStatementRows = `-- name: ExportStatementRows :many
SELECT i.invoice_number, i.invoice_date, i.status, i.currency_code,
       trim_scale(i.payable_amount)::text AS payable_amount,
       COALESCE(b.reference, '') AS batch_reference,
       COALESCE(bi.decision, '') AS batch_decision,
       trim_scale(COALESCE(bi.approved_amount, 0))::text AS approved_amount,
       COALESCE(s.reference, '') AS settlement_reference,
       trim_scale(COALESCE(s.paid_amount, 0))::text AS settlement_paid_amount
  FROM billing.invoice i
  LEFT JOIN billing.batch b ON b.tenant_id = i.tenant_id AND b.id = i.batch_id
  LEFT JOIN billing.batch_invoice bi
         ON bi.tenant_id = i.tenant_id AND bi.invoice_id = i.id AND bi.batch_id = b.id
  LEFT JOIN billing.settlement s
         ON s.tenant_id = b.tenant_id AND s.batch_id = b.id AND s.status <> 'CANCELLED'
 WHERE i.tenant_id = $1
   AND i.provider_organization_id = $2
   AND ($3::text IS NULL
        OR i.currency_code = $3::text)
   AND i.invoice_date BETWEEN $4 AND $5
   AND i.status NOT IN ('DRAFT', 'CANCELLED')
 ORDER BY i.invoice_date, i.id
 LIMIT $6
`

type ExportStatementRowsParams struct {
	TenantID               uuid.UUID
	ProviderOrganizationID uuid.UUID
	CurrencyCode           *string
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	RowLimit               int32
}

type ExportStatementRowsRow struct {
	InvoiceNumber        string
	InvoiceDate          pgtype.Date
	Status               string
	CurrencyCode         string
	PayableAmount        string
	BatchReference       string
	BatchDecision        string
	ApprovedAmount       string
	SettlementReference  string
	SettlementPaidAmount string
}

// The invoice rows of one provider's statement. It is the same shape the screen reads, so a
// reconciliation argument held over a spreadsheet and one held over the page are held over the
// same numbers.
func (q *Queries) ExportStatementRows(ctx context.Context, arg ExportStatementRowsParams) ([]ExportStatementRowsRow, error) {
	rows, err := q.db.Query(ctx, exportStatementRows,
		arg.TenantID,
		arg.ProviderOrganizationID,
		arg.CurrencyCode,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportStatementRowsRow
	for rows.Next() {
		var i ExportStatementRowsRow
		if err := rows.Scan(
			&i.InvoiceNumber,
			&i.InvoiceDate,
			&i.Status,
			&i.CurrencyCode,
			&i.PayableAmount,
			&i.BatchReference,
			&i.BatchDecision,
			&i.ApprovedAmount,
			&i.SettlementReference,
			&i.SettlementPaidAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExport = `-- name: GetExport :one
SELECT e.id, e.kind, e.parameters, e.format, e.status, e.provider_organization_id, e.period_from,
       e.period_to, e.currency_code, e.document_id, e.row_count, e.requested_by, e.requested_at,
       e.expires_at, e.watermark, e.download_count, e.failure_code, e.created_at, e.row_version
  FROM report.export e
 WHERE e.tenant_id = $1
   AND e.id = $2
   AND ($3::uuid IS NULL
        OR e.requested_by = $3::uuid)
`

type GetExportParams struct {
	TenantID    uuid.UUID
	ID          uuid.UUID
	RequestedBy uuid.NullUUID
}

type GetExportRow struct {
	ID                     uuid.UUID
	Kind                   string
	Parameters             []byte
	Format                 string
	Status                 string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	CurrencyCode           *string
	DocumentID             uuid.NullUUID
	RowCount               int32
	RequestedBy            uuid.UUID
	RequestedAt            time.Time
	ExpiresAt              time.Time
	Watermark              string
	DownloadCount          int32
	FailureCode            *string
	CreatedAt              time.Time
	RowVersion             int64
}

// One export. A caller reads its own unless it holds the tenant-wide grant: an export is a file
// with somebody's name stamped on every row of it, and "who else pulled the settlement list this
// morning" is not a question a colleague gets to ask by id.
func (q *Queries) GetExport(ctx context.Context, arg GetExportParams) (GetExportRow, error) {
	row := q.db.QueryRow(ctx, getExport, arg.TenantID, arg.ID, arg.RequestedBy)
	var i GetExportRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Parameters,
		&i.Format,
		&i.Status,
		&i.ProviderOrganizationID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.CurrencyCode,
		&i.DocumentID,
		&i.RowCount,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.Watermark,
		&i.DownloadCount,
		&i.FailureCode,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getExportIdentity = `-- name: GetExportIdentity :one
SELECT t.code AS tenant_code, a.display_name AS requester_name
  FROM platform.tenant t
  CROSS JOIN iam.actor a
 WHERE t.id = $1 AND a.id = $2
`

type GetExportIdentityParams struct {
	TenantID uuid.UUID
	ActorID  uuid.UUID
}

type GetExportIdentityRow struct {
	TenantCode    string
	RequesterName string
}

// The two names the watermark carries: the tenant this export leaves, and the person who asked
// for it. They are read in one round trip inside the command's own transaction, because a
// watermark assembled from a name cached somewhere else would be a stamp that could be stale.
//
// `platform.tenant` carries no RLS and `iam.actor` is not tenant-scoped, which is why this join
// is free to cross both.
func (q *Queries) GetExportIdentity(ctx context.Context, arg GetExportIdentityParams) (GetExportIdentityRow, error) {
	row := q.db.QueryRow(ctx, getExportIdentity, arg.TenantID, arg.ActorID)
	var i GetExportIdentityRow
	err := row.Scan(&i.TenantCode, &i.RequesterName)
	return i, err
}

const getProviderStatementTotals = `-- name: GetProviderStatementTotals :one


SELECT
    (SELECT trim_scale(COALESCE(sum(i.payable_amount), 0))::text
       FROM billing.invoice i
      WHERE i.tenant_id = $1
        AND i.provider_organization_id = $2
        AND i.currency_code = $3
        AND i.invoice_date BETWEEN $4 AND $5
        AND i.status NOT IN ('DRAFT', 'CANCELLED')) AS invoiced_total,
    (SELECT trim_scale(COALESCE(sum(b.approved_total), 0))::text
       FROM billing.batch b
      WHERE b.tenant_id = $1
        AND b.provider_organization_id = $2
        AND b.currency_code = $3
        AND b.status IN ('DECIDED', 'SETTLING', 'CLOSED')
        AND b.decided_at::date BETWEEN $4 AND $5)
        AS approved_total,
    (SELECT trim_scale(COALESCE(sum(b.cut_total), 0))::text
       FROM billing.batch b
      WHERE b.tenant_id = $1
        AND b.provider_organization_id = $2
        AND b.currency_code = $3
        AND b.status IN ('DECIDED', 'SETTLING', 'CLOSED')
        AND b.decided_at::date BETWEEN $4 AND $5)
        AS cut_total,
    (SELECT trim_scale(COALESCE(sum(b.returned_total), 0))::text
       FROM billing.batch b
      WHERE b.tenant_id = $1
        AND b.provider_organization_id = $2
        AND b.currency_code = $3
        AND b.status IN ('DECIDED', 'SETTLING', 'CLOSED')
        AND b.decided_at::date BETWEEN $4 AND $5)
        AS returned_total,
    (SELECT trim_scale(COALESCE(sum(b.rejected_total), 0))::text
       FROM billing.batch b
      WHERE b.tenant_id = $1
        AND b.provider_organization_id = $2
        AND b.currency_code = $3
        AND b.status IN ('DECIDED', 'SETTLING', 'CLOSED')
        AND b.decided_at::date BETWEEN $4 AND $5)
        AS rejected_total,
    (SELECT trim_scale(COALESCE(sum(s.payable_amount), 0))::text
       FROM billing.settlement s
      WHERE s.tenant_id = $1
        AND s.provider_organization_id = $2
        AND s.currency_code = $3
        AND s.status <> 'CANCELLED'
        AND s.due_date BETWEEN $4 AND $5)
        AS settled_total,
    (SELECT trim_scale(COALESCE(sum(s.paid_amount), 0))::text
       FROM billing.settlement s
      WHERE s.tenant_id = $1
        AND s.provider_organization_id = $2
        AND s.currency_code = $3
        AND s.status <> 'CANCELLED'
        AND s.due_date BETWEEN $4 AND $5)
        AS paid_total,
    (SELECT trim_scale(COALESCE(sum(s.payable_amount - s.paid_amount), 0))::text
       FROM billing.settlement s
      WHERE s.tenant_id = $1
        AND s.provider_organization_id = $2
        AND s.currency_code = $3
        AND s.status <> 'CANCELLED'
        AND s.due_date BETWEEN $4 AND $5)
        AS open_balance,
    (SELECT count(*)
       FROM billing.invoice i
      WHERE i.tenant_id = $1
        AND i.provider_organization_id = $2
        AND i.currency_code = $3
        AND i.invoice_date BETWEEN $4 AND $5
        AND i.status NOT IN ('DRAFT', 'CANCELLED')) AS invoice_count,
    (SELECT count(*)
       FROM billing.settlement s
      WHERE s.tenant_id = $1
        AND s.provider_organization_id = $2
        AND s.currency_code = $3
        AND s.status <> 'CANCELLED'
        AND s.due_date BETWEEN $4 AND $5)
        AS settlement_count,
    (SELECT o.display_name
       FROM directory.tenant_organization t
       JOIN directory.organization o ON o.id = t.organization_id
      WHERE t.tenant_id = $1
        AND t.id = $2) AS provider_name
`

type GetProviderStatementTotalsParams struct {
	TenantID               uuid.UUID
	ProviderOrganizationID uuid.UUID
	CurrencyCode           string
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
}

type GetProviderStatementTotalsRow struct {
	InvoicedTotal   string
	ApprovedTotal   string
	CutTotal        string
	ReturnedTotal   string
	RejectedTotal   string
	SettledTotal    string
	PaidTotal       string
	OpenBalance     string
	InvoiceCount    int64
	SettlementCount int64
	ProviderName    string
}

// WP-I7-05: the provider statement, the daily reconciliation, the operations dashboard and the
// exports a person is allowed to take out of the system.
//
// One rule runs through every statement in this file: **the server sums, and Go renders.** Every
// figure below is a `sum()` over exact decimals inside PostgreSQL, handed back as canonical
// decimal text through `trim_scale(x)::text`, and there is no read in this module that returns a
// column of amounts for Go to add up. A total assembled from a page of rows is a total that is
// wrong the moment there is a second page, and a total that passed through a float is wrong
// immediately.
//
// The reads reach into `billing`, `claim`, `workflow`, `directory`, `catalog` and `document`.
// That is deliberate and it is read-only: a statement is a claim about invoices, batches,
// settlements and payments at once, and asking four services for four halves of one page would be
// four round trips that could disagree with each other. The only write in this file that touches
// another module's table is `MarkSettlementsReconciled`, and it is the reconciliation run's own
// act -- the database refuses RECONCILED on anything short of fully paid, so it cannot be used
// for anything else.
// ---------------------------------------------------------------------------
// The provider statement
// ---------------------------------------------------------------------------
// Every figure of one provider's statement, for one period and one currency, in **one query**.
//
// Each column is a scalar subquery over its own table with its own natural date, so each one is
// reproducible by a filter a screen can apply: the invoiced total is the invoices dated in the
// period, the decision columns are the batches decided in it, and the settlement columns are the
// settlements *due* in it. A statement that mixed those windows would be a page nobody could tie
// back to any list.
//
// `open_balance` is settled minus paid over the same settlements, which is what the provider is
// actually asking when it opens this screen.
func (q *Queries) GetProviderStatementTotals(ctx context.Context, arg GetProviderStatementTotalsParams) (GetProviderStatementTotalsRow, error) {
	row := q.db.QueryRow(ctx, getProviderStatementTotals,
		arg.TenantID,
		arg.ProviderOrganizationID,
		arg.CurrencyCode,
		arg.PeriodFrom,
		arg.PeriodTo,
	)
	var i GetProviderStatementTotalsRow
	err := row.Scan(
		&i.InvoicedTotal,
		&i.ApprovedTotal,
		&i.CutTotal,
		&i.ReturnedTotal,
		&i.RejectedTotal,
		&i.SettledTotal,
		&i.PaidTotal,
		&i.OpenBalance,
		&i.InvoiceCount,
		&i.SettlementCount,
		&i.ProviderName,
	)
	return i, err
}

const getReconciliationRun = `-- name: GetReconciliationRun :one
SELECT r.id, r.scope, r.provider_organization_id, r.period_from, r.period_to, r.run_no,
       r.currency_code,
       trim_scale(r.invoiced_total)::text AS invoiced_total,
       trim_scale(r.approved_total)::text AS approved_total,
       trim_scale(r.cut_total)::text AS cut_total,
       trim_scale(r.returned_total)::text AS returned_total,
       trim_scale(r.rejected_total)::text AS rejected_total,
       trim_scale(r.settled_total)::text AS settled_total,
       trim_scale(r.paid_total)::text AS paid_total,
       trim_scale(r.open_total)::text AS open_total,
       concat(trim_scale(r.erp_total))::text AS erp_total,
       trim_scale(r.difference)::text AS difference,
       r.difference_count, r.differences, r.status, r.failure_code, r.ran_at, r.created_at,
       o.display_name AS provider_name
  FROM billing.reconciliation_run r
  LEFT JOIN directory.tenant_organization t
         ON t.tenant_id = r.tenant_id AND t.id = r.provider_organization_id
  LEFT JOIN directory.organization o ON o.id = t.organization_id
 WHERE r.tenant_id = $1
   AND r.id = $2
   AND (cardinality($3::uuid[]) = 0
        OR r.provider_organization_id = ANY($3::uuid[]))
`

type GetReconciliationRunParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type GetReconciliationRunRow struct {
	ID                     uuid.UUID
	Scope                  string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	RunNo                  int32
	CurrencyCode           string
	InvoicedTotal          string
	ApprovedTotal          string
	CutTotal               string
	ReturnedTotal          string
	RejectedTotal          string
	SettledTotal           string
	PaidTotal              string
	OpenTotal              string
	ErpTotal               string
	Difference             string
	DifferenceCount        int32
	Differences            []byte
	Status                 string
	FailureCode            *string
	RanAt                  time.Time
	CreatedAt              time.Time
	ProviderName           *string
}

// One run, with the provider's display name when it has one. A run names an organization by id
// and a screen names it by name; resolving it here is one join rather than a second request.
func (q *Queries) GetReconciliationRun(ctx context.Context, arg GetReconciliationRunParams) (GetReconciliationRunRow, error) {
	row := q.db.QueryRow(ctx, getReconciliationRun, arg.TenantID, arg.ID, arg.ScopeIds)
	var i GetReconciliationRunRow
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ProviderOrganizationID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.RunNo,
		&i.CurrencyCode,
		&i.InvoicedTotal,
		&i.ApprovedTotal,
		&i.CutTotal,
		&i.ReturnedTotal,
		&i.RejectedTotal,
		&i.SettledTotal,
		&i.PaidTotal,
		&i.OpenTotal,
		&i.ErpTotal,
		&i.Difference,
		&i.DifferenceCount,
		&i.Differences,
		&i.Status,
		&i.FailureCode,
		&i.RanAt,
		&i.CreatedAt,
		&i.ProviderName,
	)
	return i, err
}

const listExpiredExports = `-- name: ListExpiredExports :many
SELECT e.id, e.kind, e.document_id, e.requested_by, e.expires_at
  FROM report.export e
 WHERE e.tenant_id = $1
   AND e.status IN ('QUEUED', 'RUNNING', 'READY')
   AND e.expires_at <= $2
 ORDER BY e.expires_at
 LIMIT $3
`

type ListExpiredExportsParams struct {
	TenantID uuid.UUID
	AsOf     time.Time
	RowLimit int32
}

type ListExpiredExportsRow struct {
	ID          uuid.UUID
	Kind        string
	DocumentID  uuid.NullUUID
	RequestedBy uuid.UUID
	ExpiresAt   time.Time
}

// What the nightly sweep has to tidy: everything past its expiry that still believes it has a
// file. A FAILED or already EXPIRED export is outside it, so a second pass finds nothing to do.
func (q *Queries) ListExpiredExports(ctx context.Context, arg ListExpiredExportsParams) ([]ListExpiredExportsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredExports, arg.TenantID, arg.AsOf, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredExportsRow
	for rows.Next() {
		var i ListExpiredExportsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.DocumentID,
			&i.RequestedBy,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExports = `-- name: ListExports :many
SELECT e.id, e.kind, e.parameters, e.format, e.status, e.provider_organization_id, e.period_from,
       e.period_to, e.currency_code, e.document_id, e.row_count, e.requested_by, e.requested_at,
       e.expires_at, e.watermark, e.download_count, e.failure_code, e.created_at, e.row_version
  FROM report.export e
 WHERE e.tenant_id = $1
   AND ($2::uuid IS NULL
        OR e.requested_by = $2::uuid)
   AND ($3::text IS NULL OR e.kind = $3::text)
   AND ($4::text IS NULL OR e.status = $4::text)
   AND ($5::timestamptz IS NULL
        OR (e.created_at, e.id) < ($5::timestamptz,
                                   $6::uuid))
 ORDER BY e.created_at DESC, e.id DESC
 LIMIT $7
`

type ListExportsParams struct {
	TenantID       uuid.UUID
	RequestedBy    uuid.NullUUID
	Kind           *string
	Status         *string
	AfterCreatedAt *time.Time
	AfterID        uuid.NullUUID
	PageSize       int32
}

type ListExportsRow struct {
	ID                     uuid.UUID
	Kind                   string
	Parameters             []byte
	Format                 string
	Status                 string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	CurrencyCode           *string
	DocumentID             uuid.NullUUID
	RowCount               int32
	RequestedBy            uuid.UUID
	RequestedAt            time.Time
	ExpiresAt              time.Time
	Watermark              string
	DownloadCount          int32
	FailureCode            *string
	CreatedAt              time.Time
	RowVersion             int64
}

// The exports, newest first, on the usual keyset. `requested_by` narrows it to one person's own.
func (q *Queries) ListExports(ctx context.Context, arg ListExportsParams) ([]ListExportsRow, error) {
	rows, err := q.db.Query(ctx, listExports,
		arg.TenantID,
		arg.RequestedBy,
		arg.Kind,
		arg.Status,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportsRow
	for rows.Next() {
		var i ListExportsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Parameters,
			&i.Format,
			&i.Status,
			&i.ProviderOrganizationID,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.CurrencyCode,
			&i.DocumentID,
			&i.RowCount,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.ExpiresAt,
			&i.Watermark,
			&i.DownloadCount,
			&i.FailureCode,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderStatementInvoices = `-- name: ListProviderStatementInvoices :many
SELECT i.id, i.invoice_number, i.invoice_date, i.status, i.currency_code,
       trim_scale(i.payable_amount)::text AS payable_amount,
       trim_scale(i.tax_amount)::text AS tax_amount,
       b.id AS batch_id, b.reference AS batch_reference, b.status AS batch_status,
       bi.decision AS batch_decision,
       trim_scale(COALESCE(bi.approved_amount, 0))::text AS approved_amount,
       s.id AS settlement_id, s.reference AS settlement_reference, s.due_date,
       trim_scale(COALESCE(s.paid_amount, 0))::text AS settlement_paid_amount
  FROM billing.invoice i
  LEFT JOIN billing.batch b ON b.tenant_id = i.tenant_id AND b.id = i.batch_id
  LEFT JOIN billing.batch_invoice bi
         ON bi.tenant_id = i.tenant_id AND bi.invoice_id = i.id AND bi.batch_id = b.id
  LEFT JOIN billing.settlement s
         ON s.tenant_id = b.tenant_id AND s.batch_id = b.id AND s.status <> 'CANCELLED'
 WHERE i.tenant_id = $1
   AND i.provider_organization_id = $2
   AND i.currency_code = $3
   AND i.invoice_date BETWEEN $4 AND $5
   AND i.status NOT IN ('DRAFT', 'CANCELLED')
 ORDER BY i.invoice_date, i.id
 LIMIT $6
`

type ListProviderStatementInvoicesParams struct {
	TenantID               uuid.UUID
	ProviderOrganizationID uuid.UUID
	CurrencyCode           string
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	RowLimit               int32
}

type ListProviderStatementInvoicesRow struct {
	ID                   uuid.UUID
	InvoiceNumber        string
	InvoiceDate          pgtype.Date
	Status               string
	CurrencyCode         string
	PayableAmount        string
	TaxAmount            string
	BatchID              uuid.NullUUID
	BatchReference       *string
	BatchStatus          *string
	BatchDecision        *string
	ApprovedAmount       string
	SettlementID         uuid.NullUUID
	SettlementReference  *string
	DueDate              pgtype.Date
	SettlementPaidAmount string
}

// The invoice rows behind the totals: what was billed, which icmal it went into, what the payer
// decided and how much of the settlement that carried it has been paid. Ordered oldest first,
// because a statement is read down a page rather than paged through.
func (q *Queries) ListProviderStatementInvoices(ctx context.Context, arg ListProviderStatementInvoicesParams) ([]ListProviderStatementInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listProviderStatementInvoices,
		arg.TenantID,
		arg.ProviderOrganizationID,
		arg.CurrencyCode,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderStatementInvoicesRow
	for rows.Next() {
		var i ListProviderStatementInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.InvoiceDate,
			&i.Status,
			&i.CurrencyCode,
			&i.PayableAmount,
			&i.TaxAmount,
			&i.BatchID,
			&i.BatchReference,
			&i.BatchStatus,
			&i.BatchDecision,
			&i.ApprovedAmount,
			&i.SettlementID,
			&i.SettlementReference,
			&i.DueDate,
			&i.SettlementPaidAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderStatementSettlements = `-- name: ListProviderStatementSettlements :many
SELECT s.id, s.reference, s.batch_id, s.due_date, s.status, s.currency_code,
       trim_scale(s.approved_amount)::text AS approved_amount,
       trim_scale(s.withheld_amount)::text AS withheld_amount,
       trim_scale(s.payable_amount)::text AS payable_amount,
       trim_scale(s.paid_amount)::text AS paid_amount,
       trim_scale(s.payable_amount - s.paid_amount)::text AS open_amount,
       b.reference AS batch_reference,
       (SELECT count(*) FROM billing.payment_record p
         WHERE p.tenant_id = s.tenant_id AND p.settlement_id = s.id
           AND p.status <> 'DISPUTED') AS payment_count,
       (SELECT max(p.paid_at) FROM billing.payment_record p
         WHERE p.tenant_id = s.tenant_id AND p.settlement_id = s.id
           AND p.status <> 'DISPUTED') AS last_paid_at
  FROM billing.settlement s
  JOIN billing.batch b ON b.tenant_id = s.tenant_id AND b.id = s.batch_id
 WHERE s.tenant_id = $1
   AND s.provider_organization_id = $2
   AND s.currency_code = $3
   AND s.status <> 'CANCELLED'
   AND s.due_date BETWEEN $4 AND $5
 ORDER BY s.due_date, s.id
 LIMIT $6
`

type ListProviderStatementSettlementsParams struct {
	TenantID               uuid.UUID
	ProviderOrganizationID uuid.UUID
	CurrencyCode           string
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	RowLimit               int32
}

type ListProviderStatementSettlementsRow struct {
	ID             uuid.UUID
	Reference      string
	BatchID        uuid.UUID
	DueDate        pgtype.Date
	Status         string
	CurrencyCode   string
	ApprovedAmount string
	WithheldAmount string
	PayableAmount  string
	PaidAmount     string
	OpenAmount     string
	BatchReference string
	PaymentCount   int64
	LastPaidAt     interface{}
}

// The settlement rows behind the totals, with the payments recorded against each. `paid_amount`
// is the settlement's own stored figure and `payment_count` is how many records make it up:
// a screen that showed the sum without the count could not tell one transfer from six.
func (q *Queries) ListProviderStatementSettlements(ctx context.Context, arg ListProviderStatementSettlementsParams) ([]ListProviderStatementSettlementsRow, error) {
	rows, err := q.db.Query(ctx, listProviderStatementSettlements,
		arg.TenantID,
		arg.ProviderOrganizationID,
		arg.CurrencyCode,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderStatementSettlementsRow
	for rows.Next() {
		var i ListProviderStatementSettlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.BatchID,
			&i.DueDate,
			&i.Status,
			&i.CurrencyCode,
			&i.ApprovedAmount,
			&i.WithheldAmount,
			&i.PayableAmount,
			&i.PaidAmount,
			&i.OpenAmount,
			&i.BatchReference,
			&i.PaymentCount,
			&i.LastPaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationCurrencies = `-- name: ListReconciliationCurrencies :many

SELECT DISTINCT s.currency_code
  FROM billing.settlement s
 WHERE s.tenant_id = $1
   AND s.status <> 'CANCELLED'
   AND s.due_date BETWEEN $2 AND $3
 ORDER BY s.currency_code
`

type ListReconciliationCurrenciesParams struct {
	TenantID   uuid.UUID
	PeriodFrom pgtype.Date
	PeriodTo   pgtype.Date
}

// ---------------------------------------------------------------------------
// Reconciliation
// ---------------------------------------------------------------------------
// The currencies that moved in the period. The job runs one run per currency rather than one run
// summing all of them, because two currencies added together is not a figure.
func (q *Queries) ListReconciliationCurrencies(ctx context.Context, arg ListReconciliationCurrenciesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listReconciliationCurrencies, arg.TenantID, arg.PeriodFrom, arg.PeriodTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var currency_code string
		if err := rows.Scan(&currency_code); err != nil {
			return nil, err
		}
		items = append(items, currency_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationDifferences = `-- name: ListReconciliationDifferences :many
SELECT s.id, s.reference, s.due_date, s.status,
       trim_scale(s.payable_amount)::text AS expected_amount,
       trim_scale(s.paid_amount)::text AS actual_amount,
       trim_scale(s.payable_amount - s.paid_amount)::text AS difference_amount,
       CASE
           WHEN s.paid_amount <> COALESCE((
                    SELECT sum(p.amount) FROM billing.payment_record p
                     WHERE p.tenant_id = s.tenant_id AND p.settlement_id = s.id
                       AND p.status <> 'DISPUTED'), 0)
               THEN 'PAID_SUM_MISMATCH'
           ELSE 'UNDERPAID'
       END AS difference_kind
  FROM billing.settlement s
 WHERE s.tenant_id = $1
   AND s.currency_code = $2
   AND ($3::uuid IS NULL
        OR s.provider_organization_id = $3::uuid)
   AND s.status <> 'CANCELLED'
   AND s.due_date BETWEEN $4 AND $5
   AND s.due_date <= $6
   AND (s.paid_amount <> s.payable_amount
        OR s.paid_amount <> COALESCE((
               SELECT sum(p.amount) FROM billing.payment_record p
                WHERE p.tenant_id = s.tenant_id AND p.settlement_id = s.id
                  AND p.status <> 'DISPUTED'), 0))
 ORDER BY s.due_date, s.id
 LIMIT $7
`

type ListReconciliationDifferencesParams struct {
	TenantID               uuid.UUID
	CurrencyCode           string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	AsOf                   pgtype.Date
	RowLimit               int32
}

type ListReconciliationDifferencesRow struct {
	ID               uuid.UUID
	Reference        string
	DueDate          pgtype.Date
	Status           string
	ExpectedAmount   string
	ActualAmount     string
	DifferenceAmount string
	DifferenceKind   string
}

// The settlements the run disagrees with, one row each: the reference a person finds on their own
// screen, what was expected, what arrived, and which kind of disagreement it is.
//
// Two kinds are produced here and a third is M9's:
//
//   - `UNDERPAID` -- the due date has passed and the settlement is short. This is the ordinary
//     one and it is what an operator chases;
//   - `PAID_SUM_MISMATCH` -- the settlement's stored `paid_amount` is not the sum of its live
//     payment records. That is KAPSORA disagreeing with itself, and it should never happen:
//     WP-I7-04's deferred trigger exists to stop it, and this is the sweep that would notice if
//     it ever did.
//
// A settlement that is not yet due and not yet paid is not a difference. It is a settlement
// waiting for its date, and a run that called it one would raise a work item every night for
// every unpaid invoice in the system.
func (q *Queries) ListReconciliationDifferences(ctx context.Context, arg ListReconciliationDifferencesParams) ([]ListReconciliationDifferencesRow, error) {
	rows, err := q.db.Query(ctx, listReconciliationDifferences,
		arg.TenantID,
		arg.CurrencyCode,
		arg.ProviderOrganizationID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.AsOf,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReconciliationDifferencesRow
	for rows.Next() {
		var i ListReconciliationDifferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.DueDate,
			&i.Status,
			&i.ExpectedAmount,
			&i.ActualAmount,
			&i.DifferenceAmount,
			&i.DifferenceKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationProviders = `-- name: ListReconciliationProviders :many
SELECT DISTINCT s.provider_organization_id
  FROM billing.settlement s
 WHERE s.tenant_id = $1
   AND s.currency_code = $2
   AND s.status <> 'CANCELLED'
   AND s.due_date BETWEEN $3 AND $4
 ORDER BY s.provider_organization_id
`

type ListReconciliationProvidersParams struct {
	TenantID     uuid.UUID
	CurrencyCode string
	PeriodFrom   pgtype.Date
	PeriodTo     pgtype.Date
}

// The providers with any settlement due in the period. A provider with no movement gets no run:
// a table full of all-zero runs is a table nobody reads.
func (q *Queries) ListReconciliationProviders(ctx context.Context, arg ListReconciliationProvidersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listReconciliationProviders,
		arg.TenantID,
		arg.CurrencyCode,
		arg.PeriodFrom,
		arg.PeriodTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var provider_organization_id uuid.UUID
		if err := rows.Scan(&provider_organization_id); err != nil {
			return nil, err
		}
		items = append(items, provider_organization_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationRuns = `-- name: ListReconciliationRuns :many
SELECT r.id, r.scope, r.provider_organization_id, r.period_from, r.period_to, r.run_no,
       r.currency_code,
       trim_scale(r.invoiced_total)::text AS invoiced_total,
       trim_scale(r.approved_total)::text AS approved_total,
       trim_scale(r.cut_total)::text AS cut_total,
       trim_scale(r.returned_total)::text AS returned_total,
       trim_scale(r.rejected_total)::text AS rejected_total,
       trim_scale(r.settled_total)::text AS settled_total,
       trim_scale(r.paid_total)::text AS paid_total,
       trim_scale(r.open_total)::text AS open_total,
       concat(trim_scale(r.erp_total))::text AS erp_total,
       trim_scale(r.difference)::text AS difference,
       r.difference_count, r.differences, r.status, r.failure_code, r.ran_at, r.created_at,
       o.display_name AS provider_name
  FROM billing.reconciliation_run r
  LEFT JOIN directory.tenant_organization t
         ON t.tenant_id = r.tenant_id AND t.id = r.provider_organization_id
  LEFT JOIN directory.organization o ON o.id = t.organization_id
 WHERE r.tenant_id = $1
   AND (cardinality($2::uuid[]) = 0
        OR r.provider_organization_id = ANY($2::uuid[]))
   AND ($3::text IS NULL OR r.scope = $3::text)
   AND ($4::text IS NULL OR r.status = $4::text)
   AND ($5::uuid IS NULL
        OR r.provider_organization_id = $5::uuid)
   AND ($6::date IS NULL OR r.period_from >= $6::date)
   AND ($7::date IS NULL OR r.period_to <= $7::date)
   AND ($8::timestamptz IS NULL
        OR (r.created_at, r.id) < ($8::timestamptz,
                                   $9::uuid))
 ORDER BY r.created_at DESC, r.id DESC
 LIMIT $10
`

type ListReconciliationRunsParams struct {
	TenantID               uuid.UUID
	ScopeIds               []uuid.UUID
	Scope                  *string
	Status                 *string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	AfterCreatedAt         *time.Time
	AfterID                uuid.NullUUID
	PageSize               int32
}

type ListReconciliationRunsRow struct {
	ID                     uuid.UUID
	Scope                  string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	RunNo                  int32
	CurrencyCode           string
	InvoicedTotal          string
	ApprovedTotal          string
	CutTotal               string
	ReturnedTotal          string
	RejectedTotal          string
	SettledTotal           string
	PaidTotal              string
	OpenTotal              string
	ErpTotal               string
	Difference             string
	DifferenceCount        int32
	Differences            []byte
	Status                 string
	FailureCode            *string
	RanAt                  time.Time
	CreatedAt              time.Time
	ProviderName           *string
}

// The runs, newest first, on the (created_at DESC, id DESC) keyset every list in this platform
// pages by. A provider-scoped caller reads only its own runs and never the tenant-wide ones: a
// TENANT run is every provider's figures added together.
func (q *Queries) ListReconciliationRuns(ctx context.Context, arg ListReconciliationRunsParams) ([]ListReconciliationRunsRow, error) {
	rows, err := q.db.Query(ctx, listReconciliationRuns,
		arg.TenantID,
		arg.ScopeIds,
		arg.Scope,
		arg.Status,
		arg.ProviderOrganizationID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReconciliationRunsRow
	for rows.Next() {
		var i ListReconciliationRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ProviderOrganizationID,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.RunNo,
			&i.CurrencyCode,
			&i.InvoicedTotal,
			&i.ApprovedTotal,
			&i.CutTotal,
			&i.ReturnedTotal,
			&i.RejectedTotal,
			&i.SettledTotal,
			&i.PaidTotal,
			&i.OpenTotal,
			&i.ErpTotal,
			&i.Difference,
			&i.DifferenceCount,
			&i.Differences,
			&i.Status,
			&i.FailureCode,
			&i.RanAt,
			&i.CreatedAt,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExport = `-- name: LockExport :one
SELECT e.id, e.kind, e.parameters, e.format, e.status, e.provider_organization_id, e.period_from,
       e.period_to, e.currency_code, e.document_id, e.row_count, e.requested_by, e.requested_at,
       e.expires_at, e.watermark, e.download_count, e.failure_code, e.created_at, e.row_version
  FROM report.export e
 WHERE e.tenant_id = $1
   AND e.id = $2
   FOR UPDATE
`

type LockExportParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type LockExportRow struct {
	ID                     uuid.UUID
	Kind                   string
	Parameters             []byte
	Format                 string
	Status                 string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	CurrencyCode           *string
	DocumentID             uuid.NullUUID
	RowCount               int32
	RequestedBy            uuid.UUID
	RequestedAt            time.Time
	ExpiresAt              time.Time
	Watermark              string
	DownloadCount          int32
	FailureCode            *string
	CreatedAt              time.Time
	RowVersion             int64
}

// The same read, holding the row for the length of the command. The worker takes it before it
// renders and the download takes it before it counts, so two deliveries of one job and two clicks
// on one link serialise here rather than racing.
func (q *Queries) LockExport(ctx context.Context, arg LockExportParams) (LockExportRow, error) {
	row := q.db.QueryRow(ctx, lockExport, arg.TenantID, arg.ID)
	var i LockExportRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Parameters,
		&i.Format,
		&i.Status,
		&i.ProviderOrganizationID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.CurrencyCode,
		&i.DocumentID,
		&i.RowCount,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.Watermark,
		&i.DownloadCount,
		&i.FailureCode,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const markExportExpired = `-- name: MarkExportExpired :execrows
UPDATE report.export e
   SET status = 'EXPIRED'
 WHERE e.tenant_id = $1 AND e.id = $2
   AND e.status IN ('QUEUED', 'RUNNING', 'READY')
`

type MarkExportExpiredParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// The row outlives the file, exactly as a purged document's row outlives its bytes: "this export
// existed, held this many rows and stopped being downloadable on this day" is an answer somebody
// will need, and an empty table is not.
func (q *Queries) MarkExportExpired(ctx context.Context, arg MarkExportExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markExportExpired, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markExportFailed = `-- name: MarkExportFailed :execrows
UPDATE report.export e
   SET status = 'FAILED', failure_code = $1
 WHERE e.tenant_id = $2 AND e.id = $3
   AND e.status IN ('QUEUED', 'RUNNING')
`

type MarkExportFailedParams struct {
	FailureCode *string
	TenantID    uuid.UUID
	ID          uuid.UUID
}

// A render that could not be completed, with the code that says why.
func (q *Queries) MarkExportFailed(ctx context.Context, arg MarkExportFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markExportFailed, arg.FailureCode, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markExportReady = `-- name: MarkExportReady :execrows
UPDATE report.export e
   SET status = 'READY', document_id = $1,
       row_count = $2
 WHERE e.tenant_id = $3 AND e.id = $4
   AND e.status IN ('QUEUED', 'RUNNING')
`

type MarkExportReadyParams struct {
	DocumentID uuid.NullUUID
	RowCount   int32
	TenantID   uuid.UUID
	ID         uuid.UUID
}

// The finished file. The document, the row count and READY are written in one statement, because
// an export that was READY for a moment without a document would be a link that answered 500.
func (q *Queries) MarkExportReady(ctx context.Context, arg MarkExportReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markExportReady,
		arg.DocumentID,
		arg.RowCount,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markExportRunning = `-- name: MarkExportRunning :execrows
UPDATE report.export e
   SET status = 'RUNNING'
 WHERE e.tenant_id = $1 AND e.id = $2 AND e.status = 'QUEUED'
`

type MarkExportRunningParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// QUEUED to RUNNING. The predicate carries the status, so a redelivered job that finds the export
// already running or already finished changes nothing and is told so by the row count.
func (q *Queries) MarkExportRunning(ctx context.Context, arg MarkExportRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, markExportRunning, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSettlementsReconciled = `-- name: MarkSettlementsReconciled :execrows
UPDATE billing.settlement s
   SET status = 'RECONCILED', updated_by = $1
 WHERE s.tenant_id = $2
   AND s.currency_code = $3
   AND ($4::uuid IS NULL
        OR s.provider_organization_id = $4::uuid)
   AND s.due_date BETWEEN $5 AND $6
   AND s.status = 'PAID'
   AND s.paid_amount = s.payable_amount
`

type MarkSettlementsReconciledParams struct {
	ActorID                uuid.NullUUID
	TenantID               uuid.UUID
	CurrencyCode           string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
}

// **The run marks what it found settled.** A settlement whose paid amount equals its payable
// amount is RECONCILED afterwards, and this is the only statement in the codebase that writes
// that status.
//
// The predicate is the whole guarantee. `paid_amount = payable_amount` is checked here and again
// by `ck_billing_settlement_reconciled`, so a settlement that is a kuruş short cannot be marked
// by this statement, by a command, or by anybody with a psql session.
func (q *Queries) MarkSettlementsReconciled(ctx context.Context, arg MarkSettlementsReconciledParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSettlementsReconciled,
		arg.ActorID,
		arg.TenantID,
		arg.CurrencyCode,
		arg.ProviderOrganizationID,
		arg.PeriodFrom,
		arg.PeriodTo,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextReconciliationRunNo = `-- name: NextReconciliationRunNo :one
SELECT COALESCE(max(r.run_no), 0) + 1 AS run_no
  FROM billing.reconciliation_run r
 WHERE r.tenant_id = $1
   AND r.scope = $2
   AND r.provider_organization_id IS NOT DISTINCT FROM $3::uuid
   AND r.period_from = $4
   AND r.period_to = $5
   AND r.currency_code = $6
`

type NextReconciliationRunNoParams struct {
	TenantID               uuid.UUID
	Scope                  string
	ProviderOrganizationID uuid.NullUUID
	PeriodFrom             pgtype.Date
	PeriodTo               pgtype.Date
	CurrencyCode           string
}

// The next attempt at this scope, period and currency. It is read inside the run's own
// transaction and the unique index is underneath it, so two schedulers that both believe they
// lead produce runs one and two rather than one run twice.
func (q *Queries) NextReconciliationRunNo(ctx context.Context, arg NextReconciliationRunNoParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextReconciliationRunNo,
		arg.TenantID,
		arg.Scope,
		arg.ProviderOrganizationID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.CurrencyCode,
	)
	var run_no int32
	err := row.Scan(&run_no)
	return run_no, err
}
