// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_assignment.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const canManageTenantRoles = `-- name: CanManageTenantRoles :one

SELECT EXISTS (
 SELECT 1 FROM iam.tenant_membership m JOIN iam.actor a ON a.id = m.actor_id
 WHERE m.tenant_id = $1 AND m.id = $2 AND m.actor_id = $3
   AND a.status = 'ACTIVE' AND m.membership_status = 'ACTIVE' AND m.valid_period @> clock_timestamp()::date
   AND EXISTS (SELECT 1 FROM iam.access_grant g JOIN iam.role_permission rp
                 ON rp.tenant_id = g.tenant_id AND rp.role_id = g.role_id
                WHERE g.tenant_id = m.tenant_id AND g.tenant_membership_id = m.id
                  AND g.scope_type = 'TENANT' AND g.valid_period @> clock_timestamp()
                  AND rp.permission_code = 'identity.user.read')
   AND EXISTS (SELECT 1 FROM iam.access_grant g JOIN iam.role_permission rp
                 ON rp.tenant_id = g.tenant_id AND rp.role_id = g.role_id
                WHERE g.tenant_id = m.tenant_id AND g.tenant_membership_id = m.id
                  AND g.scope_type = 'TENANT' AND g.valid_period @> clock_timestamp()
                  AND rp.permission_code = 'identity.role.manage')
)
`

type CanManageTenantRolesParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ActorID  uuid.UUID
}

// MGT-03A role assignment. All statements run in tenant-bound transactions.
func (q *Queries) CanManageTenantRoles(ctx context.Context, arg CanManageTenantRolesParams) (bool, error) {
	row := q.db.QueryRow(ctx, canManageTenantRoles, arg.TenantID, arg.ID, arg.ActorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCurrentFutureGrants = `-- name: CountCurrentFutureGrants :one
SELECT count(*) FROM iam.access_grant g
 WHERE g.tenant_id = $1 AND g.tenant_membership_id = $2
   AND NOT isempty(g.valid_period)
   AND (upper_inf(g.valid_period) OR upper(g.valid_period) > clock_timestamp())
`

type CountCurrentFutureGrantsParams struct {
	TenantID           uuid.UUID
	TenantMembershipID uuid.UUID
}

func (q *Queries) CountCurrentFutureGrants(ctx context.Context, arg CountCurrentFutureGrantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCurrentFutureGrants, arg.TenantID, arg.TenantMembershipID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCurrentTenantManagersByPermission = `-- name: CountCurrentTenantManagersByPermission :one
SELECT count(DISTINCT m.id) FROM iam.tenant_membership m
 JOIN iam.actor a ON a.id = m.actor_id
 JOIN iam.access_grant g ON g.tenant_id = m.tenant_id AND g.tenant_membership_id = m.id
 JOIN iam.role_permission rp ON rp.tenant_id = g.tenant_id AND rp.role_id = g.role_id
 WHERE m.tenant_id = $1 AND m.membership_status = 'ACTIVE'
   AND m.valid_period @> clock_timestamp()::date AND a.status = 'ACTIVE'
   AND g.scope_type = 'TENANT' AND g.valid_period @> clock_timestamp()
   AND rp.permission_code = $2
`

type CountCurrentTenantManagersByPermissionParams struct {
	TenantID       uuid.UUID
	PermissionCode string
}

func (q *Queries) CountCurrentTenantManagersByPermission(ctx context.Context, arg CountCurrentTenantManagersByPermissionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCurrentTenantManagersByPermission, arg.TenantID, arg.PermissionCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const endTenantRoleGrant = `-- name: EndTenantRoleGrant :execrows
UPDATE iam.access_grant SET valid_period = tstzrange(lower(valid_period), $4::timestamptz, '[)')
 WHERE tenant_id = $1 AND tenant_membership_id = $2 AND id = $3
   AND NOT isempty(valid_period) AND valid_period @> $4::timestamptz
`

type EndTenantRoleGrantParams struct {
	TenantID           uuid.UUID
	TenantMembershipID uuid.UUID
	ID                 uuid.UUID
	Column4            time.Time
}

func (q *Queries) EndTenantRoleGrant(ctx context.Context, arg EndTenantRoleGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, endTenantRoleGrant,
		arg.TenantID,
		arg.TenantMembershipID,
		arg.ID,
		arg.Column4,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoleAssignmentCandidate = `-- name: GetRoleAssignmentCandidate :one
SELECT id, code, name, is_system_role FROM iam.role WHERE tenant_id = $1 AND code = $2
`

type GetRoleAssignmentCandidateParams struct {
	TenantID uuid.UUID
	Code     string
}

type GetRoleAssignmentCandidateRow struct {
	ID           uuid.UUID
	Code         string
	Name         string
	IsSystemRole bool
}

func (q *Queries) GetRoleAssignmentCandidate(ctx context.Context, arg GetRoleAssignmentCandidateParams) (GetRoleAssignmentCandidateRow, error) {
	row := q.db.QueryRow(ctx, getRoleAssignmentCandidate, arg.TenantID, arg.Code)
	var i GetRoleAssignmentCandidateRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsSystemRole,
	)
	return i, err
}

const getRoleAssignmentTarget = `-- name: GetRoleAssignmentTarget :one
SELECT m.id, m.actor_id, m.membership_status, m.row_version,
       m.valid_period @> clock_timestamp()::date AS membership_valid,
       a.actor_type, a.status AS actor_status
  FROM iam.tenant_membership m JOIN iam.actor a ON a.id = m.actor_id
 WHERE m.tenant_id = $1 AND m.id = $2
`

type GetRoleAssignmentTargetParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetRoleAssignmentTargetRow struct {
	ID               uuid.UUID
	ActorID          uuid.UUID
	MembershipStatus string
	RowVersion       int64
	MembershipValid  interface{}
	ActorType        string
	ActorStatus      string
}

func (q *Queries) GetRoleAssignmentTarget(ctx context.Context, arg GetRoleAssignmentTargetParams) (GetRoleAssignmentTargetRow, error) {
	row := q.db.QueryRow(ctx, getRoleAssignmentTarget, arg.TenantID, arg.ID)
	var i GetRoleAssignmentTargetRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.MembershipStatus,
		&i.RowVersion,
		&i.MembershipValid,
		&i.ActorType,
		&i.ActorStatus,
	)
	return i, err
}

const getTenantRoleGrant = `-- name: GetTenantRoleGrant :one
SELECT g.id, g.created_at, role.code AS role_code, role.name AS role_name,
       role.is_system_role, g.scope_type, g.scope_id, g.role_id,
       CASE WHEN g.scope_type = 'ORGANIZATION' AND rel.id IS NOT NULL THEN rel.id::text ELSE NULL END AS organization_relationship_id,
       CASE WHEN g.scope_type = 'ORGANIZATION' AND rel.id IS NOT NULL THEN o.display_name ELSE NULL END AS organization_display_name,
       CASE WHEN isempty(g.valid_period) OR lower_inf(g.valid_period) THEN '' ELSE
         to_char(lower(g.valid_period) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') END AS valid_from,
       CASE WHEN isempty(g.valid_period) OR upper_inf(g.valid_period) THEN '' ELSE
         to_char(upper(g.valid_period) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') END AS valid_to,
       isempty(g.valid_period) AS validity_empty,
       g.valid_period @> clock_timestamp() AS current_grant
  FROM iam.access_grant g
  JOIN iam.role role ON role.tenant_id = g.tenant_id AND role.id = g.role_id
  LEFT JOIN directory.tenant_organization rel ON rel.tenant_id = g.tenant_id
       AND rel.id = g.scope_id AND rel.relationship_role = 'PROVIDER' AND g.scope_type = 'ORGANIZATION'
  LEFT JOIN directory.organization o ON o.id = rel.organization_id
 WHERE g.tenant_id = $1 AND g.tenant_membership_id = $2 AND g.id = $3
`

type GetTenantRoleGrantParams struct {
	TenantID           uuid.UUID
	TenantMembershipID uuid.UUID
	ID                 uuid.UUID
}

type GetTenantRoleGrantRow struct {
	ID                         uuid.UUID
	CreatedAt                  time.Time
	RoleCode                   string
	RoleName                   string
	IsSystemRole               bool
	ScopeType                  string
	ScopeID                    uuid.NullUUID
	RoleID                     uuid.UUID
	OrganizationRelationshipID interface{}
	OrganizationDisplayName    interface{}
	ValidFrom                  interface{}
	ValidTo                    interface{}
	ValidityEmpty              bool
	CurrentGrant               interface{}
}

func (q *Queries) GetTenantRoleGrant(ctx context.Context, arg GetTenantRoleGrantParams) (GetTenantRoleGrantRow, error) {
	row := q.db.QueryRow(ctx, getTenantRoleGrant, arg.TenantID, arg.TenantMembershipID, arg.ID)
	var i GetTenantRoleGrantRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.RoleCode,
		&i.RoleName,
		&i.IsSystemRole,
		&i.ScopeType,
		&i.ScopeID,
		&i.RoleID,
		&i.OrganizationRelationshipID,
		&i.OrganizationDisplayName,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ValidityEmpty,
		&i.CurrentGrant,
	)
	return i, err
}

const getTenantRoleGrantRoleID = `-- name: GetTenantRoleGrantRoleID :one
SELECT role_id FROM iam.access_grant WHERE tenant_id = $1 AND tenant_membership_id = $2 AND id = $3
`

type GetTenantRoleGrantRoleIDParams struct {
	TenantID           uuid.UUID
	TenantMembershipID uuid.UUID
	ID                 uuid.UUID
}

func (q *Queries) GetTenantRoleGrantRoleID(ctx context.Context, arg GetTenantRoleGrantRoleIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTenantRoleGrantRoleID, arg.TenantID, arg.TenantMembershipID, arg.ID)
	var role_id uuid.UUID
	err := row.Scan(&role_id)
	return role_id, err
}

const hasCurrentFutureOrPersonGrant = `-- name: HasCurrentFutureOrPersonGrant :one
SELECT EXISTS (SELECT 1 FROM iam.access_grant g
 WHERE g.tenant_id = $1 AND g.tenant_membership_id = $2
   AND (g.scope_type = 'PERSON' OR
        (NOT isempty(g.valid_period) AND (upper_inf(g.valid_period) OR upper(g.valid_period) > clock_timestamp()))))
`

type HasCurrentFutureOrPersonGrantParams struct {
	TenantID           uuid.UUID
	TenantMembershipID uuid.UUID
}

func (q *Queries) HasCurrentFutureOrPersonGrant(ctx context.Context, arg HasCurrentFutureOrPersonGrantParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasCurrentFutureOrPersonGrant, arg.TenantID, arg.TenantMembershipID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasCurrentOrFutureGrantForRole = `-- name: HasCurrentOrFutureGrantForRole :one
SELECT EXISTS (SELECT 1 FROM iam.access_grant
 WHERE tenant_id = $1 AND role_id = $2 AND NOT isempty(valid_period)
   AND (upper_inf(valid_period) OR upper(valid_period) > clock_timestamp()))
`

type HasCurrentOrFutureGrantForRoleParams struct {
	TenantID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) HasCurrentOrFutureGrantForRole(ctx context.Context, arg HasCurrentOrFutureGrantForRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasCurrentOrFutureGrantForRole, arg.TenantID, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasPersonGrantHistory = `-- name: HasPersonGrantHistory :one
SELECT EXISTS (SELECT 1 FROM iam.access_grant g
 WHERE g.tenant_id = $1 AND g.tenant_membership_id = $2 AND g.scope_type = 'PERSON')
`

type HasPersonGrantHistoryParams struct {
	TenantID           uuid.UUID
	TenantMembershipID uuid.UUID
}

func (q *Queries) HasPersonGrantHistory(ctx context.Context, arg HasPersonGrantHistoryParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPersonGrantHistory, arg.TenantID, arg.TenantMembershipID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertTenantRoleGrant = `-- name: InsertTenantRoleGrant :one
INSERT INTO iam.access_grant (tenant_id, tenant_membership_id, role_id, scope_type, scope_id, valid_period, granted_by)
VALUES ($1, $2, $3, $4, $5, tstzrange($6::timestamptz, NULL, '[)'), $7) RETURNING id
`

type InsertTenantRoleGrantParams struct {
	TenantID           uuid.UUID
	TenantMembershipID uuid.UUID
	RoleID             uuid.UUID
	ScopeType          string
	ScopeID            uuid.NullUUID
	Column6            time.Time
	GrantedBy          uuid.NullUUID
}

func (q *Queries) InsertTenantRoleGrant(ctx context.Context, arg InsertTenantRoleGrantParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTenantRoleGrant,
		arg.TenantID,
		arg.TenantMembershipID,
		arg.RoleID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Column6,
		arg.GrantedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listRoleAssignmentOrganizations = `-- name: ListRoleAssignmentOrganizations :many
SELECT rel.id, rel.created_at, o.display_name, rel.tenant_code
  FROM directory.tenant_organization rel
  JOIN directory.organization o ON o.id = rel.organization_id
  JOIN provider.provider_profile p ON p.tenant_id = rel.tenant_id AND p.tenant_organization_id = rel.id
 WHERE rel.tenant_id = $1
   AND rel.relationship_role = 'PROVIDER' AND rel.status = 'ACTIVE'
   AND rel.valid_period @> clock_timestamp()::date AND o.status = 'ACTIVE'
   AND p.status = 'ACTIVE'
   AND (p.contracted_from IS NULL OR p.contracted_from <= clock_timestamp()::date)
   AND (p.contracted_to IS NULL OR p.contracted_to > clock_timestamp()::date)
   AND ($2::timestamptz IS NULL OR
        (rel.created_at, rel.id) < ($2::timestamptz, $3::uuid))
 ORDER BY rel.created_at DESC, rel.id DESC LIMIT $4
`

type ListRoleAssignmentOrganizationsParams struct {
	TenantID  uuid.UUID
	AfterAt   *time.Time
	AfterID   uuid.NullUUID
	PageLimit int32
}

type ListRoleAssignmentOrganizationsRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	DisplayName string
	TenantCode  *string
}

func (q *Queries) ListRoleAssignmentOrganizations(ctx context.Context, arg ListRoleAssignmentOrganizationsParams) ([]ListRoleAssignmentOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listRoleAssignmentOrganizations,
		arg.TenantID,
		arg.AfterAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoleAssignmentOrganizationsRow
	for rows.Next() {
		var i ListRoleAssignmentOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DisplayName,
			&i.TenantCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleAssignmentPermissions = `-- name: ListRoleAssignmentPermissions :many
SELECT rp.permission_code, p.sensitivity
  FROM iam.role_permission rp JOIN iam.permission p ON p.code = rp.permission_code
 WHERE rp.tenant_id = $1 AND rp.role_id = $2 ORDER BY rp.permission_code
`

type ListRoleAssignmentPermissionsParams struct {
	TenantID uuid.UUID
	RoleID   uuid.UUID
}

type ListRoleAssignmentPermissionsRow struct {
	PermissionCode string
	Sensitivity    string
}

func (q *Queries) ListRoleAssignmentPermissions(ctx context.Context, arg ListRoleAssignmentPermissionsParams) ([]ListRoleAssignmentPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRoleAssignmentPermissions, arg.TenantID, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoleAssignmentPermissionsRow
	for rows.Next() {
		var i ListRoleAssignmentPermissionsRow
		if err := rows.Scan(&i.PermissionCode, &i.Sensitivity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantRoleGrantHistory = `-- name: ListTenantRoleGrantHistory :many
SELECT g.id, g.created_at, role.code AS role_code, role.name AS role_name,
       role.is_system_role, g.scope_type, g.scope_id,
       CASE WHEN g.scope_type = 'ORGANIZATION' AND rel.id IS NOT NULL THEN rel.id::text ELSE NULL END AS organization_relationship_id,
       CASE WHEN g.scope_type = 'ORGANIZATION' AND rel.id IS NOT NULL THEN o.display_name ELSE NULL END AS organization_display_name,
       CASE WHEN isempty(g.valid_period) OR lower_inf(g.valid_period) THEN '' ELSE
         to_char(lower(g.valid_period) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') END AS valid_from,
       CASE WHEN isempty(g.valid_period) OR upper_inf(g.valid_period) THEN '' ELSE
         to_char(upper(g.valid_period) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') END AS valid_to,
       isempty(g.valid_period) AS validity_empty,
       g.valid_period @> clock_timestamp() AS current_grant,
       g.role_id
  FROM iam.access_grant g
  JOIN iam.role role ON role.tenant_id = g.tenant_id AND role.id = g.role_id
  LEFT JOIN directory.tenant_organization rel ON rel.tenant_id = g.tenant_id
       AND rel.id = g.scope_id AND rel.relationship_role = 'PROVIDER' AND g.scope_type = 'ORGANIZATION'
  LEFT JOIN directory.organization o ON o.id = rel.organization_id
 WHERE g.tenant_id = $1 AND g.tenant_membership_id = $2
   AND ($3::timestamptz IS NULL OR
        (g.created_at, g.id) < ($3::timestamptz, $4::uuid))
 ORDER BY g.created_at DESC, g.id DESC LIMIT $5
`

type ListTenantRoleGrantHistoryParams struct {
	TenantID     uuid.UUID
	MembershipID uuid.UUID
	AfterAt      *time.Time
	AfterID      uuid.NullUUID
	PageLimit    int32
}

type ListTenantRoleGrantHistoryRow struct {
	ID                         uuid.UUID
	CreatedAt                  time.Time
	RoleCode                   string
	RoleName                   string
	IsSystemRole               bool
	ScopeType                  string
	ScopeID                    uuid.NullUUID
	OrganizationRelationshipID interface{}
	OrganizationDisplayName    interface{}
	ValidFrom                  interface{}
	ValidTo                    interface{}
	ValidityEmpty              bool
	CurrentGrant               interface{}
	RoleID                     uuid.UUID
}

func (q *Queries) ListTenantRoleGrantHistory(ctx context.Context, arg ListTenantRoleGrantHistoryParams) ([]ListTenantRoleGrantHistoryRow, error) {
	rows, err := q.db.Query(ctx, listTenantRoleGrantHistory,
		arg.TenantID,
		arg.MembershipID,
		arg.AfterAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantRoleGrantHistoryRow
	for rows.Next() {
		var i ListTenantRoleGrantHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.RoleCode,
			&i.RoleName,
			&i.IsSystemRole,
			&i.ScopeType,
			&i.ScopeID,
			&i.OrganizationRelationshipID,
			&i.OrganizationDisplayName,
			&i.ValidFrom,
			&i.ValidTo,
			&i.ValidityEmpty,
			&i.CurrentGrant,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEligibleRoleAssignmentOrganization = `-- name: LockEligibleRoleAssignmentOrganization :one
SELECT rel.id, o.display_name, rel.tenant_code
  FROM directory.tenant_organization rel
  JOIN directory.organization o ON o.id = rel.organization_id
  JOIN provider.provider_profile p ON p.tenant_id = rel.tenant_id AND p.tenant_organization_id = rel.id
 WHERE rel.tenant_id = $1 AND rel.id = $2
   AND rel.relationship_role = 'PROVIDER' AND rel.status = 'ACTIVE'
   AND rel.valid_period @> clock_timestamp()::date AND o.status = 'ACTIVE'
   AND p.status = 'ACTIVE'
   AND (p.contracted_from IS NULL OR p.contracted_from <= clock_timestamp()::date)
   AND (p.contracted_to IS NULL OR p.contracted_to > clock_timestamp()::date)
 FOR UPDATE OF rel, o, p
`

type LockEligibleRoleAssignmentOrganizationParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type LockEligibleRoleAssignmentOrganizationRow struct {
	ID          uuid.UUID
	DisplayName string
	TenantCode  *string
}

func (q *Queries) LockEligibleRoleAssignmentOrganization(ctx context.Context, arg LockEligibleRoleAssignmentOrganizationParams) (LockEligibleRoleAssignmentOrganizationRow, error) {
	row := q.db.QueryRow(ctx, lockEligibleRoleAssignmentOrganization, arg.TenantID, arg.ID)
	var i LockEligibleRoleAssignmentOrganizationRow
	err := row.Scan(&i.ID, &i.DisplayName, &i.TenantCode)
	return i, err
}

const lockRoleAssignmentActor = `-- name: LockRoleAssignmentActor :one
SELECT id, status FROM iam.actor WHERE id = $1 FOR SHARE
`

type LockRoleAssignmentActorRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) LockRoleAssignmentActor(ctx context.Context, id uuid.UUID) (LockRoleAssignmentActorRow, error) {
	row := q.db.QueryRow(ctx, lockRoleAssignmentActor, id)
	var i LockRoleAssignmentActorRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const lockRoleAssignmentCandidate = `-- name: LockRoleAssignmentCandidate :one
SELECT id, code, name, is_system_role FROM iam.role WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type LockRoleAssignmentCandidateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type LockRoleAssignmentCandidateRow struct {
	ID           uuid.UUID
	Code         string
	Name         string
	IsSystemRole bool
}

func (q *Queries) LockRoleAssignmentCandidate(ctx context.Context, arg LockRoleAssignmentCandidateParams) (LockRoleAssignmentCandidateRow, error) {
	row := q.db.QueryRow(ctx, lockRoleAssignmentCandidate, arg.TenantID, arg.ID)
	var i LockRoleAssignmentCandidateRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsSystemRole,
	)
	return i, err
}

const lockRoleAssignmentSession = `-- name: LockRoleAssignmentSession :one
SELECT actor_id, active_tenant_id, last_seen_at, expires_at, step_up_until, revoked_at
  FROM iam.session WHERE id_hash = $1 FOR SHARE
`

type LockRoleAssignmentSessionRow struct {
	ActorID        uuid.UUID
	ActiveTenantID uuid.NullUUID
	LastSeenAt     time.Time
	ExpiresAt      time.Time
	StepUpUntil    *time.Time
	RevokedAt      *time.Time
}

func (q *Queries) LockRoleAssignmentSession(ctx context.Context, idHash []byte) (LockRoleAssignmentSessionRow, error) {
	row := q.db.QueryRow(ctx, lockRoleAssignmentSession, idHash)
	var i LockRoleAssignmentSessionRow
	err := row.Scan(
		&i.ActorID,
		&i.ActiveTenantID,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.StepUpUntil,
		&i.RevokedAt,
	)
	return i, err
}

const lockRoleAssignmentTarget = `-- name: LockRoleAssignmentTarget :one
SELECT m.id, m.actor_id, m.membership_status, m.row_version,
       m.valid_period @> clock_timestamp()::date AS membership_valid,
       a.actor_type, a.status AS actor_status
  FROM iam.tenant_membership m JOIN iam.actor a ON a.id = m.actor_id
 WHERE m.tenant_id = $1 AND m.id = $2 FOR UPDATE OF m FOR SHARE OF a
`

type LockRoleAssignmentTargetParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type LockRoleAssignmentTargetRow struct {
	ID               uuid.UUID
	ActorID          uuid.UUID
	MembershipStatus string
	RowVersion       int64
	MembershipValid  interface{}
	ActorType        string
	ActorStatus      string
}

func (q *Queries) LockRoleAssignmentTarget(ctx context.Context, arg LockRoleAssignmentTargetParams) (LockRoleAssignmentTargetRow, error) {
	row := q.db.QueryRow(ctx, lockRoleAssignmentTarget, arg.TenantID, arg.ID)
	var i LockRoleAssignmentTargetRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.MembershipStatus,
		&i.RowVersion,
		&i.MembershipValid,
		&i.ActorType,
		&i.ActorStatus,
	)
	return i, err
}

const lockRoleAssignmentTargetRead = `-- name: LockRoleAssignmentTargetRead :one
SELECT m.id, m.actor_id, m.membership_status, m.row_version,
       m.valid_period @> clock_timestamp()::date AS membership_valid,
       a.actor_type, a.status AS actor_status
  FROM iam.tenant_membership m JOIN iam.actor a ON a.id = m.actor_id
 WHERE m.tenant_id = $1 AND m.id = $2 FOR SHARE OF m
`

type LockRoleAssignmentTargetReadParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type LockRoleAssignmentTargetReadRow struct {
	ID               uuid.UUID
	ActorID          uuid.UUID
	MembershipStatus string
	RowVersion       int64
	MembershipValid  interface{}
	ActorType        string
	ActorStatus      string
}

// Keep aggregate ETag and child-grant projections in one stable read. All trusted
// grant writers lock and touch this membership before commit.
func (q *Queries) LockRoleAssignmentTargetRead(ctx context.Context, arg LockRoleAssignmentTargetReadParams) (LockRoleAssignmentTargetReadRow, error) {
	row := q.db.QueryRow(ctx, lockRoleAssignmentTargetRead, arg.TenantID, arg.ID)
	var i LockRoleAssignmentTargetReadRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.MembershipStatus,
		&i.RowVersion,
		&i.MembershipValid,
		&i.ActorType,
		&i.ActorStatus,
	)
	return i, err
}

const lockTenantRoleGrant = `-- name: LockTenantRoleGrant :one
SELECT id, role_id, scope_type, scope_id, valid_period @> clock_timestamp() AS current_grant,
       isempty(valid_period) AS validity_empty
  FROM iam.access_grant WHERE tenant_id = $1 AND tenant_membership_id = $2 AND id = $3 FOR UPDATE
`

type LockTenantRoleGrantParams struct {
	TenantID           uuid.UUID
	TenantMembershipID uuid.UUID
	ID                 uuid.UUID
}

type LockTenantRoleGrantRow struct {
	ID            uuid.UUID
	RoleID        uuid.UUID
	ScopeType     string
	ScopeID       uuid.NullUUID
	CurrentGrant  interface{}
	ValidityEmpty bool
}

func (q *Queries) LockTenantRoleGrant(ctx context.Context, arg LockTenantRoleGrantParams) (LockTenantRoleGrantRow, error) {
	row := q.db.QueryRow(ctx, lockTenantRoleGrant, arg.TenantID, arg.TenantMembershipID, arg.ID)
	var i LockTenantRoleGrantRow
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.CurrentGrant,
		&i.ValidityEmpty,
	)
	return i, err
}

const roleAssignmentNow = `-- name: RoleAssignmentNow :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) RoleAssignmentNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, roleAssignmentNow)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const touchRoleAssignmentMembership = `-- name: TouchRoleAssignmentMembership :one
UPDATE iam.tenant_membership SET membership_status = membership_status
 WHERE tenant_id = $1 AND id = $2 AND row_version = $3 RETURNING row_version
`

type TouchRoleAssignmentMembershipParams struct {
	TenantID   uuid.UUID
	ID         uuid.UUID
	RowVersion int64
}

func (q *Queries) TouchRoleAssignmentMembership(ctx context.Context, arg TouchRoleAssignmentMembershipParams) (int64, error) {
	row := q.db.QueryRow(ctx, touchRoleAssignmentMembership, arg.TenantID, arg.ID, arg.RowVersion)
	var row_version int64
	err := row.Scan(&row_version)
	return row_version, err
}
