// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: servicerequest.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceRequest = `-- name: CreateServiceRequest :one

INSERT INTO service.service_request (
    tenant_id, request_reference, request_type, person_id, program_id, enrollment_id,
    provider_tenant_organization_id, service_date, requested_start_at, requested_end_at,
    channel, supersedes_request_id, created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8,
        $9, $10,
        $11, $12,
        $13, $13)
RETURNING id, request_reference, created_at, row_version
`

type CreateServiceRequestParams struct {
	TenantID                     uuid.UUID
	RequestReference             string
	RequestType                  string
	PersonID                     uuid.UUID
	ProgramID                    uuid.UUID
	EnrollmentID                 uuid.UUID
	ProviderTenantOrganizationID uuid.NullUUID
	ServiceDate                  pgtype.Date
	RequestedStartAt             *time.Time
	RequestedEndAt               *time.Time
	Channel                      string
	SupersedesRequestID          uuid.NullUUID
	ActorID                      uuid.NullUUID
}

type CreateServiceRequestRow struct {
	ID               uuid.UUID
	RequestReference string
	CreatedAt        time.Time
	RowVersion       int64
}

// Service request queries (WP-I4-01, v1.2 9.11, 11.8, 11.9).
//
// Two properties shape this file. The first is that nothing here writes `status` as a
// field a caller chose: every statement that moves a request is named after the command
// that moves it, carries that command's precondition in its WHERE clause and sets the
// reason columns the transition owes. A generic "set the status to whatever was sent" is
// exactly the statement this package exists to not have.
//
// The second is the provider boundary. `scope_ids` is a nullable uuid[]: NULL means the
// caller is tenant-wide, a non-null array binds it to those organizations. It is applied
// in every read of a request, including the single-row ones, so a provider asking for
// another provider's request finds no row and is answered 404 rather than 403 — that such
// a request exists at all is somebody else's business.
//
// Quantities and amounts are read as `::text` and written as `::text::numeric`, so an
// exact decimal never passes through a float in either direction (handbook section 3).
// Opens a request in DRAFT. The reference is generated by the caller and unique per
// tenant; a collision surfaces as a unique violation and is retried with a new one.
func (q *Queries) CreateServiceRequest(ctx context.Context, arg CreateServiceRequestParams) (CreateServiceRequestRow, error) {
	row := q.db.QueryRow(ctx, createServiceRequest,
		arg.TenantID,
		arg.RequestReference,
		arg.RequestType,
		arg.PersonID,
		arg.ProgramID,
		arg.EnrollmentID,
		arg.ProviderTenantOrganizationID,
		arg.ServiceDate,
		arg.RequestedStartAt,
		arg.RequestedEndAt,
		arg.Channel,
		arg.SupersedesRequestID,
		arg.ActorID,
	)
	var i CreateServiceRequestRow
	err := row.Scan(
		&i.ID,
		&i.RequestReference,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const createServiceRequestStatusEvent = `-- name: CreateServiceRequestStatusEvent :exec
INSERT INTO workflow.status_event (
    tenant_id, aggregate_type, aggregate_id, from_status, to_status, transition_code,
    reason_code, reason_text, actor_id, metadata_json)
VALUES ($1, 'SERVICE_REQUEST', $2,
        $3, $4, $5,
        $6, $7, $8,
        $9)
`

type CreateServiceRequestStatusEventParams struct {
	TenantID       uuid.UUID
	AggregateID    uuid.UUID
	FromStatus     *string
	ToStatus       string
	TransitionCode string
	ReasonCode     *string
	ReasonText     *string
	ActorID        uuid.NullUUID
	MetadataJson   []byte
}

// Every transition leaves one row here. workflow.status_event is append-only (migration
// 000007): a history that could be edited is not a history.
func (q *Queries) CreateServiceRequestStatusEvent(ctx context.Context, arg CreateServiceRequestStatusEventParams) error {
	_, err := q.db.Exec(ctx, createServiceRequestStatusEvent,
		arg.TenantID,
		arg.AggregateID,
		arg.FromStatus,
		arg.ToStatus,
		arg.TransitionCode,
		arg.ReasonCode,
		arg.ReasonText,
		arg.ActorID,
		arg.MetadataJson,
	)
	return err
}

const createServiceRequestVersion = `-- name: CreateServiceRequestVersion :one
INSERT INTO service.service_request_version (
    tenant_id, service_request_id, version_no, returned_at, returned_by,
    return_reason_code, return_reason_text, created_by)
VALUES ($1, $2, $3,
        $4, $5,
        $6, $7,
        $8)
RETURNING id, version_no, status, created_at
`

type CreateServiceRequestVersionParams struct {
	TenantID         uuid.UUID
	ServiceRequestID uuid.UUID
	VersionNo        int32
	ReturnedAt       *time.Time
	ReturnedBy       uuid.NullUUID
	ReturnReasonCode *string
	ReturnReasonText *string
	ActorID          uuid.NullUUID
}

type CreateServiceRequestVersionRow struct {
	ID        uuid.UUID
	VersionNo int32
	Status    string
	CreatedAt time.Time
}

// Opens the next version. The return columns are set when the version exists because it
// was sent back: the reason belongs to the draft the requester is asked to correct, which
// is also the only version the immutability trigger of migration 000006 lets anybody
// write to.
func (q *Queries) CreateServiceRequestVersion(ctx context.Context, arg CreateServiceRequestVersionParams) (CreateServiceRequestVersionRow, error) {
	row := q.db.QueryRow(ctx, createServiceRequestVersion,
		arg.TenantID,
		arg.ServiceRequestID,
		arg.VersionNo,
		arg.ReturnedAt,
		arg.ReturnedBy,
		arg.ReturnReasonCode,
		arg.ReturnReasonText,
		arg.ActorID,
	)
	var i CreateServiceRequestVersionRow
	err := row.Scan(
		&i.ID,
		&i.VersionNo,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteServiceRequestItems = `-- name: DeleteServiceRequestItems :execrows
DELETE FROM service.service_request_item
 WHERE tenant_id = $1
   AND service_request_version_id = $2
`

type DeleteServiceRequestItemsParams struct {
	TenantID                uuid.UUID
	ServiceRequestVersionID uuid.UUID
}

// Only a draft version's lines can be deleted; tg_request_item_guard refuses the rest.
func (q *Queries) DeleteServiceRequestItems(ctx context.Context, arg DeleteServiceRequestItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceRequestItems, arg.TenantID, arg.ServiceRequestVersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const freezeServiceRequestVersion = `-- name: FreezeServiceRequestVersion :execrows
UPDATE service.service_request_version
   SET status        = 'SUBMITTED',
       snapshot_json = $1,
       submitted_at  = $2,
       submitted_by  = $3
 WHERE tenant_id = $4
   AND id = $5
   AND status = 'DRAFT'
`

type FreezeServiceRequestVersionParams struct {
	SnapshotJson []byte
	SubmittedAt  *time.Time
	ActorID      uuid.NullUUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

// Submitting freezes the version: the snapshot is the header and the lines exactly as they
// were sent, and tg_request_version_guard makes every later write to this row fail.
func (q *Queries) FreezeServiceRequestVersion(ctx context.Context, arg FreezeServiceRequestVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, freezeServiceRequestVersion,
		arg.SnapshotJson,
		arg.SubmittedAt,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServiceRequest = `-- name: GetServiceRequest :one
SELECT id, request_reference, request_type, person_id, program_id, enrollment_id,
       provider_tenant_organization_id, service_date, requested_start_at, requested_end_at,
       channel, status, current_version_no, supersedes_request_id,
       eligibility_evaluation_id, rule_evaluation_id, required_document_types,
       return_reason_code, reject_reason_code, review_comment,
       submitted_at, closed_at, created_at, row_version
  FROM service.service_request
 WHERE tenant_id = $1
   AND id = $2
   AND ($3::uuid[] IS NULL
        OR provider_tenant_organization_id = ANY($3::uuid[]))
`

type GetServiceRequestParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type GetServiceRequestRow struct {
	ID                           uuid.UUID
	RequestReference             string
	RequestType                  string
	PersonID                     uuid.UUID
	ProgramID                    uuid.UUID
	EnrollmentID                 uuid.UUID
	ProviderTenantOrganizationID uuid.NullUUID
	ServiceDate                  pgtype.Date
	RequestedStartAt             *time.Time
	RequestedEndAt               *time.Time
	Channel                      string
	Status                       string
	CurrentVersionNo             int32
	SupersedesRequestID          uuid.NullUUID
	EligibilityEvaluationID      uuid.NullUUID
	RuleEvaluationID             uuid.NullUUID
	RequiredDocumentTypes        []string
	ReturnReasonCode             *string
	RejectReasonCode             *string
	ReviewComment                *string
	SubmittedAt                  *time.Time
	ClosedAt                     *time.Time
	CreatedAt                    time.Time
	RowVersion                   int64
}

func (q *Queries) GetServiceRequest(ctx context.Context, arg GetServiceRequestParams) (GetServiceRequestRow, error) {
	row := q.db.QueryRow(ctx, getServiceRequest, arg.TenantID, arg.ID, arg.ScopeIds)
	var i GetServiceRequestRow
	err := row.Scan(
		&i.ID,
		&i.RequestReference,
		&i.RequestType,
		&i.PersonID,
		&i.ProgramID,
		&i.EnrollmentID,
		&i.ProviderTenantOrganizationID,
		&i.ServiceDate,
		&i.RequestedStartAt,
		&i.RequestedEndAt,
		&i.Channel,
		&i.Status,
		&i.CurrentVersionNo,
		&i.SupersedesRequestID,
		&i.EligibilityEvaluationID,
		&i.RuleEvaluationID,
		&i.RequiredDocumentTypes,
		&i.ReturnReasonCode,
		&i.RejectReasonCode,
		&i.ReviewComment,
		&i.SubmittedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getServiceRequestDraftVersion = `-- name: GetServiceRequestDraftVersion :one
SELECT id, service_request_id, version_no, status, snapshot_json, submitted_at,
       submitted_by, returned_at, returned_by, return_reason_code, return_reason_text,
       created_at
  FROM service.service_request_version
 WHERE tenant_id = $1
   AND service_request_id = $2
   AND status = 'DRAFT'
`

type GetServiceRequestDraftVersionParams struct {
	TenantID         uuid.UUID
	ServiceRequestID uuid.UUID
}

type GetServiceRequestDraftVersionRow struct {
	ID               uuid.UUID
	ServiceRequestID uuid.UUID
	VersionNo        int32
	Status           string
	SnapshotJson     []byte
	SubmittedAt      *time.Time
	SubmittedBy      uuid.NullUUID
	ReturnedAt       *time.Time
	ReturnedBy       uuid.NullUUID
	ReturnReasonCode *string
	ReturnReasonText *string
	CreatedAt        time.Time
}

// The single DRAFT version of a request; uq_service_request_single_draft guarantees there
// is at most one.
func (q *Queries) GetServiceRequestDraftVersion(ctx context.Context, arg GetServiceRequestDraftVersionParams) (GetServiceRequestDraftVersionRow, error) {
	row := q.db.QueryRow(ctx, getServiceRequestDraftVersion, arg.TenantID, arg.ServiceRequestID)
	var i GetServiceRequestDraftVersionRow
	err := row.Scan(
		&i.ID,
		&i.ServiceRequestID,
		&i.VersionNo,
		&i.Status,
		&i.SnapshotJson,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.ReturnedAt,
		&i.ReturnedBy,
		&i.ReturnReasonCode,
		&i.ReturnReasonText,
		&i.CreatedAt,
	)
	return i, err
}

const getServiceRequestEnrollment = `-- name: GetServiceRequestEnrollment :one
SELECT e.id, e.plan_id, p.program_id, e.status, m.person_id,
       lower(e.valid_period)::date AS valid_from,
       upper(e.valid_period)::date AS valid_to
  FROM benefit.enrollment e
  JOIN party.sponsor_membership m ON m.tenant_id = e.tenant_id AND m.id = e.sponsor_membership_id
  JOIN benefit.plan p ON p.tenant_id = e.tenant_id AND p.id = e.plan_id
 WHERE e.tenant_id = $1 AND e.id = $2
`

type GetServiceRequestEnrollmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetServiceRequestEnrollmentRow struct {
	ID        uuid.UUID
	PlanID    uuid.UUID
	ProgramID uuid.UUID
	Status    string
	PersonID  uuid.UUID
	ValidFrom pgtype.Date
	ValidTo   pgtype.Date
}

// The enrollment a request is raised under, with the person it belongs to and the program
// of its plan. A request naming an enrollment that is not this person's, or not in this
// program, is a request nobody could act on.
func (q *Queries) GetServiceRequestEnrollment(ctx context.Context, arg GetServiceRequestEnrollmentParams) (GetServiceRequestEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, getServiceRequestEnrollment, arg.TenantID, arg.ID)
	var i GetServiceRequestEnrollmentRow
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ProgramID,
		&i.Status,
		&i.PersonID,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const getServiceRequestReviewSetting = `-- name: GetServiceRequestReviewSetting :one
SELECT value_json
  FROM platform.tenant_setting
 WHERE tenant_id = $1
   AND setting_key = 'service_request.review_required'
`

// Whether a program's approved requests still need a person to look at them. It is a
// setting rather than a hard-coded rule because two sponsors running the same program type
// genuinely differ on it; the service falls back to "a person reviews it", which is the
// answer that cannot quietly approve something nobody meant to approve.
func (q *Queries) GetServiceRequestReviewSetting(ctx context.Context, tenantID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getServiceRequestReviewSetting, tenantID)
	var value_json []byte
	err := row.Scan(&value_json)
	return value_json, err
}

const getServiceRequestVersionByNo = `-- name: GetServiceRequestVersionByNo :one
SELECT id, service_request_id, version_no, status, snapshot_json, submitted_at,
       submitted_by, returned_at, returned_by, return_reason_code, return_reason_text,
       created_at
  FROM service.service_request_version
 WHERE tenant_id = $1
   AND service_request_id = $2
   AND version_no = $3
`

type GetServiceRequestVersionByNoParams struct {
	TenantID         uuid.UUID
	ServiceRequestID uuid.UUID
	VersionNo        int32
}

type GetServiceRequestVersionByNoRow struct {
	ID               uuid.UUID
	ServiceRequestID uuid.UUID
	VersionNo        int32
	Status           string
	SnapshotJson     []byte
	SubmittedAt      *time.Time
	SubmittedBy      uuid.NullUUID
	ReturnedAt       *time.Time
	ReturnedBy       uuid.NullUUID
	ReturnReasonCode *string
	ReturnReasonText *string
	CreatedAt        time.Time
}

func (q *Queries) GetServiceRequestVersionByNo(ctx context.Context, arg GetServiceRequestVersionByNoParams) (GetServiceRequestVersionByNoRow, error) {
	row := q.db.QueryRow(ctx, getServiceRequestVersionByNo, arg.TenantID, arg.ServiceRequestID, arg.VersionNo)
	var i GetServiceRequestVersionByNoRow
	err := row.Scan(
		&i.ID,
		&i.ServiceRequestID,
		&i.VersionNo,
		&i.Status,
		&i.SnapshotJson,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.ReturnedAt,
		&i.ReturnedBy,
		&i.ReturnReasonCode,
		&i.ReturnReasonText,
		&i.CreatedAt,
	)
	return i, err
}

const listPublishedRuleSetVersionsForPurposes = `-- name: ListPublishedRuleSetVersionsForPurposes :many
SELECT v.id, v.rule_set_id, s.code AS rule_set_code, s.purpose, v.version_no, v.input_schema
  FROM rules.rule_set_version v
  JOIN rules.rule_set s ON s.tenant_id = v.tenant_id AND s.id = v.rule_set_id
 WHERE v.tenant_id = $1
   AND v.status = 'PUBLISHED'
   AND s.status = 'ACTIVE'
   AND s.purpose = ANY($2::text[])
   AND daterange(v.valid_from, v.valid_to, '[)') @> $3::date
 ORDER BY s.purpose, s.code, v.version_no
`

type ListPublishedRuleSetVersionsForPurposesParams struct {
	TenantID    uuid.UUID
	Purposes    []string
	ServiceDate pgtype.Date
}

type ListPublishedRuleSetVersionsForPurposesRow struct {
	ID          uuid.UUID
	RuleSetID   uuid.UUID
	RuleSetCode string
	Purpose     string
	VersionNo   int32
	InputSchema []byte
}

// Every published rule set version of the tenant that covers the service date and serves
// one of the given purposes. The exclusion constraint on rules.rule_set_version makes at
// most one version per set match, so this is "which rules decide today" and never a
// choice between two answers.
func (q *Queries) ListPublishedRuleSetVersionsForPurposes(ctx context.Context, arg ListPublishedRuleSetVersionsForPurposesParams) ([]ListPublishedRuleSetVersionsForPurposesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedRuleSetVersionsForPurposes, arg.TenantID, arg.Purposes, arg.ServiceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedRuleSetVersionsForPurposesRow
	for rows.Next() {
		var i ListPublishedRuleSetVersionsForPurposesRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleSetID,
			&i.RuleSetCode,
			&i.Purpose,
			&i.VersionNo,
			&i.InputSchema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceRequestItems = `-- name: ListServiceRequestItems :many
SELECT id, service_request_version_id, line_no, service_definition_id,
       requested_quantity::text AS requested_quantity,
       unit_type,
       -- A NULL amount renders as the empty string rather than as a NULL text: the caller
       -- turns it back into "no value", and no cast anywhere invents a zero.
       COALESCE(requested_amount::text, '')::text  AS requested_amount,
       currency_code, status,
       COALESCE(approved_quantity::text, '')::text AS approved_quantity,
       COALESCE(approved_amount::text, '')::text   AS approved_amount,
       decision_reason_code
  FROM service.service_request_item
 WHERE tenant_id = $1
   AND service_request_version_id = $2
 ORDER BY line_no
`

type ListServiceRequestItemsParams struct {
	TenantID                uuid.UUID
	ServiceRequestVersionID uuid.UUID
}

type ListServiceRequestItemsRow struct {
	ID                      uuid.UUID
	ServiceRequestVersionID uuid.UUID
	LineNo                  int32
	ServiceDefinitionID     uuid.UUID
	RequestedQuantity       string
	UnitType                string
	RequestedAmount         string
	CurrencyCode            *string
	Status                  string
	ApprovedQuantity        string
	ApprovedAmount          string
	DecisionReasonCode      *string
}

func (q *Queries) ListServiceRequestItems(ctx context.Context, arg ListServiceRequestItemsParams) ([]ListServiceRequestItemsRow, error) {
	rows, err := q.db.Query(ctx, listServiceRequestItems, arg.TenantID, arg.ServiceRequestVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceRequestItemsRow
	for rows.Next() {
		var i ListServiceRequestItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceRequestVersionID,
			&i.LineNo,
			&i.ServiceDefinitionID,
			&i.RequestedQuantity,
			&i.UnitType,
			&i.RequestedAmount,
			&i.CurrencyCode,
			&i.Status,
			&i.ApprovedQuantity,
			&i.ApprovedAmount,
			&i.DecisionReasonCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceRequestServiceDefinitions = `-- name: ListServiceRequestServiceDefinitions :many
SELECT id, code, default_unit_type, requires_provider, active
  FROM catalog.service_definition
 WHERE tenant_id = $1
   AND id = ANY($2::uuid[])
`

type ListServiceRequestServiceDefinitionsParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

type ListServiceRequestServiceDefinitionsRow struct {
	ID               uuid.UUID
	Code             string
	DefaultUnitType  string
	RequiresProvider bool
	Active           bool
}

// The definitions named by the lines, with the unit they are counted in and whether they
// need a provider at all.
func (q *Queries) ListServiceRequestServiceDefinitions(ctx context.Context, arg ListServiceRequestServiceDefinitionsParams) ([]ListServiceRequestServiceDefinitionsRow, error) {
	rows, err := q.db.Query(ctx, listServiceRequestServiceDefinitions, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceRequestServiceDefinitionsRow
	for rows.Next() {
		var i ListServiceRequestServiceDefinitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DefaultUnitType,
			&i.RequiresProvider,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceRequestStatusEvents = `-- name: ListServiceRequestStatusEvents :many
SELECT id, from_status, to_status, transition_code, reason_code, reason_text,
       occurred_at, actor_id, metadata_json
  FROM workflow.status_event
 WHERE tenant_id = $1
   AND aggregate_type = 'SERVICE_REQUEST'
   AND aggregate_id = $2
 ORDER BY occurred_at, id
`

type ListServiceRequestStatusEventsParams struct {
	TenantID    uuid.UUID
	AggregateID uuid.UUID
}

type ListServiceRequestStatusEventsRow struct {
	ID             uuid.UUID
	FromStatus     *string
	ToStatus       string
	TransitionCode string
	ReasonCode     *string
	ReasonText     *string
	OccurredAt     time.Time
	ActorID        uuid.NullUUID
	MetadataJson   []byte
}

// The transition history of one request, oldest first.
func (q *Queries) ListServiceRequestStatusEvents(ctx context.Context, arg ListServiceRequestStatusEventsParams) ([]ListServiceRequestStatusEventsRow, error) {
	rows, err := q.db.Query(ctx, listServiceRequestStatusEvents, arg.TenantID, arg.AggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceRequestStatusEventsRow
	for rows.Next() {
		var i ListServiceRequestStatusEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.FromStatus,
			&i.ToStatus,
			&i.TransitionCode,
			&i.ReasonCode,
			&i.ReasonText,
			&i.OccurredAt,
			&i.ActorID,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceRequestVersions = `-- name: ListServiceRequestVersions :many
SELECT id, service_request_id, version_no, status, snapshot_json, submitted_at,
       submitted_by, returned_at, returned_by, return_reason_code, return_reason_text,
       created_at
  FROM service.service_request_version
 WHERE tenant_id = $1
   AND service_request_id = $2
 ORDER BY version_no DESC
`

type ListServiceRequestVersionsParams struct {
	TenantID         uuid.UUID
	ServiceRequestID uuid.UUID
}

type ListServiceRequestVersionsRow struct {
	ID               uuid.UUID
	ServiceRequestID uuid.UUID
	VersionNo        int32
	Status           string
	SnapshotJson     []byte
	SubmittedAt      *time.Time
	SubmittedBy      uuid.NullUUID
	ReturnedAt       *time.Time
	ReturnedBy       uuid.NullUUID
	ReturnReasonCode *string
	ReturnReasonText *string
	CreatedAt        time.Time
}

func (q *Queries) ListServiceRequestVersions(ctx context.Context, arg ListServiceRequestVersionsParams) ([]ListServiceRequestVersionsRow, error) {
	rows, err := q.db.Query(ctx, listServiceRequestVersions, arg.TenantID, arg.ServiceRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceRequestVersionsRow
	for rows.Next() {
		var i ListServiceRequestVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceRequestID,
			&i.VersionNo,
			&i.Status,
			&i.SnapshotJson,
			&i.SubmittedAt,
			&i.SubmittedBy,
			&i.ReturnedAt,
			&i.ReturnedBy,
			&i.ReturnReasonCode,
			&i.ReturnReasonText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceRequests = `-- name: ListServiceRequests :many
SELECT id, request_reference, request_type, person_id, program_id, enrollment_id,
       provider_tenant_organization_id, service_date, requested_start_at, requested_end_at,
       channel, status, current_version_no, supersedes_request_id,
       eligibility_evaluation_id, rule_evaluation_id, required_document_types,
       return_reason_code, reject_reason_code, review_comment,
       submitted_at, closed_at, created_at, row_version
  FROM service.service_request
 WHERE tenant_id = $1
   AND ($2::uuid[] IS NULL
        OR provider_tenant_organization_id = ANY($2::uuid[]))
   AND ($3::text IS NULL OR status = $3::text)
   AND ($4::uuid IS NULL OR person_id = $4::uuid)
   AND ($5::uuid IS NULL OR program_id = $5::uuid)
   AND ($6::uuid IS NULL
        OR provider_tenant_organization_id = $6::uuid)
   AND ($7::text IS NULL OR channel = $7::text)
   AND ($8::date IS NULL
        OR service_date >= $8::date)
   AND ($9::date IS NULL
        OR service_date <= $9::date)
   AND ($10::timestamptz IS NULL
        OR created_at >= $10::timestamptz)
   AND ($11::timestamptz IS NULL
        OR created_at <= $11::timestamptz)
   AND ($12::timestamptz IS NULL
        OR (created_at, id) < ($12::timestamptz, $13::uuid))
 ORDER BY created_at DESC, id DESC
 LIMIT $14
`

type ListServiceRequestsParams struct {
	TenantID        uuid.UUID
	ScopeIds        []uuid.UUID
	Status          *string
	PersonID        uuid.NullUUID
	ProgramID       uuid.NullUUID
	ProviderID      uuid.NullUUID
	Channel         *string
	ServiceDateFrom pgtype.Date
	ServiceDateTo   pgtype.Date
	CreatedFrom     *time.Time
	CreatedTo       *time.Time
	CursorCreatedAt *time.Time
	CursorID        uuid.NullUUID
	PageSize        int32
}

type ListServiceRequestsRow struct {
	ID                           uuid.UUID
	RequestReference             string
	RequestType                  string
	PersonID                     uuid.UUID
	ProgramID                    uuid.UUID
	EnrollmentID                 uuid.UUID
	ProviderTenantOrganizationID uuid.NullUUID
	ServiceDate                  pgtype.Date
	RequestedStartAt             *time.Time
	RequestedEndAt               *time.Time
	Channel                      string
	Status                       string
	CurrentVersionNo             int32
	SupersedesRequestID          uuid.NullUUID
	EligibilityEvaluationID      uuid.NullUUID
	RuleEvaluationID             uuid.NullUUID
	RequiredDocumentTypes        []string
	ReturnReasonCode             *string
	RejectReasonCode             *string
	ReviewComment                *string
	SubmittedAt                  *time.Time
	ClosedAt                     *time.Time
	CreatedAt                    time.Time
	RowVersion                   int64
}

// Keyset pagination on (created_at DESC, id DESC); the caller asks for limit+1 rows to
// learn whether a next page exists.
func (q *Queries) ListServiceRequests(ctx context.Context, arg ListServiceRequestsParams) ([]ListServiceRequestsRow, error) {
	rows, err := q.db.Query(ctx, listServiceRequests,
		arg.TenantID,
		arg.ScopeIds,
		arg.Status,
		arg.PersonID,
		arg.ProgramID,
		arg.ProviderID,
		arg.Channel,
		arg.ServiceDateFrom,
		arg.ServiceDateTo,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceRequestsRow
	for rows.Next() {
		var i ListServiceRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestReference,
			&i.RequestType,
			&i.PersonID,
			&i.ProgramID,
			&i.EnrollmentID,
			&i.ProviderTenantOrganizationID,
			&i.ServiceDate,
			&i.RequestedStartAt,
			&i.RequestedEndAt,
			&i.Channel,
			&i.Status,
			&i.CurrentVersionNo,
			&i.SupersedesRequestID,
			&i.EligibilityEvaluationID,
			&i.RuleEvaluationID,
			&i.RequiredDocumentTypes,
			&i.ReturnReasonCode,
			&i.RejectReasonCode,
			&i.ReviewComment,
			&i.SubmittedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockServiceRequest = `-- name: LockServiceRequest :one
SELECT id, request_reference, request_type, person_id, program_id, enrollment_id,
       provider_tenant_organization_id, service_date, requested_start_at, requested_end_at,
       channel, status, current_version_no, supersedes_request_id,
       eligibility_evaluation_id, rule_evaluation_id, required_document_types,
       return_reason_code, reject_reason_code, review_comment,
       submitted_at, closed_at, created_at, row_version
  FROM service.service_request
 WHERE tenant_id = $1
   AND id = $2
   AND ($3::uuid[] IS NULL
        OR provider_tenant_organization_id = ANY($3::uuid[]))
   FOR UPDATE
`

type LockServiceRequestParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type LockServiceRequestRow struct {
	ID                           uuid.UUID
	RequestReference             string
	RequestType                  string
	PersonID                     uuid.UUID
	ProgramID                    uuid.UUID
	EnrollmentID                 uuid.UUID
	ProviderTenantOrganizationID uuid.NullUUID
	ServiceDate                  pgtype.Date
	RequestedStartAt             *time.Time
	RequestedEndAt               *time.Time
	Channel                      string
	Status                       string
	CurrentVersionNo             int32
	SupersedesRequestID          uuid.NullUUID
	EligibilityEvaluationID      uuid.NullUUID
	RuleEvaluationID             uuid.NullUUID
	RequiredDocumentTypes        []string
	ReturnReasonCode             *string
	RejectReasonCode             *string
	ReviewComment                *string
	SubmittedAt                  *time.Time
	ClosedAt                     *time.Time
	CreatedAt                    time.Time
	RowVersion                   int64
}

// The same read taken FOR UPDATE, so two commands on one request serialise instead of
// racing each other into two different decisions.
func (q *Queries) LockServiceRequest(ctx context.Context, arg LockServiceRequestParams) (LockServiceRequestRow, error) {
	row := q.db.QueryRow(ctx, lockServiceRequest, arg.TenantID, arg.ID, arg.ScopeIds)
	var i LockServiceRequestRow
	err := row.Scan(
		&i.ID,
		&i.RequestReference,
		&i.RequestType,
		&i.PersonID,
		&i.ProgramID,
		&i.EnrollmentID,
		&i.ProviderTenantOrganizationID,
		&i.ServiceDate,
		&i.RequestedStartAt,
		&i.RequestedEndAt,
		&i.Channel,
		&i.Status,
		&i.CurrentVersionNo,
		&i.SupersedesRequestID,
		&i.EligibilityEvaluationID,
		&i.RuleEvaluationID,
		&i.RequiredDocumentTypes,
		&i.ReturnReasonCode,
		&i.RejectReasonCode,
		&i.ReviewComment,
		&i.SubmittedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const markServiceRequestApproved = `-- name: MarkServiceRequestApproved :execrows
UPDATE service.service_request
   SET status         = $1,
       review_comment = $2,
       updated_by     = $3
 WHERE tenant_id = $4
   AND id = $5
   AND row_version = $6
   AND status = 'PENDING_REVIEW'
`

type MarkServiceRequestApprovedParams struct {
	Status        string
	ReviewComment *string
	ActorID       uuid.NullUUID
	TenantID      uuid.UUID
	ID            uuid.UUID
	RowVersion    int64
}

// Approval and partial approval share one statement because they differ only in the word
// and in what the lines say; both leave the request open, because nothing has been
// authorized or delivered yet.
func (q *Queries) MarkServiceRequestApproved(ctx context.Context, arg MarkServiceRequestApprovedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markServiceRequestApproved,
		arg.Status,
		arg.ReviewComment,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markServiceRequestCancelled = `-- name: MarkServiceRequestCancelled :execrows
UPDATE service.service_request
   SET status     = 'CANCELLED',
       closed_at  = $1,
       updated_by = $2
 WHERE tenant_id = $3
   AND id = $4
   AND row_version = $5
   AND status IN ('DRAFT', 'SUBMITTED', 'PENDING_REVIEW', 'PENDING_DOCUMENT', 'ELIGIBILITY_FAILED')
`

type MarkServiceRequestCancelledParams struct {
	DecidedAt  *time.Time
	ActorID    uuid.NullUUID
	TenantID   uuid.UUID
	ID         uuid.UUID
	RowVersion int64
}

// Withdrawal before a decision. A request that has already been decided is not cancelled
// here: undoing a decision has consequences of its own and belongs to service.cancellation.
func (q *Queries) MarkServiceRequestCancelled(ctx context.Context, arg MarkServiceRequestCancelledParams) (int64, error) {
	result, err := q.db.Exec(ctx, markServiceRequestCancelled,
		arg.DecidedAt,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markServiceRequestRejected = `-- name: MarkServiceRequestRejected :execrows
UPDATE service.service_request
   SET status             = 'REJECTED',
       reject_reason_code = $1,
       review_comment     = $2,
       closed_at          = $3,
       updated_by         = $4
 WHERE tenant_id = $5
   AND id = $6
   AND row_version = $7
   AND status = 'PENDING_REVIEW'
`

type MarkServiceRequestRejectedParams struct {
	RejectReasonCode *string
	ReviewComment    *string
	DecidedAt        *time.Time
	ActorID          uuid.NullUUID
	TenantID         uuid.UUID
	ID               uuid.UUID
	RowVersion       int64
}

// A refusal is final. The request closes here and is never reopened; a further attempt is
// a new request naming this one in supersedes_request_id.
func (q *Queries) MarkServiceRequestRejected(ctx context.Context, arg MarkServiceRequestRejectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markServiceRequestRejected,
		arg.RejectReasonCode,
		arg.ReviewComment,
		arg.DecidedAt,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markServiceRequestReturned = `-- name: MarkServiceRequestReturned :execrows
UPDATE service.service_request
   SET status                  = 'DRAFT',
       submitted_at            = NULL,
       closed_at               = NULL,
       current_version_no      = $1,
       return_reason_code      = $2,
       review_comment          = $3,
       required_document_types = NULL,
       updated_by              = $4
 WHERE tenant_id = $5
   AND id = $6
   AND row_version = $7
   AND status IN ('PENDING_REVIEW', 'PENDING_DOCUMENT')
`

type MarkServiceRequestReturnedParams struct {
	CurrentVersionNo int32
	ReturnReasonCode *string
	ReviewComment    *string
	ActorID          uuid.NullUUID
	TenantID         uuid.UUID
	ID               uuid.UUID
	RowVersion       int64
}

// Back to DRAFT with the reason it was sent back. submitted_at is cleared because the
// schema defines a draft as a request that has not been submitted; the submission it did
// make is on the frozen version, which is where anybody looking for it will find it.
func (q *Queries) MarkServiceRequestReturned(ctx context.Context, arg MarkServiceRequestReturnedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markServiceRequestReturned,
		arg.CurrentVersionNo,
		arg.ReturnReasonCode,
		arg.ReviewComment,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markServiceRequestSubmitted = `-- name: MarkServiceRequestSubmitted :execrows
UPDATE service.service_request
   SET status                    = $1,
       submitted_at              = $2,
       eligibility_evaluation_id = $3,
       rule_evaluation_id        = $4,
       required_document_types   = $5::text[],
       review_comment            = $6,
       return_reason_code        = NULL,
       updated_by                = $7
 WHERE tenant_id = $8
   AND id = $9
   AND row_version = $10
   AND status = 'DRAFT'
`

type MarkServiceRequestSubmittedParams struct {
	Status                  string
	SubmittedAt             *time.Time
	EligibilityEvaluationID uuid.NullUUID
	RuleEvaluationID        uuid.NullUUID
	RequiredDocumentTypes   []string
	ReviewComment           *string
	ActorID                 uuid.NullUUID
	TenantID                uuid.UUID
	ID                      uuid.UUID
	RowVersion              int64
}

// The one write of the submit gate. It records the outcome the gate arrived at together
// with the two evaluations that produced it, so "why is this waiting for a document"
// always has an answer that outlives the rule version that decided it.
func (q *Queries) MarkServiceRequestSubmitted(ctx context.Context, arg MarkServiceRequestSubmittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markServiceRequestSubmitted,
		arg.Status,
		arg.SubmittedAt,
		arg.EligibilityEvaluationID,
		arg.RuleEvaluationID,
		arg.RequiredDocumentTypes,
		arg.ReviewComment,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const serviceRequestProviderOrganizationExists = `-- name: ServiceRequestProviderOrganizationExists :one
SELECT EXISTS (
    SELECT 1
      FROM directory.tenant_organization
     WHERE tenant_id = $1
       AND id = $2
       AND relationship_role = 'PROVIDER'
) AS ok
`

type ServiceRequestProviderOrganizationExistsParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// The provider a request names has to be an organization this tenant deals with in a
// provider role.
func (q *Queries) ServiceRequestProviderOrganizationExists(ctx context.Context, arg ServiceRequestProviderOrganizationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, serviceRequestProviderOrganizationExists, arg.TenantID, arg.ID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const supersedeServiceRequestVersion = `-- name: SupersedeServiceRequestVersion :execrows
UPDATE service.service_request_version
   SET status = 'SUPERSEDED'
 WHERE tenant_id = $1
   AND id = $2
   AND status = 'SUBMITTED'
`

type SupersedeServiceRequestVersionParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// The one update a submitted version accepts: it is marked as replaced by a later one and
// nothing else about it changes.
func (q *Queries) SupersedeServiceRequestVersion(ctx context.Context, arg SupersedeServiceRequestVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeServiceRequestVersion, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchServiceRequest = `-- name: TouchServiceRequest :execrows
UPDATE service.service_request
   SET updated_by = $1
 WHERE tenant_id = $2 AND id = $3
`

type TouchServiceRequestParams struct {
	ActorID  uuid.NullUUID
	TenantID uuid.UUID
	ID       uuid.UUID
}

// Bumps row_version without changing a business field, so replacing the lines of the
// draft invalidates the ETag the caller is holding for the request.
func (q *Queries) TouchServiceRequest(ctx context.Context, arg TouchServiceRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchServiceRequest, arg.ActorID, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateServiceRequestDraftHeader = `-- name: UpdateServiceRequestDraftHeader :execrows
UPDATE service.service_request
   SET provider_tenant_organization_id = $1,
       service_date       = $2,
       requested_start_at = $3,
       requested_end_at   = $4,
       updated_by         = $5
 WHERE tenant_id = $6
   AND id = $7
   AND row_version = $8
   AND status = 'DRAFT'
`

type UpdateServiceRequestDraftHeaderParams struct {
	ProviderTenantOrganizationID uuid.NullUUID
	ServiceDate                  pgtype.Date
	RequestedStartAt             *time.Time
	RequestedEndAt               *time.Time
	ActorID                      uuid.NullUUID
	TenantID                     uuid.UUID
	ID                           uuid.UUID
	RowVersion                   int64
}

// The merge-patch of a DRAFT request's header. `status` is absent on purpose and there is
// no statement anywhere in this file that would let a caller supply one.
func (q *Queries) UpdateServiceRequestDraftHeader(ctx context.Context, arg UpdateServiceRequestDraftHeaderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateServiceRequestDraftHeader,
		arg.ProviderTenantOrganizationID,
		arg.ServiceDate,
		arg.RequestedStartAt,
		arg.RequestedEndAt,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
