// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimWorkItem = `-- name: ClaimWorkItem :execrows
UPDATE workflow.work_item
   SET status            = 'CLAIMED',
       assignee_actor_id = $1,
       assigned_at       = now(),
       updated_by        = $2
 WHERE tenant_id = $3
   AND id = $4
   AND status = 'OPEN'
   AND row_version = $5
`

type ClaimWorkItemParams struct {
	AssigneeActorID uuid.NullUUID
	ActorID         uuid.NullUUID
	TenantID        uuid.UUID
	ID              uuid.UUID
	RowVersion      int64
}

// The whole precondition is in the predicate: this item, this tenant, still OPEN, still at
// the version the caller read. Two callers racing on one item both run this statement; the
// second one waits on the row lock, re-evaluates the predicate against the row the first
// one committed, matches nothing and affects zero rows. There is no path here that
// overwrites an owner.
func (q *Queries) ClaimWorkItem(ctx context.Context, arg ClaimWorkItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimWorkItem,
		arg.AssigneeActorID,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeWorkItem = `-- name: CompleteWorkItem :execrows
UPDATE workflow.work_item
   SET status       = 'COMPLETED',
       outcome_code = $1,
       completed_at = now(),
       completed_by = $2,
       updated_by   = $3
 WHERE tenant_id = $4
   AND id = $5
   AND status = 'CLAIMED'
   AND row_version = $6
`

type CompleteWorkItemParams struct {
	OutcomeCode *string
	CompletedBy uuid.NullUUID
	ActorID     uuid.NullUUID
	TenantID    uuid.UUID
	ID          uuid.UUID
	RowVersion  int64
}

func (q *Queries) CompleteWorkItem(ctx context.Context, arg CompleteWorkItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeWorkItem,
		arg.OutcomeCode,
		arg.CompletedBy,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countWorkItemStatusEvents = `-- name: CountWorkItemStatusEvents :one
SELECT count(*)
  FROM workflow.status_event
 WHERE tenant_id = $1
   AND aggregate_type = 'WORK_ITEM'
   AND aggregate_id = $2
   AND transition_code = $3
`

type CountWorkItemStatusEventsParams struct {
	TenantID       uuid.UUID
	AggregateID    uuid.UUID
	TransitionCode string
}

// How many times one transition has been recorded for one item. The escalation test asks
// this: running the job twice must leave one event, not two.
func (q *Queries) CountWorkItemStatusEvents(ctx context.Context, arg CountWorkItemStatusEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkItemStatusEvents, arg.TenantID, arg.AggregateID, arg.TransitionCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovalPolicy = `-- name: CreateApprovalPolicy :one
INSERT INTO workflow.approval_policy (
    tenant_id, action_code, scope_code, version_no, min_amount, max_amount,
    required_role_codes, required_approver_count, valid_from, valid_to,
    created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5::text::numeric,
        $6::text::numeric, $7,
        $8, $9, $10,
        $11, $11)
RETURNING id, COALESCE(min_amount::text, '')::text AS min_amount,
          COALESCE(max_amount::text, '')::text AS max_amount, created_at, row_version
`

type CreateApprovalPolicyParams struct {
	TenantID              uuid.UUID
	ActionCode            string
	ScopeCode             string
	VersionNo             int32
	MinAmount             *string
	MaxAmount             *string
	RequiredRoleCodes     []string
	RequiredApproverCount int32
	ValidFrom             pgtype.Date
	ValidTo               pgtype.Date
	ActorID               uuid.NullUUID
}

type CreateApprovalPolicyRow struct {
	ID         uuid.UUID
	MinAmount  string
	MaxAmount  string
	CreatedAt  time.Time
	RowVersion int64
}

// The amounts come back as the column holds them, not as the caller sent them: the write
// and the read of one policy must not disagree about how "1000.500000" is written.
func (q *Queries) CreateApprovalPolicy(ctx context.Context, arg CreateApprovalPolicyParams) (CreateApprovalPolicyRow, error) {
	row := q.db.QueryRow(ctx, createApprovalPolicy,
		arg.TenantID,
		arg.ActionCode,
		arg.ScopeCode,
		arg.VersionNo,
		arg.MinAmount,
		arg.MaxAmount,
		arg.RequiredRoleCodes,
		arg.RequiredApproverCount,
		arg.ValidFrom,
		arg.ValidTo,
		arg.ActorID,
	)
	var i CreateApprovalPolicyRow
	err := row.Scan(
		&i.ID,
		&i.MinAmount,
		&i.MaxAmount,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO workflow.comment (
    tenant_id, aggregate_type, aggregate_id, work_item_id, visibility, body, author_actor_id)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7)
RETURNING id, created_at
`

type CreateCommentParams struct {
	TenantID      uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	WorkItemID    uuid.NullUUID
	Visibility    string
	Body          string
	AuthorActorID uuid.NullUUID
}

type CreateCommentRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.TenantID,
		arg.AggregateType,
		arg.AggregateID,
		arg.WorkItemID,
		arg.Visibility,
		arg.Body,
		arg.AuthorActorID,
	)
	var i CreateCommentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createWorkItem = `-- name: CreateWorkItem :one
INSERT INTO workflow.work_item (
    tenant_id, queue_id, aggregate_type, aggregate_id, title, priority,
    created_at, sla_minutes_snapshot, due_at, created_by, updated_by)
SELECT $1, q.id, $2, $3,
       $4, $5, now(), q.sla_minutes,
       CASE WHEN q.sla_minutes IS NULL THEN NULL
            ELSE now() + make_interval(mins => q.sla_minutes) END,
       $6, $6
  FROM workflow.work_queue q
 WHERE q.tenant_id = $1
   AND q.id = $7
   AND q.active
RETURNING id, queue_id, status, priority, sla_minutes_snapshot, due_at, created_at, row_version
`

type CreateWorkItemParams struct {
	TenantID      uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	Title         string
	Priority      int32
	ActorID       uuid.NullUUID
	QueueID       uuid.UUID
}

type CreateWorkItemRow struct {
	ID                 uuid.UUID
	QueueID            uuid.UUID
	Status             string
	Priority           int32
	SlaMinutesSnapshot *int32
	DueAt              *time.Time
	CreatedAt          time.Time
	RowVersion         int64
}

// The SLA is copied from the queue here and nowhere else. Both the snapshot and the due
// date are taken from one `now()`, the transaction's own timestamp, so an item's clock
// starts exactly when the item does; retuning the queue afterwards moves neither.
func (q *Queries) CreateWorkItem(ctx context.Context, arg CreateWorkItemParams) (CreateWorkItemRow, error) {
	row := q.db.QueryRow(ctx, createWorkItem,
		arg.TenantID,
		arg.AggregateType,
		arg.AggregateID,
		arg.Title,
		arg.Priority,
		arg.ActorID,
		arg.QueueID,
	)
	var i CreateWorkItemRow
	err := row.Scan(
		&i.ID,
		&i.QueueID,
		&i.Status,
		&i.Priority,
		&i.SlaMinutesSnapshot,
		&i.DueAt,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const createWorkItemStatusEvent = `-- name: CreateWorkItemStatusEvent :exec
INSERT INTO workflow.status_event (
    tenant_id, aggregate_type, aggregate_id, from_status, to_status, transition_code,
    reason_code, reason_text, actor_id, metadata_json)
VALUES ($1, 'WORK_ITEM', $2,
        $3, $4, $5,
        $6, $7, $8,
        $9)
`

type CreateWorkItemStatusEventParams struct {
	TenantID       uuid.UUID
	AggregateID    uuid.UUID
	FromStatus     *string
	ToStatus       string
	TransitionCode string
	ReasonCode     *string
	ReasonText     *string
	ActorID        uuid.NullUUID
	MetadataJson   []byte
}

// Every claim, release, reassignment, completion and escalation leaves one row here.
// workflow.status_event is append-only (migration 000007): a history that could be edited
// is not a history.
func (q *Queries) CreateWorkItemStatusEvent(ctx context.Context, arg CreateWorkItemStatusEventParams) error {
	_, err := q.db.Exec(ctx, createWorkItemStatusEvent,
		arg.TenantID,
		arg.AggregateID,
		arg.FromStatus,
		arg.ToStatus,
		arg.TransitionCode,
		arg.ReasonCode,
		arg.ReasonText,
		arg.ActorID,
		arg.MetadataJson,
	)
	return err
}

const createWorkQueue = `-- name: CreateWorkQueue :one

INSERT INTO workflow.work_queue (
    tenant_id, code, name, domain_code, assignment_policy, sla_minutes,
    escalation_queue_id, active, created_by, updated_by)
VALUES ($1, $2, $3, $4,
        $5, $6,
        $7, $8, $9,
        $9)
RETURNING id, created_at, row_version
`

type CreateWorkQueueParams struct {
	TenantID          uuid.UUID
	Code              string
	Name              string
	DomainCode        string
	AssignmentPolicy  string
	SlaMinutes        *int32
	EscalationQueueID uuid.NullUUID
	Active            bool
	ActorID           uuid.NullUUID
}

type CreateWorkQueueRow struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	RowVersion int64
}

// Work queue, work item, comment and approval policy queries (WP-I4-03, v1.2 9.10, 11.8).
//
// Four properties shape this file.
//
// The boundary is the same shape the authorization and service request queries apply,
// over this package's own resource: `scope_ids` is a nullable uuid[] of work queue ids,
// NULL means the caller sees every queue of the tenant and a non-null array binds it to
// those queues (iam.access_grant.scope_type = 'WORK_QUEUE'). It is applied in every read
// including the single-row ones, so a caller outside it finds no row and is answered 404
// rather than 403 — that such an item exists at all is somebody else's business.
//
// Claiming is one UPDATE whose predicate carries the whole precondition: the item, the
// tenant, the status and the row_version the caller read. Zero rows affected is the only
// outcome a loser gets, and it can never be a partial write.
//
// `sla_minutes_snapshot` and `due_at` are written once, by CreateWorkItem, from the queue
// as it stands at that moment. No statement in this file recomputes either of them, and
// the escalation statements deliberately leave due_at alone: a late item stays late.
//
// Amounts are read as `::text` and written as `::text::numeric`, so an exact decimal never
// passes through a float in either direction (handbook section 3).
func (q *Queries) CreateWorkQueue(ctx context.Context, arg CreateWorkQueueParams) (CreateWorkQueueRow, error) {
	row := q.db.QueryRow(ctx, createWorkQueue,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.DomainCode,
		arg.AssignmentPolicy,
		arg.SlaMinutes,
		arg.EscalationQueueID,
		arg.Active,
		arg.ActorID,
	)
	var i CreateWorkQueueRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.RowVersion)
	return i, err
}

const deleteApprovalPolicies = `-- name: DeleteApprovalPolicies :execrows
DELETE FROM workflow.approval_policy
 WHERE tenant_id = $1
   AND action_code = $2
`

type DeleteApprovalPoliciesParams struct {
	TenantID   uuid.UUID
	ActionCode string
}

func (q *Queries) DeleteApprovalPolicies(ctx context.Context, arg DeleteApprovalPoliciesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApprovalPolicies, arg.TenantID, arg.ActionCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const escalateWorkItemToQueue = `-- name: EscalateWorkItemToQueue :execrows
UPDATE workflow.work_item
   SET queue_id                = $1,
       escalated_at            = $2,
       escalated_from_queue_id = $3
 WHERE tenant_id = $4
   AND id = $5
   AND escalated_at IS NULL
`

type EscalateWorkItemToQueueParams struct {
	QueueID              uuid.UUID
	EscalatedAt          *time.Time
	EscalatedFromQueueID uuid.NullUUID
	TenantID             uuid.UUID
	ID                   uuid.UUID
}

// The item moves to the escalation queue and keeps everything else it had: the same
// status, the same owner if it had one, and the same due_at. It is late, and moving it
// does not make it less late.
func (q *Queries) EscalateWorkItemToQueue(ctx context.Context, arg EscalateWorkItemToQueueParams) (int64, error) {
	result, err := q.db.Exec(ctx, escalateWorkItemToQueue,
		arg.QueueID,
		arg.EscalatedAt,
		arg.EscalatedFromQueueID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkItem = `-- name: GetWorkItem :one
SELECT i.id, i.queue_id, i.aggregate_type, i.aggregate_id, i.title, i.priority,
       i.assignee_actor_id, i.assigned_at, i.due_at, i.sla_minutes_snapshot, i.status,
       i.outcome_code, i.completed_at, i.completed_by, i.escalated_at,
       i.escalated_from_queue_id, i.created_at, i.row_version
  FROM workflow.work_item i
 WHERE i.tenant_id = $1
   AND i.id = $2
   AND ($3::uuid[] IS NULL OR i.queue_id = ANY($3::uuid[]))
`

type GetWorkItemParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type GetWorkItemRow struct {
	ID                   uuid.UUID
	QueueID              uuid.UUID
	AggregateType        string
	AggregateID          uuid.UUID
	Title                string
	Priority             int32
	AssigneeActorID      uuid.NullUUID
	AssignedAt           *time.Time
	DueAt                *time.Time
	SlaMinutesSnapshot   *int32
	Status               string
	OutcomeCode          *string
	CompletedAt          *time.Time
	CompletedBy          uuid.NullUUID
	EscalatedAt          *time.Time
	EscalatedFromQueueID uuid.NullUUID
	CreatedAt            time.Time
	RowVersion           int64
}

func (q *Queries) GetWorkItem(ctx context.Context, arg GetWorkItemParams) (GetWorkItemRow, error) {
	row := q.db.QueryRow(ctx, getWorkItem, arg.TenantID, arg.ID, arg.ScopeIds)
	var i GetWorkItemRow
	err := row.Scan(
		&i.ID,
		&i.QueueID,
		&i.AggregateType,
		&i.AggregateID,
		&i.Title,
		&i.Priority,
		&i.AssigneeActorID,
		&i.AssignedAt,
		&i.DueAt,
		&i.SlaMinutesSnapshot,
		&i.Status,
		&i.OutcomeCode,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.EscalatedAt,
		&i.EscalatedFromQueueID,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getWorkQueue = `-- name: GetWorkQueue :one
SELECT q.id, q.code, q.name, q.domain_code, q.assignment_policy, q.sla_minutes,
       q.escalation_queue_id, q.active, q.created_at, q.row_version
  FROM workflow.work_queue q
 WHERE q.tenant_id = $1
   AND q.id = $2
   AND ($3::uuid[] IS NULL OR q.id = ANY($3::uuid[]))
`

type GetWorkQueueParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ScopeIds []uuid.UUID
}

type GetWorkQueueRow struct {
	ID                uuid.UUID
	Code              string
	Name              string
	DomainCode        string
	AssignmentPolicy  string
	SlaMinutes        *int32
	EscalationQueueID uuid.NullUUID
	Active            bool
	CreatedAt         time.Time
	RowVersion        int64
}

func (q *Queries) GetWorkQueue(ctx context.Context, arg GetWorkQueueParams) (GetWorkQueueRow, error) {
	row := q.db.QueryRow(ctx, getWorkQueue, arg.TenantID, arg.ID, arg.ScopeIds)
	var i GetWorkQueueRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DomainCode,
		&i.AssignmentPolicy,
		&i.SlaMinutes,
		&i.EscalationQueueID,
		&i.Active,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const listApprovalPolicies = `-- name: ListApprovalPolicies :many
SELECT p.id, p.action_code, p.scope_code, p.version_no,
       -- An open band edge is NULL in the column and the empty string on the way out, so
       -- the mapping can tell "no limit" from a limit of zero without a second column.
       COALESCE(p.min_amount::text, '')::text AS min_amount,
       COALESCE(p.max_amount::text, '')::text AS max_amount,
       p.required_role_codes, p.required_approver_count, p.valid_from, p.valid_to,
       p.created_at, p.row_version
  FROM workflow.approval_policy p
 WHERE p.tenant_id = $1
   AND ($2::text IS NULL OR p.action_code = $2::text)
   AND ($3::text IS NULL OR p.scope_code = $3::text)
 ORDER BY p.action_code, p.scope_code, p.valid_from
`

type ListApprovalPoliciesParams struct {
	TenantID   uuid.UUID
	ActionCode *string
	ScopeCode  *string
}

type ListApprovalPoliciesRow struct {
	ID                    uuid.UUID
	ActionCode            string
	ScopeCode             string
	VersionNo             int32
	MinAmount             string
	MaxAmount             string
	RequiredRoleCodes     []string
	RequiredApproverCount int32
	ValidFrom             pgtype.Date
	ValidTo               pgtype.Date
	CreatedAt             time.Time
	RowVersion            int64
}

func (q *Queries) ListApprovalPolicies(ctx context.Context, arg ListApprovalPoliciesParams) ([]ListApprovalPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listApprovalPolicies, arg.TenantID, arg.ActionCode, arg.ScopeCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovalPoliciesRow
	for rows.Next() {
		var i ListApprovalPoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionCode,
			&i.ScopeCode,
			&i.VersionNo,
			&i.MinAmount,
			&i.MaxAmount,
			&i.RequiredRoleCodes,
			&i.RequiredApproverCount,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEscalatableWorkItems = `-- name: ListEscalatableWorkItems :many
SELECT i.id, i.queue_id, i.status, q.escalation_queue_id
  FROM workflow.work_item i
  JOIN workflow.work_queue q ON q.tenant_id = i.tenant_id AND q.id = i.queue_id
 WHERE i.tenant_id = $1
   AND i.status IN ('OPEN','CLAIMED')
   AND i.escalated_at IS NULL
   AND i.due_at IS NOT NULL
   AND i.due_at < $2
 ORDER BY i.due_at, i.id
 LIMIT $3
   FOR UPDATE OF i SKIP LOCKED
`

type ListEscalatableWorkItemsParams struct {
	TenantID uuid.UUID
	AsOf     *time.Time
	PageSize int32
}

type ListEscalatableWorkItemsRow struct {
	ID                uuid.UUID
	QueueID           uuid.UUID
	Status            string
	EscalationQueueID uuid.NullUUID
}

// The overdue items the escalation job may still act on, with the target their queue
// names, taken FOR UPDATE SKIP LOCKED so two schedulers that both believe they lead never
// escalate the same row twice. `escalated_at IS NULL` is what makes a second pass a no-op:
// moving an item does not change its status and leaves it overdue in its new queue, so
// without the marker it would be moved again on every run.
func (q *Queries) ListEscalatableWorkItems(ctx context.Context, arg ListEscalatableWorkItemsParams) ([]ListEscalatableWorkItemsRow, error) {
	rows, err := q.db.Query(ctx, listEscalatableWorkItems, arg.TenantID, arg.AsOf, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEscalatableWorkItemsRow
	for rows.Next() {
		var i ListEscalatableWorkItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.QueueID,
			&i.Status,
			&i.EscalationQueueID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItemComments = `-- name: ListWorkItemComments :many
SELECT c.id, c.aggregate_type, c.aggregate_id, c.work_item_id, c.visibility, c.body,
       c.author_actor_id, c.created_at
  FROM workflow.comment c
  JOIN workflow.work_item i ON i.tenant_id = c.tenant_id AND i.id = c.work_item_id
 WHERE c.tenant_id = $1
   AND c.work_item_id = $2
   AND ($3::uuid[] IS NULL OR i.queue_id = ANY($3::uuid[]))
   AND ($4::text[] IS NULL
        OR c.visibility = ANY($4::text[]))
 ORDER BY c.created_at, c.id
 LIMIT $5
`

type ListWorkItemCommentsParams struct {
	TenantID     uuid.UUID
	WorkItemID   uuid.NullUUID
	ScopeIds     []uuid.UUID
	Visibilities []string
	PageSize     int32
}

type ListWorkItemCommentsRow struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	WorkItemID    uuid.NullUUID
	Visibility    string
	Body          string
	AuthorActorID uuid.NullUUID
	CreatedAt     time.Time
}

// The comments of one item, oldest first: a conversation read in the order it happened.
func (q *Queries) ListWorkItemComments(ctx context.Context, arg ListWorkItemCommentsParams) ([]ListWorkItemCommentsRow, error) {
	rows, err := q.db.Query(ctx, listWorkItemComments,
		arg.TenantID,
		arg.WorkItemID,
		arg.ScopeIds,
		arg.Visibilities,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkItemCommentsRow
	for rows.Next() {
		var i ListWorkItemCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.WorkItemID,
			&i.Visibility,
			&i.Body,
			&i.AuthorActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItems = `-- name: ListWorkItems :many
SELECT i.id, i.queue_id, i.aggregate_type, i.aggregate_id, i.title, i.priority,
       i.assignee_actor_id, i.assigned_at, i.due_at, i.sla_minutes_snapshot, i.status,
       i.outcome_code, i.completed_at, i.completed_by, i.escalated_at,
       i.escalated_from_queue_id, i.created_at, i.row_version
  FROM workflow.work_item i
 WHERE i.tenant_id = $1
   AND ($2::uuid[] IS NULL OR i.queue_id = ANY($2::uuid[]))
   AND ($3::uuid IS NULL OR i.queue_id = $3::uuid)
   AND ($4::text IS NULL OR i.status = $4::text)
   AND ($5::uuid IS NULL
        OR i.assignee_actor_id = $5::uuid)
   AND ($6::text IS NULL
        OR i.aggregate_type = $6::text)
   AND ($7::uuid IS NULL OR i.aggregate_id = $7::uuid)
   AND ($8::boolean IS NULL
        OR ($8::boolean
            AND i.due_at IS NOT NULL AND i.due_at < $9)
        OR (NOT $8::boolean
            AND (i.due_at IS NULL OR i.due_at >= $9)))
   AND ($10::timestamptz IS NULL
        OR (i.created_at, i.id) < ($10::timestamptz, $11::uuid))
 ORDER BY i.created_at DESC, i.id DESC
 LIMIT $12
`

type ListWorkItemsParams struct {
	TenantID        uuid.UUID
	ScopeIds        []uuid.UUID
	QueueID         uuid.NullUUID
	Status          *string
	AssigneeActorID uuid.NullUUID
	AggregateType   *string
	AggregateID     uuid.NullUUID
	Overdue         *bool
	AsOf            *time.Time
	CursorCreatedAt *time.Time
	CursorID        uuid.NullUUID
	PageSize        int32
}

type ListWorkItemsRow struct {
	ID                   uuid.UUID
	QueueID              uuid.UUID
	AggregateType        string
	AggregateID          uuid.UUID
	Title                string
	Priority             int32
	AssigneeActorID      uuid.NullUUID
	AssignedAt           *time.Time
	DueAt                *time.Time
	SlaMinutesSnapshot   *int32
	Status               string
	OutcomeCode          *string
	CompletedAt          *time.Time
	CompletedBy          uuid.NullUUID
	EscalatedAt          *time.Time
	EscalatedFromQueueID uuid.NullUUID
	CreatedAt            time.Time
	RowVersion           int64
}

// `assigned_to_me` and `overdue` are the two questions the morning list is: what is mine,
// and what is late. `overdue` is answered from the item's own due_at, never from the
// queue's SLA, so an item is late by the clock it was given.
func (q *Queries) ListWorkItems(ctx context.Context, arg ListWorkItemsParams) ([]ListWorkItemsRow, error) {
	rows, err := q.db.Query(ctx, listWorkItems,
		arg.TenantID,
		arg.ScopeIds,
		arg.QueueID,
		arg.Status,
		arg.AssigneeActorID,
		arg.AggregateType,
		arg.AggregateID,
		arg.Overdue,
		arg.AsOf,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkItemsRow
	for rows.Next() {
		var i ListWorkItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.QueueID,
			&i.AggregateType,
			&i.AggregateID,
			&i.Title,
			&i.Priority,
			&i.AssigneeActorID,
			&i.AssignedAt,
			&i.DueAt,
			&i.SlaMinutesSnapshot,
			&i.Status,
			&i.OutcomeCode,
			&i.CompletedAt,
			&i.CompletedBy,
			&i.EscalatedAt,
			&i.EscalatedFromQueueID,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkQueues = `-- name: ListWorkQueues :many
SELECT q.id, q.code, q.name, q.domain_code, q.assignment_policy, q.sla_minutes,
       q.escalation_queue_id, q.active, q.created_at, q.row_version
  FROM workflow.work_queue q
 WHERE q.tenant_id = $1
   AND ($2::uuid[] IS NULL OR q.id = ANY($2::uuid[]))
   AND ($3::text IS NULL OR q.domain_code = $3::text)
   AND ($4::boolean IS NULL OR q.active = $4::boolean)
   AND ($5::timestamptz IS NULL
        OR (q.created_at, q.id) < ($5::timestamptz, $6::uuid))
 ORDER BY q.created_at DESC, q.id DESC
 LIMIT $7
`

type ListWorkQueuesParams struct {
	TenantID        uuid.UUID
	ScopeIds        []uuid.UUID
	DomainCode      *string
	Active          *bool
	CursorCreatedAt *time.Time
	CursorID        uuid.NullUUID
	PageSize        int32
}

type ListWorkQueuesRow struct {
	ID                uuid.UUID
	Code              string
	Name              string
	DomainCode        string
	AssignmentPolicy  string
	SlaMinutes        *int32
	EscalationQueueID uuid.NullUUID
	Active            bool
	CreatedAt         time.Time
	RowVersion        int64
}

// Keyset pagination on (created_at DESC, id DESC); the caller asks for limit+1 rows to
// learn whether a next page exists.
func (q *Queries) ListWorkQueues(ctx context.Context, arg ListWorkQueuesParams) ([]ListWorkQueuesRow, error) {
	rows, err := q.db.Query(ctx, listWorkQueues,
		arg.TenantID,
		arg.ScopeIds,
		arg.DomainCode,
		arg.Active,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkQueuesRow
	for rows.Next() {
		var i ListWorkQueuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.DomainCode,
			&i.AssignmentPolicy,
			&i.SlaMinutes,
			&i.EscalationQueueID,
			&i.Active,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkItemEscalated = `-- name: MarkWorkItemEscalated :execrows
UPDATE workflow.work_item
   SET status       = 'ESCALATED',
       escalated_at = $1
 WHERE tenant_id = $2
   AND id = $3
   AND escalated_at IS NULL
`

type MarkWorkItemEscalatedParams struct {
	EscalatedAt *time.Time
	TenantID    uuid.UUID
	ID          uuid.UUID
}

// The queue has nowhere to escalate to, so the item is marked instead of moved. The owner
// is left exactly as it was: somebody holding late work still holds it.
func (q *Queries) MarkWorkItemEscalated(ctx context.Context, arg MarkWorkItemEscalatedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkItemEscalated, arg.EscalatedAt, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const maxApprovalPolicyVersion = `-- name: MaxApprovalPolicyVersion :one
SELECT coalesce(max(version_no), 0)::int AS version_no
  FROM workflow.approval_policy
 WHERE tenant_id = $1
   AND action_code = $2
`

type MaxApprovalPolicyVersionParams struct {
	TenantID   uuid.UUID
	ActionCode string
}

// The version the next written set gets. It survives the delete below because it is read
// first: replacing a set is an edit of the same policy, and the number says how many
// edits it has had.
func (q *Queries) MaxApprovalPolicyVersion(ctx context.Context, arg MaxApprovalPolicyVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxApprovalPolicyVersion, arg.TenantID, arg.ActionCode)
	var version_no int32
	err := row.Scan(&version_no)
	return version_no, err
}

const reassignWorkItem = `-- name: ReassignWorkItem :execrows
UPDATE workflow.work_item
   SET status            = 'CLAIMED',
       assignee_actor_id = $1,
       assigned_at       = now(),
       updated_by        = $2
 WHERE tenant_id = $3
   AND id = $4
   AND status IN ('OPEN','CLAIMED')
   AND row_version = $5
`

type ReassignWorkItemParams struct {
	AssigneeActorID uuid.NullUUID
	ActorID         uuid.NullUUID
	TenantID        uuid.UUID
	ID              uuid.UUID
	RowVersion      int64
}

// Reassignment reaches an OPEN item as well as a CLAIMED one: giving unclaimed work to a
// named person is the same act as taking it off somebody else.
func (q *Queries) ReassignWorkItem(ctx context.Context, arg ReassignWorkItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, reassignWorkItem,
		arg.AssigneeActorID,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseWorkItem = `-- name: ReleaseWorkItem :execrows
UPDATE workflow.work_item
   SET status            = 'OPEN',
       assignee_actor_id = NULL,
       assigned_at       = NULL,
       updated_by        = $1
 WHERE tenant_id = $2
   AND id = $3
   AND status = 'CLAIMED'
   AND row_version = $4
`

type ReleaseWorkItemParams struct {
	ActorID    uuid.NullUUID
	TenantID   uuid.UUID
	ID         uuid.UUID
	RowVersion int64
}

// Back to the queue, owner cleared. due_at is untouched: putting work down does not buy
// more time to do it.
func (q *Queries) ReleaseWorkItem(ctx context.Context, arg ReleaseWorkItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseWorkItem,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveApprovalPolicy = `-- name: ResolveApprovalPolicy :one
SELECT p.id, p.action_code, p.scope_code, p.version_no,
       -- An open band edge is NULL in the column and the empty string on the way out, so
       -- the mapping can tell "no limit" from a limit of zero without a second column.
       COALESCE(p.min_amount::text, '')::text AS min_amount,
       COALESCE(p.max_amount::text, '')::text AS max_amount,
       p.required_role_codes, p.required_approver_count, p.valid_from, p.valid_to,
       p.created_at, p.row_version
  FROM workflow.approval_policy p
 WHERE p.tenant_id = $1
   AND p.action_code = $2
   AND ($3::text IS NULL OR p.scope_code = $3::text)
   AND daterange(p.valid_from, p.valid_to, '[)') @> $4::date
   AND (p.min_amount IS NULL OR p.min_amount <= $5::text::numeric)
   AND (p.max_amount IS NULL OR p.max_amount >= $5::text::numeric)
 ORDER BY p.min_amount DESC NULLS LAST, p.max_amount ASC NULLS LAST, p.scope_code
 LIMIT 1
`

type ResolveApprovalPolicyParams struct {
	TenantID   uuid.UUID
	ActionCode string
	ScopeCode  *string
	AsOf       pgtype.Date
	Amount     string
}

type ResolveApprovalPolicyRow struct {
	ID                    uuid.UUID
	ActionCode            string
	ScopeCode             string
	VersionNo             int32
	MinAmount             string
	MaxAmount             string
	RequiredRoleCodes     []string
	RequiredApproverCount int32
	ValidFrom             pgtype.Date
	ValidTo               pgtype.Date
	CreatedAt             time.Time
	RowVersion            int64
}

// Which roles may approve this action for this amount on this day, and how many of them.
// The exclusion constraint already guarantees one policy per (action, scope) per day, so
// the ordering only decides between scopes: the narrowest band that contains the amount
// wins, which is what makes a high-value scope override a general one.
func (q *Queries) ResolveApprovalPolicy(ctx context.Context, arg ResolveApprovalPolicyParams) (ResolveApprovalPolicyRow, error) {
	row := q.db.QueryRow(ctx, resolveApprovalPolicy,
		arg.TenantID,
		arg.ActionCode,
		arg.ScopeCode,
		arg.AsOf,
		arg.Amount,
	)
	var i ResolveApprovalPolicyRow
	err := row.Scan(
		&i.ID,
		&i.ActionCode,
		&i.ScopeCode,
		&i.VersionNo,
		&i.MinAmount,
		&i.MaxAmount,
		&i.RequiredRoleCodes,
		&i.RequiredApproverCount,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const updateWorkQueue = `-- name: UpdateWorkQueue :execrows
UPDATE workflow.work_queue
   SET name                = $1,
       assignment_policy   = $2,
       sla_minutes         = $3,
       escalation_queue_id = $4,
       active              = $5,
       updated_by          = $6
 WHERE tenant_id = $7
   AND id = $8
   AND row_version = $9
`

type UpdateWorkQueueParams struct {
	Name              string
	AssignmentPolicy  string
	SlaMinutes        *int32
	EscalationQueueID uuid.NullUUID
	Active            bool
	ActorID           uuid.NullUUID
	TenantID          uuid.UUID
	ID                uuid.UUID
	RowVersion        int64
}

// The expected row_version is part of the predicate, so a stale If-Match updates nothing.
// The touch trigger moves the version and updated_at; `code` and `domain_code` are absent
// because they are what other rows already point at by name.
func (q *Queries) UpdateWorkQueue(ctx context.Context, arg UpdateWorkQueueParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWorkQueue,
		arg.Name,
		arg.AssignmentPolicy,
		arg.SlaMinutes,
		arg.EscalationQueueID,
		arg.Active,
		arg.ActorID,
		arg.TenantID,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
