/**
 * Which page help each route shows, in the router's own spelling. The key names the page
 * under `help:pages.backoffice`; `help.test.ts` fails when a page in this table has no
 * help written.
 */
export const HELP_ROUTES: Readonly<Record<string, string>> = {
  '/': 'home',
  '/people': 'people',
  '/people/new': 'personNew',
  '/people/$personId': 'person',
  '/programs': 'programs',
  '/programs/new': 'programNew',
  '/programs/$programId': 'program',
  '/plans/$planId': 'plan',
  '/plan-versions/$planVersionId': 'planVersion',
  '/entitlement-adjustments': 'adjustments',
  '/imports': 'imports',
  '/imports/new': 'importNew',
  '/imports/$importId': 'import',
  '/catalog/categories': 'catalogCategories',
  '/catalog/definitions': 'catalogDefinitions',
  '/catalog/definitions/new': 'catalogDefinitionNew',
  '/catalog/definitions/$definitionId': 'catalogDefinition',
  '/catalog/code-systems': 'codeSystems',
  '/catalog/code-systems/$codeSystemId': 'codeSystem',
  '/contracts': 'contracts',
  '/contracts/new': 'contractNew',
  '/contracts/$contractId': 'contract',
  '/contract-versions/$contractVersionId': 'contractVersion',
  '/rule-sets': 'ruleSets',
  '/rule-sets/$ruleSetId': 'ruleSet',
  '/rule-set-versions/$ruleSetVersionId': 'ruleSetVersion',
  '/pricing': 'pricing',
  '/providers': 'providers',
  '/providers/new': 'providerNew',
  '/providers/$providerId': 'provider',
  '/organizations': 'organizations',
  '/organizations/new': 'organizationNew',
  '/organizations/$organizationId': 'organization',
  '/organizations/$organizationId/edit': 'organizationEdit',
  '/requests': 'requests',
  '/requests/new': 'requestNew',
  '/requests/$requestId': 'request',
  '/worklist': 'worklist',
  '/claims': 'claims',
  '/claims/$claimId': 'claim',
  '/medical-reports': 'medicalReports',
  '/medical-reports/$reportId': 'medicalReport',
  '/lodging/properties': 'properties',
  '/lodging/properties/$propertyId': 'property',
  '/lodging/bookings': 'bookings',
  '/lodging/bookings/$bookingId': 'booking',
  '/lodging/waitlist': 'waitlist',
  '/billing/batches': 'batches',
  '/billing/batches/$batchId': 'batch',
  '/billing/settlements': 'settlements',
  '/billing/settlements/$settlementId': 'settlement',
  '/billing/reimbursements': 'reimbursements',
  '/billing/reimbursements/$reimbursementId': 'reimbursement',
  '/billing/reconciliation': 'reconciliation',
  '/billing/reconciliation/$runId': 'reconciliationRun',
  '/billing/exports': 'exports',
  '/notifications': 'notifications',
  '/profile': 'profile',
};
