<#
.SYNOPSIS
  Downloads the pinned native dependencies (MinIO, mc, Mailpit, ClamAV) into tools/ and
  verifies every file against scripts/native/versions.json. Checks PostgreSQL 18 and Go.
.NOTES
  No admin rights needed. Nothing is installed system-wide. Re-running is a no-op for
  files that already match their checksum. PostgreSQL is not installed by this script.
#>
[CmdletBinding()]
param(
    [switch]$Force
)

. "$PSScriptRoot\_common.ps1"

$versions = Get-VersionManifest
Initialize-Directory $ToolsDir
Initialize-Directory $BinDir
Initialize-Directory $DownloadDir
Initialize-Directory $DataDir
Initialize-Directory $RunDir

# TLS 1.2 for older Windows PowerShell hosts.
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

function Get-VerifiedDownload([string]$Name, $Spec) {
    $file = Join-Path $DownloadDir ($Spec.url.Split('/')[-1])
    if ((Test-Path $file) -and -not $Force) {
        if ((Get-Sha256 $file) -eq $Spec.sha256) { Write-Ok "$Name download already verified"; return $file }
        Write-Warn "$Name download has a different checksum; downloading again"
    }
    Write-Step "downloading $Name $($Spec.url)"
    $tmp = "$file.part"
    Invoke-WebRequest -Uri $Spec.url -OutFile $tmp -UseBasicParsing
    $actual = Get-Sha256 $tmp
    if ($actual -ne $Spec.sha256) {
        Remove-Item $tmp -Force
        throw "$Name checksum mismatch: expected $($Spec.sha256), got $actual. Refusing to install."
    }
    Move-Item $tmp $file -Force
    Write-Ok "$Name checksum verified"
    return $file
}

function Install-Binary([string]$Name, $Spec) {
    $file = Get-VerifiedDownload $Name $Spec
    $target = Join-Path $ToolsDir $Spec.target
    Copy-Item $file $target -Force
    Write-Ok "$Name -> tools\$($Spec.target)"
}

function Install-ZipMember([string]$Name, $Spec) {
    $file = Get-VerifiedDownload $Name $Spec
    $target = Join-Path $ToolsDir $Spec.target
    $stage = Join-Path $DownloadDir "$Name-extract"
    if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
    Expand-Archive -Path $file -DestinationPath $stage -Force
    $member = Get-ChildItem -Path $stage -Recurse -Filter $Spec.member | Select-Object -First 1
    if ($null -eq $member) { throw "$Name archive does not contain $($Spec.member)" }
    Copy-Item $member.FullName $target -Force
    Remove-Item $stage -Recurse -Force
    Write-Ok "$Name -> tools\$($Spec.target)"
}

function Install-ZipTree([string]$Name, $Spec) {
    $file = Get-VerifiedDownload $Name $Spec
    $target = Join-Path $ToolsDir $Spec.target
    $marker = Join-Path $target '.installed-sha256'
    if ((Test-Path $marker) -and -not $Force -and ((Get-Content $marker -Raw).Trim() -eq $Spec.sha256)) {
        Write-Ok "$Name already extracted"
        return
    }
    if (Test-Path $target) { Remove-Item $target -Recurse -Force }
    Write-Step "extracting $Name (this one is large)"
    Expand-Archive -Path $file -DestinationPath $target -Force
    Set-Content -Path $marker -Value $Spec.sha256 -Encoding ascii
    Write-Ok "$Name -> tools\$($Spec.target)"
}

Write-Step "checking prerequisites"
$go = Get-Command go -ErrorAction SilentlyContinue
if ($null -eq $go) { Write-Warn "Go not found on PATH (needed to build and run KAPSORA): https://go.dev/dl/" } else { Write-Ok ((& go version) -join '') }

$pg = Get-Command psql -ErrorAction SilentlyContinue
$pgPath = $null
if ($null -ne $pg) { $pgPath = $pg.Source } elseif (Test-Path 'C:\Program Files\PostgreSQL\18\bin\psql.exe') { $pgPath = 'C:\Program Files\PostgreSQL\18\bin\psql.exe' }
if ($null -eq $pgPath) {
    Write-Warn "PostgreSQL $($versions.postgresql.version) not found. Install it from https://www.postgresql.org/download/windows/ (service postgresql-x64-18, port 5432) and re-run."
} else {
    $pgVersion = (& $pgPath --version) -join ''
    if ($pgVersion -match 'PostgreSQL\) (\d+)' -and [int]$matches[1] -ge [int]$versions.postgresql.version) {
        Write-Ok $pgVersion
    } else {
        Write-Warn "$pgVersion found; KAPSORA needs major version $($versions.postgresql.version)"
    }
}

Install-Binary 'minio' $versions.minio.'windows-amd64'
Install-Binary 'mc' $versions.mc.'windows-amd64'
Install-ZipMember 'mailpit' $versions.mailpit.'windows-amd64'
Install-ZipTree 'clamav' $versions.clamav.'windows-amd64'

# ClamAV configuration files from the shipped samples, pointing at tools/data.
$clamd = Get-ChildItem -Path $ClamDir -Recurse -Filter 'clamd.exe' | Select-Object -First 1
if ($null -eq $clamd) { throw "clamd.exe not found under tools\clamav" }
$clamHome = $clamd.DirectoryName
$clamDb = Join-Path $DataDir 'clamav-db'
Initialize-Directory $clamDb
$clamConf = Join-Path $ClamDir 'clamd.conf'
$freshConf = Join-Path $ClamDir 'freshclam.conf'
if (-not (Test-Path $clamConf) -or $Force) {
    @(
        "# Generated by scripts/native/install.ps1 for local development only."
        "DatabaseDirectory $clamDb"
        "LogFile $(Join-Path $RunDir 'clamd.log')"
        "LogTime yes"
        "TCPSocket 3310"
        "TCPAddr 127.0.0.1"
        "MaxThreads 4"
        "StreamMaxLength 100M"
        "MaxFileSize 100M"
        "MaxScanSize 200M"
        "SelfCheck 3600"
    ) | Set-Content -Path $clamConf -Encoding ascii
    Write-Ok "wrote tools\clamav\clamd.conf"
}
if (-not (Test-Path $freshConf) -or $Force) {
    @(
        "# Generated by scripts/native/install.ps1 for local development only."
        "DatabaseDirectory $clamDb"
        "UpdateLogFile $(Join-Path $RunDir 'freshclam.log')"
        "DatabaseMirror database.clamav.net"
        "Checks 12"
    ) | Set-Content -Path $freshConf -Encoding ascii
    Write-Ok "wrote tools\clamav\freshclam.conf"
}
Set-Content -Path (Join-Path $ClamDir 'home.txt') -Value $clamHome -Encoding ascii

Write-Step "done"
Write-Host "Next: copy .env.example to .env (fill CHANGE_ME values), then .\scripts\native\up.ps1"
