-- Authorization, fulfilment and voucher queries (WP-I4-02, v1.2 9.11, 11.4, 16.7).
--
-- Three properties shape this file.
--
-- The provider boundary is the same one the service request queries apply: `scope_ids` is
-- a nullable uuid[], NULL means the caller is tenant-wide and a non-null array binds it to
-- those organizations. An authorization has no provider column of its own, so the boundary
-- is read from the request it was granted against; it is applied in every read, including
-- the single-row ones, so a caller outside it finds no row and is answered 404 rather than
-- 403 — that such an authorization exists at all is somebody else's business.
--
-- Quantities and amounts are read as `::text` and written as `::text::numeric`, so an
-- exact decimal never passes through a float in either direction (handbook section 3).
--
-- Nothing here writes a balance. `reserved_total` and `consumed_total` are the
-- authorization's arithmetic over its own lines; the entitlement itself moves only through
-- benefit.entitlement_ledger, which has its own statements and its own account lock.

-- name: CreateAuthorization :one
-- The reference is generated by the caller and unique per tenant; a collision surfaces as
-- a unique violation and is retried with a new one. The idempotency key is unique too:
-- creating twice under one key must return the first authorization, not reserve again.
INSERT INTO service.authorization (
    tenant_id, request_id, authorization_reference, valid_from, valid_to,
    reserved_total, currency_code, price_quote_id, approved_by, approved_at,
    idempotency_key, created_by, updated_by)
VALUES (sqlc.arg('tenant_id'), sqlc.arg('request_id'), sqlc.arg('authorization_reference'),
        sqlc.arg('valid_from'), sqlc.arg('valid_to'),
        sqlc.arg('reserved_total')::text::numeric, sqlc.narg('currency_code'),
        sqlc.narg('price_quote_id'), sqlc.narg('actor_id'), sqlc.arg('approved_at'),
        sqlc.arg('idempotency_key'), sqlc.narg('actor_id'), sqlc.narg('actor_id'))
RETURNING id, authorization_reference, status, created_at, row_version;

-- name: GetAuthorization :one
SELECT a.id, a.request_id, a.authorization_reference, a.valid_from, a.valid_to, a.status,
       a.reserved_total::text AS reserved_total, a.consumed_total::text AS consumed_total,
       a.currency_code, a.price_quote_id, a.approved_by, a.approved_at,
       a.cancel_reason_code, a.created_at, a.row_version
  FROM service.authorization a
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE a.tenant_id = sqlc.arg('tenant_id')
   AND a.id = sqlc.arg('id')
   AND (sqlc.narg('scope_ids')::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY(sqlc.narg('scope_ids')::uuid[]));

-- name: LockAuthorization :one
-- The same read taken FOR UPDATE, so two commands on one authorization serialise instead
-- of racing each other into two different outcomes. Only the authorization row is locked:
-- the request it points at is read here, never written.
SELECT a.id, a.request_id, a.authorization_reference, a.valid_from, a.valid_to, a.status,
       a.reserved_total::text AS reserved_total, a.consumed_total::text AS consumed_total,
       a.currency_code, a.price_quote_id, a.approved_by, a.approved_at,
       a.cancel_reason_code, a.created_at, a.row_version
  FROM service.authorization a
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE a.tenant_id = sqlc.arg('tenant_id')
   AND a.id = sqlc.arg('id')
   AND (sqlc.narg('scope_ids')::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY(sqlc.narg('scope_ids')::uuid[]))
   FOR UPDATE OF a;

-- name: GetAuthorizationByIdempotencyKey :one
-- The replay path of createAuthorization. It ignores the provider boundary on purpose:
-- the key is the caller's own, so a row under it was written by this caller.
SELECT a.id, a.request_id, a.authorization_reference, a.valid_from, a.valid_to, a.status,
       a.reserved_total::text AS reserved_total, a.consumed_total::text AS consumed_total,
       a.currency_code, a.price_quote_id, a.approved_by, a.approved_at,
       a.cancel_reason_code, a.created_at, a.row_version
  FROM service.authorization a
 WHERE a.tenant_id = sqlc.arg('tenant_id')
   AND a.idempotency_key = sqlc.arg('idempotency_key');

-- name: ListAuthorizations :many
-- Keyset pagination on (created_at DESC, id DESC); the caller asks for limit+1 rows to
-- learn whether a next page exists.
SELECT a.id, a.request_id, a.authorization_reference, a.valid_from, a.valid_to, a.status,
       a.reserved_total::text AS reserved_total, a.consumed_total::text AS consumed_total,
       a.currency_code, a.price_quote_id, a.approved_by, a.approved_at,
       a.cancel_reason_code, a.created_at, a.row_version
  FROM service.authorization a
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE a.tenant_id = sqlc.arg('tenant_id')
   AND (sqlc.narg('scope_ids')::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY(sqlc.narg('scope_ids')::uuid[]))
   AND (sqlc.narg('status')::text IS NULL OR a.status = sqlc.narg('status')::text)
   AND (sqlc.narg('request_id')::uuid IS NULL OR a.request_id = sqlc.narg('request_id')::uuid)
   AND (sqlc.narg('person_id')::uuid IS NULL OR r.person_id = sqlc.narg('person_id')::uuid)
   AND (sqlc.narg('provider_id')::uuid IS NULL
        OR r.provider_tenant_organization_id = sqlc.narg('provider_id')::uuid)
   AND (sqlc.narg('valid_from')::timestamptz IS NULL
        OR a.valid_to >= sqlc.narg('valid_from')::timestamptz)
   AND (sqlc.narg('valid_to')::timestamptz IS NULL
        OR a.valid_from <= sqlc.narg('valid_to')::timestamptz)
   AND (sqlc.narg('cursor_created_at')::timestamptz IS NULL
        OR (a.created_at, a.id) < (sqlc.narg('cursor_created_at')::timestamptz, sqlc.narg('cursor_id')::uuid))
 ORDER BY a.created_at DESC, a.id DESC
 LIMIT sqlc.arg('page_size');

-- name: ExtendAuthorization :execrows
-- valid_to moves forward only, and only while the authorization is ACTIVE: extending a
-- promise that has already been used up or withdrawn would revive it.
UPDATE service.authorization
   SET valid_to   = sqlc.arg('valid_to'),
       updated_by = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
   AND status = 'ACTIVE'
   AND valid_to < sqlc.arg('valid_to');

-- name: CancelAuthorization :execrows
UPDATE service.authorization
   SET status             = 'CANCELLED',
       cancel_reason_code = sqlc.arg('cancel_reason_code'),
       updated_by         = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
   AND status IN ('ACTIVE','PARTIALLY_USED');

-- name: ApplyAuthorizationConsumption :execrows
-- Adds what a completed fulfilment delivered and moves the authorization to the status
-- the new total implies. ck_authorization_consumed refuses a total above what was
-- promised, so an over-fulfilment that slipped past the application layer still cannot
-- be written.
UPDATE service.authorization
   SET consumed_total = consumed_total + sqlc.arg('delta_consumed')::text::numeric,
       status         = CASE
                          WHEN consumed_total + sqlc.arg('delta_consumed')::text::numeric
                               >= reserved_total THEN 'USED'
                          ELSE 'PARTIALLY_USED'
                        END,
       updated_by     = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND status IN ('ACTIVE','PARTIALLY_USED');

-- name: ListExpirableAuthorizations :many
-- The expiry sweep, one tenant at a time. Only holds that still hold something are
-- listed, so re-running the job after it has done its work returns nothing.
SELECT a.id, a.row_version
  FROM service.authorization a
 WHERE a.tenant_id = sqlc.arg('tenant_id')
   AND a.status IN ('ACTIVE','PARTIALLY_USED')
   AND a.valid_to < sqlc.arg('expired_before')
 ORDER BY a.valid_to
 LIMIT sqlc.arg('page_size')
   FOR UPDATE SKIP LOCKED;

-- name: MarkAuthorizationExpired :execrows
UPDATE service.authorization
   SET status = 'EXPIRED'
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND status IN ('ACTIVE','PARTIALLY_USED');

-- name: CreateAuthorizationItem :one
-- The line is written before its hold is taken, because the reservation references the
-- line: two lines of one authorization may draw on the same entitlement account, and
-- uq_entitlement_reservation_reference would fold them into a single hold if they shared
-- a reference. The reservation id is written back by SetAuthorizationItemReservation.
INSERT INTO service.authorization_item (
    tenant_id, authorization_id, request_item_id, service_definition_id,
    approved_quantity, approved_amount, member_amount)
VALUES (sqlc.arg('tenant_id'), sqlc.arg('authorization_id'), sqlc.arg('request_item_id'),
        sqlc.arg('service_definition_id'), sqlc.arg('approved_quantity')::text::numeric,
        sqlc.narg('approved_amount')::text::numeric, sqlc.arg('member_amount')::text::numeric)
RETURNING id, created_at, row_version;

-- name: SetAuthorizationItemReservation :execrows
UPDATE service.authorization_item
   SET entitlement_reservation_id = sqlc.arg('entitlement_reservation_id')
 WHERE tenant_id = sqlc.arg('tenant_id') AND id = sqlc.arg('id');

-- name: ListAuthorizationItems :many
SELECT id, authorization_id, request_item_id, service_definition_id,
       approved_quantity::text AS approved_quantity,
       COALESCE(approved_amount::text, '')::text AS approved_amount,
       member_amount::text AS member_amount,
       entitlement_reservation_id,
       consumed_quantity::text AS consumed_quantity,
       row_version
  FROM service.authorization_item
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND authorization_id = sqlc.arg('authorization_id')
 ORDER BY created_at, id;

-- name: LockAuthorizationItems :many
-- The line set taken FOR UPDATE, which is what a completing fulfilment reads before it
-- consumes: the remainder it checks must be one nobody else can change until it commits.
SELECT id, authorization_id, request_item_id, service_definition_id,
       approved_quantity::text AS approved_quantity,
       COALESCE(approved_amount::text, '')::text AS approved_amount,
       member_amount::text AS member_amount,
       entitlement_reservation_id,
       consumed_quantity::text AS consumed_quantity,
       row_version
  FROM service.authorization_item
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND authorization_id = sqlc.arg('authorization_id')
 ORDER BY created_at, id
   FOR UPDATE;

-- name: AddAuthorizationItemConsumption :execrows
UPDATE service.authorization_item
   SET consumed_quantity = consumed_quantity + sqlc.arg('delta_consumed')::text::numeric
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id');

-- name: CreateFulfilment :one
INSERT INTO service.fulfilment (
    tenant_id, fulfilment_reference, authorization_id, provider_profile_id, location_id,
    practitioner_id, performed_at, recorded_by)
VALUES (sqlc.arg('tenant_id'), sqlc.arg('fulfilment_reference'), sqlc.arg('authorization_id'),
        sqlc.narg('provider_profile_id'), sqlc.narg('location_id'),
        sqlc.narg('practitioner_id'), sqlc.arg('performed_at'), sqlc.narg('actor_id'))
RETURNING id, fulfilment_reference, status, created_at, row_version;

-- name: GetFulfilment :one
SELECT f.id, f.fulfilment_reference, f.authorization_id, f.provider_profile_id, f.location_id,
       f.practitioner_id, f.performed_at, f.status, f.completed_at, f.cancelled_at,
       f.cancel_reason_code, f.recorded_by, f.created_at, f.row_version
  FROM service.fulfilment f
  JOIN service.authorization a
    ON a.tenant_id = f.tenant_id AND a.id = f.authorization_id
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE f.tenant_id = sqlc.arg('tenant_id')
   AND f.id = sqlc.arg('id')
   AND (sqlc.narg('scope_ids')::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY(sqlc.narg('scope_ids')::uuid[]));

-- name: LockFulfilment :one
SELECT f.id, f.fulfilment_reference, f.authorization_id, f.provider_profile_id, f.location_id,
       f.practitioner_id, f.performed_at, f.status, f.completed_at, f.cancelled_at,
       f.cancel_reason_code, f.recorded_by, f.created_at, f.row_version
  FROM service.fulfilment f
  JOIN service.authorization a
    ON a.tenant_id = f.tenant_id AND a.id = f.authorization_id
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE f.tenant_id = sqlc.arg('tenant_id')
   AND f.id = sqlc.arg('id')
   AND (sqlc.narg('scope_ids')::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY(sqlc.narg('scope_ids')::uuid[]))
   FOR UPDATE OF f;

-- name: ListFulfilments :many
SELECT f.id, f.fulfilment_reference, f.authorization_id, f.provider_profile_id, f.location_id,
       f.practitioner_id, f.performed_at, f.status, f.completed_at, f.cancelled_at,
       f.cancel_reason_code, f.recorded_by, f.created_at, f.row_version
  FROM service.fulfilment f
  JOIN service.authorization a
    ON a.tenant_id = f.tenant_id AND a.id = f.authorization_id
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE f.tenant_id = sqlc.arg('tenant_id')
   AND (sqlc.narg('scope_ids')::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY(sqlc.narg('scope_ids')::uuid[]))
   AND (sqlc.narg('status')::text IS NULL OR f.status = sqlc.narg('status')::text)
   AND (sqlc.narg('authorization_id')::uuid IS NULL
        OR f.authorization_id = sqlc.narg('authorization_id')::uuid)
   AND (sqlc.narg('provider_profile_id')::uuid IS NULL
        OR f.provider_profile_id = sqlc.narg('provider_profile_id')::uuid)
   AND (sqlc.narg('performed_from')::timestamptz IS NULL
        OR f.performed_at >= sqlc.narg('performed_from')::timestamptz)
   AND (sqlc.narg('performed_to')::timestamptz IS NULL
        OR f.performed_at <= sqlc.narg('performed_to')::timestamptz)
   AND (sqlc.narg('cursor_created_at')::timestamptz IS NULL
        OR (f.created_at, f.id) < (sqlc.narg('cursor_created_at')::timestamptz, sqlc.narg('cursor_id')::uuid))
 ORDER BY f.created_at DESC, f.id DESC
 LIMIT sqlc.arg('page_size');

-- name: CompleteFulfilment :execrows
UPDATE service.fulfilment
   SET status = 'COMPLETED', completed_at = sqlc.arg('completed_at')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
   AND status = 'RECORDED';

-- name: CancelFulfilmentRecord :execrows
-- Only a RECORDED fulfilment may be cancelled. A completed one has already consumed from
-- the ledger, and undoing that is a reversal movement rather than a status change.
UPDATE service.fulfilment
   SET status = 'CANCELLED', cancelled_at = sqlc.arg('cancelled_at'),
       cancel_reason_code = sqlc.arg('cancel_reason_code')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
   AND status = 'RECORDED';

-- name: CreateFulfilmentItem :one
INSERT INTO service.fulfilment_item (
    tenant_id, fulfilment_id, authorization_item_id, service_definition_id,
    actual_quantity, actual_amount)
VALUES (sqlc.arg('tenant_id'), sqlc.arg('fulfilment_id'), sqlc.arg('authorization_item_id'),
        sqlc.arg('service_definition_id'), sqlc.arg('actual_quantity')::text::numeric,
        sqlc.narg('actual_amount')::text::numeric)
RETURNING id, created_at;

-- name: ListFulfilmentItems :many
SELECT id, fulfilment_id, authorization_item_id, service_definition_id,
       actual_quantity::text AS actual_quantity,
       COALESCE(actual_amount::text, '')::text AS actual_amount
  FROM service.fulfilment_item
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND fulfilment_id = sqlc.arg('fulfilment_id')
 ORDER BY created_at, id;

-- name: CreateVoucher :one
-- Only the digest and the masked tail are written. The plaintext exists in the issue
-- response and nowhere else: not in a column, not in a log line, not in an audit row.
INSERT INTO service.voucher (
    tenant_id, authorization_id, token_hash, token_masked, valid_from, valid_to, issued_by)
VALUES (sqlc.arg('tenant_id'), sqlc.arg('authorization_id'), sqlc.arg('token_hash'),
        sqlc.arg('token_masked'), sqlc.arg('valid_from'), sqlc.arg('valid_to'),
        sqlc.narg('actor_id'))
RETURNING id, status, issued_at, created_at, row_version;

-- name: GetVoucherByTokenHash :one
-- Redemption looks the voucher up by digest, never by the token itself, so the plaintext
-- never becomes a query parameter that a statement log could keep.
SELECT v.id, v.authorization_id, v.token_masked, v.valid_from, v.valid_to, v.status,
       v.redeemed_at, v.redeemed_by_actor_id, v.issued_at, v.created_at, v.row_version
  FROM service.voucher v
  JOIN service.authorization a
    ON a.tenant_id = v.tenant_id AND a.id = v.authorization_id
  JOIN service.service_request r
    ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE v.tenant_id = sqlc.arg('tenant_id')
   AND v.token_hash = sqlc.arg('token_hash')
   AND (sqlc.narg('scope_ids')::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY(sqlc.narg('scope_ids')::uuid[]))
   FOR UPDATE OF v;

-- name: ListVouchers :many
SELECT v.id, v.authorization_id, v.token_masked, v.valid_from, v.valid_to, v.status,
       v.redeemed_at, v.redeemed_by_actor_id, v.issued_at, v.created_at, v.row_version
  FROM service.voucher v
 WHERE v.tenant_id = sqlc.arg('tenant_id')
   AND v.authorization_id = sqlc.arg('authorization_id')
 ORDER BY v.issued_at DESC, v.id DESC;

-- name: CountLiveVouchers :one
-- How many vouchers for this authorization are still usable. Issuing takes the
-- authorization's row lock first, so this count cannot change underneath the check that
-- reads it; uq_voucher_one_live_per_authorization is the guarantee, and this is only how
-- the caller is told which of its two clicks arrived second.
SELECT count(*)
  FROM service.voucher
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND authorization_id = sqlc.arg('authorization_id')
   AND status = 'ISSUED';

-- name: RedeemVoucher :execrows
UPDATE service.voucher
   SET status = 'REDEEMED', redeemed_at = sqlc.arg('redeemed_at'),
       redeemed_by_actor_id = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND status = 'ISSUED';

-- name: ListExpiringAuthorizations :many
-- The authorizations whose validity ends on one particular day, with the member behind
-- them. It is a day and not a window because the reminder is published once per
-- authorization per expiry day: the job's deduplication key carries the same date, so an
-- hourly sweep of the same day writes one message and twenty-three no-ops.
SELECT a.id, a.authorization_reference, a.valid_to, r.person_id
  FROM service.authorization a
  JOIN service.service_request r ON r.tenant_id = a.tenant_id AND r.id = a.request_id
 WHERE a.tenant_id = sqlc.arg('tenant_id')
   AND a.status IN ('ACTIVE','PARTIALLY_USED')
   AND a.valid_to >= sqlc.arg('day_start')
   AND a.valid_to < sqlc.arg('day_end')
 ORDER BY a.valid_to, a.id
 LIMIT sqlc.arg('page_size');
