-- Eligibility queries (WP-I2-04): the reads one check needs and the immutable
-- evaluation snapshot it leaves behind.
--
-- The reads are deliberately narrow. An eligibility check answers "may this person use
-- this benefit today"; it never needs a name, a birth date or an identifier, so those
-- columns are not selected at all and cannot leak into a log, a snapshot or a response.
-- Everything runs inside the caller's db.WithTenantTx transaction, so the person, the
-- membership, the enrollment, the plan version and the balances are all read from one
-- consistent point in time.

-- name: GetPersonForEligibility :one
-- Existence and status only: PERSON_NOT_FOUND and PERSON_INACTIVE need nothing else.
SELECT id, status
  FROM party.person
 WHERE tenant_id = $1 AND id = $2;

-- name: ListMembershipsForEligibility :many
-- Every sponsor membership period of the person; the resolver picks the ones covering
-- the service date and tells MEMBERSHIP_NONE from MEMBERSHIP_SUSPENDED.
SELECT id, status,
       lower(valid_period)::date AS valid_from,
       upper(valid_period)::date AS valid_to
  FROM party.sponsor_membership
 WHERE tenant_id = $1 AND person_id = $2
 ORDER BY lower(valid_period) DESC, id;

-- name: ListEnrollmentsForEligibility :many
-- Every enrollment of the person with the plan and program behind it. The program is
-- joined in because a check may be restricted to one program.
SELECT e.id, e.plan_id, p.program_id, e.status,
       lower(e.valid_period)::date AS valid_from,
       upper(e.valid_period)::date AS valid_to
  FROM benefit.enrollment e
  JOIN party.sponsor_membership m ON m.tenant_id = e.tenant_id AND m.id = e.sponsor_membership_id
  JOIN benefit.plan p ON p.tenant_id = e.tenant_id AND p.id = e.plan_id
 WHERE e.tenant_id = $1 AND m.person_id = $2
 ORDER BY lower(e.valid_period) DESC, e.id;

-- name: CreateEligibilityEvaluation :one
-- The append-only snapshot. The id and the evaluation timestamp are generated by the
-- caller so the stored result document carries exactly the evaluationId and evaluatedAt
-- of the row it lives in; the column defaults (uuidv7, clock_timestamp) remain the
-- fallback for hand-written inserts.
INSERT INTO benefit.eligibility_evaluation (
    id, tenant_id, person_id, program_id, enrollment_id, plan_version_id,
    provider_tenant_organization_id, service_date, outcome, request_hash,
    request_snapshot, result_snapshot, data_classification, idempotency_key,
    evaluated_at, evaluated_by)
VALUES (sqlc.arg('id'), sqlc.arg('tenant_id'), sqlc.arg('person_id'), sqlc.narg('program_id'),
        sqlc.narg('enrollment_id'), sqlc.narg('plan_version_id'),
        sqlc.narg('provider_tenant_organization_id'), sqlc.arg('service_date'),
        sqlc.arg('outcome'), sqlc.arg('request_hash'), sqlc.arg('request_snapshot'),
        sqlc.arg('result_snapshot'), sqlc.arg('data_classification'),
        sqlc.narg('idempotency_key'), sqlc.arg('evaluated_at'), sqlc.narg('evaluated_by'))
RETURNING id, evaluated_at;

-- name: GetEligibilityEvaluation :one
SELECT id, person_id, program_id, enrollment_id, plan_version_id,
       provider_tenant_organization_id, service_date, outcome, request_hash,
       request_snapshot, result_snapshot, data_classification, idempotency_key,
       evaluated_at, evaluated_by
  FROM benefit.eligibility_evaluation
 WHERE tenant_id = $1 AND id = $2;

-- name: FindEligibilityEvaluationByKey :one
-- The replay lookup of an Idempotency-Key. uq_eligibility_evaluation_key makes the key
-- unique per tenant, so at most one row can match.
SELECT id, person_id, program_id, enrollment_id, plan_version_id,
       provider_tenant_organization_id, service_date, outcome, request_hash,
       request_snapshot, result_snapshot, data_classification, idempotency_key,
       evaluated_at, evaluated_by
  FROM benefit.eligibility_evaluation
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND idempotency_key = sqlc.arg('idempotency_key')::text;
