-- Party queries (WP-I2-01): persons, encrypted identifiers, family relationships and
-- sponsor memberships. Every statement filters on tenant_id explicitly and runs inside
-- db.WithTenantTx, so RLS is the second line of defence behind the predicate.

-- name: ListIdentifierTypes :many
SELECT code, display_name, is_sensitive, uniqueness_scope, status
  FROM party.identifier_type
 WHERE tenant_id = $1
 ORDER BY code;

-- name: GetIdentifierType :one
SELECT code, display_name, is_sensitive, uniqueness_scope, status
  FROM party.identifier_type
 WHERE tenant_id = $1 AND code = $2;

-- name: ListRelationshipTypes :many
SELECT code, display_name, is_directional, status
  FROM party.relationship_type
 WHERE tenant_id = $1
 ORDER BY code;

-- name: GetRelationshipType :one
SELECT code, display_name, is_directional, status
  FROM party.relationship_type
 WHERE tenant_id = $1 AND code = $2;

-- name: ListMembershipTypes :many
SELECT code, display_name, requires_principal, status
  FROM party.membership_type
 WHERE tenant_id = $1
 ORDER BY code;

-- name: GetMembershipType :one
SELECT code, display_name, requires_principal, status
  FROM party.membership_type
 WHERE tenant_id = $1 AND code = $2;

-- name: CreatePerson :one
INSERT INTO party.person (tenant_id, first_name, middle_name, last_name, normalized_name,
                          birth_date, sex_at_birth, created_by, updated_by)
VALUES (sqlc.arg('tenant_id'), sqlc.arg('first_name'), sqlc.narg('middle_name'), sqlc.arg('last_name'),
        sqlc.arg('normalized_name'), sqlc.narg('birth_date'), sqlc.narg('sex_at_birth'),
        sqlc.narg('actor_id'), sqlc.narg('actor_id'))
RETURNING id, created_at, row_version;

-- name: GetPerson :one
SELECT id, first_name, middle_name, last_name, birth_date, sex_at_birth, status,
       merged_into_id, created_at, row_version
  FROM party.person
 WHERE tenant_id = $1 AND id = $2;

-- name: UpdatePerson :one
-- Optimistic concurrency: a stale If-Match matches no row. platform.tg_touch_row bumps
-- row_version and updated_at, so this statement never assigns them.
UPDATE party.person
   SET first_name = sqlc.arg('first_name'),
       middle_name = sqlc.narg('middle_name'),
       last_name = sqlc.arg('last_name'),
       normalized_name = sqlc.arg('normalized_name'),
       birth_date = sqlc.narg('birth_date'),
       sex_at_birth = sqlc.narg('sex_at_birth'),
       status = sqlc.arg('status'),
       updated_by = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
RETURNING row_version;

-- name: ListPeople :many
-- Keyset pagination on (created_at DESC, id DESC); the caller asks for limit+1 rows to
-- learn whether a next page exists. `q` is matched token by token against the folded
-- normalized_name so the trigram index can serve it.
SELECT p.id, p.first_name, p.middle_name, p.last_name, p.status, p.created_at,
       COALESCE(mi.masked_value, '')::text AS masked_primary_identifier
  FROM party.person p
  LEFT JOIN LATERAL (
       SELECT i.masked_value
         FROM party.person_identifier i
        WHERE i.tenant_id = p.tenant_id AND i.person_id = p.id AND i.is_primary
        ORDER BY i.created_at
        LIMIT 1) mi ON true
 WHERE p.tenant_id = $1
   AND (sqlc.narg('status')::text IS NULL OR p.status = sqlc.narg('status')::text)
   AND (sqlc.narg('q')::text IS NULL
        OR p.normalized_name LIKE ALL (
             SELECT '%' || token || '%'
               FROM unnest(string_to_array(sqlc.narg('q')::text, ' ')) AS token))
   AND (sqlc.narg('sponsor_id')::uuid IS NULL
        OR EXISTS (SELECT 1
                     FROM party.sponsor_membership m
                    WHERE m.tenant_id = p.tenant_id
                      AND m.person_id = p.id
                      AND m.sponsor_tenant_organization_id = sqlc.narg('sponsor_id')::uuid
                      AND m.status = 'ACTIVE'))
   AND (sqlc.narg('cursor_created_at')::timestamptz IS NULL
        OR (p.created_at, p.id) < (sqlc.narg('cursor_created_at')::timestamptz, sqlc.narg('cursor_id')::uuid))
 ORDER BY p.created_at DESC, p.id DESC
 LIMIT sqlc.arg('page_size');

-- name: AddPersonIdentifier :exec
-- The row id is generated by the application because scope_key NONE is the row's own id.
INSERT INTO party.person_identifier (id, tenant_id, person_id, identifier_type, identifier_cipher,
                                     identifier_hash, masked_value, scope_key, is_primary)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9);

-- name: ListPersonIdentifiers :many
SELECT id, identifier_type, identifier_cipher, masked_value, scope_key, is_primary
  FROM party.person_identifier
 WHERE tenant_id = $1 AND person_id = $2
 ORDER BY is_primary DESC, identifier_type;

-- name: DeletePersonIdentifiers :execrows
DELETE FROM party.person_identifier
 WHERE tenant_id = $1 AND person_id = $2 AND identifier_type = $3;

-- name: FindPersonByIdentifierHash :one
-- Equality search on the tenant-salted blind index; the plaintext never reaches SQL.
SELECT person_id
  FROM party.person_identifier
 WHERE tenant_id = $1
   AND identifier_type = $2
   AND identifier_hash = $3
   AND (sqlc.narg('scope_key')::text IS NULL OR scope_key = sqlc.narg('scope_key')::text)
 LIMIT 1;

-- name: CreatePersonRelationship :one
INSERT INTO party.person_relationship (tenant_id, source_person_id, target_person_id, relationship_type, valid_period)
VALUES ($1, $2, $3, $4, daterange(sqlc.arg('valid_from')::date, sqlc.narg('valid_to')::date, '[)'))
RETURNING id, row_version;

-- name: GetPersonRelationship :one
SELECT r.id, r.source_person_id, r.target_person_id, r.relationship_type, r.status,
       lower(r.valid_period)::date AS valid_from, upper(r.valid_period)::date AS valid_to,
       r.end_reason_code, r.row_version, t.is_directional
  FROM party.person_relationship r
  JOIN party.relationship_type t ON t.tenant_id = r.tenant_id AND t.code = r.relationship_type
 WHERE r.tenant_id = $1 AND r.id = $2;

-- name: ListPersonRelationships :many
-- Both directions in one page; the other person is joined in as a summary.
SELECT r.id, r.source_person_id, r.target_person_id, r.relationship_type, r.status,
       lower(r.valid_period)::date AS valid_from, upper(r.valid_period)::date AS valid_to,
       r.end_reason_code, r.row_version, t.is_directional,
       o.id AS other_person_id, o.first_name AS other_first_name, o.middle_name AS other_middle_name,
       o.last_name AS other_last_name, o.status AS other_status,
       COALESCE(mi.masked_value, '')::text AS other_masked_identifier
  FROM party.person_relationship r
  JOIN party.relationship_type t ON t.tenant_id = r.tenant_id AND t.code = r.relationship_type
  JOIN party.person o ON o.tenant_id = r.tenant_id
       AND o.id = CASE WHEN r.source_person_id = $2 THEN r.target_person_id ELSE r.source_person_id END
  LEFT JOIN LATERAL (
       SELECT i.masked_value
         FROM party.person_identifier i
        WHERE i.tenant_id = o.tenant_id AND i.person_id = o.id AND i.is_primary
        ORDER BY i.created_at
        LIMIT 1) mi ON true
 WHERE r.tenant_id = $1 AND (r.source_person_id = $2 OR r.target_person_id = $2)
 ORDER BY r.created_at DESC, r.id DESC;

-- name: EndPersonRelationship :one
UPDATE party.person_relationship
   SET valid_period = daterange(lower(valid_period), sqlc.arg('ends_on')::date, '[)'),
       status = 'ENDED',
       end_reason_code = sqlc.arg('reason_code'),
       end_reason_text = sqlc.narg('reason_text')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
RETURNING row_version;

-- name: GetSponsorOrganization :one
SELECT t.id, t.relationship_role, t.status, o.display_name
  FROM directory.tenant_organization t
  JOIN directory.organization o ON o.id = t.organization_id
 WHERE t.tenant_id = $1 AND t.id = $2;

-- name: CreateSponsorMembership :one
INSERT INTO party.sponsor_membership (tenant_id, person_id, sponsor_tenant_organization_id,
                                      principal_membership_id, membership_type, external_member_no,
                                      status, valid_period)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        daterange(sqlc.arg('valid_from')::date, sqlc.narg('valid_to')::date, '[)'))
RETURNING id, row_version;

-- name: GetSponsorMembership :one
SELECT m.id, m.person_id, m.sponsor_tenant_organization_id, m.principal_membership_id,
       m.membership_type, m.external_member_no, m.status,
       lower(m.valid_period)::date AS valid_from, upper(m.valid_period)::date AS valid_to,
       m.source_system, m.created_at, m.row_version, o.display_name AS sponsor_display_name
  FROM party.sponsor_membership m
  JOIN directory.tenant_organization t ON t.tenant_id = m.tenant_id AND t.id = m.sponsor_tenant_organization_id
  JOIN directory.organization o ON o.id = t.organization_id
 WHERE m.tenant_id = $1 AND m.id = $2;

-- name: ListSponsorMemberships :many
SELECT m.id, m.person_id, m.sponsor_tenant_organization_id, m.principal_membership_id,
       m.membership_type, m.external_member_no, m.status,
       lower(m.valid_period)::date AS valid_from, upper(m.valid_period)::date AS valid_to,
       m.source_system, m.created_at, m.row_version, o.display_name AS sponsor_display_name
  FROM party.sponsor_membership m
  JOIN directory.tenant_organization t ON t.tenant_id = m.tenant_id AND t.id = m.sponsor_tenant_organization_id
  JOIN directory.organization o ON o.id = t.organization_id
 WHERE m.tenant_id = $1 AND m.person_id = $2
 ORDER BY m.created_at DESC, m.id DESC;

-- name: UpdateSponsorMembership :one
UPDATE party.sponsor_membership
   SET status = sqlc.arg('status'),
       external_member_no = sqlc.narg('external_member_no'),
       valid_period = daterange(lower(valid_period), sqlc.narg('valid_to')::date, '[)')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
RETURNING row_version;

-- name: ActiveSponsorOrganizations :many
-- Sponsors of the person's active principal memberships; used to derive the scope_key of
-- SPONSOR-scoped identifiers (D5).
SELECT DISTINCT sponsor_tenant_organization_id
  FROM party.sponsor_membership
 WHERE tenant_id = $1 AND person_id = $2 AND status = 'ACTIVE' AND principal_membership_id IS NULL;
