-- Pricing quote queries (WP-I3-05, v1.2 11.5, 11.6).
--
-- A quote is the number somebody was given before anything was booked. Everything here
-- is either a read the calculation needs or the append-only row it leaves behind; there
-- is deliberately no statement in this file that touches benefit.entitlement_account or
-- benefit.entitlement_ledger, because a quote reserves nothing and moves no balance.
--
-- Money and quantities are read as `::text` and written as `::text::numeric`, so the
-- exact decimal never passes through a float on the way in or out (handbook section 3).

-- name: GetPricingQuoteTTLHours :one
-- The tenant's quote lifetime, as text so an integer-valued JSON number arrives exactly.
-- A missing setting is not an error: the service falls back to its documented default.
SELECT (value_json #>> '{}')::text AS value
  FROM platform.tenant_setting
 WHERE tenant_id = $1 AND setting_key = 'pricing.quote_ttl_hours';

-- name: GetProviderProfileForQuote :one
-- Existence and the organization behind the profile. The organization is what a
-- provider-scoped actor's access grant names, so it is what the scope check compares.
SELECT id, tenant_organization_id, status
  FROM provider.provider_profile
 WHERE tenant_id = $1 AND id = $2;

-- name: ProviderLocationBelongsToProvider :one
-- A location has to belong to the provider being quoted; anything else would price a
-- service at a place that provider does not run.
SELECT EXISTS (
    SELECT 1 FROM provider.location
     WHERE tenant_id = $1 AND id = $2 AND provider_profile_id = $3
) AS ok;

-- name: PriceQuoteEligibilityEvaluationExists :one
-- The caller may name an eligibility evaluation it already made; it must be this
-- tenant's and about this person, or it is not the check it claims to be.
SELECT EXISTS (
    SELECT 1 FROM benefit.eligibility_evaluation
     WHERE tenant_id = $1 AND id = $2 AND person_id = $3
) AS ok;

-- name: ListPricePackageDefinitions :many
-- The packages named by the request, with the service definitions inside them. A package
-- line is priced against the package, so the selection is asked about it directly.
SELECT id, code FROM contract.package_definition
 WHERE tenant_id = $1 AND id = ANY(sqlc.arg('ids')::uuid[]);

-- name: ListPublishedPriceRuleSetVersions :many
-- Every published PRICE rule set version of the tenant covering the service date. The
-- exclusion constraint on rules.rule_set_version makes at most one version per set
-- match, so this is "which rules decide today" and never a choice between two answers.
SELECT v.id, v.rule_set_id, s.code AS rule_set_code, v.version_no, v.input_schema
  FROM rules.rule_set_version v
  JOIN rules.rule_set s ON s.tenant_id = v.tenant_id AND s.id = v.rule_set_id
 WHERE v.tenant_id = sqlc.arg('tenant_id')
   AND v.status = 'PUBLISHED'
   AND s.status = 'ACTIVE'
   AND s.purpose = 'PRICE'
   AND daterange(v.valid_from, v.valid_to, '[)') @> sqlc.arg('service_date')::date
 ORDER BY s.code, v.version_no;

-- name: CreatePriceQuote :one
-- The append-only header. The id, the quote timestamp and the expiry are generated by
-- the caller so the stored result document carries exactly the id it lives under; the
-- column defaults remain the fallback for hand-written inserts.
INSERT INTO contract.price_quote (
    id, tenant_id, person_id, program_id, provider_profile_id, location_id, service_date,
    currency_code, outcome, requested_amount, contract_amount, covered_amount,
    payer_amount, member_amount, request_hash, request_snapshot, result_snapshot,
    contract_version_id, plan_version_id, eligibility_evaluation_id, expires_at,
    quoted_at, quoted_by, idempotency_key)
VALUES (sqlc.arg('id'), sqlc.arg('tenant_id'), sqlc.arg('person_id'), sqlc.narg('program_id'),
        sqlc.arg('provider_profile_id'), sqlc.narg('location_id'), sqlc.arg('service_date'),
        sqlc.arg('currency_code'), sqlc.arg('outcome'),
        sqlc.arg('requested_amount')::text::numeric,
        sqlc.arg('contract_amount')::text::numeric,
        sqlc.arg('covered_amount')::text::numeric,
        sqlc.arg('payer_amount')::text::numeric,
        sqlc.arg('member_amount')::text::numeric,
        sqlc.arg('request_hash'), sqlc.arg('request_snapshot'), sqlc.arg('result_snapshot'),
        sqlc.narg('contract_version_id'), sqlc.narg('plan_version_id'),
        sqlc.narg('eligibility_evaluation_id'), sqlc.arg('expires_at'),
        sqlc.arg('quoted_at'), sqlc.narg('quoted_by'), sqlc.narg('idempotency_key'))
RETURNING id, quoted_at, expires_at;

-- name: CreatePriceQuoteItem :batchexec
-- One priced line. The five figures are stored separately because an operator and a
-- member need to read them apart from one another (v1.2 11.6).
INSERT INTO contract.price_quote_item (
    tenant_id, price_quote_id, line_no, service_definition_id, package_definition_id,
    price_item_id, quantity, requested_amount, contract_amount, covered_amount,
    payer_amount, member_amount, outcome, explanations)
VALUES (sqlc.arg('tenant_id'), sqlc.arg('price_quote_id'), sqlc.arg('line_no'),
        sqlc.narg('service_definition_id'), sqlc.narg('package_definition_id'),
        sqlc.narg('price_item_id'),
        sqlc.arg('quantity')::text::numeric,
        sqlc.arg('requested_amount')::text::numeric,
        sqlc.arg('contract_amount')::text::numeric,
        sqlc.arg('covered_amount')::text::numeric,
        sqlc.arg('payer_amount')::text::numeric,
        sqlc.arg('member_amount')::text::numeric,
        sqlc.arg('outcome'), sqlc.arg('explanations'));

-- name: GetPriceQuote :one
SELECT id, person_id, program_id, provider_profile_id, location_id, service_date,
       currency_code, outcome,
       requested_amount::text AS requested_amount,
       contract_amount::text  AS contract_amount,
       covered_amount::text   AS covered_amount,
       payer_amount::text     AS payer_amount,
       member_amount::text    AS member_amount,
       request_hash, request_snapshot, result_snapshot, contract_version_id,
       plan_version_id, eligibility_evaluation_id, expires_at, quoted_at, quoted_by,
       idempotency_key
  FROM contract.price_quote
 WHERE tenant_id = $1 AND id = $2;

-- name: FindPriceQuoteByKey :one
-- The replay lookup of an Idempotency-Key. uq_price_quote_idempotency makes the key
-- unique per tenant, so at most one row can match and a replay needs no time window.
SELECT id, person_id, program_id, provider_profile_id, location_id, service_date,
       currency_code, outcome,
       requested_amount::text AS requested_amount,
       contract_amount::text  AS contract_amount,
       covered_amount::text   AS covered_amount,
       payer_amount::text     AS payer_amount,
       member_amount::text    AS member_amount,
       request_hash, request_snapshot, result_snapshot, contract_version_id,
       plan_version_id, eligibility_evaluation_id, expires_at, quoted_at, quoted_by,
       idempotency_key
  FROM contract.price_quote
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND idempotency_key = sqlc.arg('idempotency_key')::text;

-- name: ListPriceQuoteItems :many
-- The lines of one quote in the order they were requested.
SELECT id, price_quote_id, line_no, service_definition_id, package_definition_id,
       price_item_id,
       quantity::text         AS quantity,
       requested_amount::text AS requested_amount,
       contract_amount::text  AS contract_amount,
       covered_amount::text   AS covered_amount,
       payer_amount::text     AS payer_amount,
       member_amount::text    AS member_amount,
       outcome, explanations, created_at
  FROM contract.price_quote_item
 WHERE tenant_id = $1 AND price_quote_id = $2
 ORDER BY line_no;
