-- Service request queries (WP-I4-01, v1.2 9.11, 11.8, 11.9).
--
-- Two properties shape this file. The first is that nothing here writes `status` as a
-- field a caller chose: every statement that moves a request is named after the command
-- that moves it, carries that command's precondition in its WHERE clause and sets the
-- reason columns the transition owes. A generic "set the status to whatever was sent" is
-- exactly the statement this package exists to not have.
--
-- The second is the provider boundary. `scope_ids` is a nullable uuid[]: NULL means the
-- caller is tenant-wide, a non-null array binds it to those organizations. It is applied
-- in every read of a request, including the single-row ones, so a provider asking for
-- another provider's request finds no row and is answered 404 rather than 403 — that such
-- a request exists at all is somebody else's business.
--
-- Quantities and amounts are read as `::text` and written as `::text::numeric`, so an
-- exact decimal never passes through a float in either direction (handbook section 3).

-- name: CreateServiceRequest :one
-- Opens a request in DRAFT. The reference is generated by the caller and unique per
-- tenant; a collision surfaces as a unique violation and is retried with a new one.
INSERT INTO service.service_request (
    tenant_id, request_reference, request_type, person_id, program_id, enrollment_id,
    provider_tenant_organization_id, service_date, requested_start_at, requested_end_at,
    channel, supersedes_request_id, created_by, updated_by)
VALUES (sqlc.arg('tenant_id'), sqlc.arg('request_reference'), sqlc.arg('request_type'),
        sqlc.arg('person_id'), sqlc.arg('program_id'), sqlc.arg('enrollment_id'),
        sqlc.narg('provider_tenant_organization_id'), sqlc.arg('service_date'),
        sqlc.narg('requested_start_at'), sqlc.narg('requested_end_at'),
        sqlc.arg('channel'), sqlc.narg('supersedes_request_id'),
        sqlc.narg('actor_id'), sqlc.narg('actor_id'))
RETURNING id, request_reference, created_at, row_version;

-- name: GetServiceRequest :one
SELECT r.id, r.request_reference, r.request_type, r.person_id, r.program_id, r.enrollment_id,
       r.provider_tenant_organization_id, r.service_date, r.requested_start_at, r.requested_end_at,
       r.channel, r.status, r.current_version_no, r.supersedes_request_id,
       r.eligibility_evaluation_id, r.rule_evaluation_id, r.required_document_types,
       r.return_reason_code, r.reject_reason_code, r.review_comment,
       r.submitted_at, r.closed_at, r.created_at, r.row_version,
       concat_ws(' ', p.first_name, p.middle_name, p.last_name) AS person_display_name,
       o.display_name AS provider_display_name
  FROM service.service_request r
  JOIN party.person p ON p.tenant_id = r.tenant_id AND p.id = r.person_id
  LEFT JOIN directory.tenant_organization po
       ON po.tenant_id = r.tenant_id AND po.id = r.provider_tenant_organization_id
  LEFT JOIN directory.organization o ON o.id = po.organization_id
 WHERE r.tenant_id = sqlc.arg('tenant_id')
   AND r.id = sqlc.arg('id')
   AND (sqlc.narg('scope_ids')::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY(sqlc.narg('scope_ids')::uuid[]));

-- name: LockServiceRequest :one
-- The same read taken FOR UPDATE, so two commands on one request serialise instead of
-- racing each other into two different decisions.
SELECT r.id, r.request_reference, r.request_type, r.person_id, r.program_id, r.enrollment_id,
       r.provider_tenant_organization_id, r.service_date, r.requested_start_at, r.requested_end_at,
       r.channel, r.status, r.current_version_no, r.supersedes_request_id,
       r.eligibility_evaluation_id, r.rule_evaluation_id, r.required_document_types,
       r.return_reason_code, r.reject_reason_code, r.review_comment,
       r.submitted_at, r.closed_at, r.created_at, r.row_version,
       concat_ws(' ', p.first_name, p.middle_name, p.last_name) AS person_display_name,
       o.display_name AS provider_display_name
  FROM service.service_request r
  JOIN party.person p ON p.tenant_id = r.tenant_id AND p.id = r.person_id
  LEFT JOIN directory.tenant_organization po
       ON po.tenant_id = r.tenant_id AND po.id = r.provider_tenant_organization_id
  LEFT JOIN directory.organization o ON o.id = po.organization_id
 WHERE r.tenant_id = sqlc.arg('tenant_id')
   AND r.id = sqlc.arg('id')
   AND (sqlc.narg('scope_ids')::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY(sqlc.narg('scope_ids')::uuid[]))
   -- `OF r` and not a bare FOR UPDATE: two commands on one request must serialise, and
   -- nothing about that should take a lock on the member's own row or on an organization
   -- every other request in the tenant also names.
   FOR UPDATE OF r;

-- name: ListServiceRequests :many
-- Keyset pagination on (created_at DESC, id DESC); the caller asks for limit+1 rows to
-- learn whether a next page exists.
SELECT r.id, r.request_reference, r.request_type, r.person_id, r.program_id, r.enrollment_id,
       r.provider_tenant_organization_id, r.service_date, r.requested_start_at, r.requested_end_at,
       r.channel, r.status, r.current_version_no, r.supersedes_request_id,
       r.eligibility_evaluation_id, r.rule_evaluation_id, r.required_document_types,
       r.return_reason_code, r.reject_reason_code, r.review_comment,
       r.submitted_at, r.closed_at, r.created_at, r.row_version,
       concat_ws(' ', p.first_name, p.middle_name, p.last_name) AS person_display_name,
       o.display_name AS provider_display_name
  FROM service.service_request r
  JOIN party.person p ON p.tenant_id = r.tenant_id AND p.id = r.person_id
  LEFT JOIN directory.tenant_organization po
       ON po.tenant_id = r.tenant_id AND po.id = r.provider_tenant_organization_id
  LEFT JOIN directory.organization o ON o.id = po.organization_id
 WHERE r.tenant_id = sqlc.arg('tenant_id')
   AND (sqlc.narg('scope_ids')::uuid[] IS NULL
        OR r.provider_tenant_organization_id = ANY(sqlc.narg('scope_ids')::uuid[]))
   AND (sqlc.narg('status')::text IS NULL OR r.status = sqlc.narg('status')::text)
   AND (sqlc.narg('person_id')::uuid IS NULL OR r.person_id = sqlc.narg('person_id')::uuid)
   AND (sqlc.narg('program_id')::uuid IS NULL OR r.program_id = sqlc.narg('program_id')::uuid)
   AND (sqlc.narg('provider_id')::uuid IS NULL
        OR r.provider_tenant_organization_id = sqlc.narg('provider_id')::uuid)
   AND (sqlc.narg('channel')::text IS NULL OR r.channel = sqlc.narg('channel')::text)
   AND (sqlc.narg('service_date_from')::date IS NULL
        OR r.service_date >= sqlc.narg('service_date_from')::date)
   AND (sqlc.narg('service_date_to')::date IS NULL
        OR r.service_date <= sqlc.narg('service_date_to')::date)
   AND (sqlc.narg('created_from')::timestamptz IS NULL
        OR r.created_at >= sqlc.narg('created_from')::timestamptz)
   AND (sqlc.narg('created_to')::timestamptz IS NULL
        OR r.created_at <= sqlc.narg('created_to')::timestamptz)
   AND (sqlc.narg('cursor_created_at')::timestamptz IS NULL
        OR (r.created_at, r.id) < (sqlc.narg('cursor_created_at')::timestamptz, sqlc.narg('cursor_id')::uuid))
 ORDER BY r.created_at DESC, r.id DESC
 LIMIT sqlc.arg('page_size');

-- name: UpdateServiceRequestDraftHeader :execrows
-- The merge-patch of a DRAFT request's header. `status` is absent on purpose and there is
-- no statement anywhere in this file that would let a caller supply one.
UPDATE service.service_request
   SET provider_tenant_organization_id = sqlc.narg('provider_tenant_organization_id'),
       service_date       = sqlc.arg('service_date'),
       requested_start_at = sqlc.narg('requested_start_at'),
       requested_end_at   = sqlc.narg('requested_end_at'),
       updated_by         = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
   AND status = 'DRAFT';

-- name: TouchServiceRequest :execrows
-- Bumps row_version without changing a business field, so replacing the lines of the
-- draft invalidates the ETag the caller is holding for the request.
UPDATE service.service_request
   SET updated_by = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id') AND id = sqlc.arg('id');

-- name: MarkServiceRequestSubmitted :execrows
-- The one write of the submit gate. It records the outcome the gate arrived at together
-- with the two evaluations that produced it, so "why is this waiting for a document"
-- always has an answer that outlives the rule version that decided it.
UPDATE service.service_request
   SET status                    = sqlc.arg('status'),
       submitted_at              = sqlc.arg('submitted_at'),
       eligibility_evaluation_id = sqlc.narg('eligibility_evaluation_id'),
       rule_evaluation_id        = sqlc.narg('rule_evaluation_id'),
       required_document_types   = sqlc.narg('required_document_types')::text[],
       review_comment            = sqlc.narg('review_comment'),
       return_reason_code        = NULL,
       updated_by                = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
   AND status = 'DRAFT';

-- name: MarkServiceRequestReturned :execrows
-- Back to DRAFT with the reason it was sent back. submitted_at is cleared because the
-- schema defines a draft as a request that has not been submitted; the submission it did
-- make is on the frozen version, which is where anybody looking for it will find it.
UPDATE service.service_request
   SET status                  = 'DRAFT',
       submitted_at            = NULL,
       closed_at               = NULL,
       current_version_no      = sqlc.arg('current_version_no'),
       return_reason_code      = sqlc.arg('return_reason_code'),
       review_comment          = sqlc.narg('review_comment'),
       required_document_types = NULL,
       updated_by              = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
   AND status IN ('PENDING_REVIEW', 'PENDING_DOCUMENT');

-- name: MarkServiceRequestRejected :execrows
-- A refusal is final. The request closes here and is never reopened; a further attempt is
-- a new request naming this one in supersedes_request_id.
UPDATE service.service_request
   SET status             = 'REJECTED',
       reject_reason_code = sqlc.arg('reject_reason_code'),
       review_comment     = sqlc.narg('review_comment'),
       closed_at          = sqlc.arg('decided_at'),
       updated_by         = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
   AND status = 'PENDING_REVIEW';

-- name: MarkServiceRequestApproved :execrows
-- Approval and partial approval share one statement because they differ only in the word
-- and in what the lines say; both leave the request open, because nothing has been
-- authorized or delivered yet.
UPDATE service.service_request
   SET status         = sqlc.arg('status'),
       review_comment = sqlc.narg('review_comment'),
       updated_by     = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
   AND status = 'PENDING_REVIEW';

-- name: MarkServiceRequestCancelled :execrows
-- Withdrawal before a decision. A request that has already been decided is not cancelled
-- here: undoing a decision has consequences of its own and belongs to service.cancellation.
UPDATE service.service_request
   SET status     = 'CANCELLED',
       closed_at  = sqlc.arg('decided_at'),
       updated_by = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND row_version = sqlc.arg('row_version')
   AND status IN ('DRAFT', 'SUBMITTED', 'PENDING_REVIEW', 'PENDING_DOCUMENT', 'ELIGIBILITY_FAILED');

-- name: CreateServiceRequestVersion :one
-- Opens the next version. The return columns are set when the version exists because it
-- was sent back: the reason belongs to the draft the requester is asked to correct, which
-- is also the only version the immutability trigger of migration 000006 lets anybody
-- write to.
INSERT INTO service.service_request_version (
    tenant_id, service_request_id, version_no, returned_at, returned_by,
    return_reason_code, return_reason_text, created_by)
VALUES (sqlc.arg('tenant_id'), sqlc.arg('service_request_id'), sqlc.arg('version_no'),
        sqlc.narg('returned_at'), sqlc.narg('returned_by'),
        sqlc.narg('return_reason_code'), sqlc.narg('return_reason_text'),
        sqlc.narg('actor_id'))
RETURNING id, version_no, status, created_at;

-- name: GetServiceRequestDraftVersion :one
-- The single DRAFT version of a request; uq_service_request_single_draft guarantees there
-- is at most one.
SELECT id, service_request_id, version_no, status, snapshot_json, submitted_at,
       submitted_by, returned_at, returned_by, return_reason_code, return_reason_text,
       created_at
  FROM service.service_request_version
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND service_request_id = sqlc.arg('service_request_id')
   AND status = 'DRAFT';

-- name: GetServiceRequestVersionByNo :one
SELECT id, service_request_id, version_no, status, snapshot_json, submitted_at,
       submitted_by, returned_at, returned_by, return_reason_code, return_reason_text,
       created_at
  FROM service.service_request_version
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND service_request_id = sqlc.arg('service_request_id')
   AND version_no = sqlc.arg('version_no');

-- name: ListServiceRequestVersions :many
SELECT id, service_request_id, version_no, status, snapshot_json, submitted_at,
       submitted_by, returned_at, returned_by, return_reason_code, return_reason_text,
       created_at
  FROM service.service_request_version
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND service_request_id = sqlc.arg('service_request_id')
 ORDER BY version_no DESC;

-- name: FreezeServiceRequestVersion :execrows
-- Submitting freezes the version: the snapshot is the header and the lines exactly as they
-- were sent, and tg_request_version_guard makes every later write to this row fail.
UPDATE service.service_request_version
   SET status        = 'SUBMITTED',
       snapshot_json = sqlc.arg('snapshot_json'),
       submitted_at  = sqlc.arg('submitted_at'),
       submitted_by  = sqlc.narg('actor_id')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND status = 'DRAFT';

-- name: SupersedeServiceRequestVersion :execrows
-- The one update a submitted version accepts: it is marked as replaced by a later one and
-- nothing else about it changes.
UPDATE service.service_request_version
   SET status = 'SUPERSEDED'
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = sqlc.arg('id')
   AND status = 'SUBMITTED';

-- name: ListServiceRequestItems :many
SELECT id, service_request_version_id, line_no, service_definition_id,
       requested_quantity::text AS requested_quantity,
       unit_type,
       -- A NULL amount renders as the empty string rather than as a NULL text: the caller
       -- turns it back into "no value", and no cast anywhere invents a zero.
       COALESCE(requested_amount::text, '')::text  AS requested_amount,
       currency_code, status,
       COALESCE(approved_quantity::text, '')::text AS approved_quantity,
       COALESCE(approved_amount::text, '')::text   AS approved_amount,
       decision_reason_code
  FROM service.service_request_item
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND service_request_version_id = sqlc.arg('service_request_version_id')
 ORDER BY line_no;

-- name: DeleteServiceRequestItems :execrows
-- Only a draft version's lines can be deleted; tg_request_item_guard refuses the rest.
DELETE FROM service.service_request_item
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND service_request_version_id = sqlc.arg('service_request_version_id');

-- name: CreateServiceRequestItem :batchexec
INSERT INTO service.service_request_item (
    tenant_id, service_request_version_id, line_no, service_definition_id,
    requested_quantity, unit_type, requested_amount, currency_code)
VALUES (sqlc.arg('tenant_id'), sqlc.arg('service_request_version_id'), sqlc.arg('line_no'),
        sqlc.arg('service_definition_id'),
        sqlc.arg('requested_quantity')::text::numeric,
        sqlc.arg('unit_type'),
        sqlc.narg('requested_amount')::text::numeric,
        sqlc.narg('currency_code'));

-- name: DecideServiceRequestItem :batchexec
-- The line-level outcome a reviewer recorded. These are the only columns of a submitted
-- version's line that migration 000006 leaves writable, which is the point: what was asked
-- for is frozen, what was decided about it is not.
UPDATE service.service_request_item
   SET status               = sqlc.arg('status'),
       approved_quantity    = sqlc.narg('approved_quantity')::text::numeric,
       approved_amount      = sqlc.narg('approved_amount')::text::numeric,
       decision_reason_code = sqlc.narg('decision_reason_code')
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND service_request_version_id = sqlc.arg('service_request_version_id')
   AND line_no = sqlc.arg('line_no');

-- name: CreateServiceRequestStatusEvent :exec
-- Every transition leaves one row here. workflow.status_event is append-only (migration
-- 000007): a history that could be edited is not a history.
INSERT INTO workflow.status_event (
    tenant_id, aggregate_type, aggregate_id, from_status, to_status, transition_code,
    reason_code, reason_text, actor_id, metadata_json)
VALUES (sqlc.arg('tenant_id'), 'SERVICE_REQUEST', sqlc.arg('aggregate_id'),
        sqlc.narg('from_status'), sqlc.arg('to_status'), sqlc.arg('transition_code'),
        sqlc.narg('reason_code'), sqlc.narg('reason_text'), sqlc.narg('actor_id'),
        sqlc.arg('metadata_json'));

-- name: ListServiceRequestStatusEvents :many
-- The transition history of one request, oldest first.
SELECT id, from_status, to_status, transition_code, reason_code, reason_text,
       occurred_at, actor_id, metadata_json
  FROM workflow.status_event
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND aggregate_type = 'SERVICE_REQUEST'
   AND aggregate_id = sqlc.arg('aggregate_id')
 ORDER BY occurred_at, id;

-- name: GetServiceRequestEnrollment :one
-- The enrollment a request is raised under, with the person it belongs to and the program
-- of its plan. A request naming an enrollment that is not this person's, or not in this
-- program, is a request nobody could act on.
SELECT e.id, e.plan_id, p.program_id, e.status, m.person_id,
       lower(e.valid_period)::date AS valid_from,
       upper(e.valid_period)::date AS valid_to
  FROM benefit.enrollment e
  JOIN party.sponsor_membership m ON m.tenant_id = e.tenant_id AND m.id = e.sponsor_membership_id
  JOIN benefit.plan p ON p.tenant_id = e.tenant_id AND p.id = e.plan_id
 WHERE e.tenant_id = sqlc.arg('tenant_id') AND e.id = sqlc.arg('id');

-- name: ServiceRequestProviderOrganizationExists :one
-- The provider a request names has to be an organization this tenant deals with in a
-- provider role.
SELECT EXISTS (
    SELECT 1
      FROM directory.tenant_organization
     WHERE tenant_id = sqlc.arg('tenant_id')
       AND id = sqlc.arg('id')
       AND relationship_role = 'PROVIDER'
) AS ok;

-- name: ListServiceRequestServiceDefinitions :many
-- The definitions named by the lines, with the unit they are counted in and whether they
-- need a provider at all.
SELECT id, code, default_unit_type, requires_provider, active
  FROM catalog.service_definition
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND id = ANY(sqlc.arg('ids')::uuid[]);

-- name: ListPublishedRuleSetVersionsForPurposes :many
-- Every published rule set version of the tenant that covers the service date and serves
-- one of the given purposes. The exclusion constraint on rules.rule_set_version makes at
-- most one version per set match, so this is "which rules decide today" and never a
-- choice between two answers.
SELECT v.id, v.rule_set_id, s.code AS rule_set_code, s.purpose, v.version_no, v.input_schema
  FROM rules.rule_set_version v
  JOIN rules.rule_set s ON s.tenant_id = v.tenant_id AND s.id = v.rule_set_id
 WHERE v.tenant_id = sqlc.arg('tenant_id')
   AND v.status = 'PUBLISHED'
   AND s.status = 'ACTIVE'
   AND s.purpose = ANY(sqlc.arg('purposes')::text[])
   AND daterange(v.valid_from, v.valid_to, '[)') @> sqlc.arg('service_date')::date
 ORDER BY s.purpose, s.code, v.version_no;

-- name: GetServiceRequestReviewSetting :one
-- Whether a program's approved requests still need a person to look at them. It is a
-- setting rather than a hard-coded rule because two sponsors running the same program type
-- genuinely differ on it; the service falls back to "a person reviews it", which is the
-- answer that cannot quietly approve something nobody meant to approve.
SELECT value_json
  FROM platform.tenant_setting
 WHERE tenant_id = sqlc.arg('tenant_id')
   AND setting_key = 'service_request.review_required';

-- name: ListServiceRequestDocumentEvidence :many
-- A link alone is not proof: both the linked object and its canonical bytes must
-- still be clean and retained. Do not use another provider's attachment.
SELECT o.id, l.document_type_code
  FROM document.link l
  JOIN document.object o ON o.tenant_id = l.tenant_id AND o.id = l.object_id
  JOIN document.object stored ON stored.tenant_id = o.tenant_id
       AND stored.id = COALESCE(o.duplicate_of_object_id, o.id)
 WHERE l.tenant_id = sqlc.arg('tenant_id')
   AND l.aggregate_type = 'SERVICE_REQUEST'
   AND l.aggregate_id = sqlc.arg('request_id')
   AND l.document_type_code = ANY(sqlc.arg('required_types')::text[])
   AND o.scan_status = 'CLEAN' AND o.bucket = 'secure' AND o.purged_at IS NULL
   AND stored.scan_status = 'CLEAN' AND stored.bucket = 'secure' AND stored.purged_at IS NULL
   AND (sqlc.narg('provider_id')::uuid IS NULL OR o.owner_tenant_organization_id IS NULL
        OR o.owner_tenant_organization_id = sqlc.narg('provider_id')::uuid)
 ORDER BY l.document_type_code, o.id;
